### ISSUE TITLE
リリースマネジメントについてprojectsprint.orgに記載

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#102]
#37 から派生しています。

まず、
https://github.com/copilot-jp/project-sprint/commit/ec9810eb67a5c283d7c8a4668fb1123f82a348f0
https://github.com/copilot-jp/project-sprint/commit/e06eb4fd6967d13771d9f02166ebe6866d8cbfc4
で、

- READMEの中で、コントリビューターの参加方法を / contributeでディレクトリを新しく切ったうえで、
- コントリビューターと議論して反映された変更内容はリリースノートと Slackコミュニティに投稿される
旨を追記しました。

最終的にREADME を入り口として、下記のような形にもっていきたいと思っています。
/contribute -> コントリビューターにとってどのような貢献の方法があるかの全体像の説明
/releasemanagement -> リリースまでの作業手順の明示化
/releasenote -> リリース内容の履歴明示、どんなリリースがあったかをわかるようにする

/contribute には大枠でこうしていますよ、というどちらかといえば初見の人向けの内容。
/realesemangement のほうは内部でいま暗黙的に行っているリリースまでの作業手順や、バージョン管理の考え方を書いていくイメージです。（これはまだディレクトリ切っていません。）

https://github.com/copilot-jp/project-sprint/issues/37#issue-619370969
や
https://github.com/copilot-jp/project-sprint/issues/37#issuecomment-645280916
ではなされているように、リリース後のアクションをしっかりまとめるという話があり、

これは、v1.0.0のスコープに入っていない
#70 
#68 
#69 
などもあるので、これらと一緒に、v1.0.0以降のアップデートの対応とする、としたいと思います。

ちなみに、これらの「リリース後のアクションをしっかりまとめる」修正は、 /releasemanagement に記載していくようなイメージを持っています。

**Comment by KokoroKagawa** [comment]
@motoi @Satoshi-Matsumoto 
- リリースマネジメントについて記述（新しくディレクトリ切りました）
https://github.com/copilot-jp/project-sprint/commit/c6645109ea85def0b3bb841a7acefd9e1ce417a4
- 「コントリビューターとしての参加の方法」アップデート
https://github.com/copilot-jp/project-sprint/commit/ab72f3c4b1f2aa9177e6761e858cb20399bb8705

記述の方針は以下に従っています。夜ご相談させてくださいー。
>最終的にREADME を入り口として、下記のような形にもっていきたいと思っています。
/contribute -> コントリビューターにとってどのような貢献の方法があるかの全体像の説明
/releasemanagement -> リリースまでの作業手順の明示化
/releasenote -> リリース内容の履歴明示、どんなリリースがあったかをわかるようにする

>/contribute には大枠でこうしていますよ、というどちらかといえば初見の人向けの内容。
/realesemangement のほうは内部でいま暗黙的に行っているリリースまでの作業手順や、バージョン管理の考え方を書いていくイメージです。（これはまだディレクトリ切っていません。）

**Comment by KokoroKagawa** [comment]
v.2.2.0にマージしたので閉じます。
