### ISSUE TITLE
Windows環境で欧文フォントだけ太く見えるので調整したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#111]
Windows 10 Chrome

![image](https://user-images.githubusercontent.com/680855/89081611-a1d07500-d3c6-11ea-9731-e17d1ce73b24.png)

Edge環境です。
![image](https://user-images.githubusercontent.com/680855/89081841-3e931280-d3c7-11ea-909c-5d4b3f42fdde.png)

スマホだと私のiPhoneやPixelで違和感ない太さなのでWindowsだけの問題なのかしら。

**Comment by motoi** [comment]
Slackでもらった環境も確認。してみました。違和感は減りました！
https://kikuchiharuma.github.io/project-sprint/ja/practice/basic.html

![image](https://user-images.githubusercontent.com/680855/89081919-7ef29080-d3c7-11ea-88c8-e9363dd8a201.png)

![image](https://user-images.githubusercontent.com/680855/89081969-a47f9a00-d3c7-11ea-8d65-9a92f2c0b5ad.png)

あとは菊地さんの見た目の美しさ的な視点で調整してもらえればと！

**Comment by motoi** [comment]
![Screenshot_20200801-083102.png](https://user-images.githubusercontent.com/680855/89088068-74d58f80-d3d1-11ea-9cee-0a4cb40aebe7.png)

![Screenshot_20200801-083128.png](https://user-images.githubusercontent.com/680855/89088073-77d08000-d3d1-11ea-930e-cbc58cf3bcc7.png)

Pixelでの見た目

**Comment by kikuchiharuma** [comment]
weight 800だとごん太すぎたので600に変更
https://github.com/copilot-jp/project-sprint/commit/5bdc67974b7b72e196dc004b64eefbb1911ff947

**Comment by kikuchiharuma** [comment]
@motoi このプレビューサイトで確認できます。どうでしょう。
https://deploy-preview-121--project-sprint-staging.netlify.app/

**Comment by motoi** [comment]
@kikuchiharuma 確認しました！自然になりました。反映お願いします！

**Comment by kikuchiharuma** [comment]
@motoi あざっす！閉じます
