### ISSUE TITLE
ルートのページのスタイルを下層ページに合わせたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#112]
![image](https://user-images.githubusercontent.com/680855/89082080-f32d3400-d3c7-11ea-9f8f-18ee7d64256b.png)

見出しを太くするCSSがあたっていない？下層ページと合わせたいです。

**Comment by kikuchiharuma** [comment]
これでサイト全部の見出しにスタイルが適用されるはず
https://github.com/copilot-jp/project-sprint/commit/5bdc67974b7b72e196dc004b64eefbb1911ff947

**Comment by kikuchiharuma** [comment]
@motoi このプレビューサイトで確認できます。どうでしょう。
https://deploy-preview-121--project-sprint-staging.netlify.app/

**Comment by motoi** [comment]
@kikuchiharuma プレビューサイト確認しました！よいとおもいます！反映お願いしますー。

**Comment by kikuchiharuma** [comment]
@motoi あざっす！閉じます
