### ISSUE TITLE
各CODEのページフッタにあるリンクに日本語トップへのリンクがない

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#113]
![image](https://user-images.githubusercontent.com/680855/89082200-3f787400-d3c8-11ea-8408-66af9e449954.png)

あんまり使わない気がするけど、なんか構造的に気持ち悪い気がしていまして。違和感的イシュー。菊地さん、サトマツさん的に、別に…ってことであればクローズで問題ないです。

**Comment by Satoshi-Matsumoto** [comment]
他のナビゲーション系のイシューと一緒に進め方の足並みそろえます、ということで、いったん @Satoshi-Matsumoto にアサイン。

**Comment by Satoshi-Matsumoto** [comment]
#156でこちらも一緒に解決するのでクローズで。
