### ISSUE TITLE
「超高速な認識合わせ」の定義

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#12]
> 超高速な認識合わせ

これをもう少し意味合いを持たせたい。
ワードを変えるのか、どういう認識を合わせるために行っているのかという補足でもよいかもしれない。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/8_

**Comment by motoi** [comment]
ちなみに、これプロダクトチームからも質問でました。

**Comment by Satoshi-Matsumoto** [comment]
- 超高速 => 高速？

- 効率的に・互いに理解のずれがなくなる
- 時間かければできるかもしれないが効率よく高いところに到達する
- このプロセスが身についてくるとこの会議に参加するとあんま意識せずに認識がそろう、みたいなものになると思っている。
- 認識合わせするぞ！！みたいなことを考えなくても合う、もの。
- 素早く認識が合う状態をつくる
- 自然と認識が合うような状態になる。
- 阿吽の呼吸状態にすぐうつることができる

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
90a06a4e7e0eafb192d71ea926391ca3597ae214
こんな感じでどうでしょう？

**Comment by motoi** [comment]
テキストで表現するとこうなるのかー面白い！よいとおもいました。
そして話として足せそうであれば検討したいのが、

全員で議論に参加する → どういう条件・態度で望めばよいのか、が深ぼりたい

これが実現していれば「プロセスに参加するだけで」「認識を合わせることができる」がもっとしっくりくる気がする！
これちょっと議論したらでるかなーとおもったけどどうだろう。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ここはこの後段につづく以下の部分で一応話としてはあるのですが、
ここに、不足している部分があるという感じですかね？
（全体の構成としては、ミーティングの意義 => そのミーティングはどういうものであるべきなのか、という流れで記載しているので、追記するとしてもこの部分のどこかになると思います。）

> ###### 議論する人
> 超高速な認識合わせとこれに伴う意思決定を実現させるためには、アジェンダに関して網羅的に議論ができるメンバーがそろっており、またその議論をもとに正式に意思決定できる権限をもっている人が参加する必要がある(**必要十分な参加者** の招集) 。
> 
> ##### 場
> ここでいうところの場(ba)とはミーティングが行われるの物理的・心理的空間のことを指す。
> 
> 物理的には、プロジェクトスプリントの迅速な認識合わせを実現するために、前述の参加者が漏れなく参加でき、かつ、情報をリアルタイムに共有できる環境が整備されている必要がある。
> 
> またプロジェクトスプリントにおける意思決定は、メンバーの納得を伴うものである。このためには各メンバーが自律的に意見を発していることが不可欠となるが、これを保障するのが **心理的安全性** であり、これを保障できるような空間づくりが求められる。
> 
> ##### 時間
> 
> ミーティングは、**予め開催日時の決められた定例会議**　となっていることが必要である。
> 
> ###### あらかじめ決められた開催日時
> 超高速な認識合わせと納得形成・意思決定に必要な参加者と場を確保するには、必要に応じたミーティングの開催では手遅れになってしまう。したがって、将来にわたって予め参加者の予定を確保しておかなければならない。
> 
> ###### ミーティング開催の間隔
> また、ミーティングはある一定の期間による開催とすることが不可欠である。これは、不確実性の高い状況下ではプロジェクトの進捗やゴールの妥当性・チームの状況の定点観測が欠かせないことから求められる。
>

**Comment by motoi** [comment]
いっかいセンスメイキング理論についてまとめるのでそれを持ってアップデートを検討しましょう！
ちなみにこのテキストにでてくる「超高速な認識合わせ」は別のワードに置き換わるんだよね？

**Comment by Satoshi-Matsumoto** [comment]
> 全員で議論に参加する → どういう条件・態度で望めばよいのか、が深ぼりたい
> これが実現していれば「プロセスに参加するだけで」「認識を合わせることができる」がもっとしっくりくる気がする！
> これちょっと議論したらでるかなーとおもったけどどうだろう。
>いっかいセンスメイキング理論についてまとめるのでそれを持ってアップデートを検討しましょう！

ここは、別issueを立てて対応。

> ちなみにこのテキストにでてくる「超高速な認識合わせ」は別のワードに置き換わるんだよね？
ここは、de580ca963fbb5bec505f7f8ae5570d8bf93a9a5 で対応済みです！

なので、問題なければcloこちらはいったんcloseください @motoi

**Comment by motoi** [comment]
おす問題なしです！
