### ISSUE TITLE
Pull Requestごとにプレビューサイトがデプロイされることを説明

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#122]

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
これ、たぶんPR時Netlifyでプレビューサイトが見れるようにしていただいた件を説明する、といういものだと思うのですが、あっていますか？
説明いただいた & リリースも完了していると思うので、クローズしてしまいますね。ありがとうございました！！

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto あ、これはreadme等で誰にでもわかるように、ということで作ったIssueです

**Comment by kikuchiharuma** [comment]
説明を追加
https://github.com/copilot-jp/project-sprint/pull/157/commits/d7b01c8d8b39e93804676642c307a15288a3752b

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto (サイト構築の知識があって確認環境やデプロイの方法を知りたい)コントリビューターへの説明として適切か、みてほしいです！

**Comment by KokoroKagawa** [comment]
@kikuchiharuma 
こちら、違和感ないです！ありがとうございました！
