### ISSUE TITLE
pjs.orgにコントリビューターとして参加したい人への導線がない

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#124]
PJS.orgに以下のファイルへのリンクがない。
project-sprint/ja/appendix.md
project-sprint/README.md
また GitHubのPJSのリポジトリへのリンクもあってもよいんじゃないかと思いました。

**Comment by motoi** [comment]
GitHubカルチャーを知る菊地さんからご意見プリーズ。
・そもそもGitHubのリポジトリへのリンクがあればよいのか？
・そうではなく上記したファイルはすべてorg側でも見ることがよいのか？
私はorgからでもみえてよいんじゃないかなとおもいましたが。

**Comment by motoi** [comment]
@kikuchiharuma わかりづらそうだったのでイシューのタイトルかえましたー。修正の方向性のご確認ください。ってどっかのファイルでリンクがあったのみたきがするけどそのブランチが見つからず。。。

@Satoshi-Matsumoto これもうミーティングでリンクが必要だよねという話になったので、サトマツさんの方で修正でよいんでしたっけ？

**Comment by kikuchiharuma** [comment]
トップページにリンクを追加
https://github.com/copilot-jp/project-sprint/pull/157/commits/a8e2d27d7e714e32a2c8c307d60e34782216cf08

**Comment by motoi** [comment]
確認しました！
