### ISSUE TITLE
サイトにライセンス表示を追加

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#125]

**Comment by kikuchiharuma** [comment]
フッターとトップページに追加
https://github.com/copilot-jp/project-sprint/pull/157/commits/545714592eeb23e06d30bc2e5b77619a3c7ab761
https://github.com/copilot-jp/project-sprint/pull/157/commits/cf0f0eaeefaf49c7494505b66cfd1f04d17a6919

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma これ、CCライセンスついているので解決済みで大丈夫ですか？

**Comment by kikuchiharuma** [comment]
あ、そうですね。クローズします！
