### ISSUE TITLE
ライセンスが CC BY SA でよいか弁護士さんに確認

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#135]
馬場さんにCC BY SAでよいか？あとから厳しくなる場合はどういう扱いになるのか？
たとえばあとから非営利に限定したいなどがあった時の処理をどのようにするか。
Slackで確認中。

**Comment by motoi** [comment]
9/25の弁護士さんとのMTGで詳細を話しながら確認予定。

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479553212
の経緯で、現時点でprojectsprint.orgではCC-BY SAとしてリリース済み。変更があれば、その修正対応。

**Comment by motoi** [comment]
@kikuchiharuma 
弁護士さんに確認しました！

結論から書くと、CC BY SA は同じ哲学で使ってよいよと宣言しているものなので、話を聞くとPJSはそのライセンスでよさそう、ということでした。

CCは違反されたとしても何か罰則があるわけではない。
著作物の哲学を表現するものというニュアンス。厳密にしばるものではない。

あとからCCを変更してみる（例えばNCをつけたい場合など）は変更してもよいが、通知する手段がない。
なので、途中でつけると利用しているひとが前と違うので困る人がいるぐらい。みんな割と同じことで困っているが解決する手段が現状はない。

なので、徐々にライセンスを緩くするやり方はよくあるが、徐々にしばるケースは少ない。
もしPJSがNDをつける可能性があるなら最初からつけて徐々に緩くする方が良いかも。

また、この手のメソッドに関しては、現状の選択肢はCCしかないので、現状の話を聞くと CC BY SA がベストな選択肢ではないか。（SAがあると使いづらいという意見がでそうだが、その意見がでたらはずすという流れの方が自然）

ということでした。

菊地さんが確認して問題なければイシュークローズください！

**Comment by kikuchiharuma** [comment]
@motoi あざす！
