### ISSUE TITLE
レビューの仕方のご相談

### ISSUE THREAD

**Issue by yoneyama-tomohiro** [copilot-jp/project-sprint#136]
@kikuchiharuma @Satoshi-Matsumoto 先生！

下記を読んでいて、全般的に日本語をわかりやすくしていきたいと思っているのですが、
https://github.com/copilot-jp/project-sprint/blob/master/ja/theory/basic.md

そういうときは、どのようなプロセスで行っていったら良いでしょうか？

先ほど @motoi さんから、ブランチ化などのやり方をいくつか伺ってはいるのですが、
あるページ全般的に手を加えたいときの最適なやり方が分からずでして。。

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro 
ご質問ありがとうございます！

1)「理論編ペーシックをわかりやすくする」みたいなタイトルで、issueを新規に立ててください。

2）masterから、適当な名前でブランチを切り、masterへのプルリクをつくってください。プルリクタイトルはissue XXにかんする修正　とかにしておいてもらい、冒頭に［WIP］といれてください。

3)修正が終わりましたら、終わったことをissueでご連絡ください。プルリク上でレビューします。

こんな感じです！

**Comment by yoneyama-tomohiro** [comment]
@Satoshi-Matsumoto 
ありがとうございます！
トライしてみます！

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro 
お願いします！何かわからないことがあれば聞いてください　& 基本的に間違っても元に戻せるので大胆にやってもらって、大丈夫です！

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro 
いったん解決したと思うのでこのissueはcloseします。わからないところがあれば再度issueあげる or このissue reopenしてください。
