### ISSUE TITLE
チーミングの理想の状態について「ロールの期待値がそろっている状態」でいいのか？見直し

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#137]
_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r476375965_

**Comment by Satoshi-Matsumoto** [comment]
マニュアルv0.8.0のレビューの中で出てきた話ですが、これはCODEの側の議論として引継ぎます。

**Comment by Satoshi-Matsumoto** [comment]
もとの議論をもとに、まずCODEの部分の修正案を記述。

**Comment by Satoshi-Matsumoto** [comment]
#239 で継続的改善アプローチを考えたあと、立ち戻る。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/235
こちらとマージにつきクローズ
