### ISSUE TITLE
Project Sprintでありうる会議の目的は議論に限定されるのか、またそのとき会議に人数制限があるか

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#138]
_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479652759_

**Comment by Satoshi-Matsumoto** [comment]
経緯

https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479088286

に対し、 @Satoshi-Matsumoto から下記のコメントを返した流れから。

====

> 割と色んな資料で10人以上にはしないでねとは言っている。多くなると議論の場ではなく共有の場になるので目的が変わるから。

このコメントだと、共有の場としてのミーティングはProject Sprintでは存在しない、という風に読めるのですが、それはそれでよいんでしたっけ？という点がまず気になったポイントです。

3人だろうと10人以上であろうと必要十分な人数であれば出席しておくべきなので、どういう目的の会議であればだいたい10人もいらないでしょ、となり、どういう目的の会議であれば10人超えるよね、という話になるのかと。

そのうえで、10人以上の会議であれば共有目的だし、かつそういう目的の会議はProject Sprintでは認めない、となって初めて10人以上にしないでね、といえると思います。

てことで、issue化して深堀りしましょう。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
こちらもともとの議論の経緯を確認していただいて、 @motoi さんの見解もらえると、助かります。
ちょっとわかりにくかったらそのあたりも返してもらえますと。

**Comment by motoi** [comment]
@Satoshi-Matsumoto あたま整理できた。
プロジェクトスプリンとのポイントはご存知の通り、ミーティング終了後にタスクができていて、次のミーティングまでにそのタスクを実行していること、そしてそのタスクの実行結果を元にアジェンダがあがっていることです。
ミーティング全部が共用のアジェンダかつタスクが発生しないのであれば、プロジェクトスプリントと呼ばないかなとおもいます。複数あるトラックの一つがそうなっているとかはよいけど、全部のトラックがそうなっているプロジェクトはプロジェクトスプリントじゃない、といって良いかなと。
大人数で共有しかない会議体しかもたないチームの活動をプロジェクトと呼ぶか？という話かも。多分それプロジェクトじゃない。
プロジェクトスプリントのプロセス（ファシリテーションのやりかたとか、アジェンダの書き方とか）をその大人数の会議体に適応できる部分はもちろんあるとおもう。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
コメントありがとうございました。
共有目的のみの会議しか設定していないプロジェクト = プロジェクトスプリントではない、もっというとプロジェクトでもない、ということですよね。

で、もともとは

> ミーティングの開催頻度は、週次/月次/隔週など、プロジェクトの性質やチームメンバーの人数などを勘案して任意に決めてください。ただし、プロジェクトスプリントがプロジェクト推進メソッドであることを考えると、隔月以上の間隔でのミーティング開催は考えにくいでしょう。
> 
> なお、各ミーティングの参加者はアジェンダに応じて必要十分な程度でかまいません。ここでいう必要十分とは、アジェンダに関して網羅的に議論でき（＝「誰かがいないから今日はこの話ができないね」ということがないようにする）、また議論をもとに正式な意思決定ができること（＝「誰かがいないから今日はこの話は決まらないね」ということがないようにする）を意味しています。
> 

ここの記述について、

> 割と色んな資料で10人以上にはしないでねとは言っている。多くなると議論の場ではなく共有の場になるので目的が変わるから。

ともらっていて、ポイントは人数ではなくて、共有の場になっているかどうか、だと思います。つまり、10人以上でも議論の場となっていればプロジェクトスプリント的には問題ないといえる。

たぶん10人以上にしないでねとアドバイスしている理由は、"大人数呼ぶのって共有が目的の会議になっちゃってる可能性があるけど大丈夫ですか？（**もし議論の場になっていれば10人以上でも構わない**）"ということだと思います。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このあたりのはなしも加味するとこんな感じが言いたいことなのかなと。ご確認ください。
b252db63080889d6c4f48ae514c79bab1859c2a1

**Comment by motoi** [comment]
一旦これで良いとおもいました！
