### ISSUE TITLE
マイルストーン確認をミーティングで必須のアジェンダとするかどうか

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#139]
_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479655319_

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479658409
も参照

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
元のコメントの流れを引き継いで、見解もらえると助かります。

**Comment by motoi** [comment]
関連するコメントをもらいました。
---
プロジェクトのゴールとマイルストーンを見直す
この辺りの見直さなきゃ、とか、達成した、とかSGMs上でなにかサポートしてあげられるようになると良いなぁと思いました。いまは人が確認して修正しなくてはいけないので。そういうメソッドのやり方であればそれで良いのかもしれませんが。
uniba koide

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このissueですが、まず↓のコメントからスタートしたいと思いますので、見解もらえますか？
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479655319

koideさんのくれている内容に対しては、修正が完了した後に、フィードバックできるものがあったら返せればと思います。

**Comment by yoneyama-tomohiro** [comment]
米山メモ：
- 長期的マイルストーンは、月1とかで
- 短期的マイルストーンは、毎週確認、とか。

**Comment by motoi** [comment]
マイルストーンがある方がミーティングのファシリテーションが非常にやりやすくなる。
・このアジェンダを今日やるべきか判断できる
・どこまでの結論まで持っていくべきなのかが判断できる
とはいえ、マイルストーンが精緻になっていないときに毎回みても仕方がないフェーズもあるから、必ずマイルストーンを毎回みましょう、は言いすぎなきがする。

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん

> マイルストーンがある方がミーティングのファシリテーションが非常にやりやすくなる。
> ・このアジェンダを今日やるべきか判断できる
> ・どこまでの結論まで持っていくべきなのかが判断できる
> とはいえ、マイルストーンが精緻になっていないときに毎回みても仕方がないフェーズもあるから、必ずマイルストーンを毎回みましょう、は言いすぎなきがする。

上記を踏まえるとマイルストーン参照は
- ミーティング序盤のアジェンダトリアージ時
- アジェンダ進行時
- ミーティング終盤のタスク確認・次回のアジェンダ確認時
にしたほうがいいということになると思いました。

ということで、
- ミーティング序盤は 32e8c92eea1a329b7a60c76ee68e836493ff765e でもう少し意義を明確に。
- ミーティング終盤は 9f3c153163dbd251b983e37d649ed0b368fdafce で文言追加。
- アジェンダ進行時にはすでに下記のような文言があるのでママイキでいきます。(意義を何度も説明すると冗長なため）
> ここでも、直近のマイルストーン達成のためにはどのような選択が有効か、が基本的な判断基準となりますが、最終的にはチームメンバーの話し合いで出た結論が優先されます。

cc @yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
koideさんのコメントについては、

> プロジェクトのゴールとマイルストーンを見直す
> この辺りの見直さなきゃ、とか、達成した、とかSGMs上でなにかサポートしてあげられるようになると良いなぁと思いました。いまは人が確認して修正しなくてはいけないので。そういうメソッドのやり方であればそれで良いのかもしれませんが。

いまのメソッドの到達地点だとマイルストーンを参照して人が確認する・チームで検討する、しかないですね。達成度合いとかを構造化してとらえられないかという意図も含まれている気がしますが、いまいま解はないです。というわけでManualへの反映はありません。

ツールへの反映という意味だと、ミーティング序盤・アジェンダ進行時・ミーティング終盤のそれぞれのタイミングでマイルストーンを参照しやすくなる・自然とするようになるようなインターフェースがあるといいなとは思います。

cc @motoi  @yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro さんの

> 長期的マイルストーンは、月1とかフェーズごととかで確認
> 短期的マイルストーンは、毎週確認、とか。

についてはすみません、このイシューとの関係で意図が汲み取れなかったのでいったんスルーします。
このあたりをこうしたほうがいいという意図があれば別イシューを立てていただいたうえ、別のマイルストーンで対応します。

@motoi

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
というわけで
https://github.com/copilot-jp/project-sprint/issues/139#issuecomment-699497101
の修正確認いただきOKであればこのイシュークローズください。

**Comment by motoi** [comment]
確認しましたーこれで良いと思いました。
