### ISSUE TITLE
ミーティングの型についてのTips作成

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#140]
_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479659975_

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
元のコメントを確認いただき、

> ミーティングのテンプレがあるとよいよ
> という話をいれてもよいんじゃないかなとおもいました。
> だいたい定例によってミーティングの冒頭と終結で型が決まっていくので、最初はよちよちとはじめるけど、最終的には型ができて、その型があるほうがスムースで効率よくなるよ

ここの「型」「テンプレ」についていくつか具体例をもらえますか？それをもとに、新tipsとして私の方で書いてみます。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://docs.google.com/presentation/d/1MZXbvbmbHhU5Rx253hCP0njeHzRXHzIiK_MKt-VJNEc/edit#slide=id.p
昔作ったこんなのでよい？

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ありがとうございます。改めて考え直して、TipsにするとTutorialで書いている内容の焼き増しになりそうだな、と思ったので、Tutorial側に追加で内容入れるかたちにしてみました。

fed413d772bf73b668e449d050c89d4a6f1eceb0

こんな感じで、どうでしょうか。ご確認ください。

**Comment by motoi** [comment]
よいとおもいました！
