### ISSUE TITLE
マイルストーンマップの概念図を挿入して読者の理解を助けたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#143]
マイルストーンマップはPJSの中でも重要な要素ですが、構造が分かりづらいので図で表現したほうが構造を理解しやすいとおもっています。
![image](https://user-images.githubusercontent.com/680855/91659758-e148c900-eb0c-11ea-918a-dccb86c137da.png)
とか
![image](https://user-images.githubusercontent.com/680855/91659788-0fc6a400-eb0d-11ea-9a6f-bb21b9677c56.png)
とかの絵が私たちは頭に入っているので、この文章が読めるんだと感じます。

なのでこのようにマイルストーンマップという抽象的な概念を絵にしたほうがりかいしてもらいやすいのでは？という提案です。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479768028_

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
イシュー化しました。

サトマツさんもこのイシューに共感する！ → 進め方検討ください。菊地さんに依頼でよいのかな。
サトマツさんは別にこの絵なくてもよいんじゃね？とおもう → だとしたら私の読解力の問題な気がするので、イシュークローズしますのでおしえてください。

まずこのイシューに共感できるかが知りたいです。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

まず、貼ってくれた画像のような概念は概念図としてあったほうがいいと思います。
図にするのは @kikuchiharuma さんの手を借りたいです。

ただし画像にするのはマイルストーンマップではなくマイルストーンとは何ぞや、という話だと思うので、画像を掲載すべき場所は
https://projectsprint.org/ja/manual/tips/tips2.html
ではなく、
https://projectsprint.org/ja/manual/tutorial/section2-1.html
だと思います。

補足ですが、いまTipsに記載しているマイルストーンマップの記述は下記です。

> マイルストーンマップとは、プロジェクト内のマイルストーンの全体像を把握するための**シートのことです**。期日と成果物以外の情報を載せ、複数のマイルストーンを横断的に記載することで、マイルストーン間の関係や設定の背景も含めたより深い理解を可能にします。

つまり、あくまでツールとしてマイルストーンマップを位置付けています。

マイルストーンマップの概念がイメージと違ったら、教えてください。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このissueなんですが、v0.9.0のアップデートで
https://projectsprint.org/ja/manual/tutorial/section2-1.html
![image](https://user-images.githubusercontent.com/61894329/95672659-bfe3fe00-0bdd-11eb-83c7-6ed8993fabb3.png)
この画像が追加されているので、いったんそれで良さそうですかね？
問題なさそうであればcloseお願いします。

**Comment by motoi** [comment]
@Satoshi-Matsumoto これいったんはこれでよいけど、菊地さんにちゃんとした絵にしてもらうイシューは別でもう立ってるんだっけ？

**Comment by Satoshi-Matsumoto** [comment]
@motoi そもそもこれがPJS概念図の菊池さんの絵から持ってきているのと、内容的にも今ある図で十分だと思ってます。

「ちゃんとした絵」として別アウトプットのイメージがあるということであれば、別issueを立ててもらえますか？

**Comment by motoi** [comment]
@Satoshi-Matsumoto スクショで切り抜きましたってだけだと、クオリティとして仕上がってない感がでるなとおもっています。それが私は気になっている。
けども改めてマイルストーンとかマイルストーンマップの定義を行ってそれができたらよき絵にしてもらおうかなと思いました。それで別イシュー立てます。
