### ISSUE TITLE
成果（アウトカム）の表現について必要であれば調整したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#144]
まず、実践上において 成果（アウトカム）の使い方イメージしたい。
その具体的な使用法用をもとにCODEやチュートリアルの内容のアップデートが必要であれば行いたい。

流れはこのあたりに。
https://github.com/copilot-jp/project-sprint/pull/132/files#r479568446

**Comment by motoi** [comment]
成果（アウトカム）の具体的なイメージが私が浮かんでいないので教えてもらえますか？
メソッドチームにおける事例が一番共通で理解しやすいかなとおもっているので例示いただけると！

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、
"アウトカムとは何か"というよりは、"アウトプットだけどアウトカムではないものは何か"という視点から理解してもらうのが良い気がします。

例えばこれ。
https://docs.google.com/presentation/d/1IEXjaQU8gYLwcnjqJYK-sgNftCW4gVJNSrNmIngvffo/edit#slide=id.g825ad771ab_0_38
この表は、確かにタスクの結果としてのアウトプットなのですが、どの成果物との関係でどういうものであったのか判然としません。

決して無駄ということではないのですが、成果物の一部を構成していないという点で、アウトカム(成果)ではない、という整理ができます。もちろん、将来的には別の文脈でアウトカムになることはありえます。

全てのアウトプットは成果物につながる、と考えると、アウトカムの概念は特にいらないのですが、
現実にはアウトプットの中でも成果物には直接関係ないものが出てくると思っていて、それらを削いだものが、アウトカム、の概念です。

うーん、こうしてみると特に書かなくてもいいですかね？ご意見ください。

**Comment by motoi** [comment]
言わんとしていることはわかった。

目に見える出力されたもの → アウトプット
成果物につながるアウトプット → アウトカム

ってことだよね。アウトプットのほうが大きな概念。

アウトカムを日本語にすると成果物にめちゃ近い意味だとおもっているんだけどその認識は私と合ってるかな。
用語を分けるとしてもアウトカムって名前じゃないほうが良い気がする。

たとえばピボタルトラッカーでいうとバックログを「feature：機能」と「Chore：ユーザーに関係ない改善」みたいに直接成果につながらないものを分けたいということだよね。これは明確にシステム開発なので分けると優先順位をつけやすいみたいなメリットはある気がしていて。
タスク管理の方にそういう概念をいれるならわかる気はしなくもないけど、あってもめんどくさくて使わないんじゃないかな。。。

私がつかうイメージが沸かない！

@yoneyama-tomohiro さんご意見プリーズ。一回消しても良いかな的なご相談です。

**Comment by yoneyama-tomohiro** [comment]
@motoi 
結論からいえば、個人的には「アウトカム」の分けは、不要だと考えます。
仮に概念整理的に正しいものだとしても、実践的に必要なければ説明コストが増えるだけなので、なるべくシンプルにしたいです。

言いたいことは「小さなアウトプットを積み重ねて、最終的なゴール・成果を達成する」という話だと思うので、だとすると、2つがあれば事足りるかなと思っています。

その上で、以下、整理の私案です。

- アウトプットの個人的定義：「ゴール」「成果」に繋がりうる目に見える有形物
- 「成果物」という表現が私はしっくり来ていなくて、字に含まれている通り「物」だけを想像させるので使いにくく、「ゴール」や「成果」（下のページでは「成果（1st）」などと使われている）にしたいです
https://projectsprint.org/ja/code/theory/basic.html
- 理由：「物」ではなく「状態」を成果とすることがしばしばあるため

**Comment by Satoshi-Matsumoto** [comment]
- アウトプットの個人的定義：「成果」に繋がりうる目に見える有形物
- 成果は、アウトプットが集積した成果物と、あるべき状態によって構成される。マイルストーンは、成果に対応する。

**Comment by Satoshi-Matsumoto** [comment]
- アウトプットの個人的定義：目に見える有形物
- 成果は、アウトプットが集積した成果物と、あるべき状態によって構成される。マイルストーンは、成果に対応する。

**Comment by Satoshi-Matsumoto** [comment]
これ結局誰が修正するかぼやっとしちゃっていますが、せっかくなので @yoneyama-tomohiro さんお願いできますか？
がっつり検討 & 議論に入ってもらったので書いてもらえるといいかなと。

cc @motoi

**Comment by Satoshi-Matsumoto** [comment]
アサインはそのままにしておきます。

**Comment by yoneyama-tomohiro** [comment]
了解です。

**Comment by yoneyama-tomohiro** [comment]
@motoi @Satoshi-Matsumoto 
アウトカムの件、以下で修正しました。
やり方間違っているところがあれば、ご指摘ください。
https://github.com/copilot-jp/project-sprint/commit/8071deeab35db36f82b5abdff0eba7487506691f

**Comment by motoi** [comment]
@yoneyama-tomohiro さん
https://github.com/copilot-jp/project-sprint/commit/8071deeab35db36f82b5abdff0eba7487506691f
定金がおもうところをコメントしました。

@Satoshi-Matsumoto さん
ご意見くださいー。

**Comment by Satoshi-Matsumoto** [comment]
確認しました。@tomohiro-yoneyama さんの整理でいいと思っています。
https://github.com/copilot-jp/project-sprint/commit/8071deeab35db36f82b5abdff0eba7487506691f#r44026324
https://github.com/copilot-jp/project-sprint/commit/8071deeab35db36f82b5abdff0eba7487506691f#r44026345

このコメントですけれども、「結局成果物もアウトプットじゃん」と考えるとそれはそうなのですが、この文章にたどり着く人は、アウトプットの定義 / 成果物の定義、もしくはその違いを知りたいと思うので、並記でいいと思います。

というわけでほかのページからの導線も修正しました。
50520ece3d9cd6f0272cc13d9982267dfe4d4502

あと、[このコメント ](https://github.com/copilot-jp/project-sprint/commit/8071deeab35db36f82b5abdff0eba7487506691f#r44026236
) も修正対応しました。
7d76acb2ef1c40bd759b92ee705a4e399df34cb1

@motoi さん確認してもらって、そのあと @yoneyama-tomohiro さん問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
やっと論点が自分の中で整理できてきました。
今回はこの整理でよいとおもいました。（気になるところがあるので、頭を整理して別イシューを立てます）
@yoneyama-tomohiro さん、ご確認くださいー。

**Comment by yoneyama-tomohiro** [comment]
@motoi @tk2hiroaki 
異論ありませんので、クローズします。
