### ISSUE TITLE
「管理」という言葉をPJSで使っていくことを検討したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#145]
ここで管理ということばが3つ連続ででてきて初めて大きく違和感になったんだけど、すごくPJSぽくない言葉だなとおもった「管理」。
管理という言葉だと誰か一人がコントロールして、計画通りにする感が大きい。
なんか言葉開発したいけど、共同管理の方がまだよい。
なんか言葉のニュアンスもみんなでみようぜ！みたいなことにしたいなー。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479572994_

**Comment by motoi** [comment]
まずは定金がもう少し調べたりねって見る。

**Comment by motoi** [comment]
他の資料のロールの設定で（さだかね思い出し用にメモ:不動産デベ案件）リードという言葉をつかったのが非常にしっくり来ている。
チーム全体でうまく各ドメインを推進するためのリードをするみたいな。
リードで良いんじゃないかと思い始めているので、ロールシートを更新しながら馴染む言葉かどうかを検証する。
メモ。

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/95806076-d1461b00-0d41-11eb-81bf-43d4f1acddaf.png)
リンクの貼り方がわからないのでダサいととおもいつつもスクショ

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このissueですがどう進めますか？
- 具体的な修正箇所
- 修正方針
など。

**Comment by Satoshi-Matsumoto** [comment]
このタイミングで進捗ないのでmanual v1.0.0から外したほうがいいのかと思ってますがどうでしょうか。

**Comment by motoi** [comment]
最近の情報を貼っておきます。
これらを見ると私のなかでは管理よりも「共有」のほうが近いかも。長くかくなら「いつでもアクセスしやすく共同編集が可能な状態をつくる」というニュアンスに近い言葉にしたいという感じです。それを管理といいいたくない感じです。

▼環境設定シート
![image](https://user-images.githubusercontent.com/680855/98487474-661b3600-2266-11eb-8039-a3424776d9d2.png)

▼Miroによるワークシートの入力項目
![image](https://user-images.githubusercontent.com/680855/98487494-91058a00-2266-11eb-8c73-dd71161d57a6.png)

なんかいいワードがサトマツさんでひらめいたらそれで、うーんひらめかない！ってことであればマニュアル1.0.0から外すで！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なるほど。すみません、いったん先送りしてもいいですか？
読み返すと「管理」って結構いろいろなところでつかっていて、「共有」だけじゃなくて「確認」というワードに翻訳したほうがいい場合などもあるんじゃないかと思っていて、全体にわたって見直しかけたいなと。

そして
https://github.com/copilot-jp/project-sprint/issues/64
これと一緒に対応したほうがいい気がしているというのも理由です。

**Comment by Satoshi-Matsumoto** [comment]
アサイン上は #64に合わせて私のままにしておきます。

**Comment by KokoroKagawa** [comment]
@motoi https://github.com/copilot-jp/project-sprint/commit/5b9b330ccf0848947b0dd01f07940732fdfffb0a

アジェンダに関しては「取りまとめ」(「管理」よりは共同作業のニュアンス出るかと)、「確認」、「調整」
ファイル・スケジュール・タスクについては「共有」
マイルストーン・ロール・ミーティングについては濁し、
時間に関してのみ「管理」を残す形としました。

いかがでしょう。

**Comment by motoi** [comment]
よいとおもいました！

**Comment by KokoroKagawa** [comment]
v2.2.0にマージしたのでクローズとします。
