### ISSUE TITLE
継続的改善アプローチにロール確認をいれるか検討したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#146]
> 「継続的改善アプローチ」

どこかの記述ではこれに「ロール確認」も入ってなかったっけ？そしてそれは入ってよいとおもっていて。とおもったけどCODEには入ってなかった。
いったん全体で統一されていればそれでよいですー。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479540273_

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479660718
の通り、Manual v0.8.0ではいったんCODEとの関係としては統一されているので、

https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479819739
のところで残っている問題意識・このissueで解決したいことを改めて記載ください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
テンションを上げるために何が必要か。
テンションとは、理想と現状のギャップなので、理想形が必要になります。
そのためにプログレスで必要なものはマイルストーン。
そのためにチーミングで必要なものはロール。
という構造になります。PJS1枚概要図でも表現されているように。
![image](https://user-images.githubusercontent.com/680855/93077144-5f879c80-f6c3-11ea-9f7c-4f74472a40ba.png)

ということで、継続的改善アプローチには理想形が必要で、マイルストーンやロールが必要。
なのでその2つを確認する要素が必要ですよ、という記述はあってよいかとおもいました。
ということでした。これ読んでみてどうでしょう？！

**Comment by motoi** [comment]
コメントもらいました。
↓
ロールを確認する
これって常に参照できるべきものなんですかね？たとえば毎回ミーティング前に確認するとか。定義していないような作業が生まれる、というのはどういうタイミングで発生するのでしょうか。アジェンダを話してるときとかに生まれるのかな。
uniba koide

**Comment by motoi** [comment]
コメントもらいました
↓
ロールを確認する
期待値が満たされていない、自分が思ってる以上の期待値を感じる、のもどうやって拾っていくのかが気になりました。テンショントリアージとかなんですかね。
uniba koide

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/issues/146#issuecomment-691975974
なるほどこのコメントは納得です。

これを踏まえて、
テンショントリアージの部分
db665f1607f89c8cbf414bd45f74e096e5422e9e
ca68a3d2cfedd80910ab406334fec8ef66b8da19

振り返りの部分
fe6be40ba91ee6afd3671b7071d39ee5c37e7887

いずれも修正してみました。これでkoideさんのコメントにも答えられているんじゃないかと思うですが、いかがでしょうか。
cc @yoneyama-tomohiro

**Comment by motoi** [comment]
定金が25金にフィードバックする→土日サトマツ作業

**Comment by motoi** [comment]
よいとおもいました！
