### ISSUE TITLE
メソッドでトラックを複数チームと表現するか、そもそもチームとは何かを定義するかを検討。

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#147]
@Satoshi-Matsumoto 
修正先を読んでのコメントです。複数チームについての言及は避けているけど今回は表現してくれている、ということでよいですよね。

プロジェクトに複数チームが存在することは普通におこっていることだとおもうので、複数チームが存在する場合のことを書くのはよいかなとおもっています。
で、その複数チームのことをトラックと表現するかどうかは判断だなと思いました。
個人的には、トラックはエッセンシャルズに入っている概念でもないので、他のチームのメンバーが、みたいな表現でも違和感はないかなとおもいました。

どうでしょ？

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479764897_

**Comment by motoi** [comment]
一度このコメントに対して感想ください！

**Comment by Satoshi-Matsumoto** [comment]
元コメントがリンクわかりにくかったので取り急ぎ貼っておきます
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479764897

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

まず課題の認識というか前提をそろえたいと思います。

この話ですが、まずプロジェクトにおける"チーム"の単位（？）を意識することが必要だと思いました。
私が思ったのは下記です。

===============
1.  複数トラックを含む一つのプロジェクトを"チーム" と呼ぶ
※SGMの"Project Sprint"プロジェクトにはプロダクト、メソッド、デリバリーなど複数のトラックがありますがそれに取り組んでいる総体を"チーム"と呼ぶ

2. 個別トラックを"チーム"と呼ぶ
※上の例でいうとプロダクト、メソッド、デリバリーなど

3. 個別トラックとは別に一定の機能を基に"チーム"と呼ぶ
※わかりやすいのはエンジニアチーム、デザイナーチーム、ライターチーム、など職能で分ける方法

4. プロジェクトに所属している元組織を"チーム"と呼ぶ
※上の例でいうとコパイロツト、ユニバ、など

==============

で、もともとのコメントで私がひっかかっていたのは、「ほかのチーム」といったとき、
- プロジェクトの外にあるチームのことを言うのか(1をベースにした考え方）、
- 同じプロジェクトの中でのチームのことを言うのか（2または3をベースにした考え方）
どちらなのか？という点です。

マイルストーンを"ほかのチームからわかりやすいように書く"というとき、それは同じプロジェクト内の別チームの人にとってわかりやすいものであるべきなのか、プロジェクト外の別チームの人にとってわかりやすいものであるべきのか、という点ですね。

(4はいまのところそこまで気にする必要がない概念だと思います。)

cc @yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
と、自分できちんと言語化してみて思ったのですが、元コメントにあった"ほかのチームからわかりやすいように"というのは、
プロジェクト内の別チームのこと、を指すということでよさそうですね。（プロジェクトの外にある別チーム、というのは当然あると思いますが、プロジェクトスプリントの仕組み上、特に検討する必要がなく、どちらかというとイベントの概念で処理される）

そのうえで 2トラック = チームとするか、3 トラック ≠ チームとするか、ですが、
https://github.com/copilot-jp/project-sprint/issues/62#issue-642501583
で トラックは人 = チームではなくて、マイルストーン = 成果物で定義されるもの、という議論が既にされています。

なので結論としては、次のようになると思います。
- プロジェクトスプリントにおいて"複数チーム"というときは、プロジェクト内にある何らかの機能別のチームのことをいう。これは、トラックとイコールになることもあるものの、トラックは一義的にはマイルストーンで定義される。
- マイルストーンの定義が"他のチームのメンバーからみてわかりやすい"ことは、記述としては特に問題ないが、それに加えて、"他のトラックとの依存性がわかりやすいこと"が重要。
って感じでしょうか。

cc @yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ただトラックのないようなプロジェクトの場合には"ほかのチームのメンバーからみてわかりやすい"といえないので、この場合は、"プロジェクトの外にいるメンバーがからみて客観的にわかりやすいこと、自分たちへの影響がわかるようにすること"と書くしかないでしょうね。

cc @yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なんやかんや理屈をこねましたが、
https://github.com/copilot-jp/project-sprint/issues/62
https://github.com/copilot-jp/project-sprint/issues/162
これらと一緒に修正して更新します。

@yoneyama-tomohiro

**Comment by Satoshi-Matsumoto** [comment]
"チーム"は同じ目的を持った人の集まりである。
そう考えると、整理としては、
- トラックはマイルストーンで定義される
- トラックを進めるために集まった人たちは「チーム」と呼んでよい。
なので、「マイルストーンを他のチームメンバーがみてわかりやすいようにする」という表現は別に問題ない。

ドキュメント上の結論としては、修正の必要なし。

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro 問題なさそうであればクローズください！
