### ISSUE TITLE
ミーティングにはタイマーだけでよいのか、時刻が分かる時計があればよいのかを検討

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#148]
タイマーを複数個用意しようという意味ではないです。絶対時刻を表示する時計があったほうが良いという話です。

その理由です。

・ミーティングが遅れて/はやめに始まることがあるので、絶対時刻を把握するものがあったほうがよい。
・タイマーが鳴っても多少そのままアジェンダを延期する場合があるので、ものすごく厳密にタイマーを管理しないかぎり、タイマーの時間の総和が会議の時間になることはない。
・会議を延長する際に、何時まで伸ばします？みたいな会話の時も現在時刻がわかるものが欲しい。

この観点で時刻がわかる時計とタイマーがあったほうが良いなとおもっています。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479773738_

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん、コメント読んで一度検討ください。

**Comment by Satoshi-Matsumoto** [comment]
元リンクがたどりにくかったので取り急ぎ貼っておきます。
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479773738

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
意図理解しました。
a0338d93322cefbd84c17309c7e62d0f097aff2f
こんな感じでどうでしょう。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/4c45702897e03901e1edbb91e326f883e20d44fb
用語統一しました。ってこの使い方であってるよね？

**Comment by Satoshi-Matsumoto** [comment]
@motoi ありがとうございます。問題ないです、クローズします。
