### ISSUE TITLE
ホワイトボードという名称がアナログを感じすぎるので調整したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#149]
@Satoshi-Matsumoto 
ここにコメント書いた記憶があるんだけど、他のところと被ってたらすみません。

これホワイトボードだとフィジカルなモノが想起されすぎる感があるなと。
本文中ではフォローしてくれているけどタイトルの雰囲気を変えたい。
「手書き入力により認識合わせするツール」
みたいなニュアンスがわかるタイトルにできないですかね。
パッとひらめかないようであれば後ほどのバージョンで検討でよいです。
スゲー問題だとはおもっておらず、なんかアナログっぽい感じするなとおもったので。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#r479774157_

**Comment by motoi** [comment]
@Satoshi-Matsumoto ここなんかよい表現ないか検討したいんだけど、あんま違和感ない？

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
これ
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479571419
こっちの流れもありますが調整必要です？

**Comment by motoi** [comment]
必要ナイです。

**Comment by Satoshi-Matsumoto** [comment]
@motoi はーい、閉じちゃいます。
