### ISSUE TITLE
PJS.orgにfavicon設定したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#15]
優先度は高くないですが！

**Comment by motoi** [comment]
faviconだけじゃなくてiOSとかでショートカットをデスクトップにおくやつとかも設定難しくなければおねがいします！ @kikuchiharuma さんかな。ヨンさんもここに呼ぶ？

**Comment by kikuchiharuma** [comment]
追加
https://github.com/copilot-jp/project-sprint/commit/87042391201ad602d8c775f346634616e4ed4505
