### ISSUE TITLE
マイルストーン作成までの流れの記述修正

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#150]
実務で一番多いパターンは、
ゼロからみんなで議論するして、発散的に意見をみんなでだし、なんとなくマイルストーンの形が見える
ぐらいまでミーティングで行い、その精査やら整理を誰かが作業してきて、チームメンバーみんなで改めて議論する、という流れが一番おおいかなとおもいます。
いきなり誰かがたたき台をもってくるというのはほぼないんじゃないかしら。

このコメントを考えてみて、チュートリアルやチップスは、理想の流れと、実際にはどういうケースが多い、というものを明確にしながら並記するのがよいんじゃないかとおもいました。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479775660_

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479070807

も同様の問題。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
これなんですが、私は

理想:みんなで考える
現実:実務でだれかがドラフトする

だと思ってました。
過去メソッドチームだと、菊池さんがドラフトしていたり、私がこうだと思いますと言っていたり。
他の議論でも、一番わかっている誰かが書いてよ、という流れが多かった気がしていて。
その前の、発散的にみんなで考えてみる、みたいな段階って私の過去の経験だとぱっと思いつかないのですが…

とはいえ実務ベースの意見だと @motoi さんのほうが実例を多く見ていると思うので、言われたていで直してみます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
43ddd1267405b512e201c034a2f7132598804d51
こんな感じでしょうか。

**Comment by motoi** [comment]
ほんとは理想形でやりたいよね、それは時間がかかるけど必要なプロセスであることもあるよ、とかまで書きたいけど、まあマニュアルっぽくて良いなと思ったのでこれでクローズで！
