### ISSUE TITLE
マイルストーンの書き方のコツとして「足並みをそろえる」ニュアンスの内容を追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#151]
@Satoshi-Matsumoto 
プロジェクトにおける足並みを揃えた実績としては以下のようなものです。

・広報チームのマイルストーンに合わせて、他のチームが自発的にアウトプットを用意する
・プロダクトチームの進捗状況に合わせて、プロダクトのデリバリーチームが自分たちの取るべき行動を変えていく

もっと詳しく書いたほうが良いかしら？

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479779581_

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
足並みをそろえるってそういうことですね。表現ぶり含めて修正検討します。

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/162
の内容を受けてさらにニュアンスを追加するか検討

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このissueの内容はたぶん意味的には #162 で話した内容でカバーされていると思いました。

そのうえで、このissueで例示されている内容も踏まえて、追加で修正を加えました。
ecac25ddae8fefae9ffbdcb679e5a3f407e5df07

マニュアルとしてはより具体的にどういうことかをイメージしてもらう記述があるのかを書く必要があると思ったので、それを反映しています。

ご確認 & 問題なさそうであればクローズください。

cc @yoneyama-tomohiro

**Comment by motoi** [comment]
よいとおもいました！こういう説明している！
