### ISSUE TITLE
フェーズの終わりに振り返りを行う理由を記述するか検討

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#152]
@motoi 

読点いれました。
eda9158e580657dad8c8d65dc232bf24fda1819b

フェーズ終わりのほうなんですが推奨する理由について少し材料もらえますか？これまでの議論でも自分がいまいちぴんと来ていないことに気づきました。「キリがいいからやっておく」っていう以外にあんまり説明ができず、それもそうなのかなと思いつつ、なんかぼやっとした理解な気がしていて。

そこのところはファイル読んでもやっぱりよくわからず…ちょっと素材をもらえると助かります。

それでも紛糾しそうならissue化します。

_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479661815_

**Comment by motoi** [comment]
定金が一回理由をまとめる

**Comment by motoi** [comment]
きりが良いから、に実は尽きるのではないかとおもっていて。
きりが良い≒意味的に区切りができている
ということで、以下の目線の両方において振り返ることができるということかと。

・意味的な区切りなのでプログレスの振り返りがしやすい
・フェーズのスタートからゴールまでのプロセスの振り返りもしやすい
・フェーズが次に続く場合は次のキックオフにもなりうること

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なるほど。
864d73c92de75887d059b6882ea07c60f14ad574
こんな感じでしょうか？

- プロセス / プログレスという言葉はManualでは使いすぎると硬くなるので避けています
- フェーズという言葉の利用はTips読んでいる前提になってしまうのでいちおうここでは避けました。意味的には普通に通るので問題ないかと

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/b1ca20345226c0ef851ba367b348944d01aa15d8
こんな感じに補足しました。
問題なければクローズで１

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ありがとうございます。内容的には異論ないんですがちょっと表現だけ変えました。「不確実性」という言葉の硬さだけManualではとりたくて、それを反映したものです。
6be68c0f0790dc86c55f15ff6561b4d791d5538a

**Comment by motoi** [comment]
というか私の書いている方が超冗長なので改善案のほうがとてもよいとおもいました！
マニュアルは硬くしたくない、の方向性も理解です。
