### ISSUE TITLE
プロジェクトの足並みをもっと想像しやすい表現にしたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#153]
@Satoshi-Matsumoto 
プロジェクトにおける足並みを揃えた実績としては以下のようなものです。

・広報チームのマイルストーンに合わせて、他のチームが自発的にアウトプットを用意する
・プロダクトチームの進捗状況に合わせて、プロダクトのデリバリーチームが自分たちの取るべき行動を変えていく

もっと詳しく書いたほうが良いかしら？

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/pull/132#discussion_r479779581_

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
サトマツさんまずはご意見くださいー。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/issues/151
こっちとかぶっちゃってますね。
#151
のほうに集約するので、こちらは閉じます。
