### ISSUE TITLE
フェーズの概念の修正

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#154]
ba114e14bf1ea30673b3cc3274754d695ee3a0a6
を受けて、 @motoi さんより、
https://github.com/copilot-jp/project-sprint/pull/132#commitcomment-41890165
https://github.com/copilot-jp/project-sprint/pull/132#commitcomment-41890257

**Comment by Satoshi-Matsumoto** [comment]
いったん @Satoshi-Matsumoto が修正案考えます

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/pull/132#commitcomment-41890257
でもともといただいた内容でしっくりきたので、ママ採用しました。

0701477afa5c7b717d550c1a52f296c9f43e617e

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/bae65dbf111e0b0381aa6774e47eaccb97cf28ee
ちらっとだけ修正しました。問題なければクローズしてくださいー。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 問題ないです、ありがとうございました！
