### ISSUE TITLE
チュートリアル・チップスのページ内の導線が少ない

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#156]
ディレクトリ内に遷移するリンクだったり、トップに戻るリンクだったりがページのフッタにあるような構造の方が良いのではないか。CODEの方が随分と見やすく遷移できるので、比べちゃってるところもあるけど、同じようなものがあると良いと感じた。

きっかけ：
メルマガで以下のページへのリンクがあって、あれおもったよりこのページから外にリンクしてないなと気づきました。
https://projectsprint.org/ja/manual/tips/tips4.html

**Comment by motoi** [comment]
@Satoshi-Matsumoto さんに一旦検討お願いしてみます！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
まずは ドキュメント内にマークダウンで記述できるレベルで、検討します。
ページ全体のheaderとかfooterにしたほうがいいじゃん、みたいなものになってきたら、 @kikuchiharuma さんに相談ということになるかなと。

**Comment by motoi** [comment]
閲覧した人から、チッブスのフッタのリンクがリンク切れしてるとの報告もあるのでそこも合わせてチェックくださいー。

**Comment by motoi** [comment]
チップスのフッタリンクが全部きれてる。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/pull/165
リンク切れの件だけ直してマージ、liveに反映しました。

**Comment by Satoshi-Matsumoto** [comment]
修正の方向性
フッタに、サイトの構造が理解できるように全部のリンク並べてしまう。メガナビっぽいやつ。

@kikuchiharuma さん、このissueサイトの構造？しくみ？で解決したく。
イメージ図つくって、このissueのなかで。ご相談します。

**Comment by kikuchiharuma** [comment]
@motoi こんな感じになっております。どうでしょう。https://6151b24e649be90008e1aa6c--project-sprint-staging.netlify.app/
