### ISSUE TITLE
ミートアップ開催情報がSlackコミュニティにながれていない

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#158]
コントリビューター向けページに書いてあることが実現されていないため。

**Comment by motoi** [comment]
ミーティング終わりに、次回ミーティングを掲載するルーチンをつくる、もしくは公開のグーグルカレンダーにしてそのURLを貼っておく、どちらかかなー。

**Comment by motoi** [comment]
そもそもそういう人が来たら
・ファイルをどこで管理するのか？
・SGMsのPJSチームに入ってもらってよいのか？
など懸念点が多い。
そもそもコパユニバ以外のコントリビューターが入ってきたときの環境をつくる必要がある。

ファイル共有 → 専用の共有ドライブ
SGMs → トラックのみシェアという機能がつくまでは、画面共有でみてもらう、もしくは別途プロジェクトを立てる

**Comment by yoneyama-tomohiro** [comment]
- Slack上で次回ミーティングを掲載するルーチンをつくる

**Comment by motoi** [comment]
実践し始めたのでいったんクローズ！
