### ISSUE TITLE
プロセスドメインにおける理想状態を表現するのか？を検討

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#159]
CODEから修正

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
すみません、これたぶんPJSメンバーまたはCPメンバーからのフィードバックで出てきたものだと思うのですが、
どういうイシューでしたっけ。。。。ちょっとタイトルだけだとわからず

**Comment by Satoshi-Matsumoto** [comment]
PJS の一枚概念図にプロセスの理想状態がないので入りうるのか？の検討でした

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/98238734-317b5600-1faa-11eb-8b12-a35ea85891b8.png)
この絵の一番右の黄色の部分。

**Comment by Satoshi-Matsumoto** [comment]
アサイン変更します。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @yoneyama-tomohiro

このイシューですが、次のように修正しました。
b3c0548b44c9bfaa1cb091c5b1922b49992b5d37

https://projectsprint.org/ja/code/theory/basic.html で
> プロジェクトは、プログレスとチーミングのステータスを理想的な状態に近づけることを目的としている。

と書かれています。たしかに、プログレス / チーミングが理想の状態 になることがプロジェクト / プロジェクトスプリントの目的だ、といえると思うのですが、プロセスが理想状態になることがプロジェクト / プロジェクトスプリントの目的だ、というのはちょっと違う気がします。なので、「プロセスの理想状態」を定義して、プログレス / チーミングの理想状態と同列に考えるのは難しいのではないかと。

いっぽう、確かにプロセスについて「これがベストだ」みたいなものはある気がします。ただそれは、プログレス / チーミングを理想に近づけるために最も効率的 / 効果的 = 最適化された状態、ということなのかと思いました。

とりあえず一義的に @motoi さん、ご確認ください。

**Comment by motoi** [comment]
> プロセスが理想状態になることがプロジェクト / プロジェクトスプリントの目的だ、というのはちょっと違う気がします。


> いっぽう、確かにプロセスについて「これがベストだ」みたいなものはある気がします。ただそれは、プログレス / チーミングを理想に近づけるために最も効率的 / 効果的 = 最適化された状態、ということなのかと思いました。

これですね。すごく納得できた。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
修正もよいとおもいました！
