### ISSUE TITLE
自分で意思決定をして行動はどうしたらできるのか

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#162]
Tipsか？も含めて検討

**Comment by Satoshi-Matsumoto** [comment]
※マニュアルにおけるマイルストーンの設定の話です

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、

このissueですが
https://projectsprint.org/ja/manual/tutorial/section2-1.html
の、下記の記述太字部分に対するものです。

```
#### マイルストーンの設定
マイルストーンとは、具体的な成果物とそれに紐づく期限をセットにして記述したもののことです。マイルストーンはゴールに向けて複数あることがほとんどです。

マイルストーンも、ゴール同様最初のドラフトは誰がつくってもかまいませんし、一人でつくっても複数でつくってもかまいません。
ただし、これもゴール同様、マイルストーンはチームメンバー全員に明文化されたかたちで共有され、全員が納得された状態になるまで議論されなければいけません。そのため、みんなが理解しやすいように、極力シンプルなものになるよう心掛けてください。

マイルストーンの粒度は、ゴールとの距離感によってばらつきが出てもかまいません。ただし、マイルストーンを見たチームメンバーが、**それぞれ自分で意思決定をして行動できる粒度を持っている必要があります。**
なお、通常、直近のマイルストーンは期日・成果物ともに具体的なものになり、ゴールに近いものほど抽象的で大まかな記載になります。

マイルストーンが作れないときは、ゴールを見直してください。前述のように、ゴールにはマイルストーンがかける程度の具体性がある必要があります。

```
更新内容によって同じセクションを更新するか、tipsにするか検討しようと思いますが、
「自分で意思決定して行動できる粒度」にするための方法や、具体例（どのようなものであったらよくて、どのようなものはわるいものなのか）という点についてすでに得られている実践知はありますか？

cc @yoneyama-tomohiro

**Comment by yoneyama-tomohiro** [comment]
自分の行動についての意思決定

**Comment by yoneyama-tomohiro** [comment]
- メタな状況の理解
- 間違っているかもしれない仮説を提示し、行動できる安心感

**Comment by Satoshi-Matsumoto** [comment]
2020/9/24時点で、解がないため、manual v0.9.0からはスコープアウト。記述できる内容ができ次第、 @motoi さんからアップデート。

**Comment by motoi** [comment]
マイルストーンを書く粒度、抽象度はプロジェクトによって異なる。
自分たちのチームについてはもちろんのこと、同じプロジェクトの違うチームから見て、違うチームの行動が決定できるレベルにすることが望ましい。
そしてその状態というのは自分たちでわからないこともあるので、みんなでマイルストーンマップに意見をしあって、常に自分たちの行動が起こせる状態をつくりつづけることが大事である。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
コメント受けまして、
87199eea282aad6f419bc80c0e8dba6e7c452990
こんな感じで、どうでしょう？

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/a58343f0038fc01c401439e03f8cde96f345ec8b
ちとだけ修正しました。問題なければクローズで！

**Comment by motoi** [comment]
ちなみに人のブランチにコミットしてそれをここにリンクを貼るのがすごく面倒なのでいいやり方あったら知りたい。。ちょい修正とかならブラウザから直接ブランチにコミットできればよいのにできない。。。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 修正ありがとうございます、良くなったと思いました。

> ちなみに人のブランチにコミットしてそれをここにリンクを貼るのがすごく面倒なのでいいやり方あったら知りたい。。ちょい修正とかならブラウザから直接ブランチにコミットできればよいのにできない。。。

やり方はすみません、定金さんがどういうやり方でやっているのかがわからないとどうにもコメントできないっす。。。

とりあえずこのissueの内容としては完結しているのでcloseします。
