### ISSUE TITLE
タスクの作成の重要項目・ポイントを記述する

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#163]
tips？かも含めて検討

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、

このissueですが、「タスクを記述するときにどのようなことに気をつければよいか」
という感じのタイトルでtipsを一つ作るのが良いと思います。

タスクに関する何らかの実践知など、ありますか？

@yoneyama-tomohiro

**Comment by motoi** [comment]
タスクの実践知はこちら
![image](https://user-images.githubusercontent.com/680855/94140836-d59bb880-fea6-11ea-98c7-87077a8aa0d6.png)
![image](https://user-images.githubusercontent.com/680855/94140871-e2b8a780-fea6-11ea-961e-debcabb33f9b.png)

**Comment by yoneyama-tomohiro** [comment]
29日（月）AM中までに見ます。

**Comment by motoi** [comment]
9/28 月 朝：サトマツさんアップ
9/28 月中にフィードバック
修正あれば 9/30 火曜日に更新

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
2e9fc8c03e401b5577650ee4c80a0f32c85b72f6
追加してみました。

もらった図と意識的に変えている部分だと、「想定成果物」のところは「想定アウトプット」に変えています。
https://projectsprint.org/ja/manual/tips/tips3.html
の定義だと、タスクの完了結果はアウトプットになり、成果物はマイルストーンと対応するためです。（このtips書いててよかったなーとおもいました、日の目をみた。。。。）

ほか導線追加や関連文言の調整は、下記です。
e946bb6b678312d202a1b53945b219b8ab146613
680b2ccf8b5f5cf46caa94097687d6f07fed61a3
aa35df5fa319504cb104564609965a69557e3c16

どでしょう？ご確認のうえ問題なければこのイシュークローズください。

@yoneyama-tomohiro

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
![image](https://user-images.githubusercontent.com/680855/94367365-2dd9f100-0119-11eb-9dfa-f314ccb26dc1.png)
言いたいことはこのスクショの部分もあって。
・リーンのMVPのように目的が達成できる必要最小限のサイズをつくってこよう
・次のMTGまでにアウトプット可能なサイズにしよう
このニュアンスを足してもらいたいです！

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
あとこの2つも書きました。
https://github.com/copilot-jp/project-sprint/commit/aa35df5fa319504cb104564609965a69557e3c16#r42762083
https://github.com/copilot-jp/project-sprint/commit/e946bb6b678312d202a1b53945b219b8ab146613#r42761994

**Comment by Satoshi-Matsumoto** [comment]
対応しました。

> 言いたいことはこのスクショの部分もあって。
> ・リーンのMVPのように目的が達成できる必要最小限のサイズをつくってこよう
> ・次のMTGまでにアウトプット可能なサイズにしよう
> このニュアンスを足してもらいたいです！
は
74f27c827ab96bb3d4928038635eb1f4d1d4d9e3
a4050d57fffca3409d88bc64e880ab4b1bb4f27c
で。目的に沿って小さくてもいいから確実にアウトプットしていこうよ、ということだと捉えました。そのニュアンスを入れています。

https://github.com/copilot-jp/project-sprint/commit/aa35df5fa319504cb104564609965a69557e3c16
は
34d4c5f3147c476a9cb16245d76aad80bc0166cf

https://github.com/copilot-jp/project-sprint/commit/e946bb6b678312d202a1b53945b219b8ab146613#r42761994
は
41409a18521c74967f0381467b2d78197f215a1a

でそれぞれ対応しました。

**Comment by motoi** [comment]
よいとおもいます！クローズ！
