### ISSUE TITLE
マニュアルにfigureを適宜いれたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#164]
ターゲットによると思うのですが、全体的にもじもじしいので、ちょっとでもイラストが入ってたりするといいのかもなあと思ったりしました。内容よりも先に文字と文字がすごいつまってるなと思ってしまったというか……。
デリバリー平林

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/77
がCODEの話なのですがそれのマニュアル版です。

**Comment by Satoshi-Matsumoto** [comment]
@motoi  @yoneyama-tomohiro
この話ですがまずどんな図があるといいかある程度案出したあと個別issue化、 @kikuchiharuma さんにお願いしてfigureにしていってもらうという進行でどうかと思います。

というわけで、お二人からどういう図があるかざっくりご意見もらいたく。

いますでにあがっているのは、↓のトラックの概念を説明するための図。
https://github.com/copilot-jp/project-sprint/issues/141

また、PJSの概念図の一枚絵は↓にあってもよいと思っています。
https://projectsprint.org/ja/manual/tutorial/section1-2.html
たとえば「インクリメンタルに～」みたいな文言はTutorialには登場していないので、多少デフォルメ（？）はしたほうがいいかもしれませんが‥‥

まず @yoneyama-tomohiro さん、いかがでしょう？
見解をコメントで残していただいたあと、 @motoi さんにアサインを変えてください。

**Comment by yoneyama-tomohiro** [comment]
25日（金）AM中にコメント

**Comment by motoi** [comment]
定金も案をだし、必要な図を決定し、イシューをたてて別途進行する。

**Comment by yoneyama-tomohiro** [comment]
0.9版は、菊池さんスタイルの絵でなくてもよい。

**Comment by motoi** [comment]
サトマツがとりあえず定金スライド芸の絵をいれて更新してみる → 違和感あるユーザーにみてもらって確認する

**Comment by yoneyama-tomohiro** [comment]
https://projectsprint.org/ja/code/theory/basic.html
・追加ではありませんが、一番下の概念図は一番上の方に置いた方が良いかと思いました（図の存在に気づかないため）
・3つのドメインの関係図
---
https://projectsprint.org/ja/code/theory/advance.html
・
---
https://projectsprint.org/ja/code/practice/basic.html
・
---

**Comment by motoi** [comment]
@yoneyama-tomohiro これコメント終了してます？中黒だけあったりとかよく読み取れず。。。。そして終わってるということであればアサイン付け替えてくださいー。

**Comment by yoneyama-tomohiro** [comment]
@motoi 
アサイン変えを失念していました。
私のコメントは終わっていますので、よろしくおねがいします。

**Comment by motoi** [comment]
https://projectsprint.org/ja/code/practice/basic.html
ミーティング環境は図示したほうが分かりやすいのではないかなと思いました。

継続的改善アプローチを定期的に行う必要がある理由でよく話すものを図で入れてもよいかとおもいました。
そのためにはプロジェクトの性質を理解する必要があって。理解のためには比較表が重要。
![image](https://user-images.githubusercontent.com/680855/94328981-21a74400-fff2-11ea-82d7-577e4273f832.png)
プロジェクトにおけるプロセスがいつ始まっていつ終わるかがわからないので定期的に行う必要がある。
![image](https://user-images.githubusercontent.com/680855/94328949-d0975000-fff1-11ea-9f64-522a64d75ef8.png)
この辺があると定期的に振り返りする必要が分かりやすいかなと。

https://projectsprint.org/ja/code/practice/advance.html
発散収束共有の部分は絵の方が分かりやすいと思いました。

https://projectsprint.org/ja/manual/tutorial/section1-2.html
エッセンシャルズのPJSにあるPJSの3つのドメインを表示する1枚絵的な全体像と3つのドメインがわかるものを入れてもよいと思いました。

https://projectsprint.org/ja/manual/tutorial/section2-1.html
ゴールやマイルストーンの構造を図示したほうが分かりやすいと思いました。

定金は以上。この後に選定します！

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん、まとめです。

https://github.com/copilot-jp/project-sprint/issues/164#issuecomment-691999291
このサトマツさんのコメントにあるように、一旦、今回はマニュアル版の図を載せましょう、というイシューになっている。
ということだと以下の二つを対応したいなと思います。

> https://projectsprint.org/ja/manual/tutorial/section1-2.html
> エッセンシャルズのPJSにあるPJSの3つのドメインを表示する1枚絵的な全体像と3つのドメインがわかるものを入れてもよいと思いました。
![image](https://user-images.githubusercontent.com/680855/94330903-5bcd1180-0003-11eb-833d-d155fa296b78.png)
⇒ この絵のことなんですけど、このまま「理論のベーシックより引用」みたいな形で載せるのか、もっと省略版にするのかを検討してもらえればとおもいます。私は今回は一旦引用で載せればよいんじゃないかなとおもいました。

> https://projectsprint.org/ja/manual/tutorial/section2-1.html
> ゴールやマイルストーンの構造を図示したほうが分かりやすいと思いました。
⇛ こちらは以下の2枚の絵あたりが参考になるのかなと思いました。
![image](https://user-images.githubusercontent.com/680855/94331426-2cb89f00-0007-11eb-94f5-fafec061faf5.png)
![image](https://user-images.githubusercontent.com/680855/94331451-61c4f180-0007-11eb-83b7-7fcae69093b3.png)
2つ目の絵が参考になるんじゃないかなとおもいました。がこれはサトマツさんとしてどんな絵があったらよいかという意見がほしいかなと思いました。

ということでサトマツさんご確認ください！

**Comment by Satoshi-Matsumoto** [comment]
@yoneyama-tomohiro @motoi 
お二人とも、コメントありがとうございます。まずCODEに関するものはこちらに転記しました。よってこのissueからはスコープアウトします。
https://github.com/copilot-jp/project-sprint/issues/77#issuecomment-699512146

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
残る対応ですが[私がコメントしている分](https://github.com/copilot-jp/project-sprint/issues/164#issuecomment-696537661)と合わせると下記3点ということですね。
①Tips1にトラックの概念を説明する図の追加
②https://projectsprint.org/ja/manual/tutorial/section1-2.html に概念図の追加
③https://projectsprint.org/ja/manual/tutorial/section2-1.html にゴールとマイルストーンの関係図を追加

①については @kikuchiharuma さんにfigureを#141 で依頼する一方、 @motoi さんのスライドで対応。
=> 対応しました 6db6468824862a3f11a3e623fd29fd1e44a8d15b & 3ea5ed8b91ca2e615483cb9a97ddc838511d3473

②については @motoi さんの言う通りいったん引用で対応しましょう。
=> 対応しました 5e4216043785bdc744a122983503d5d143dea508

③についてはだいたいイメージあっていますが、PJS一枚絵から抜粋するのがよいのでは？と思いました。添付してくれた図だとゴールとマイルストーンの関係以外も入ってくるので。（Tipsでしか説明していないイベントの概念など）
=> 対応しました 837b692e5ea0b83d78ea0e060f4880186ebca2f0

cc @yoneyama-tomohiro

**Comment by motoi** [comment]
@Satoshi-Matsumoto コメントしました！
> ①については @kikuchiharuma さんにfigureを#141 で依頼する一方、 @motoi さんのスライドで対応。
> => 対応しました 6db6468 & 3ea5ed8
https://github.com/copilot-jp/project-sprint/commit/6db6468824862a3f11a3e623fd29fd1e44a8d15b#commitcomment-42762325

> ②については @motoi さんの言う通りいったん引用で対応しましょう。
> => 対応しました 5e42160
https://github.com/copilot-jp/project-sprint/commit/5e4216043785bdc744a122983503d5d143dea508#commitcomment-42762242

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正対応しました！
①
3e64f92534a211cd5720e05f3441b267a4430bcc
d4da3802ee96f350727bd3faf26c2d63446b722d
②
04443cdc05b7b4ac08287f15e83d8c827d9e51e2

ご確認ください。

**Comment by motoi** [comment]
よいとおもいます！
