### ISSUE TITLE
マークダウンの表が崩れている

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#166]
https://projectsprint.org/ja/manual/tips/tips2.html

![Screenshot_20200920-173258.png](https://user-images.githubusercontent.com/680855/93707219-7ae12480-fb67-11ea-82c7-42816c81492c.png)

**Comment by Satoshi-Matsumoto** [comment]
CODEv2.0.0でなおしているので、クローズしてしまいます。 @motoi 
https://projectsprint.org/ja/code/tips/tips2.html

![image](https://user-images.githubusercontent.com/61894329/107146089-61f8c600-68f2-11eb-8091-333bee2d722d.png)
