### ISSUE TITLE
pjs.orgの言語トップページがCODE⇒マニュアルの掲載順位になっておりCODEを読んで「難しい…」とおもって離脱する人がいる

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#169]
ドキュメントの比較表を早めに登場されるのか、いっそマニュアルの方を先に表示させるのか、など初めての人にとってとっつきやすい部分から表示させるのがよいのではないか。
（コパイロツト社内からのフィードバック）

**Comment by Satoshi-Matsumoto** [comment]
CODE v2.0.0 で対応済みなので更新します。
