### ISSUE TITLE
Project Sprint ってそもそもどういうメソッドなの？などの前提情報がもうちょっと書かれていてほしい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#170]
定金が説明で使っているPJS資料のように、そもそもどういうメソッドなのか？（ミーティングを活用してプロジェクトをすするめるんです、とか）などメソッドの全体像がサッとわかるようなものがトップページなり言語トップページにないと、いきなり説明が始まりすぎる感がある。
（コパイロツト社内よりコメント）

**Comment by motoi** [comment]
https://www.youtube.com/watch?v=oblAj4a3AHQ&t=38s
これのリンク貼っても良いかもしれない。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 何か素材あります？これまでの導入時の資料とか。

**Comment by motoi** [comment]
PJS導入のための紹介資料から
![image](https://user-images.githubusercontent.com/680855/107115182-2c31ee00-68ae-11eb-81d2-7c23a2d0929f.png)
![image](https://user-images.githubusercontent.com/680855/107115195-3b18a080-68ae-11eb-8242-9f06f866374d.png)
![image](https://user-images.githubusercontent.com/680855/107115201-453a9f00-68ae-11eb-922f-de2c4233322c.png)

**Comment by motoi** [comment]
PJS概要資料v2
![image](https://user-images.githubusercontent.com/680855/107115260-b8441580-68ae-11eb-822e-26661e9f0718.png)
![image](https://user-images.githubusercontent.com/680855/107115266-c1cd7d80-68ae-11eb-859f-f01a62c42bcf.png)
![image](https://user-images.githubusercontent.com/680855/107115284-da3d9800-68ae-11eb-8b89-9621f6e70a7c.png)

**Comment by motoi** [comment]
https://projectsprint.copilot.jp/about.html

プロジェクトをみんなで成功させるために。
チーム全体でリーダーシップを発揮するきっかけをつくります。

年々、社会の変化のスピードは上がり、プロジェクトも常に変化を要請されるようになりました。解決しなければならない問題は複雑になり、未来の予測がいっそう難しくなってきています。その状況下において、プロジェクトをより良い形で推進していくにはどうしたらよいでしょうか。

プロジェクトを率いるリーダーだけがリーダーシップを発揮するのではなく、関わるメンバーが、多様な視点でプロジェクトに向き合い、進む方向や解決策を模索、検討できるようになったほうが良いのではないか。
さらに、複雑な問題に対し柔軟に対応できるツールが存在していたら、多くのひとがもっと安心してプロジェクトにコミットできるのではないか、とわたしたちは考えました。

コパイロツトはこれまで、数々のプロジェクトの推進支援をしてきました。その経験を参照しながら、チームで行うプロジェクト推進の汎用的な方法論とツールを開発しました。

わたしたちはひとつでも多くのプロジェクトを成功させたい。
そして、そのためには関わるすべてのメンバーが各々のリーダーシップを発揮できるよう、プロジェクトの状態や環境を整える必要があります。コパイロツトはその環境作りのきっかけと、プロジェクトを成功に導くプロセスを提供します。

プロジェクト推進メソッド
Project Sprint
これまでわたしたちが推進したプロジェクトの成功事例を振り返ってみると、どの場合においても「定例ミーティングの雰囲気が良い」と気づきました。そこからわたしたちは定例ミーティングに着目し、Project Sprintという方法論を練り上げてきました。
Project Sprintは不確実性が高い状況でより効果を発揮するプロジェクト推進メソッドです。
定例ミーティングを活用し、タスクの検討、決定、実行を推し進めることでプロジェクトがドライブします。

Project Sprintが向いているプロジェクト
不確実性の高い環境・状況、複雑なアウトプットが求められるプロジェクト
部門/組織横断のチーム、多様性のあるメンバーで構成されたプロジェクト

**Comment by motoi** [comment]
@Satoshi-Matsumoto これぐらいでどうでしょう？！

**Comment by KokoroKagawa** [comment]
@motoi 1点気になったのですが、orgってどこ経由での流入が多いのでしょうか。
もし https://projectsprint.copilot.jp/about.html からが大半ということであれば、文章丸かぶりになるのでちょっと冗長かなとも思いました。

そこを気にしなくてよいのであれば、文章これでよいかと！
置き場所は言語ページではなくトップページに日英併記を想定しています。

**Comment by motoi** [comment]
> orgってどこ経由での流入が多いのでしょうか。
現状はこれはあんまり気にしなくてもよいかとおもいました。
同じこと言っても良いと思いますし。

文章ですけど、方法論とツールとかもいっているので、SGMsも含まれています。
これを参考に多少はリライトしてもらえればと思いましたー。

**Comment by KokoroKagawa** [comment]
v.3.1.0待ち（プロジェクトスプリントのコア概念の整理）。

**Comment by KokoroKagawa** [comment]
一旦対応完了ということで。
>定例ミーティングで取り組みの成果を共有して環境への認識を揃えることを繰り返し、プロジェクトチームが進化するプロジェクトゴールを自律的に達成しつづけるためのメソッド。
