### ISSUE TITLE
[Manual のCODEへの反映] プロジェクトのゴールの記述の追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#178]
Manual v0.9における
https://projectsprint.org/ja/manual/tutorial/section2-1.html
の、プロジェクトのゴールの記述を、CODEに反映したい。

いまCODE上でゴールについては深ぼった説明がないので、これに対応するように。

**Comment by Satoshi-Matsumoto** [comment]
#90, #185, #186 でマイルストーンの更新が終わってから。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
プロジェクトのゴールについて
https://projectsprint.org/ja/manual/tutorial/section2-1.html
における「プロジェクトのゴールの設定」の部分をCODEに反映しました。

a4fdc78566d16f88d3a42f29dd8c3aa5fb0c1a08

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
このイシューの内容的にはマニュアルからもってこようということであればこうなるってのは理解です。

これ前に議論していた、マニュアルとCODEが似すぎる印象になるやつかもとおもいました。
マニュアルに「ここはコードからの引用だよ」ってのがわかるようになっているとよいのかもしれない。
（これはCODEのベーシックとアドバンスとかの関係でもその引用ができていると、同じこと書いてるね問題、が解消するかも）とおもいました。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
> このイシューの内容的にはマニュアルからもってこようということ

はいそうです。基本的にはCODEとマニュアルの差分解消、マニュアルにあってCODEに必要な概念・抜けている概念の追加なので。

マニュアルとCODEが似すぎる印象問題は、どちらかというと引用表現で解決するべきものというよりは、CODEに必要な内容を洗練する（マニュアルとのかぶりをなくす or 役割の違いを明確にする、など）ことで解消すべきと思います。これは別マイルストーンでの議論ですね。

というわけで、このイシューはクローズします。
