### ISSUE TITLE
[Manual のCODEへの反映] マイルストーンの記述の充実

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#179]
この定義をCODEにも反映
> マイルストーンとは、具体的な成果物とそれに紐づく期限をセットにして記述したもののこと

この文言に相当するものを追加
> マイルストーンはチームメンバー全員に明文化されたかたちで共有され、全員が納得された状態になるまで議論されなければいけません。そのため、みんなが理解しやすいように、極力シンプルなものになるよう心掛けてください

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
まずissueの内容ご確認ください。manual の
https://projectsprint.org/ja/manual/tutorial/section2-1.html
をもとにして出してきたものです。

そのうえで、
3b75ea901d13b0756e08b1c17e833bbb5b3cf4ec
みたいな感じで修正してみました。

そうですね、であればクローズ。
記述内容に対して違和感があればその点をコメント。
こういう視点もCODEに反映したい、ということであればそのあたりのコメントください。（これは、内容によって別issueにするかどうかなど考えます）

cc @yoneyama-tomohiro

**Comment by motoi** [comment]
これはこないだの成果物とかアウトプットとかアウトカムの話から整理が必要だとおもうので、このあたりで整理し始めました。
整理しきったら追記してもらうと思うのでこちらはクローズ！
https://github.com/copilot-jp/project-sprint/issues/207

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/144
アウトカム議論はこのあたりで！
