### ISSUE TITLE
[英訳]日本語版からなくなったロールがEssentialsに残っている

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#18]
https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/en/essentials/index.md#progress-management

**Comment by motoi** [comment]
日本語と英語でバージョン変えるとか、日本語がある程度まとまったら英語にするとか、効率良きやり方も含めて  @Satoshi-Matsumoto さんのほうで検討くださいー。

**Comment by Satoshi-Matsumoto** [comment]
いちどv1.0.0のタイミングで英日揃えますね。
そのあと、たぶん一つ一つの修正がそこまで大きなボリュームにならない（たぶん）ので、並行運用でいけると思います。

**Comment by Satoshi-Matsumoto** [comment]
#241でCODE2.0.0に合わせて一括対応。こちらはクローズします。
