### ISSUE TITLE
[Manual のCODEへの反映] ミーティングロール、ファシリテーター・モデレーター・アクセラレーターの記述方法の調整

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#180]
Manual v0.9
https://projectsprint.org/ja/manual/tutorial/section3-1.html

> ファシリテーター：アジェンダの管理(アジェンダの合意から、その後のアジェンダ進行とタイムキープ、ミーティング終了時の次回のアジェンダの決定)および議論の促進と成果の質の向上(アジェンダの改善、その後の議論形成のサポート)をするロール。前者をモデレーター、後者をアクセラレーターとして区別して別々のロールとして割り当てることもある。

CODE v1.0
https://projectsprint.org/ja/code/practice/basic.html

> ファシリテーター
> モデレーター：モデレーターの使命は、アジェンダを管理することである。冒頭のアジェンダの合意から、その後のアジェンダ進行とタイムキープ、会議終了時の次回のアジェンダの決定等が含まれる。
> アクセラレーター：アクセラレーターの使命は、議論の促進と成果の質の向上である。会議冒頭におけるアジェンダの改善、その後の議論形成のサポート等が含まれる。

基本はファシリテーターの用語に集約して、分ける場合はモデレーターとアクセラレーターである、という記述の仕方で統一。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正必要な個所はイシュー冒頭の記述をご確認ください。
なおしました。
5dbf37328997cf880d796f43f1da181aa2c6598f

問題ないと思いますが一応ご確認 / クローズください。

**Comment by motoi** [comment]
問題ないっす。
