### ISSUE TITLE
[Manual のCODEへの反映]ミーティングロールが持ち回りだとなぜ良いのか、を追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#181]
Manual v0.9
https://projectsprint.org/ja/manual/tutorial/section3-1.html

> いずれも属人性が低いもののため、固定ではなく、ミーティングごとに持ち回りにすることが望ましいものです。**これにより、ミーティング運営に関する問題点や最適な方法について、参加者全員が自分から考えやすくなります。**

CODE v1.0
https://projectsprint.org/ja/code/practice/basic.html

> ミーティングロールは属人的な性質の低い作業であり、したがって持ち回りで担当することが可能である。

Manualの太字部分のニュアンスをCODEに反映

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正すべきポイントはイシュー冒頭の記述を参照ください。
下記で直しました。
cfd30a01115c96d02b386c2d5cb0b6d8fb9ebc17

持ち回りでもよい => 持ち回りのほうがよい とニュアンスを変更。その理由も追記しています。

**Comment by motoi** [comment]
あざす！本来の意味のファシリテーターの意味でとらえられるとそんなことないじゃん！と言われる可能性は高いけどPJSに限っていうとそういう特徴もあるよってことで。
