### ISSUE TITLE
[Manual のCODEへの反映] タスクの進捗報告の概念をCODEに追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#182]
Manual v0.9で記載されている「タスクの進捗報告」の概念はCODEにないので、プロセスを構成するものとして追加。
https://projectsprint.org/ja/manual/tutorial/section3-2.html

> タスクの進捗報告
> 初回のミーティングを除けば、前回までのミーティングを経て、何かしらの各自のタスクが生まれているはずです。これらのタスクの進捗状況を確認しましょう。
> 
> タスクをこなした結果、アウトプットが生まれている場合には、アウトプットをもとに話し合うべきアジェンダがないか確認しましょう。 もしアウトプットがなくても、進捗が思うように進まないことについての相談があったりする場合があります。このような場合も、これを解決するためにアジェンダとしてミーティング内で議論する必要がないか、確認しましょう。
> 
> なお、すでにあらかじめアジェンダとして提出されていた場合は、ここでさらに追加する必要はありません。

**Comment by Satoshi-Matsumoto** [comment]
いまのCODEではプロセスの概念の中にミーティングとアジェンダしかない。
https://github.com/copilot-jp/project-sprint/issues/86
でそれ以外の概念が追加されたのち、タスクの進捗報告も入れ込むべき。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正すべきポイントはイシュー冒頭の記述を確認ください。

なおしました。
3739d1cc83a6b155c30189f8d76a97ddeee58344

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
問題ないですー。
