### ISSUE TITLE
[Manual のCODEへの反映] テンションの定義の更新

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#183]
Manual v0.9では
https://projectsprint.org/ja/manual/tutorial/section3-2.html

> テンションとは、「プロジェクトを過ごす中で他のメンバーに伝えたい違和感」のことです。具体的には、メンバー一人一人が思う「こうしたらもっとより良くなるのに」という現状とよりよい状態の間のギャップ、ちょっとしたアイデア・気になること・不安などのことを指します。

CODE v1.0では
https://projectsprint.org/ja/code/theory/basic.html

> 他のメンバーに伝えたい違和感(テンション)が生まれる。

もうすこしCODEでも詳しく記載できるように。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正すべきポイントはイシュー冒頭の記述を確認下さい。

どこのドキュメント直すべきか若干迷ったのですがストレートに理論編ベーシックの記述を直しました。
68cb8254ab0b947a0e4e511b4c5ed9cc8195bdd2

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
「テンション」という言葉の定義がなくない？とおもったけども。
一応もう一回貼っておきます。最新版。

![image](https://user-images.githubusercontent.com/680855/98528663-f5a10300-22bf-11eb-91c8-087b0e7f304d.png)

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

すみません貼ってるリンクがまちがってます。 ただしくはこっち
f6f8bd34caf0291789ea153b51fcc0943ca9db41

**Comment by motoi** [comment]
確認しました！
