### ISSUE TITLE
[Manual のCODEへの反映] テンショントリアージの記述の更新

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#184]
Manual v0.9で表現されている
https://projectsprint.org/ja/manual/tutorial/section3-2.html

テンショントリアージとはそもそも何か
> テンショントリアージとは、各メンバーが感じている違和感を全員で共有したうえで、いまチームを改善するために必要なものを優先的に選び、解決しようとすること

を追記

対象はCODE v1.0の
https://projectsprint.org/ja/code/practice/basic.html

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
反映すべきポイントはissue冒頭の記述を確認ください。
なおしました。
82c88f1d07964fcc6242a2ff6b8446260bcb6762

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
確認しました！
