### ISSUE TITLE
[Manual のCODEへの反映] マイルストーン / ロールを参照できるようにしておくこと、の記述を追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#185]
Manual v0.9において
https://projectsprint.org/ja/manual/tutorial/section3-2.html

> テンショントリアージを行う際にプログレスドメイン・チーミングドメインにおける理想の状態（＝プロジェクトのゴール・マイルストーンとチームのロール）を参照できるようにしておくことが、テンションをあげるために効果的です。

> アジェンダトリアージは、これらのアジェンダのうち、その日のミーティングで議論すべきものと議論する順番を決める作業です。プロジェクトのマイルストーンやゴールが参照しながら、優先順位をつけていきましょう。

> これらの作業の前提として、マイルストーンの確認を実施することも効果的です。これによって、次回のミーティングまでに何をどこまでするべきか、の優先順位付けをしやすくなります。

で表現されているような、理想の状態 = マイルストーンやロールを参照しておくこと、の重要性がCODEで示されていないので、それを反映する必要がある。

**Comment by Satoshi-Matsumoto** [comment]
マイルストーンの記述の修正は順番に対応。まずは
#179

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正すべきポイントはイシュー冒頭の記述を確認ください。

0b76e7d45166ac78cba1b9eaa0b868c42548e64a
d80c8e86041e5919fc7915fb3b77b19f16d3c7d9
でなおしています。

> アジェンダトリアージは、これらのアジェンダのうち、その日のミーティングで議論すべきものと議論する順番を決める作業です。プロジェクトのマイルストーンやゴールが参照しながら、優先順位をつけていきましょう。

ここに相当する部分の記述は、別イシュー対応の際に一緒に対応したので、今回は無視してよいです。

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
よいとおもいました！
