### ISSUE TITLE
[Manual のCODEへの反映] マイルストーンの見直しについての記述を追加

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#186]
Manual v0.9で示されているような
https://projectsprint.org/ja/manual/tutorial/section4-2.html
マイルストーンの見直しが生じるパターンについてはいまCODE v1.0 に記述がない。

理論編アドバンスの
https://projectsprint.org/ja/code/theory/advance.html

> マイルストーンは、チームによって任意に変更されうる。これは、実際にプログレス・アクティビティをこなす中でAs-IsとTo-Beが変化し、プロジェクトのゴールのために必要なことや、場合によってはプロジェクトのゴールそのものを見直すことがあるからである。

ここをもう少し記述の充実できるのと、

Manualに記載されているような、マイルストーンの見直しやプロジェクトのゴールの見直しをするべきタイミングは
実践編アドバンスとして追記したい。

> マイルストーンの見直しをするべきタイミングは、次のようなときです。

> あるマイルストーンが達成されたとき
> あるマイルストーンが予定通りに達成されないことが明らかになったとき（予定よりも遅い場合、早い場合のいずれも含む）
> プロジェクトのゴールに対してあるマイルストーンが適切ではないことが明らかになったとき
> プロジェクトのゴールが変わったためマイルストーンも変える必要が出てきたとき
> その他何らかの理由でチームメンバーがマイルストーンを見直したほうがよいと考えたとき
> また、プロジェクトのゴールの見直しをするべきタイミングは、次のようなときです。
> 
> プロジェクトが進行した結果プロジェクトのゴールそのものを見直したほうが良いことが分かったとき
> マイルストーンが予定通りに達成されなかった結果、プロジェクトのゴールを見直したほうが良いことがわかったとき
> その他何らかの理由でチームメンバーがプロジェクトのゴールを見直したほうがよいと考えたとき
>

**Comment by Satoshi-Matsumoto** [comment]
マイルストーンの記述の修正は順番に対応。まずは
https://github.com/copilot-jp/project-sprint/issues/179

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正すべきポイントはイシュー冒頭の記述を確認ください。
3badbeaa42b10b19b050ce8b95f26a475a7508a0
b341e9b79126030c086c364042bb51a0e8533fad
でなおしました。

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
読んでいてわかったんだけど「見直し」の言葉の使い方が私と違う気がしてきた。
（私はガバっと方向修正するみたいな意味で見直しをとらえておりました）

サトマツさん的には「プロジェクトの進行に合わせて徐々に詳細になってきたのでマイルストーンをだんだんと詳細に記述していく」も見直しという意味で使っているのであれば、以下の文章の冒頭の1文にそのニュアンスを追加するようなものなのか、下の箇条書きの部分に1項目追加してもらいたいです。

冒頭の文章とはこれね。
> マイルストーンの見直しのタイミングは、次のようなときである。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
冒頭の分に追記しました。
b5dd3a0aebdf748c86a97033e1a0e21314288445

見直しとしては確かに複数の規模があると思いますがタイミングとしては増えないと思います。

**Comment by motoi** [comment]
確認しました！
