### ISSUE TITLE
[Manual のCODEへの反映] ロール確認の記述を充実

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#187]
Manual v0.9で示されているような
https://projectsprint.org/ja/manual/tutorial/section4-3.html
ロール確認の記述はいまCODE v1.0だと次の部分しかない。

https://projectsprint.org/ja/code/practice/basic.html

> ロール確認は、チームメンバーが互いのロールを明示的に確認し、期待値が合致していることを確認することである。これによって、チームのステータスを確認することが可能になる。

ロール確認をするべきタイミング、について、実践編アドバンスあたりに追記したい。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @yoneyama-tomohiro

更新完了しました。
9e448c7539f4847a410dd5680b6b45d0bf6e2f9b

ただし確認は #186 と同時がいいと思うので、いったんアサインは私のままにしておき、レビューお願いするタイミングでアサイン変えます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
こちら確認ください。
9e448c7539f4847a410dd5680b6b45d0bf6e2f9b

#186 で対応している  b341e9b79126030c086c364042bb51a0e8533fad と一緒に確認するとわかりやすいと思います。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
これ両方見て思ったけど、ここに書いてあるのはスポット的なモノが箇条書きで書かれていると思いました。
なので、プロジェクトは不確実なものなので定期的な見直しも入れたいです。

ある一定期間を経たら見直す（チェックするという意味合いも含む）
→ ロールは1か月毎とかが望ましい
→ マイルストーンは毎週チェックするが望ましい
これ入れ込めるかしら？

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ロール・マイルストーンとも記述追加しました。毎月なのか毎週なのかは書くとしてもマニュアルなのと、プロジェクトの状況による要素も大きいと思うのでここでは更新してません。

ロール
e51dff7183e69afb85434c538679a970e71036b1

マイルストーン
faa7aad5f8d2f3f0a0cce74d83e028d5b7ef3083

**Comment by motoi** [comment]
マイルストーンの方だけ補足しました。

151008df85ef25bb16c32ab748cbcccf65055995

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なるほどですね。課題感としては超わかります。いただいたものでいいと思います。
