### ISSUE TITLE
[英訳]Domainに言及されていない

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#19]
https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/en/essentials/index.md#principle

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/18
と合わせて対応

**Comment by Satoshi-Matsumoto** [comment]
#241に合流。こちらはクローズします。
