### ISSUE TITLE
[Manual のCODEへの反映] ミーティングの定例性についてManual v1.0.0用最新版記述をCODEに反映

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#190]
https://github.com/copilot-jp/project-sprint/issues/80
で対応したミーティングの定例性に関する記述をCODE v1.1.0に反映します。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
今回Manual v1.0.0に反映する予定の #80の内容をCODEに反映させました。
8f1f1eb2d3bfe90f1752e0eb7b7866e76f2a1beb

ご確認 & 問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
よいとおもいました！
が、最近、PJSのMTGの性質について質問が多いので、以下のように説明しています。
これ読んでもらって追記があったら検討くださいー。

![image](https://user-images.githubusercontent.com/680855/98538865-c219a500-22ce-11eb-8e46-907ee56719f7.png)

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
いただいたのはどっちかというと理論編アドバンスの内容かなと思います。「ミーティングの定例性」というよりは、その背後にある「ミーティングの性質」「ミーティングの意義」といったテーマなので。※CODEの体系整理が話としてありますが、アドバンスに入るべきこういう内容はなんらか残ると思います。

で、この内容はすみませんが別issueとさせてください。issueはたてておきます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 別イシューたてました。こちらのイシュー確認いただいたらこちらはクローズしてしまってください。
https://github.com/copilot-jp/project-sprint/issues/210

**Comment by motoi** [comment]
良いと思いましたー。
