### ISSUE TITLE
マイルストーンやゴールは変えてよい、という表現

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#193]
https://github.com/copilot-jp/project-sprint/blame/master/ja/manual/tutorial/section2-1.md#L49

> マイルストーンやゴールは変えてはならないものではないことを意識しておいてください。

これは、

> マイルストーンやゴールは状況に合わせて変えてもよい、と意識してください。

このくらいストレートに言ってもよいのではないかと思いました。
ブログ記事で引用されたのを読んだときに、まわりくどくて混乱しました。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma こちら対応しました。
CODE全編通して同じ類の部分は直しました。
482583b6496e457bd4e699bfc779e5afa32b7f80

問題なさそうであればクローズをお願いします。
