### ISSUE TITLE
あるべき姿についてまとまった説明があっても良いかも

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#20]
「自律的で理想的なチーム」に違和感
理想的なチーム＝チーミング・ステータスにおけるあるべき姿
自律的なチーム＝PJSにおいてチーミングが目指すあるべき姿

プログレスについてもゴール達成、とサラッと書いているが、プログレス、チーミングのドメインの説明と、それぞれのドメインで何を目指すのかは別のセクションで書ききると図との対応が良いと思いました

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/essentials/index.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%B9%E3%83%97%E3%83%AA%E3%83%B3%E3%83%88%E3%81%AE%E5%8E%9F%E7%90%86

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん、これかつてプロジェクトの成功指標とかでも話してたことだけど今現在の情報で書けるか、書けなそうであれば別途1度会話してまとめるなど設計くださいー。

**Comment by Satoshi-Matsumoto** [comment]
これはコメントの意図をもう少し丁寧に確認したほうがいいと思うので会話して話しましょう。
@motoi @kikuchiharuma

**Comment by Satoshi-Matsumoto** [comment]
プログレスステータス / チーミングステータス いずれも、理想の状態 = プロジェクトのゴール / いいチーム　を目指す。

そのうえで、PJSが目指す、是とする、ゴール / チームは何か？

**ゴール：**
- 最初は、誰かの何かの期待をそのまま表す程度でよい
- マイルストーンの見直しをするときに参照されるに足る強度のあるもの
※マイルストーンは、それぞれのメンバーの行動を規定できるもの
- 書き換わるダイナミズム / 進化する目的

**チーム：**
- 自律的なチーム

企業ビジョンだと、自分たちがこういう機能はいりません、という判断をするためのもの。
自分たちの意思決定に足りるもの。

**Comment by Satoshi-Matsumoto** [comment]
対応しました。
https://github.com/copilot-jp/project-sprint/commit/678046633447428c192a9255187ced579498e7c2
https://github.com/copilot-jp/project-sprint/commit/ac8f9daf7c407daa719b49f78a3c82f693d7a2ae

@motoi @kikuchiharuma 
コメントください！

**Comment by kikuchiharuma** [comment]
とてもいいと思います！！

**Comment by kikuchiharuma** [comment]
@motoi オネシャス

**Comment by motoi** [comment]
@Satoshi-Matsumoto コメントしましたー。細かいのからとぼけたやつまで。ご一読ください。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
諸々修正しました。
https://github.com/copilot-jp/project-sprint/commit/678046633447428c192a9255187ced579498e7c2
https://github.com/copilot-jp/project-sprint/commit/ac8f9daf7c407daa719b49f78a3c82f693d7a2ae
上で、もらったコメントに対して返信しています。修正かかっているものは、返信から飛び先のコミットをご確認ください。

**Comment by motoi** [comment]
実践と最適化、以外の部分は確認しました！（また混ぜてすません）オケーです。クローズしやす。
