### ISSUE TITLE
マイルストーンとマイルストーンマップを理解しやすく図解したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#201]
最重要概念であるマイルストーンやマイルストーンマップをまず定金がテキストとポンチ絵で定義する

**Comment by Satoshi-Matsumoto** [comment]
#207 を受けての図解。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/343
こちらに移行したのでクローズ
