### ISSUE TITLE
チームの定義をする

### ISSUE THREAD

**Issue by yoneyama-tomohiro** [copilot-jp/project-sprint#202]
11/5MTGより：

- チームとグループの対比で書くか？
- バーナードの組織の3定義を参照しても良い

**Comment by Satoshi-Matsumoto** [comment]
- 「チーム」という言葉の定義があったほうがいいのではないか？
-  Project と 組織の違いも分かるようにした方がよいのではないか？

**Comment by yoneyama-tomohiro** [comment]
（検討中メモ）

■チームの必須要件（チームであることの要件）
・共通のゴール
・相互依存的なメンバー間によるプロジェクト遂行

■その要件を実現するための重要な要素（良いチームであるための要件）
【プログレス視点】
・マイルストーン・成果物の理解

【プロセス視点】
・定例MTGでの役割を理解している

【チーミング視点】
・チームメンバー双方の期待値が揃っている
・違和感があれば、遠慮なく伝えられる関係

**Comment by yoneyama-tomohiro** [comment]
↑ではごちゃごちゃ描きましたが、シンプルに言うと、こういうことかな案。

以下（TIPS）に項目を追加する想定。
https://projectsprint.org/ja/code/tips/

---

チームとは、これまでの議論を踏まえると以下の2点が必須要件と考えられます。
1）共通のゴール
2）相互依存的なメンバー間によるプロジェクト遂行

参考：
「チーム」については、これまで様々な定義がなされています。

`目標を共有しつつ、相互作用をしながら、物事を達成する社会集団`
`（出典：中原ら「チームワーキング ケースとデータで学ぶ「最強チーム」のつくり方」）

`Teams are social entities composed of members with high task interdependency and shared and valued common goals (Dyer, 1984)
`（出典：Dyer「Team research and team training: A state of the art review」）

`Work teams (a) are composed of two or more individuals, (b) who exist to perform organizationally relevant tasks, (c) share one or more common goals, (d) interact socially, (e) exhibit task interdependencies (i.e., workflow, goals, outcomes), (f) maintain and manage boundaries, and (g) are embedded in an organizational context that sets boundaries, constrains the team, and influences exchanges with other units in the broader entity.
`（出典：Kozlowski & Bell「Work groups and teams in organizations： Handbook of psychology: Industrial and organizational psychology (Vol. 12)」)

`ワークグループ: 相互依存性が最小限という特徴があり、組織または管理上の階層関係に基づいています。ワークグループのメンバーは、情報交換のために定期的に集まる場合があります。 
`チーム: メンバーは相互に強く依存しながら、特定のプロジェクトを遂行するために、作業内容を計画し、問題を解決し、意思決定を下し、進捗状況を確認します。チームのメンバーは、作業を行うために互いを必要とします。
`（出典：Google）

しかし、今の時代のプロジェクト遂行においては、それだけでは十分ではなく、「ゴール」そのものをチーム自ら再定義することがチームには不可欠と考えています。
なぜなら、一度設定したゴールで動き出したとしても、状況に応じてゴールそのものが変わりうる、もしくは変えなければならない状況があるためです。

SGMの中でも、プロジェクトごとに「目的」「ゴール」を記載する欄がありますが、誰かから一方的に与えられた「目的」「ゴール」に対応するだけでは、現代のチームとしては不十分で、それらを書き換えていくことができるかどうかがチームか否かを左右する条件と考えています。



　では具体的にどうすればよいか

**Comment by motoi** [comment]
チームの定義にプロジェクトを使うとややこしそう

**Comment by yoneyama-tomohiro** [comment]
1人でもチーム？
→いや2人以上

**Comment by yoneyama-tomohiro** [comment]
みたいなことを書いておく

**Comment by yoneyama-tomohiro** [comment]
なぜなら、「相互依存的な」だから。

**Comment by yoneyama-tomohiro** [comment]
グループにも共通目標はありそう。

**Comment by yoneyama-tomohiro** [comment]
グループは、所与のゴールを固定的なものとして、変えようというマインドはない

**Comment by yoneyama-tomohiro** [comment]
チーム：主体的
グループ：受身的

**Comment by yoneyama-tomohiro** [comment]
以下で作成中
https://docs.google.com/document/d/1UCen01VSHmcqcTeo83idDlffngOzmdBCPN4nD9k9hng/edit#

**Comment by yoneyama-tomohiro** [comment]
@motoi 
チームの定義を書きましたので、TIPSに追加いただけますでしょうか？

■原稿
https://docs.google.com/document/d/1UCen01VSHmcqcTeo83idDlffngOzmdBCPN4nD9k9hng/edit#

■追加場所
https://projectsprint.org/ja/code/tips/
→「15. チームの定義」として

**Comment by motoi** [comment]
追加しました！
