### ISSUE TITLE
ハイライトがついたときのフォント指定がおかしい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#206]
https://deploy-preview-188--project-sprint-staging.netlify.app/ja/manual/tips/tips1.html
のページのハイライト部分です。ウィンドウズChromeのスクショ貼ります。
ご確認ください！

![image](https://user-images.githubusercontent.com/680855/98487231-30298200-2265-11eb-9b97-245f7939e7ee.png)

**Comment by kikuchiharuma** [comment]
次の更新で対策してみますー

**Comment by kikuchiharuma** [comment]
こちら、中身見てみたのですが、markdown で code を指定してあるんですね。
https://commonmark.org/help/tutorial/09-code.html
それで、等幅フォントが指定されているようです。

code は本来、こういう使い方のためのものです。

<img width="770" alt="Screen Shot 2021-04-27 at 13 38 19" src="https://user-images.githubusercontent.com/607971/116186187-140b9580-a75e-11eb-873b-64bda5c3c536.png">

**Comment by kikuchiharuma** [comment]
プログラミング言語でない内容を強調したい場合には、こんな感じの「強調」
https://commonmark.org/help/tutorial/02-emphasis.html

<img width="761" alt="Screen Shot 2021-04-27 at 13 42 17" src="https://user-images.githubusercontent.com/607971/116186364-719fe200-a75e-11eb-8982-9dc3bae4445b.png">

か、「ブロッククオート」
https://commonmark.org/help/tutorial/05-blockquotes.html

<img width="748" alt="Screen Shot 2021-04-27 at 13 42 14" src="https://user-images.githubusercontent.com/607971/116186349-68af1080-a75e-11eb-90cc-660b08cbd652.png">

を使うのが正しいと (セマンティクスおじさん的には) 思いましたがどうでしょう。 @motoi 
強調やブロッククオートのスタイルを調整したい、というのはまた別の問題として。

**Comment by motoi** [comment]
確かにそうですね。意味合い的には強調だと思うのでその指定にしますのでレビューお願いします！

**Comment by motoi** [comment]
解消！
