### ISSUE TITLE
プロセスの記述に「ミーティング終了後」を追加する

### ISSUE THREAD

**Issue by yoneyama-tomohiro** [copilot-jp/project-sprint#208]
タスクの共有や、次回MTGのアジェンダ展開など、定常的に「ミーティング終了後」の作業もあるため、「ミーティング終了後」を一つの項目として追加したほうが良いと思われる。

たとえば、こんな話。
https://docs.google.com/presentation/d/1dQgbxB6_0kosazzgfk0Gmoa8c7dInfOy_NvZejfpneo/edit#slide=id.g83fa5a3645_0_79
![スクリーンショット 2020-11-10 9 26 26](https://user-images.githubusercontent.com/48910885/98612154-df825980-2336-11eb-89ab-5f2489b36a39.png)

追加先は以下
https://projectsprint.org/ja/code/practice/basic.html

参照元：
https://github.com/copilot-jp/project-sprint/issues/86#issuecomment-723549460

**Comment by motoi** [comment]
理想はミーティング中ということで、ずれ込むことはあるが、そこまで記述しない。
