### ISSUE TITLE
アジェンダは必須というニュアンス

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#21]
アジェンダとなることで、ひとつの成果やテンションにチームメンバー全員が注目することが容易になる。

とありますが、

アジェンダとなることで、ひとつの成果やテンションにチームメンバー全員が注目することが可能になる。

くらい踏み込んで書いたほうが良い気がします。

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/essentials/index.md#%E3%83%97%E3%83%AD%E3%82%BB%E3%82%B9

アジェンダにしないと他のメンバーから見えないんだよ、という点。かなり強調してもいいように思います。

**Comment by motoi** [comment]
これ追加がありまして。一度コパ社内で議論なったりプロダクトチームでも会話がでているのですが、「アジェンダ」 と 「議題」って違うんじゃないかと。

1つ1つの議論すべき話題 → 議題
議題があつまったもの → アジェンダ
じゃね？と。
いまPJSでもSGMsでも議題も、議題があつまったものもアジェンダと呼んでいるなと。
これは定金の完全に言葉の認識の違いから来ているものなんだけどこの整理を一緒にやりたいなと。
英語ではここでいう議題とアジェンダをつかいわけているのかとかも含めてリサーチいれてまとめたいとおもっています。
@Satoshi-Matsumoto さんが全部このあたり含めてやるのか、定金が言葉の定義を決めたほうが良いのか、一回会話するのかとか、まずこの辺の作業切り分けもしてもらってよい？

**Comment by Satoshi-Matsumoto** [comment]
これは、一度話してから、まとまればそれでよし、
まとまらなければ @motoi さんに定義決めてもらったほうがいいと思います。

先に個人の見解を残しておくと、

> 1つ1つの議論すべき話題 → 議題
> 議題があつまったもの → アジェンダ

この後者を"アジェンダ"ということには結構違和感あります。むしろ、"複数の議論すべきポイントが集まっているもの"を背景 / アウトプット / 完了の定義とかを用いて分割不可能にしたもの = PJSでいうところの"アジェンダ"と思っているので。よって"議題"という概念が不要と思います。

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/21#issue-614510860
=> このissue上でそのまま検討

https://github.com/copilot-jp/project-sprint/issues/21#issuecomment-626064653
=> issue #36

**Comment by Satoshi-Matsumoto** [comment]
修正してみました。
https://github.com/copilot-jp/project-sprint/commit/00abcdd877f2408b454b428f1d022b00814a8568

@kikuchiharuma どうでしょう？

**Comment by kikuchiharuma** [comment]
最高です！

**Comment by motoi** [comment]
@Satoshi-Matsumoto いいとおもいます！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
特に問題ないと思いますのでクローズします。
