### ISSUE TITLE
PJSにおけるミーティングの性質について追記

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#210]
#190より派生。内容的には、理論編アドバンスの「ミーティングの意義」の後続か？

@Satoshi-Matsumoto 
よいとおもいました！
が、最近、PJSのMTGの性質について質問が多いので、以下のように説明しています。
これ読んでもらって追記があったら検討くださいー。

![image](https://user-images.githubusercontent.com/680855/98538865-c219a500-22ce-11eb-8e46-907ee56719f7.png)

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/issues/190#issuecomment-723970719_

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
貼ってもらっている画像のニュアンスをTutorialに追加しました。こんな感じでどうでしょう。
ミーティングの設計　に追記
601451ab85f255156fb2742b4ab4c6f9c04c2943
ミーティングの定例性　に追記
03c1a14fd9a47d3d55046323654c69e1cf2b5424

**Comment by motoi** [comment]
@Satoshi-Matsumoto 各コミットにコメントしたりプルリクしましたー。

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、
修正プルリクはマージしました。
コメントの方は
0ae8b943353b2ef1c11f760abd2e0cfc84f20999
直したのでご確認ください。

**Comment by motoi** [comment]
よいとおもいました！

**Comment by motoi** [comment]
@Satoshi-Matsumoto これ私のイシューじゃないけどこういうときって誰がクローズすればよいんだっけ？

**Comment by Satoshi-Matsumoto** [comment]
@motoi イシュー起票した人がクローズです。これに関しては、私が代理起票してますがもともと定金さんの修正リクエストから来てるので、クローズしてよいかご判断お願いします。
