### ISSUE TITLE
チームの状態はいつどのように評価される(ステータスとして意識される)のか？

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#22]
図を描いていた時の疑問
プログレスと違って、チームが不連続に成長するのは仕方ないにしても、ステータスは一体いつ意識されたりチームで共有されるのだろうか？と思いました。

振り返りや、ロールの明文化、などのチームで共有する機会を提供していかないと、チームのステータスは暗黙的なままになってしまうと思います。
Essentialsでは示唆するくらいでいいかも知れないですが、Advanceでは積極的な言及が必要な気がします。
プロセスの中にチーミングを扱う方法、プログレスを扱う方法、その中にさらにアクティビティを扱う方法、ステータスを扱う方法、のように整理できるときれいかも

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/essentials/index.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%B9%E3%83%97%E3%83%AA%E3%83%B3%E3%83%88%E6%A6%82%E5%BF%B5%E5%9B%B3

**Comment by Satoshi-Matsumoto** [comment]
いったん書いてみて、プルリク前に共有するので、それをもとにコメントください！
@kikuchiharuma @motoi

**Comment by Satoshi-Matsumoto** [comment]
振り返り
定期的にやるステータス確認のもの、チーミングエリアに大事なもの。という位置づけ。
essentialsにはこのくらいの位置づけでいれる。

テンショントリアージはミーティングごとでやるもの、
振り返りは長いスパンでやるもの？

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
2ee8f2a2ec6475c72b9535d61e2413ff87747d2c
こんな感じでどうでしょう？
ちなみに、テンションとアウトプットについては、のちの記述でアジェンダにひもづく概念として記述しているので、これと併せて

> テンショントリアージはミーティングごとでやるもの、
> 振り返りは長いスパンでやるもの
が表現できていることになります。

**Comment by kikuchiharuma** [comment]
いいと思います！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 確認ありがとうございました。
@motoi クローズしちゃいます。
