### ISSUE TITLE
「アウトプット」という言葉の定義

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#229]
PJSにおける「アウトプット」は以下のチップスにある。

"チームメンバーが割り当てられた作業（タスク）を完了したことで生まれた目に見える有形物のことです。”

タスク→アウトプット

という流れが必然であるように読めた。

単純に
"目に見える有形物"
のことをアウトプットとして言葉をSGMsでも使っている。
いろんなところでこの言葉を無邪気に使ってよいのかが不明になったので確認したい。

https://projectsprint.org/ja/manual/tips/tips3.html

**Comment by motoi** [comment]
@Satoshi-Matsumoto 私のイシューに対して一回認識を共有ください！

**Comment by Satoshi-Matsumoto** [comment]
CODEv2.0.0で更新済みなのでクローズします。
https://projectsprint.org/ja/code/tips/tips3.html

> アウトプットは、チームメンバーが割り当てられた作業（タスク）を完了したことで生まれた目に見える有形物のことです。プロジェクトを通じて生み出されるものを示す言葉の中で最小単位のものです。
