### ISSUE TITLE
インクリメンタルなデリバリーについて言及がない

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#23]
図の中にはインクリメンタルなデリバリー、という表現が登場するのですがドキュメント側に言及がなさそう

マイルストーンとは別に、ひとつひとつのミーティングがデリバリーの機会、というようなイメージが図の表現

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/essentials/index.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%B9%E3%83%97%E3%83%AA%E3%83%B3%E3%83%88%E6%A6%82%E5%BF%B5%E5%9B%B3

**Comment by motoi** [comment]
これは定金の方でTODOいる？から端を発して検討しているものをまずまとめます。
https://docs.google.com/presentation/d/1CxqS6RX2vP46d3eFwBq3EDqBsI-XNYPf_zR3E1TRKIA/edit#slide=id.p

**Comment by Satoshi-Matsumoto** [comment]
@motoi さんのまとめを待ちますが、

> プロジェクトチームは、プログレス・ステータスを プロジェクトのゴールの達成 に近づけることを目的としている。これは、現在いる地点から理想とするプロジェクトの最終到達地点に向かって**漸進的に成果物を積み重ねていくということ**である。

太字部分がインクリメンタルなデリバリーにあたります。文章のトンマナ的にカタカナ使わなかったのですが揃えたほうがいいですかね？

いったんv0.9に向けて解決するようにしたいと思うので、@motoi さん、適宜進捗状況を確認させてくださいまし

**Comment by motoi** [comment]
要議論なので二人メンショヌ。 @Satoshi-Matsumoto @kikuchiharuma 
 
前回の議論ででたフィードバック内容をこの資料の一番最後に記載しています。
https://docs.google.com/presentation/d/1CxqS6RX2vP46d3eFwBq3EDqBsI-XNYPf_zR3E1TRKIA/edit#slide=id.p

このながれと、前回の議論といまのエッセンシャルズを読んでおもったこと。

何かの機能を提供するものがプロジェクトで常につくられるのではないので、インクリメンタルなデリバリーはアウトプットの集合体ぐらいしかいまは言えないかもしれない。

タスクの結果で出力されるもの => アウトプット
インクリメンタルなデリバリー => アウトプットがまとまったもの ＝＞成果
マイルストーンで作られるもの => 成果物

なので今のエッセンシャルズで書かれている
> 漸進的に成果物を積み重ねていくこと

とは
マイルストーンをクリアしていくこと
になるなと。

ということで
> マイルストーンとは別に、ひとつひとつのミーティングがデリバリーの機会
これは改めて何かしら検討をする必要あって

・ミーティングではデリバリーするとはいわない（タスクからでたアウトプットを確認する場所）
・ミーティングでデリバリーするというのであればアウトプットが重なったものを何かしら呼び名をつける

かなとおもいました。

あと質問ありました件。
> 揃えたほうがいいですかね？
図とドキュメントは用語は統一したほうが良いのではないかと私はおもいます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
言われていることで私は特に問題ありません。
ミーティングでの各アウトプットの集積については、あまり用語を増やしたくないので、名称はいらないと思います。（使うシーンもあまり想定できないため）

@kikuchiharuma 
どうですか？特に問題なければ修正内容は
- 図の中で、デリバリーされるものがマイルストーン単位であることをわかりやすくする
- "インクリメンタルにデリバリーされる"の文言を、"インクリメンタルに成果物がデリバリーされる"
とかかなと思います。

図と文の整合性は、文中の"漸進的に成果物が積み重なる"は、"インクリメンタルに成果物がデリバリーされる"に合わせることでよいのかなと。

**Comment by kikuchiharuma** [comment]
修正の方向OKです。

**Comment by kikuchiharuma** [comment]
画像に反映してみました。
https://github.com/copilot-jp/project-sprint/commit/5fb55659c911208255a78c6c2c9935f4c37acd34

**Comment by kikuchiharuma** [comment]
ミーティングのアウトプットはいらないのではということでしたが、定金さんの整理に合わせて「成果/Outcome」としてみました。
Output - Outcome - Deliverables
という関係です。

図としてはas-is to-beの関係があるのですが、それに対応する実態がないと、アウトプットと成果物があるのにその中間バージョンがない、という都合の悪いことになってしまいます。
アジャイルの考えに照らしても、常に途中の成果はあると考える方が自然のように思いました。
この点、サトマツさんに再考いただきたいです！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/commit/7efe05af3a6531077d8ed317e83b10dee1f56426
こんな感じでどうでしょう？

指摘の内容自体は特に違和感なくて、文章的にも表現できていると思うのですが、用語が増えすぎないといいなーというくらいです。
読んでみてとくにそこは大丈夫そうであれば、問題ないと思います。

**Comment by kikuchiharuma** [comment]
いいと思います！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma ありがとうございます！クローズします。
