### ISSUE TITLE
CODE 内にですます調が混ざっている

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#230]
> 解決しようとすることです。

CODE の文体だと、解決しようとすることである。解決することである。あたりでしょうか。

https://github.com/copilot-jp/project-sprint/blob/master/ja/code/practice/basic.md#%E3%83%86%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%88%E3%83%AA%E3%82%A2%E3%83%BC%E3%82%B8

**Comment by kikuchiharuma** [comment]
こっちにもあった

> ゴールに近いものほど抽象的で大まかな記載になります。

https://github.com/copilot-jp/project-sprint/blob/master/ja/code/practice/basic.md#%E3%83%9E%E3%82%A4%E3%83%AB%E3%82%B9%E3%83%88%E3%83%BC%E3%83%B3%E3%81%AE%E4%BD%9C%E6%88%90%E6%96%B9%E6%B3%95

**Comment by Satoshi-Matsumoto** [comment]
CODE v2.0.0にて、ですます調でとういつしたので閉じてしまいますね @motoi
