### ISSUE TITLE
マイルストーンの差分は、積極的な共有が強く推奨されるのでは

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#231]
> マイルストーンは全員に…共有され、つねに参照可能でなければならない。

https://github.com/copilot-jp/project-sprint/blob/master/ja/code/theory/advance.md#%E3%83%9E%E3%82%A4%E3%83%AB%E3%82%B9%E3%83%88%E3%83%BC%E3%83%B3%E3%81%AE%E6%80%A7%E8%B3%AA

全員に共有され、全員にとって参照可能であるのは必要条件ですが、積極的に変更することが推奨されるマイルストーンの性質上、差分が十分に共有されず、知らないあいだに変わってた、と感じる人が発生することで (最初は議論を尽くして決めたマイルストーンなのに、時間経過とともに) 価値が下がっていく場面があるように思います。

SGMs のようなツールの上に明文化されていれば、「参照可能」ではあるのですが、常に変更があったかどうか注視するわけにはいかないので、それだけでは不十分なのではないかと思いました。

変更があったときには、全員がそれを納得するように積極的に差分を共有したり、それについて合意できるかどうかチームの全員が再度咀嚼する、というアップデートのプロセスにエネルギーをかける必要がある。そうしないとマイルストーンは価値あるものとして存在できない性質がある、という言い方ができるのではないかと思いました。

マイルストーンが自分にとっても目標であると信じられていない人が出てきてしまっている場面が、チームとして危機的なことが多いな、という経験があるので、書かれているが納得されていないマイルストーンは、何もないよりむしろ危険だなとも感じます。

**Comment by motoi** [comment]
定金が思うことをテキストで補足する。

**Comment by motoi** [comment]
菊地さんの言われることに非常に共感します。
運用面のコメントをすると、マイルストーンの差分を非同期においてうまく表現できるツールがないため、ミーティングでみんなで編集する、もしくは前に作ったものと変更後のものを並べて見せながらマイルストーンをアップデートすることを強く推奨しています。
ということで @Satoshi-Matsumoto さん検討ください！

**Comment by Satoshi-Matsumoto** [comment]
マイルストーンの手順について記している箇所に追記するのがよいとおもいました。

というわけで @motoi さん
7190c20b313cf9d2e71d4009f65dcfe5f7ec0751
こんな感じでいかがでしょうか。

**Comment by motoi** [comment]
よいとおもいました！
@kikuchiharuma この修正でどうでしょう？

**Comment by motoi** [comment]
事務局判断でリリース対応を @KokoroKagawa さんお願いします

**Comment by KokoroKagawa** [comment]
次回リリース用ブランチv2.1.0にマージしたので、本Issueはcloseとします。
https://github.com/copilot-jp/project-sprint/compare/v2.1.0
