### ISSUE TITLE
議論する項目、の意味でアジェンダという用語を使うのは変

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#234]
ドキュメント全体として、アジェンダの一般的な用法から逸脱していると思います

議題、アジェンダ項目などとすべきじゃないでしょうか

**Comment by motoi** [comment]
miroをみてみました。
![image](https://user-images.githubusercontent.com/680855/104145202-7a67e480-5409-11eb-8ca9-908c12988192.png)
ここで言うとagendaとagenda itemってことですよね？

一般的な用法ってどこか参照すべきものってありませんかね。
これかつて指摘をもらったときに私も気になったので調べたのですがあんまりしっくりくるものがなくとりあえずバクっと使っている現状でして。

**Comment by kikuchiharuma** [comment]
@motoi 
そうですね、このリストのように Meeting agenda という枠の中に要素 (agenda item) がある、というのは違和感ないです。

PJS の記述が特殊に見えているので、一般的な用法をこれと言うのは難しいですが…例を挙げると、アジェンダを配布する、みたいに言う時などでしょか。個別の議題ごとに配るわけじゃない、まとまったものを配るイメージだと思うのですが、そういうイメージを持って「アジェンダを追加」のような言い方を聞くと、変だな、と思うと言う感じです。新しいアジェンダを配布するか、アジェンダを変更ならわかります。

似たようなものとして、大学の講義でレジュメを配る、結婚式の参加者に式次第を配る、みたいなものがあると思います。
レジュメを追加する、式次第を追加する、という表現があるとすると、同じように変だな、と感じます。
(内容を追加することで) レジュメを変更する、式次第を変更する、と言うのであればいいと思うのですが。

**Comment by motoi** [comment]
国連とかも「アジェンダ」って言葉を大きなテーマみたいな感じで使いますもんね。
まとまりをアジェンダと呼ぶのはまあ理解できるのですが、議題をなんて呼ぶかがあんまりしっくりこなくて、そのまま使ってるんすよね。
アジェンダアイテムかなー。日本語で議題ですかね。ちと日本語のいろんなの改めてあたってみます。

**Comment by motoi** [comment]
調査中メモ

●ぎ‐だい【議題】 の解説
会議にかけて討議する問題。「議題にとり上げる」

●議題／議案 の解説 - 小学館 類語例解辞典
議題／議案 の共通する意味
審議、議決するために、会議にかける事柄。

英語表現 an agenda

議題／議案 の使い方
議題
▽議題を提出する ▽議題にのぼる ▽中心議題
議案
▽執行部から提出された議案 ▽議案は原案どおり可決された
議題／議案 の使い分け
会議にかけて討議する題目を「議題」といい、会議で討論、議決するために提出する原案を「議案」という。
議題／議案 の関連語
議事
ある事を会議にかけて討議すること。「議事進行」「議事録」

●精選版 日本国語大辞典の「議題」解説
〘名〙 会議に提出される問題。

**Comment by kikuchiharuma** [comment]
パッと思いつくのは、アジェンダアイテムと議題ですかねえ。
特にひねる必要は感じません。

**Comment by motoi** [comment]
コパナレラボチームのアジェンダマスター @takahashisatoshi に確認中。

**Comment by takahashisatoshi** [comment]
結論から言うと、
アイテム（仮）の集まりを、「アジェンダ」と呼ぶ。
アイテム（仮）は、アジェンダ以外の名称をつける。
topic, subject, title あたりのどれかか。

アジェンダも議題も、情報量の幅がそれぞれに大きすぎる言葉なのに微妙にニュアンスがちがうので、英語か日本語か、どちらかで統一するほうが望ましいかと。

**Comment by takahashisatoshi** [comment]
ここからは今日のリサーチ
https://ejje.weblio.jp/content/agenda

agendaの語源。
ラテン語「実行に移されるべき(ことがら)」の意

なにか、使命感とかのようなものが意味としてありそう。（議題にはない）
SDGsのようなものとか、政策とかの大きなものから、
少人数の人が集まって話し合うときの大きなテーマのようなものとか（感想です）。

agendaの意味
協議事項、議事日程、予定表

感想＝なんか情報の集まり感は必要な気がする。

例文
the first item on the agenda発音を聞く例文帳に追加
議事日程の第 1 項目.

ここらへんからも、そんな雰囲気が。

ーー

一方、「議題」。
定金くんが調べてくれたとおり、agendaに負けない幅の広さはある。
同じように国際会議の主要テーマくらいのものでも使えそう。
でも、アイテムレベルでも使えそう。

ーー
という幅広さはあるもののニュアンスがちがうので、英語で統一したほうがいいかと思ってます。

**Comment by motoi** [comment]
リサーチ マイクロソフトのテンプレート
![Uploading image.png…]()

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/110623526-4f6af880-81e0-11eb-898b-4c405a76c6a8.png)

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/110623668-82ad8780-81e0-11eb-9d2c-45ce5339491d.png)

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/110623938-e2a42e00-81e0-11eb-86d9-1ba2c63525d7.png)

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/110627990-ee462380-81e5-11eb-9e26-efdff31e3c91.png)
![image](https://user-images.githubusercontent.com/680855/110628049-0027c680-81e6-11eb-8dbd-94adcce8f22b.png)
![image](https://user-images.githubusercontent.com/680855/110628079-0ae25b80-81e6-11eb-94c6-c2cd8ec82687.png)
![image](https://user-images.githubusercontent.com/680855/110628165-251c3980-81e6-11eb-91b4-2e6a9ef7e121.png)
![image](https://user-images.githubusercontent.com/680855/110628309-3402ec00-81e6-11eb-8f50-1cbe33207962.png)
![image](https://user-images.githubusercontent.com/680855/110628382-48df7f80-81e6-11eb-82f2-61e5beaafdfc.png)

**Comment by motoi** [comment]
@takahashisatoshi 
英語ということなので調べてみました。
複数のテンプレを見た結果 agenda item か topic かなーとおもうのですが、決め手にかける。。。ご意見プリーズ！

**Comment by takahashisatoshi** [comment]
@motoi 

▼PJS文書内
　アジェンダ・アイテム
もしくは、
　アジェンダ・アイテム（議題）

▼実際の運用（口頭とかチャットとか）
議題


**１．英語の意味**
サンプルからすると、以下のわけになっている。

**Agenda Item**
議題に関する情報全体を指す。
![スクリーンショット 2021-03-18 14 11 45](https://user-images.githubusercontent.com/25312587/111577441-9c108e00-87f5-11eb-9017-6ce5fc046b07.png)

**topic**
議題のタイトル。Agenda Itemのうちの１要素。
![スクリーンショット 2021-03-18 14 11 54](https://user-images.githubusercontent.com/25312587/111577453-a468c900-87f5-11eb-825e-d87f53bef5cb.png)


**２．どちらを採用するかを検討**
ふだん、「議題」と発語するときのイメージはtopicに近い。
しかし、topicという言葉のイメージは「話題」。議題のイメージでも使うが、情報番組や情報誌、軽めのニュースサイトなどで使われる「話題」のイメージが強い印象。（これは主観が多分に含まれるので、違和感があれば要検討）

一方のアジェンダ・アイテム。
議題の集合体＝アジェンダ
議題＝アジェンダ・アイテム
と、構造がわかりやすい。

という経緯でアジェンダ・アイテムのほうがいいかなあと。

**３．運用を検討する**
とはいえ、アジェンダ・アイテムは、発語したりタイプするのには、長すぎる。
また、「議題」のイメージと距離感がある（これも主観含む）。

だから、口頭やチャットでは「議題」とするのが現実的かなあ、と。

運用を含めてこれでいこう、というなら、文書内の表記も併記で「アジェンダ・アイテム（議題）」。

**Comment by nanamikagwa** [comment]
@motoi 
6/10　1h 賀川調べの共有

**結論：**現時点では議題の集まり全体をAgenda, 議題一つ一つのものをAgenda Itemが良いと思った。

**調べた詳細結果：**
英語のテンプレートを色々調べてみたところ
Agenda/ Meeting Agenda = 議題の集まりの配下に
→Agenda Item
→Agenda Topic 
→Topic 
→Title
→Subject の種類があった

TODOはAction Itemがほとんどだった
決定事項はDecisions, Conclusions が多かった

**感想：**
Meetingで決まったTODOはAction itemと表現していることが多かったので、itemという言葉に統一感を持たせるために
議題にもAgenda Itemと表現するのがシンプルなのではないかと思った。
例）〜というAgenda Item で決まったAction Itemは〜である、というような表現。

**次のアクション：**
日本語版のテンプレートが調べられていないので、次は日本語テンプレートと英語版の違いを調べてみる。
![Screenshot at Jun 10 09-31-36](https://user-images.githubusercontent.com/77031685/121447004-bbbbea80-c9cf-11eb-920f-98b2bc8ef161.png)
![Screenshot at Jun 10 09-33-12](https://user-images.githubusercontent.com/77031685/121447024-c7a7ac80-c9cf-11eb-9fba-7eceddb23e8b.png)
![20210610](https://user-images.githubusercontent.com/77031685/121447032-cb3b3380-c9cf-11eb-92d5-74966e2a9839.png)

**Comment by nanamikagwa** [comment]
@motoi 
日本語のアジェンダや議題調べの共有　賀川めも 6/16

**結論：**議論するテーマは議題。会議日程、参加者や議題などを含めた総称をアジェンダという 。

**調べた詳細結果**
辞典での定義やJicooさんサービス紹介（https://www.jicoo.com/resources/blog/agenda）に書いてあった内容をもとに考えてみると、
- アジェンダはこれから（未来）行われることや目的、未来の課題（決定事項）をリスト化したものであったり表題化したものである。これから行われる会議内容全体のまとめ。
- そのアジェンダの要素の１つに会議で討議するべき具体的な題目として議題が含まれている。

**感想**
- 議事が議題と同じ意味合いを持ってそうですが、違うようなニュアンスの定義も出てきて認識が難しいため、議論する項目＝議題で良いのではないかと思いました。議題や日時などのこれからの会議詳細をまとめてアジェンダという認識で一旦落ち着きました。

**Comment by motoi** [comment]
アジェンダ：ミーティング全体でもつ
アジェンダアイテム：アジェンダのなかの議論したい項目

でいきます。カタカナ統一。

考え方としては以下です。
- 議題も、会議全体を指す場合もあるし、1つの話題をさすこともある
- アジェンダと議題が並ぶと言語が違うのでニュアンスがわからない
- 日本語だと、国会や法規的な文章では議題・議案・議事などつかわれているが明確な定義がなさそう
- なので広いものと狭いものをアジェンダという言葉を両方つかうことで表現できるのがシンプルだなとおもった。
- アイテムという言葉が項目的に使えるので今後も便利につかえそう。

@kikuchiharuma さんも候補として出してくれてるので問題なさそうなので、違和感あったらまたテンションもらうとします。
ということで @KokoroKagawa さん、code への反映お願いしますー。

以下の意見を参考にしました。
> Meetingで決まったTODOはAction itemと表現していることが多かったので、itemという言葉に統一感を持たせるために
議題にもAgenda Itemと表現するのがシンプルなのではないかと思った。
> 例）〜というAgenda Item で決まったAction Itemは〜である、というような表現。

> 一方、「議題」。
> 定金くんが調べてくれたとおり、agendaに負けない幅の広さはある。
> 同じように国際会議の主要テーマくらいのものでも使えそう。
> でも、アイテムレベルでも使えそう。
> ーー
> という幅広さはあるもののニュアンスがちがうので、英語で統一したほうがいいかと思ってます。

**Comment by KokoroKagawa** [comment]
「アジェンダオーナー」は「アジェンダアイテムオーナー」にすべきなのだろうが、長いな…

**Comment by KokoroKagawa** [comment]
@motoi 以下の前提で修正しました。ご確認お願いします。
アジェンダ：ミーティング全体でもつ
アジェンダアイテム：アジェンダのなかの議論したい項目

https://github.com/copilot-jp/project-sprint/tree/%23234

**Comment by motoi** [comment]
@KokoroKagawa
https://github.com/copilot-jp/project-sprint/commit/b4b54ef7941afff18a68833ed32999d95fd197ac
今回のブランチの差分であるリンクを貼ってもらえたほうが確認しやすいですー。次回からこちらでおねがいします。

**Comment by motoi** [comment]
@KokoroKagawa 修正箇所はよいとおもいました！
どこかにアジェンダとアジェンダアイテムの用語の説明的なものってありましたっけ？なければあってもよいかも、とおもいました。
どうでしたっけ。

**Comment by KokoroKagawa** [comment]
@motoi ありがとうございます！

> アジェンダとアジェンダアイテムの用語の説明

こちらです。
https://github.com/copilot-jp/project-sprint/commit/b4b54ef7941afff18a68833ed32999d95fd197ac#diff-b5138971f828b2cc1ba49aa107f018ab8376b3495ee2a16d941ba9554d6a1f70

**Comment by motoi** [comment]
@KokoroKagawa
こちらで良いと思いましたー。公開しましょう！

**Comment by KokoroKagawa** [comment]
@kikuchiharuma リリースしました！
違和感ある箇所があればご指摘いただき、特になければIssueのクローズをお願いいたしますm(__)m

**Comment by KokoroKagawa** [comment]
起案者の最終reviewは不要との方針が固まったのでcloseします。
