### ISSUE TITLE
継続的改善アプローチという概念の追加

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#239]
実践しながらふりかえり・今の気持ちをアップデートした。時系列にまとめた、継続的改善アプローチについてメソッドに記述したい。
もともとチーミングのドメインが記述として少ないということもあるし、運用にするにあたり、ロールも含まれるかなり重要な概念だと思っている。

**Comment by motoi** [comment]
[Uploading 継続的改善アプローチ：プロジェクトスプリントにおけるチームビルディング.pdf…]()
元となる資料でございやす

**Comment by yoneyama-tomohiro** [comment]
@KokoroKagawa 
こちら、gitへのアップ作業をお願いできますでしょうか？
（というお願いを、こころさんにして大丈夫でしたっけ？）
https://docs.google.com/document/d/1ryy2a7z7xsPAN0Nni7PpHgrriJMJPI054JAFTeolxGw/edit

アップ場所は、[TIPS](https://projectsprint.org/ja/code/tips/)です。

**Comment by KokoroKagawa** [comment]
@yoneyama-tomohiro 
ありがとうございました！
PJS内の表記揺れを統一するための修正と、その他てにをはレベルの調整を加えましたのでご確認ください。
https://github.com/copilot-jp/project-sprint/commit/b9cdfc851f8ab70f9b970ba86d6f091fd19e4cc7
（米山さんの初稿そのままのものと、私の修正版とのdiffです）

@motoi @yoneyama-tomohiro 
また、Tipsですが、現在順不同に近い形（更新順？）に並んでいるように思え、並べ替えを提案したいです。
ご意見くださいませ！
現状：https://projectsprint.org/ja/code/tips/
修正案：（段落分けはプログレス・チーミング・プロセスでのグルーピングを意識しています。本番環境では段落分けは行いません。）
```
プロジェクトの環境整備

プロジェクトの時間軸を整理するための便利な考え方（トラック/フェーズ/イベント)
マイルストーンマップの利用
プロジェクトで作り出されるものにはどのようなものがあるのか（アウトプット/成果物）

チームの定義
実務で使いやすいロールの設定
ロールの分類と性質
ロールシートの利用

ミーティング環境についてのノウハウ
ミーティングを定例開催にする理由
アジェンダに含まれているとよい全要素
アジェンダの目的
チームが納得できて作業効率のよいタスクの設定方法

継続的改善アプローチ[仮]
代表的な振り返りの手法
テンショントリアージの方法
```

**Comment by motoi** [comment]
グルーピングする方向でいきましょう！（夜会より）

**Comment by motoi** [comment]
グルーピングの方向で修正しつつ、 @yoneyama-tomohiro さんと定金で進め方の確認ができたら定金がレビューする。

**Comment by KokoroKagawa** [comment]
@motoi
グルーピングしました。 @yoneyama-tomohiro さんと進め方確認の上で、レビューお願いいたします。

b9cdfc8　（米山さんの初稿そのままのものと、私の修正版とのdiff）
024aac0　（グルーピング作業のdiff）

**Comment by motoi** [comment]
@KokoroKagawa どちらのdiffにもコメントしました！

**Comment by KokoroKagawa** [comment]
@motoi 
Tipsの再グルーピング含め、ありがとうございました！
https://github.com/copilot-jp/project-sprint/commit/024aac0074174462a4aea47797830ce014be73d1#commitcomment-54184388

ということで、ご指摘反映させました。　https://github.com/copilot-jp/project-sprint/commit/9d406fe2db335fdd84dcf478c20de298d3767d07
問題なければこちらで v2.1.0 のブランチにマージします（本件がv2.1.0のメイン修正箇所となる予定です）。

**Comment by motoi** [comment]
@KokoroKagawa
よいとおもいました！

**Comment by KokoroKagawa** [comment]
8795aed
マージしたので閉じます。
