### ISSUE TITLE
EssentialsからAdvance等の関連項目にリンク

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#24]

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/32
でCODEの体系について方針が再決定されてから、その内容をEssentials上に反映。
イメージとしては末尾に関連リンクとして載せる

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/32
待ち

**Comment by Satoshi-Matsumoto** [comment]
#32
に合わせるのでマイルストーン調整

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん
https://github.com/copilot-jp/project-sprint/commits/code-v0.9.0-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E9%96%93%E3%81%AE%E3%83%AA%E3%83%B3%E3%82%AF%E8%A8%AD%E5%AE%9A

#32 の議論が落ち着いてきたのでこちらも作業しました。
新しい体系に合わせてリンク設定しましたがどうでしょう？ cc @motoi

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto いいと思います！

リンクがいくつか機能していなかったのと、今まであまり統一できてなかった表記の統一をしておきました。
https://github.com/copilot-jp/project-sprint/commit/f3edbbd1bc47aaf29a5aa2eedb23e50ef400ff92

.md でリンクをしておくと、GitHubの中でも文書を辿ることができますし、Jekyllが良い感じでhtmlに置き換えてくれますので、今後mdからmdへのリンクは、md指定で行いつつ、デバッグとして文書のリンクをGitHub内で辿ってみる、というのができると良いかと。

僕がまたリンクミス作ってるかもしれないので、一通りリンク辿ってみてほしいです。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
ありがとうございます！

リンクたどってみました。特に問題ないと思います。
そしてプラグインのフッターリンク（的なもの）が漏れていたので、追加しておきました。
https://github.com/copilot-jp/project-sprint/commit/9115b65edcae0d694a8358e58bf3b1959bbd47e9

> .md でリンクをしておくと、GitHubの中でも文書を辿ることができますし、Jekyllが良い感じでhtmlに置き換えてくれますので、今後mdからmdへのリンクは、md指定で行いつつ、デバッグとして文書のリンクをGitHub内で辿ってみる、というのができると良いかと。

こちらはりょうかいです。

@motoi てことで、このissueは私のほうでcloseしますね。
