### ISSUE TITLE
モードの概念の導入と、モード切り替えした時のコア部分の整理

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#240]
（今すぐに、4月までにorgに公開するかどうかは置いといて）Project Sprintの新しい整理の方向性になる気がするので徐々に紐解いていきたい。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
これですが、まずモードの話を受けての私の頭の中の整理を（ほぼ感想に近いですが）

まずモードの概念自体はある程度納得感があります。
そのうえで、
- マイルストーン
- ミーティング
- ミーティングの進行
- アジェンダ
- タスク
このあたりの材料（構成要素、コンポーネントみたいな表現がいいでしょうか）
についても三つのモードにで共通するものだと思うので、

「三つのモードに共通するものをコア概念として定義しなおし、
これプラス”モードが三つあること”くらいまでをきちんと整理・言及したドキュメント」をつくって、それを「Essentials」とするのが良いのではないかと思いました。

そのうえで、実際に作るかどうかは別として概念上は
- モード1のTutorial / Tips
- モード2のTutroial / Tips
- モード3のTutorial / Tips
があるようなイメージ。いまは、モード3のTutorial / Tipsはつくられている、ということかなと。

残り、CODEにはReference / Advanceあたりがありますが、これらはEssentialsと同じくモード共通のドキュメントになればいいと思います。

まとめるとこういう整理ですね。※太字はいまのCODE上にあるコンテンツ

  | モード1 | モード2 | モード3
-- | -- | -- | --
Essentials | 共通| 共通| **共通**
Tutorials | モード1のTutorial | モード2のTutorial | **モード3のTutorial**
Tips | モード1のTips | モード2のTips | **モード3のTips**
Advance | 共通| 共通| **共通**
Reference | 共通| 共通| **共通**

Essentialsに関してモード1 / モード2への拡張性を持った記述にするのが1stステップで、モード1 / モード2についてはTutorial や Tipsをつくるべきか、また改めて議論かと思います。
個人的には検討すすめれば作れないこともないと思いますが、あえて作る意味ある？っていうのが若干疑問でして、今のところ要らないのかなーと思っています。

**Comment by Satoshi-Matsumoto** [comment]
@motoi あとは、どこまでを"Project Sprint"と呼ぶかですね。これはひとえに何を重視したいのか、広めたいのかによると思います。

「ある程度のスキーム（マイルストーン・アジェンダ・タスクといった一連の構成要素のセットと使い方）によるプロジェクト推進メソッド」を広めたいということであればモード1 ~ モード3のコア部分を総称して「プロジェクトスプリント」といっていいと思いますし
![image](https://user-images.githubusercontent.com/61894329/107367101-5db3e080-6a8b-11eb-974b-5090ed17b020.png)

そうではなくて「全員で納得して進める、それぞれ自律的に動くメソッド」を広めたいのであれば、モード3の部分を中心に「プロジェクスプリント」というべきだと思います。
![image](https://user-images.githubusercontent.com/61894329/107367261-92279c80-6a8b-11eb-8474-1e8150a75515.png)

Super Good Meetingsはしくみを便利に使えるツールという側面が強いと思うので、前者、モード1 ~3全部スコープに入れていいと思いますが、PJSについては悩ましいですね。
マーケット上どっちが必要とされているか、とかで定義決めていいのかなとかも思うんですが、どうですかね？

**Comment by Satoshi-Matsumoto** [comment]
@motoi てことで整理の方向性という意味でコメントしてみましたがどうでしょうか。具体的にどうできるかなーというのはいったん書いてみていけばもうちょっとひも解いていけると思いますが。

あと、一応後からすぐ振り返られるように、公開可能な状態でモード概念・コアとカスタマイズの概念の資料、PDFあたりではりつけてもらうことできますか？

**Comment by motoi** [comment]
今の構想メモ。
- モード1,2をくっつけて誰かの仮説で進めるモードする
- 誰かの仮説ですすめるモードとみんなで進めるモードの2つの状態を同時に実現することをPJSとしては目指す
かなーとおもっております。

**Comment by motoi** [comment]
> あと、一応後からすぐ振り返られるように、公開可能な状態でモード概念・コアとカスタマイズの概念の資料、PDFあたりではりつけてもらうことできますか？

一応あなたは見れる位置に資料はおいてるけどpdfにしました！
[Project Sprint の持つ新たな共通点[WIP].pdf](https://github.com/copilot-jp/project-sprint/files/5994851/Project.Sprint.WIP.pdf)

**Comment by motoi** [comment]
プロジェクトの重要な要素としてベクトルに当たるものになるのかわからないけど「問い」があると感じられている。
アジェンダのタイトルをクエスチョンにする、リサーチクエスチョン、スプリントクエスチョン、プロペリングクエスチョンのように、問いが方向をつけている感覚。
プロジェクトクエスチョン、マイルストーンクエスチョン、ミーティングクエスチョン、アジェンダクエスチョン
ミーティングクエスチョンはリードアプローチの場合にミーティングでマイルストーンの設計に使うイメージ。

**Comment by KokoroKagawa** [comment]
@motoi これ、モードというよりはプロジェクトライフサイクルの文脈で整理していくことになりそうという理解で合っているでしょうか。
モードとライフサイクルの関連とか今後の方向性についてはちょっと議論して頭整理したいかもです。

**Comment by motoi** [comment]
ライフサイクルと、リーダーシップと、フラッグの考え方で整理できた感があるのでクローズ。
