### ISSUE TITLE
CODE英語版作成 v2.0.0準拠

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#241]

**Comment by Satoshi-Matsumoto** [comment]
#18 より派生。

**Comment by Satoshi-Matsumoto** [comment]
@nanamikagwa さん、
@motoi さんからGitHubの手ほどきを受けたのち、まとまって作業が完了したり、途中経過の報告や、わからないこと（Githubの使い方でも、中身の話でも）はこちらで会話ください！

**Comment by motoi** [comment]
トップページとエッセンシャルズからまず英訳していく

**Comment by motoi** [comment]
@nanamikagwa 
まずはこのページから翻訳しましょう！すでにファイルもあるし。
https://github.com/copilot-jp/project-sprint/blob/master/ja/index.md
↓
https://github.com/copilot-jp/project-sprint/blob/master/en/index.md

あとエッセンシャルズも翻訳できればと。
https://github.com/copilot-jp/project-sprint/blob/master/ja/code/essentials.md
↓
（まだこのファイルがないので新規につくる）

ぐらいから始めてもらえればと！

**Comment by nanamikagwa** [comment]
承知しました。（まずはトップ、その後エッセンシャルズ）

**Comment by nanamikagwa** [comment]
@motoi 
上記のタスクはいつまでに完了を理想としていますか？（すみません、事前に確認すればよかったです）
今のところ、トップ分の翻訳自体は終わっていて、翻訳だけは１時間もかからないくらいで終わりました。
github上に落とし込む作業は今途中ですが、翻訳と落とし込む作業込みで２時間ぐらいで作業完了するかなという印象です。

感触としてですが、１週間のうちに翻訳作業に割ける時間は今のところ多くて３時間ほどかなと。

**Comment by motoi** [comment]
@nanamikagwa 
返事がほしいときは右上のアサインを返事がほしい人に付け替えてください。基本は1名。
今回でいうと私にアサインをつけてください。

他の業務もあるとおもうので期限は特に定めませんがあったほうがうごきやすいということであれば遅くとも3月末までにはトップとエッセンシャルズを更新終わらせたいです。

またgithubの活動をみました。
いきなりマスターにコミットするのはよくないので、ブランチを切ってそこで作業してからプルリクだしてください。
という感じでいけそうならgithub上で活動してもらってよいですが書いてることがよくわからんということであれば、使い方をレクチャーしたほうがよいとおもうので、いまはgithub上で更新するのではなく、まずはエッセンシャルズの翻訳作業自体を進めてください。

足りない情報ありましたらご連絡くださいー。

**Comment by nanamikagwa** [comment]
@motoi ご返信が遅れました。すみません。
アサイン、返信が欲しい時は付け替えます。

状況として、TOPとエッセンシャルズの翻訳は一通り終わりました。
先ほどカレンダー（１５分程度です）を共有させていただいたのですが、ブランチを新しく作成してから作業を進める使い方の流れを一度実際の画面も踏まえて確認させてください。

**Comment by motoi** [comment]
完了につきクローズ！
