### ISSUE TITLE
デイリースクラム的な施策を提案することが多い

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#246]
定例を待たずして進捗を簡単に確認する、デイリースクラムの三つのプロセスを提案してやってみることが多い。これどこかに書かれてもよいとおもいました。検査と適応。

**Comment by motoi** [comment]
この記述したいなと思ってるんすけど、わたしからも少しまとめて情報提供したらよいすかね？その情報見なきゃ掲載するか判断できないよね？

**Comment by Satoshi-Matsumoto** [comment]
@motoi そうですね、お願いします！

**Comment by motoi** [comment]
書きましたー。あんまりデイリースクラムと変わらんかった。。。。
[定期的なタスク進捗共有方法-デイリースクラム導入.pdf](https://github.com/copilot-jp/project-sprint/files/6075665/-.pdf)

@Satoshi-Matsumoto さん確認ください！

**Comment by motoi** [comment]
スクラムガイドをまず読んでください
https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Japanese.pdf

**Comment by motoi** [comment]
ティール組織のインプット
https://www.amazon.co.jp/dp/4297102579
ホラクラシー
https://www.amazon.co.jp/dp/4569827713/

**Comment by KokoroKagawa** [comment]
@motoi 
ご共有いただいた資料をもとに、Tips16として一旦書いてみました。ご確認くださいませ。
https://github.com/copilot-jp/project-sprint/commit/d26af6da2c6ed436a400f83b5bb921e413ba0e38

**Comment by motoi** [comment]
@KokoroKagawa デイリースクラムって名前は変えてもよいかもとおもいました。
その理由
・毎日じゃなくてもよい。というか毎日やるほうが少ない。
・スクラムじゃないからスクラムという名前を使うのは違和感がある。本物のスクラムみたいに組んでるみたいなイメージだったありかもだけど。

よくあるのは毎週ミーティングだと週のまんなかぐらいに確認的に挟む、隔週の定例だと1週間の終わりとか始まりとかに行うことがおおい。
途中結果報告ミーティングみたいなイメージなんだけどなんかネーミングひらめきますかね！？

**Comment by KokoroKagawa** [comment]
@motoi 進捗報告会…？メソッドチームだとそれこそ「進捗会議」ですよね。

**Comment by motoi** [comment]
スタンドアップ → 短い時間で行う感じ
ハドル → 行動前の短い作戦会議（最近Slackが実装したので普及する用語になりそう）

良さげな参考があった。
https://www.atlassian.com/ja/agile/scrum/standups

なんだかんだスポーツ用語多いよなーとおもいつつ、敵がいないプロジェクトに適しているのかはなかなか謎のまま。
まあ「問題 vs 私達」をつくるとすると問題が敵って考えればよいのか。そう考えると問題解決が私達の目的か。

ということで「スタンドアップ」でお願いします！

**Comment by KokoroKagawa** [comment]
@motoi 書きました。ご確認お願いします！
94552f0
6cc5fb5

**Comment by motoi** [comment]
@KokoroKagawa
https://github.com/copilot-jp/project-sprint/commit/94552f0f62945a8f4a97eee72c612b268c44377b
ちょっとスクラムのデイリーに近くなってた感があったので調整しました。
元原稿がそうなってんじゃんってものばかりですみませんが、PJSがアップデートしているということで。。。

**Comment by KokoroKagawa** [comment]
@motoi https://github.com/copilot-jp/project-sprint/commit/c6ceb89598f603ba8f53d04c265a235b468e1a8e
具体例諸々ありがとうございました。こんな感じでいかがでしょうか。

**Comment by motoi** [comment]
よいとおもいました！ @KokoroKagawa

**Comment by KokoroKagawa** [comment]
ありがとうございました。v.2.2.0にマージしたのでクローズします
