### ISSUE TITLE
リファレンスで心理的安全性をもっと詳しく紹介したい

### ISSUE THREAD

**Issue by ji-daraku** [copilot-jp/project-sprint#247]
プロジェクトスプリントにおいてみんなで進める環境を構築するためには心理的安全性が非常に重要な要素になる。
心理的安全性の概要や、どのように導入するものなのかを含めてリファレンスで紹介したい。
またそれ以外で心理的安全性の測定方法などもcodeでも紹介することになるかもしれない。

最初に心理的安全性の概要を作成してチームに共有することを目指します。

**Comment by motoi** [comment]
リファレンスには詳細な用語説明をしない方向性になったのでクローズします！
