### ISSUE TITLE
リリース用のプルリクにターゲット日いれない？

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#250]
@Satoshi-Matsumoto さん、どのプルリクがいつあがるのかってちょっとわからなくなってきたので、プルリクにターゲット日入れるのとかどうでしょう？

**Comment by motoi** [comment]
@Satoshi-Matsumoto
サトマツさん考えてください！

**Comment by KokoroKagawa** [comment]
次回アップデート用の管理ブランチ：次回リリースのターゲット日を入れる
	管理ブランチの命名ルール：
	dev-yyyy-mm-dd-release
	※yyyy-mm-dd-は、次回リリース予定日

管理ブランチをMasterにマージするためのpull request：：次回リリースのターゲット日を入れる
	pull requestの命名ルール：
	yyyy-mm-dd-release
	※最終的なリリース作業にはいるまでは、冒頭に[WIP]を記載する。
	例：[WIP] 2021-12-09-release
