### ISSUE TITLE
各言語のトップページに戻る導線が欲しい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#252]
今、各言語のトップページにラーニングパスが書いてあるので記事読了後にその部分に戻りたいかそのパスが現状存在しないので不便。

![image](https://user-images.githubusercontent.com/680855/111227086-64eb8280-8625-11eb-84a8-3edacc588d87.png)

**Comment by motoi** [comment]
@yoneyama-tomohiro これ米山さんへのイシューとして良いですかね？サトマツさん？

**Comment by yoneyama-tomohiro** [comment]
https://copilotjp.slack.com/archives/CR5H88YJH/p1619506964008100

**Comment by motoi** [comment]
グロナビとフッタに各言語トップのリンクが欲しい

**Comment by motoi** [comment]
各ページフッタは手作りの可能性があるので仕様を確認して菊地さんに連絡
@nanamikagwa さんお願いします。

**Comment by nanamikagwa** [comment]
@kikuchiharuma 
ご相談なのですが、各Project Sprint CODEのページ（Tutorial, Essentials, Tips, Advance, Referenceのページ）のフッター 部分に各言語のトップページに遷移するよう下記スクショのように作成してみました（イメージでお伝えしたかったので、header_footerブランチで作成しています）
そのProject Sprint Topリンクがあるフッター部分をスクショ2枚目のように固定フッターとして作成することというのはできますでしょうか？もしくは今固定してあるフッター部分にTopリンクをつけることというのは可能でしょうか？

各言語のトップページを固定としておくことで、いつでも各CODEページからTopのラーニングパスなどを確認できるようにしたいなと思っておりました。説明が不足しておりましたら、ご指摘ください。

![image](https://user-images.githubusercontent.com/77031685/123931234-628e1800-d9cb-11eb-8bec-088eddcfca65.png)
![image](https://user-images.githubusercontent.com/77031685/123931471-80f41380-d9cb-11eb-89da-c3011a994809.png)

**Comment by kikuchiharuma** [comment]
フッターにメニューを置いてみました。こういうことでしょうか
https://61516b3b0073a90008aae278--project-sprint-staging.netlify.app/

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/156
こっちに吸収された認識ですー。認識あってたらクローズお願いします。
