### ISSUE TITLE
わからない単語：〇〇ドメイン（プログレスドメインなど）という言葉が理解しづらい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#253]
元コメント
https://github.com/copilot-jp/project-sprint/issues/117#issuecomment-776579631

**Comment by motoi** [comment]
なんらか補足の言葉を入れるのかなど方向性を決めたいのをサトマツさんにパス。
もっとヒアリング必要ということであれば @ji-daraku さんと一回コミュニケーション
ということで一旦サトマツさんコメントください！

**Comment by KokoroKagawa** [comment]
@motoi @ji-daraku 
「ドメイン」という言葉そのものが分かりにくいのか、「プログレスドメイン」「チーミングドメイン」「プロセスドメイン」というそれぞれのドメインの内容が分かりにくいのか、まずはお伺いしたいです！
前者は直接的な説明はorg内にはないのですが、「プロジェクトを３つの領域に分けている」というだけの話なので、補足いらないような気がしています。後者であればEssentialsに記載があります。

**Comment by motoi** [comment]
これは私もこころさんと同意見かな。
@ji-daraku さんからのご連絡待ちってことでアサインつけかえ。

**Comment by motoi** [comment]
@KokoroKagawa さんから理由をつけてもらってクローズ

**Comment by KokoroKagawa** [comment]
Issueの起票者に修正方針・修正稿の確認をお願いするというフローをなくし、Issue化後は基本的に事務局で対応（賀川(こ)作業→定金さんレビュー）することとしました。起票者の負担が過大になることや、対応速度が落ち非効率であることが理由です。
ただし、Issueの明確化のために起票者との会話を必要とするケースや、起票者にさらに深掘りをしてもらうべく当該IssueのAssigneeとするケースは、引き続き発生しうる見込みです。

本Issueは https://github.com/copilot-jp/project-sprint/issues/253#issuecomment-878150311 の通り対応不要との事務局判断でcloseします。
