### ISSUE TITLE
わからない単語： [場所]tips1＞イベント 　「イベント」（「プロジェクト外部環境」という言葉が違和感あり、プロジェクトとの相関関係があり外部と切り離すこと&プロジェクト内にもイベントがありそう）

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#254]
元コメント：
https://github.com/copilot-jp/project-sprint/issues/117#issuecomment-776653187

なんらか補足の言葉を入れるのかなど方向性を決めたいのをサトマツさんにパス。
もっとヒアリング必要ということであれば @ji-daraku さんと一回コミュニケーション
ということで一旦サトマツさんコメントください！

**Comment by KokoroKagawa** [comment]
@motoi 
>プロジェクトとの相関関係があり外部と切り離すこと
(※賀川：「プロジェクトとの相関関係があるのに、『外部』として切り離してしまっていいのか」という問題意識だと理解しました。)
>プロジェクト内にもイベントがありそう

「イベント」というのは、プロジェクトの外部の環境だとか制約だとかを指すので、プロジェクト内のものはそもそもイベントと呼ばない。
（自分たちで制約を作れるか？⇒決めても自分たちで変えてしまえるので制約足りえない、という話に近い）
また、代表的なイベントである、社内の意思決定機関・稟議体制等は、プロジェクトを制約こそすれ、あくまでプロジェクトの外部に位置するものです。

よって修正不要と思うのですが、ご意見伺いたく。わたしの認識違いがあればぜひ教えてください！

※「イベント」、確かにイメージにぶれが出そう・違和感を抱く人がいそうな用語だなとは思います。イベントと制約が厳密には異なるというのは理解しているのですが、「イベント」はここのPJS内ではここのtipsでしか出てこないので、いっそ「制約」と書き換えるのもありなのかな、と思ったりしていました。

**Comment by KokoroKagawa** [comment]
@motoi https://github.com/copilot-jp/project-sprint/commit/9ca929f5457e0bff7a287ec554b1e2756ec5ebfa
書き直してみました。いかがでしょうか。

--メモ---------------------------------＊゜

イベント→制約に書き換えてもよいのでは？
制約＝マイルストーンやゴールに影響を与える前提条件。イベントであることが多い。
イベント＝マイルストーンやゴールの設定時に、影響を与えるものとして意識されていたもの

イベントは外部のもの。
プロジェクト内のイベント的なもの＝ファンクションのロードマップ

①大きな制約：意識しなくていい（プロジェクトが大幅に変更・停止するから）
②マイルストーンに影響を及ぼす制約：都度マイルストーンを見直していく必要あり

**Comment by motoi** [comment]
@KokoroKagawa よいとおもいました！めちゃわかりやすくなりました。

**Comment by KokoroKagawa** [comment]
確認ありがとうございました！
v2.2.0にマージしたのでクローズします。
