### ISSUE TITLE
咀嚼難しい説明： [場所]tips2 　「フェーズ名: マイルストーン間の意味的な位置づけ」がどういうことか抽象的で理解しずらいように感じました。（下の例に具体的な言葉が入っていると嬉しいです）

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#255]
元コメント
https://github.com/copilot-jp/project-sprint/issues/117#issuecomment-780458295

**Comment by motoi** [comment]
なんらか補足の言葉を入れるのかなど方向性を決めたいのをサトマツさんにパス。
もっとヒアリング必要ということであれば @ji-daraku さんと一回コミュニケーション
ということで一旦サトマツさんコメントください！

**Comment by KokoroKagawa** [comment]
@motoi 
フェーズに関しては[Tips1](https://projectsprint.org/ja/code/tips/tips1.html)に分かりやすい記載があったので、そちらをベースに、例示されている表形式を埋めました。いかがでしょうか。
https://github.com/copilot-jp/project-sprint/compare/%23255

ここまでやるなら「あるべき姿」も書いたほうが美しいかもしれないのですが、冗長になりすぎると思ったのでいったん省いています。

**Comment by motoi** [comment]
@KokoroKagawa 
これだいぶ返事おくれてすみません。
マイルストーンを資料化に時間がかかってしまいました。
といいつつ、現状の最新版は以下の資料なんですが、まだアップデートされそう感あるので（ただいま様々なプロジェクトで実験中）、いったん現状こころさんに修正でアップデートしてもらえればとおもいました。
具体的な事例として表を埋めるのはこのデータを使ってもらっても良いかもですが。

[1-8. Project Sprint で活用する マイルストーンの意義と記入・運用方法.pdf](https://github.com/copilot-jp/project-sprint/files/6878142/1-8.Project.Sprint.pdf)

**Comment by KokoroKagawa** [comment]
@motoi ありがとうございます！
いただいた資料をもとに、マイルストーンマップの運用方法等について追記し、具体事例を差し替えました。
144918f

ご確認いただき、違和感なければ一旦これで次回リリース（v.2.1.0）に乗せます。

**Comment by motoi** [comment]
@KokoroKagawa 
よいとおもいました！

**Comment by KokoroKagawa** [comment]
v.2.1.0 にマージしたのでcloseとします。
https://github.com/copilot-jp/project-sprint/commit/deb16d46cdfd7ac3d961a943beb1a2ee4cc5c64a
