### ISSUE TITLE
咀嚼の難しい説明」： [場所]tips8＞5段落目3項目 　「参加者がアジェンダの完了について納得していることを証明する手段」共感しつつも、どうやればいいのか具体的な手段が思いつかないので、具体的な手段例があると嬉しいと感じました。

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#256]
元コメント
https://github.com/copilot-jp/project-sprint/issues/117#issuecomment-780495343

**Comment by motoi** [comment]
なんらか補足の言葉を入れるのかなど方向性を決めたいのをサトマツさんにパス。
もっとヒアリング必要ということであれば @ji-daraku さんと一回コミュニケーション。
ということで一旦サトマツさんコメントください！

**Comment by KokoroKagawa** [comment]
@motoi 確かに参加者全員が納得していることは担保されているべきだなと思うものの、私も具体例が思いつかないので、補足を入れたほうが親切でしょうね。
ただし、これは必ずしもミーティング前に準備されているべき要素ではないような気もします（「結果」要素も議論が終わってからの記載となりそうなので、アジェンダアイテムのすべての要素がミーティング前に準備されているべきではないとの理解です。議論すべき項目として記載されていればOK）。
となると、「議論の最後に、参加者から更なる不明点や異論が出ないか確認する」という、アジェンダアイテムの要素というよりは議論の手順に近いものなのかな、とも思います。

いかがでしょうか＆具体例ありますか？

**Comment by KokoroKagawa** [comment]
あ、こっちと合わせて考えるべきであることに気づいた。
https://github.com/copilot-jp/project-sprint/issues/83

**Comment by KokoroKagawa** [comment]
https://github.com/copilot-jp/project-sprint/issues/83　と対応内容が重複するので、マージしてクローズします。
