### ISSUE TITLE
分からない単語： [場所]essenntials＞ステータス＞２段落2行目 　「インクリメンタル」、２段落3行目 　「デリバリー」

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#257]
元コメント
https://github.com/copilot-jp/project-sprint/issues/117#issuecomment-788674219

**Comment by motoi** [comment]
なんらか補足の言葉を入れるのかなど方向性を決めたいのをサトマツさんにパス。
もっとヒアリング必要ということであれば @ji-daraku さんと一回コミュニケーション。
ということで一旦サトマツさんコメントください！

**Comment by KokoroKagawa** [comment]
@motoi 以下赤字のような一文を入れるのはいかがでしょうか。
![image](https://user-images.githubusercontent.com/84454164/124450128-170aae00-ddbf-11eb-9e10-eaaace4ff355.png)
Essentials: https://projectsprint.org/ja/code/essentials.html

**Comment by motoi** [comment]
@KokoroKagawa 
「一気通貫で全体を完成させようとするのではなく、」がなくてもよいかもとおもいました。
あとはわかりやすくなったとおもいました。

**Comment by motoi** [comment]
https://rihoublog.com/2020/06/07/%E3%82%A4%E3%83%86%E3%83%AC%E3%83%BC%E3%83%86%E3%82%A3%E3%83%96%E9%96%8B%E7%99%BA%E3%81%A8%E3%82%A4%E3%83%B3%E3%82%AF%E3%83%AA%E3%83%A1%E3%83%B3%E3%82%BF%E3%83%AB%E9%96%8B%E7%99%BA%E3%81%AE%E9%81%95/
参照先。
イテレーティブをいれるように @KokoroKagawa さんが調整。

**Comment by KokoroKagawa** [comment]
@motoi 対応しました。ご確認お願いします。
864f64d

**Comment by motoi** [comment]
@KokoroKagawa よいとおもいましたー！

**Comment by KokoroKagawa** [comment]
v2.1.0にマージしたのでcloseとします。
https://github.com/copilot-jp/project-sprint/commit/a426a1e3d5d1ef59da6e02f9e9c79b24620e3f98
