### ISSUE TITLE
オープンなGithubやSlackに移行するにあたりファイルサーバーをどうするか検討したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#26]
いまはコパのファイルサーバーで行っているがもっとオープンなファイル置き場を作りたい。どの運用体制が良いかを検討したい。 @hatake0-0 さん相談にのってちょ！

**Comment by kikuchiharuma** [comment]
@motoi 誰でも取りに行けるファイル置き場、ということであれば、projectsprint.org/resources/... とかにファイル一覧と一緒に置いておけばいいんじゃないでしょうか

**Comment by Satoshi-Matsumoto** [comment]
これいつまでに解決します？
いったんMilestoneをv1.0.0に設定するので間に合わなさそうであればコメントくださいまし。

**Comment by motoi** [comment]
> @motoi 誰でも取りに行けるファイル置き場、ということであれば、projectsprint.org/resources/... とかにファイル一覧と一緒に置いておけばいいんじゃないでしょうか

公開が決まった固定バージョンはそれでよいとおもいます。
私がここで話題にしているのは、検討中のGoogleドキュメントとか制作途中のファイルをどこで扱うか、のはなしでした。コパの共有ドライブでリンク知っている人には全開放、みたいなものをつくればよいのかしら。。。とかそういう話ですね。

**Comment by motoi** [comment]
っていま書きながらおもったのですが、この内容であればここで扱うイシューではない？ @kikuchiharuma さんどうでしょう？

**Comment by kikuchiharuma** [comment]
@motoi 誰がなんのために使う置き場なのか、によると思います。PJSのコミッターになる上で必要な情報をどこに置こうか、ということであればIssueで議論する内容かなと思いますし、ここ(GitHubのどこか)に置くのが自然のように思います。

**Comment by kikuchiharuma** [comment]
このリポジトリを、サイトで公開するファイルと中間成果のファイルに分ける、という運用も(今はreadme.mdだけがそういった扱いですが、このフォルダ以下だけがサイト用、それ以外は別の目的のもの、というやり方があるのです)やってもいいかもしれませんね。

**Comment by motoi** [comment]
いったん現状は考えない。
