### ISSUE TITLE
【Orgサイト】注釈機能

### ISSUE THREAD

**Issue by yoneyama-tomohiro** [copilot-jp/project-sprint#263]

**Comment by yoneyama-tomohiro** [comment]
@kikuchiharuma cc: @nanamikagwa 

大変遅くなってしまいすみません。。m(_ _)m
こちらですが、以前菊池さんから以下のコメントをいただいていましたが、

> こちらの件、具体例をいただけるというお話をしていたような気がしていますが、どうでしょう。PJS のこのページのこの箇所に、こういう内容の注釈を入れたい、といった具体的なサンプルです。markdown を自動でページ化している都合上、markdown の表現力を超えている「注釈」の追加は扱いが難しく、具体例をベースに話す必要があると思っています。

個人的には、以下あたりが実現案になるかなと思っています。

案1）CPブログのようなスタイル（前述していたもの）
- CPブログのような形で、注釈をつけたい単語の近くで説明文を記載する形
- https://blog.copilot.jp/entry/what_is_knowledge_management

案2）一般的な書籍のスタイル
- 文中には「*1」「*2」などを入れつつ、ページの最後に注釈分を入れる形
- その場合、できれば、「文中の脚注数字」と「文末の脚注部分で表示される数字」は、相互に行き来できるような形でリンクさせられると読みやすいかなと思っていますが、実現性・実現コストとの判断で良いかなと思います
- 以下のブログのようなイメージです
- http://affiliate-hatekun.hatenablog.com/entry/%E5%85%A5%E9%96%80/%E3%81%AF%E3%81%A6%E3%81%AA%E3%83%96%E3%83%AD%E3%82%B0%E3%81%A7%E8%84%9A%E6%B3%A8%E3%82%92%E4%BB%98%E3%81%91%E3%82%8B

**Comment by kikuchiharuma** [comment]
@yoneyama-tomohiro ありがとうございます。形式についてはよくわかりました。質問は2つありまして、PJS の現状のドキュメントに対して「こういう内容の注釈を入れたい、といった具体的なサンプル」についてはいかがでしょう。それをいただければ何がしか提案できそうな気がします。

**Comment by yoneyama-tomohiro** [comment]
@kikuchiharuma 
ご要望のサンプルになっているかわかりませんが、このようなイメージです。

■ケース1）内容の補足説明として文章を記載したい場合
該当ページ：https://projectsprint.org/ja/code/tutorial/section1-1.html

「プロジェクトスプリントでは、プロジェクトを推進するための活動を3つに分けて考えます。」という文章が冒頭の方にありますが、ここで言う「プロジェクト」とはどういうものなのかということを補足したほうが良いと思われ、たとえば、以下のような内容のことを補足できればというイメージです。

※ここで言う「プロジェクト」は、・・・という内容のものを前提としています。具体的には・・・であり、・・・のようなケースはここではプロジェクトとは考えていません。

■ケース2）参考資料のURLを貼り付けたい場合
該当ページ：https://projectsprint.org/ja/code/tips/tips9.html

このページではふりかえりのやり方について言及していますが、参考として、実際のふりかえりで使用するスライドのURLを注釈として入れてもよいのではないかと思っています。
（スライド以外にも、関連記事を注釈で入れるようなケースもあるかもしれません）

**Comment by kikuchiharuma** [comment]
Gitbook で解消見込み
