### ISSUE TITLE
【Orgサイト】文字文字しさを軽減するスタイルに変更したい

### ISSUE THREAD

**Issue by yoneyama-tomohiro** [copilot-jp/project-sprint#264]
一旦、スタイルシートで対応可能な範囲で？

（例）
・フォントを100%黒ではなくグレーにする
・行間隔を広げる
・見出しのデザイン（例：アンダーラインを入れるとか）

**Comment by yoneyama-tomohiro** [comment]
@kikuchiharuma 

orgサイトの件のご相談です！
以前のMTGでちょこっとお話させていただいたかもしれませんが、
サイト内の文章を読みやすい形にできるといいなぁ、と思っています。

たとえば、以下のような事項で、CSSでまとめて修正することを想定しているのですが、いかがでしょうか？
・フォントを100%黒ではなくグレーにする
・行間隔を広げる
・見出しのデザイン（例：アンダーラインを入れるとか）

もう少し具体的に修正内容をご提示したほうが良いですかね？
私に美的センスがないので、菊池さんセンスで修正いただく形でも、、、と思っていますが、ご相談させてください！

**Comment by kikuchiharuma** [comment]
Gitbook で解消見込み
