### ISSUE TITLE
[PJS概念図]と[ゴールとマイルストーンの関係]図を英語版に編集できる図の資料を共有していただけたら助かります。 

### ISSUE THREAD

**Issue by nanamikagwa** [copilot-jp/project-sprint#265]
Essentials等などのCODEの英語版を作成しておりまして、[PJS概念図]と[ゴールとマイルストーンの関係]図を英語版に編集できる図の資料を共有していただけたら助かります。 [PJS概念図]はEssetialsにありまして、[ゴールとマイルストーンの関係]図は[プロジェクトのゴールとマイルストーンを設定する]のページにあるものです。

![image](https://user-images.githubusercontent.com/77031685/113136012-ce8ea200-925d-11eb-9ddf-88782023e7bf.png)
![image](https://user-images.githubusercontent.com/77031685/113136085-e1a17200-925d-11eb-93cb-19b7ac776048.png)

**Comment by kikuchiharuma** [comment]
@nanamikagwa 元データは Figma で、ここにあります。https://www.figma.com/file/SYjW9eBHexFxG44RDBKMET/Project-Sprint?node-id=0%3A1
