### ISSUE TITLE
最初にでるPJSロゴがでかすぎません？

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#27]
細かいですが（笑）みるたびにでかいなーなんかアピール感がありすぎるなーとおもってしまうので検討ください！

**Comment by kikuchiharuma** [comment]
デカすぎますね！何とかします

**Comment by Satoshi-Matsumoto** [comment]
v1.0までに修正しましょう。

**Comment by kikuchiharuma** [comment]
サイズ指定するにはimgタグを使うしかないらしい

**Comment by kikuchiharuma** [comment]
幅50％にした
https://github.com/copilot-jp/project-sprint/commit/881cc2daf9d3df8890dacad055edaf7559f2178d

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto これ、あとはリリースするだけなんですが、サトマツさんアサインされても困りますよね…リリースと言っても文書のリリースとサイトの体裁のリリース分けて、サイトは僕が勝手にリリースした方がいいですかね
