### ISSUE TITLE
英語版ページのナビゲーションが各カテゴリをクリックすると日本語ページに遷移する件について

### ISSUE THREAD

**Issue by nanamikagwa** [copilot-jp/project-sprint#274]
定金さんが一旦マージさせてしまったのでまだナビゲーション部分は対応していないということだと思うのですが、
英語ページを確認していたところ各カテゴリのナビゲーション部分を選択すると、日本語ページのTutorial やEssentialに遷移しました。こちらを各カテゴリ英語ページに遷移していただけたらと思います。試してやってみようと思ったのですが、うまくいかず.....
※すでに把握していらっしゃることかと思いますが、気づいた点だったので念のためIssueにてあげておきます。

**Comment by kikuchiharuma** [comment]
/en/ 以下で英語メニューが出るようになりました
https://61516b3b0073a90008aae278--project-sprint-staging.netlify.app/
