### ISSUE TITLE
タスクがもつチーミング効果を明晰にして記述したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#275]
いまタスクをPJSのなかでどういう機能、要素として位置づけられるかについて考えている。
マイルストーンに沿ったタスクの実践は、インクリメント、イテレーションで考えると、マイルストーンの進行に寄与するもの。これは異論はないとおもうしメソッドでも定義されている。

さらにタスクとはチーミングにも効果があるなと感じているし考えてもいる。
そのため、まずは考えやすくするために、チームとして学習できている状態とタスクの関係性を考えている。

チームとして学習するということはどういうことか。
学習していないとはどういうタスクが与えられた状態か。
単に振られたタスクを実践していて学習というものはできないのか。
チームとしての学習と個人としての学習の違いはなにか。

先程のミーティングでは、発散するために雑な質問として、
チームの学習の反対語として、誰かの仮説の検証スピードというものがありえるのか？について問いをたててみた。

**Comment by motoi** [comment]
議論後の定金のコメント。
シュチュエーショナルリーダーシップとか考えると単なるタスク処理でも学習になるか。
私は自分でタスクについて考えないから、学習効果がすくないのではないか、とおもってしまった。これは自律性みたいなものと学習がごっちゃになってしまった感がある。

**Comment by motoi** [comment]
みんなからもらったコメント
学習の反対語として、誰かの仮説の検証スピードというものがあるようには感じない。
とはいえ、学習していないという状態もなさそうな予感もする。

**Comment by motoi** [comment]
こころさんが現状の記述と照らし合わせて問題なければクローズ

**Comment by KokoroKagawa** [comment]
記述を微調整した上でクローズとします。
