### ISSUE TITLE
トラックとチームの言葉をもうすこし厳密に定義したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#276]
プロジェクトにはチームが存在している。
トラックが存在してそのトラックの役割を担うのはトラックのチームと呼ぶのかなど、もう少し明晰にしたい。

**Comment by motoi** [comment]
@kikuchiharuma さんメモ。なんか追記あればこちらにぜひ。
トラック、チームの使い分け。ビジネストラック、ビジネスチーム、という言い方が出てきて、似たような対象を呼んでそうで定義をはっきりしたい
(メソッドがトラックという呼び方を提案していて、その周辺の話題として)

**Comment by KokoroKagawa** [comment]
一旦閉じ。また気になったら議論する。
