### ISSUE TITLE
明示ロールと暗黙ロールはどちらが多い方が良いか

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#28]
> 暗黙ロールは、明示ロールに転化していればいるほど良い

とありますが、逆のように思いました。
最高の状態は明示ロールを必要としない十分な暗黙ロールを持つチーム、というイメージです。

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/advance/index.md#%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AE%E6%80%A7%E8%B3%AA

**Comment by motoi** [comment]
一回、ロールが明示されて、そのあと暗黙に進むみたいなイメージだと思っていまして。その辺がうまく表現できれば良い気がしました！

**Comment by Satoshi-Matsumoto** [comment]
修正しました。
1fe0487

ほんとは最初から暗黙 - 阿吽の呼吸だったらいいんだけど、そんなことはあんまりないので、いったん明示化されてから、そのうえで暗黙的にいろんなことに対応できることになるのが通常だよ、ということを表現したつもりです。

@kikuchiharuma @motoi 
違和感ないか確認お願いします。

**Comment by kikuchiharuma** [comment]
表現したいチームのダイナミズムは共有できた気がします。ただ項目としては違和感が残りました。

表現としては、〜すればするほどよい、という形で揃っているリストなので、ここだけ「全て〜であるべき」という言いきりになっているのが気になりました。明示ロールが残ってるとダメ、みたいに読めてしまうかも知れません。前回はその逆で、暗黙ロールがあるとダメ、に読めます。

ここで言うべきは、暗黙ロールでも明示ロールでも共有方法は問わないから、そのチームが無駄なコストをかけずに共有できるそのときに適した方法で、共有すべきロールがたくさん共有されていればいるほどよい、ということじゃないでしょうか。

**Comment by kikuchiharuma** [comment]
@motoi どこまで誰が進めるか、ハンドリングオネシャス

**Comment by motoi** [comment]
@Satoshi-Matsumoto 定金コメントです。
私も菊地さんのコメントの感覚に近いです。

> 暗黙ロールでも明示ロールでも共有方法は問わないから、そのチームが無駄なコストをかけずに共有できるそのときに適した方法で、共有すべきロールがたくさん共有されていればいるほどよい、ということ

これだとおもいます。そのうえでコメントしていきまっす。

> ・暗黙ロール・明示ロール問わず、ロールの種類は多ければ多いほど良い（ただしこれは、不必要にロールを規定することを意味しない）

→ 多ければ多いほうが良いってのはちょっとよくわからなかった。そっちの方がよいんだっけ。

> ・必要なロールが、すべて暗黙ロールとしてまかなわれている。（ただし、最初からメンバー間で期待値が十分に一致した暗黙ロールができることはことはほとんどない。多くの場合それらの暗黙ロールは一度明示ロールとして表現され、期待値のすり合わせが行われる。そうしてできた明示ロールをベースに、各メンバーは未知の事柄にたいしても暗黙ロールとして引き受け、対応することが可能になる）

これは菊地さんのコメントにある感じかなと。
のこすべきは、カッコ書きの部分はよいとおもいました。

> ・暗黙ロール・明示ロール問わず、より多くのメンバーによって引き受けられているのがよい

→ 確かに多いほうがチーム作りに寄与しそうなので良い気がするものの、バシッと言えるほどの確信はあんまりないなー。
ロールを理解したうえでより多くのメンバーが各ロールのやるべきことをお互いにフォローし合える、とかのニュアンスだとめっちゃいいチームと自信もっていえる。

**Comment by Satoshi-Matsumoto** [comment]
こんな感じで、どうでしょう？刻んでコミットしてしまいましたが、
時系列で読んでみてください。

905d4311acbd6915ab9897ff54c2cd2f4cb95855
d0f9fe3465e220e38dd007347c90e003128fb414
a14304e3311d9f1680fa39d7b622ae4aa5b00c3f
7e224d74b294ffe47a80bbe4384f92fe5571508e

ポイントとしては、明示ロールと暗黙ロールのどっちがおおいかは、別にどっちでもよい。
ただ、明示ロールと暗黙ロールの遷移の仕方というものはある。

また、明示ロールと暗黙ロール問わず、ロールというものに対して好ましい状態はあって、
それは
- ロールの理解されている粒度の細かさ（ロールが多い少ないではない）
- チームに適した方法で共有されている
- 共有 + 理解があったうえで、互いにフォローしあえる状態である

ということなのかなと。

まず @kikuchiharuma そのあと、 @motoi　レビュー確認、おねがいします！

**Comment by kikuchiharuma** [comment]
ここでまとめて読みました。全体的に良いと思うのですが、

> そのチームにとって最もコストのかからない方法で、共有すべきロールが多く共有されているほどよい。

ここは確かに僕が「たくさん共有」と書いたと思うのですが、不必要に多いほうがよい、という感じに読めてしまうなあと思いました。
「チームが成果を出すために必要十分なロールが共有されているのがよい」
(必要十分というのは、チームのメンバーが望む以上は必要なくて、無理して作らなくていいよということ)
「ロールが多いほうがいいのか少ないほうがいいのか、暗黙ロールが多いほうがよいか、明示ロールが多いほうがよいかはその場面やチームの状態によるので一概に言えない」
ということが誤解なく伝わるとよいなと思いました。

**Comment by kikuchiharuma** [comment]
一度サトマツさんで

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/commit/b59db70d09e7d8c69c123daa86d0c42c362934ea
全体としてなるほど、という感じだったのでその通りに調整しました。いかがでしょう？

**Comment by kikuchiharuma** [comment]
いいと思います！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma ありがとうございます！

@motoi ご確認いただき、問題なさそうならクローズください。

**Comment by motoi** [comment]
確認しました。よいとおもいます！
