### ISSUE TITLE
チームマネジメントがアドバンスとプラグイン両方にある

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#29]
https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/plug-in/index.md#%E3%83%81%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0%E7%B7%A8

https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/plug-in/index.md#%E3%83%81%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0%E7%B7%A8

**Comment by kikuchiharuma** [comment]
プラグインにもあった
https://github.com/copilot-jp/project-sprint/blob/develop/v0.8.2/ja/plug-in/index.md#%E3%83%81%E3%83%BC%E3%83%A0%E3%83%9E%E3%83%8D%E3%82%B8%E3%83%A1%E3%83%B3%E3%83%88

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/commit/f43b157f94ff0435f58997ca546432a520bdf85d
で対応しました。

@motoi 
特に問題なければ、クローズをお願いします。

**Comment by motoi** [comment]
クローズで！
