### ISSUE TITLE
tipsトップの表示崩れ

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#292]
![image](https://user-images.githubusercontent.com/680855/131314289-416116c6-6e14-4a72-83ac-6ece45c537be.png)
見出しが表示崩れしているので修正ください！

**Comment by KokoroKagawa** [comment]
@motoi
リリース前ですが作業済みです。ご指摘ありがとうございます。
https://github.com/copilot-jp/project-sprint/commit/00829a3e683bf7a35daebf2d2d332a587d0d1877

2.1.0のパッチとして、2.2.0にマージする形で出します。
