### ISSUE TITLE
ファンクションという名前が残っているがロールの古い言い方？

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#30]
プロセスを担う役割の説明として、ファンクションという用語が残っている
初見の人はロールを理解してもファンクションて何となってしまいそう
https://github.com/copilot-jp/project-sprint/blob/master/ja/advance/index.md#%E8%AD%B0%E8%AB%96%E3%82%92%E4%BF%83%E3%81%99%E4%BA%BA

**Comment by kikuchiharuma** [comment]
プロダクトチームとの対話の中では「帽子」という呼び名が話題になりました
外部化した、選択的に身につけたり、外したりできるものという意味
PJSもそのままならってもいいと思いました。

**Comment by Satoshi-Matsumoto** [comment]
ここは意図的にファンクションとしている箇所で、ロールとは別のものになります。
なので、残っているというか、消すつもりがそもそもないですね。
意味としては、だれがやってもいいもの、ただし機能的には必須でおいてほしいもの、です。
ロールが暗黙や明示の間のなかで無意識下 / 意識下でつくられていくものである & それはチームによって大きく異なりうるものである一方で、こちらはプロセスのいち機能として、だれかがやることをある種指定しているものです。（なので、名称は「ファンクション」）

ロールの記述と戸惑いやすいのはそうだと思うので、ファンクションの説明をきちんとしてあげたほうがいいのかもしれません。

@kikuchiharuma ちなみに、プロダクトチームとの会話は上記の文脈でいうと「ロール」と「ファンクション」とどっちの意味合いが強いですかね？

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto プロダクトチームとの対話の中では、ロール-ファンクションの区別はあまり意識されないままだったように思います。ファンクションのことを忘れてました。

これは僕の解釈含む話ですが、PJSに「ロール」があるという期待自体がなく、どうして(いっとき誰かが受け持つファンクションのようなものを)ロールと呼ぶのだろう？という疑問として話されていたように思います。

https://github.com/copilot-jp/project-sprint/blob/dev-v0.9.0/ja/essentials/index.md#%E3%83%AD%E3%83%BC%E3%83%AB
この記述あたりが、帽子やファンクションを想起させる気がしますね。それでそういう話になったのかなと。

個人的にも、積極的に担ったり、複数人でシェアするようなものはロールと呼ぶのは違和感あります。
またPJSにファンクションとは別に、属人的な「ロール然としたもの」が必要かというと、個人的にはいらないかな思います。理想のチームとして定義しているものの中でそれが必要と思えない、という感じで。

**Comment by kikuchiharuma** [comment]
@motoi この話の進め方決めた方が良さそう、という意味で定金さんアサインに変えます

**Comment by Satoshi-Matsumoto** [comment]
ロールの名称 / 役割の話という意味で
https://github.com/copilot-jp/project-sprint/issues/33
に集約させましょう。

@motoi 
こちらは、クローズをお願いします。

**Comment by motoi** [comment]
了解。クローズで。
