### ISSUE TITLE
英語の問い合わせ先の調整

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#304]
README.mdファイル冒頭

This is the repository for the Project Sprint site hosted by GitHub Pages and build with Minima Template. Project Sprint is the methodology for a diverse and cross-functional teams to drive projects that produce complex outputs in highly uncertain environments and situations. Discussion in this repository should be done in Japanese until English version of documents are made. However, if you have any questions, opinions or anything else though you cannot use Japanese, please contact @Satoshi-Matsumoto in English.

これsatomatuになってるけどkokoroさんの方が良いのでは？

**Comment by KokoroKagawa** [comment]
@motoi ありがとうございます！対応しました。
