### ISSUE TITLE
チュートリアル：いきなりマイルストーンをつくるのが重いという人がいるので、まずはプロジェクトをみんなのものにする、プリチームからチームになるミーティングから始めても良いよ、みたいな選択肢が欲しい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#305]
![image](https://user-images.githubusercontent.com/680855/144588847-69fe81d1-2289-499b-91d0-ae49d06009cf.png)
だいたいこういう流れを通るんだけど、まずマイルストーン作りましょう、となるのはある程度チームになってから。
まだよくわからないなーという時はとりあえずミーティングを繰り返して、プリチームからチームになり、やっとマイルストーンを引こうとなる。
チュートリアルとして「マイルストーンを引こう！」は良いかもなんだけど、とはいえまだまだ決まってない人はまずチームになるミーティングや、マイルストーンを引くミーティングから始めよう、みたいな気軽さが欲しい。

以前に読んだ人からフィードバックを元に書いてみてます。

**Comment by motoi** [comment]
3.0.0で対応する

**Comment by KokoroKagawa** [comment]
対応しました
