### ISSUE TITLE
用語集をつくって全体のメンテナンスをしやすくしたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#306]
用語集があると読者がリファレンスしやすくのなるというメリットはもちろん、コントリビューターとしてもやりやすくなる。
用語を並べて定義がブラッシュアップし、そのブラッシュアップした内容に合わせて全体を調整するような方法も可能になると思う。

**Comment by motoi** [comment]
おいおいやりましょう

**Comment by KokoroKagawa** [comment]
まずは入れたい言葉をリストアップ
https://docs.google.com/document/d/1T7RqBDbLLZ2whlFk89OlfsXgmMrEaJlV0OEuiV9ciIs/edit

**Comment by KokoroKagawa** [comment]
v4より実装。以後随時ブラッシュアップ。
