### ISSUE TITLE
ミーティングの定義をバージョンアップしたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#307]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section2-3.md

> プロジェクトスプリントでは「ミーティング」を、「チームメンバー全員が空間や時間を共有し、素早く効率的な認識合わせと、全員が納得した意思決定をする場」として位置づけています。

の部分をちょっとアップデートしたい。
相対主義的な考え方で主体と客体が依存する関係では、環境を一時的に固定できる場所として会議が重要だと思っています。

![image](https://user-images.githubusercontent.com/680855/144590832-ac5afdf9-c485-4ee3-9b4b-842c0ec43b03.png)

リアルタイムに集まるミーティングがプロジェクトの意思決定において最適な選択
リアルタイムに集まり、環境を一時的に固定することで、認識が合い、大きな意思決定に対して納得することが可能になる。
非同期のメールやチャットのコミュニケーションでは環境の同期が取りずらいため意思決定しづらい。

この辺りのニュアンスをミーティングの定義に追加したい。

**Comment by motoi** [comment]
3.0.0で対応する
会話が大事も入れる。

**Comment by KokoroKagawa** [comment]
0319de0
対応しました。
