### ISSUE TITLE
ミーティングと会議の表記について最終確認する

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#308]
どちらかに統一するのか、一般的なミーティングを表す場合は会議、PJSらしいミーティングは、ミーティング、とするなどルールを確認して最終調整する。

**Comment by motoi** [comment]
3.0.0で対応する

**Comment by KokoroKagawa** [comment]
対応しました。
d0a95b0
一般的なミーティングを表す場合は会議、PJSらしいミーティングはミーティングとしました。
