### ISSUE TITLE
ミーティングを意味のある箱とするか、意味のないただの場とするかを書きたい。

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#309]
> とはいえ、ミーティングにおけるアジェンダは常に一定とは限りませんから、最初にミーティングを設計する際には、あらかじめチームメンバー全員が集まることのできるミーティングを設定したほうがいい場合も多いでしょう。

https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section2-3.md

バックキャストで設計できる場合は1つ1つのミーティング単体が目的や完了の定義を持っても良いが、その状態になると他のアジェンダが上げづらくなる。みんなで進めるミーティングになればなるほど、ミーティング単体で目的は持たず、ただの時間と場所と参加者が決まった箱になる。その辺りを表現したい。

![image](https://user-images.githubusercontent.com/680855/144592860-59cee4df-65d2-4541-a64d-75852c376323.png)

**Comment by motoi** [comment]
3.0.0で対応する
連続した箱になるのがみんなで進めているPJSぽいよ。

**Comment by KokoroKagawa** [comment]
対応しました。
