### ISSUE TITLE
ロールについてのセクションにロールの説明を集約した方が良い？

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#31]
チーミングドメインの中の話としてロールが登場している
https://github.com/copilot-jp/project-sprint/blob/master/ja/advance/index.md#%E8%AD%B0%E8%AB%96%E3%82%92%E4%BF%83%E3%81%99%E4%BA%BA

プログレスにもプロセスにも関係するロールの説明があるが、
チーミング > ロール > 各ロールの説明
という構成にするために集約した方が良いのではと思いました

プロジェクトスプリントにはどんな予約ロールがあるんだろ、と思ったときにまとめて読める箇所があり(今の構成であればアドバンスのチーミングの章の中)、その文書を必要なところから参照する構造

**Comment by Satoshi-Matsumoto** [comment]
これすみません、完全にアップデート漏れなのですが、エッセンシャルズのなかでもともと予約ロールとしていたプログレスマネジメント / チームマネジメント / プロセスアドミン / スプリントマスターをPlug-inに移している時点で、予約ロールの概念がなくなっているんですよね。

https://github.com/copilot-jp/project-sprint/commit/177ae22b8c7711ed93b3d24250cea92bf79548bf

なので、
- ロールの説明はチーミングの章に集約
- 各ドメインに書かれている予約ロールの説明は削除
の対応になるかと思います。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma @motoi 
修正しました。特に問題なければ、 @motoi クローズをお願いします。
https://github.com/copilot-jp/project-sprint/commit/f43b157f94ff0435f58997ca546432a520bdf85d

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto ロールの集約としていい感じと思います！ファンクションとの区別の話が気になってますが、それはこのあたり https://github.com/copilot-jp/project-sprint/issues/33 https://github.com/copilot-jp/project-sprint/issues/30 が結論出てからですね。

**Comment by motoi** [comment]
おけっす。クローズで！
