### ISSUE TITLE
コーディネーターを残すか消すか

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#310]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section3-1.md

> コーディネーター：ミーティング環境をつくるロール。適切なミーティングルームの確保（オンラインの場合はミーティング環境の設定）、ホワイトボードやモニターの手配をする。

必須なのはファシリテーターとレコーダー。

**Comment by motoi** [comment]
とりあえずもう少し考える

**Comment by KokoroKagawa** [comment]
現状あってよさそうなので閉じる。
