### ISSUE TITLE
ファシリテーターを、ファシリテーターとモデレーターに分解するか？

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#311]
ファシリテーター：アジェンダの取りまとめ(アジェンダの合意から、その後のアジェンダ進行とタイムキープ、ミーティング終了時の次回のアジェンダの決定)および議論の促進と成果の質の向上(アジェンダの改善、その後の議論形成のサポート)をするロール。前者をモデレーター、後者をアクセラレーターとして区別して別々のロールとして割り当てることもある。

https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section3-1.md

この辺の資料を参考に分割するかを検討したい。
分割することでみんなでミーティングを進める時に、みんながファシリテーションをするんだよ！という意識を植え付けたい。
[3-1. ファシリテーションの定義とProjectSprint におけるモデレーション.pdf](https://github.com/copilot-jp/project-sprint/files/7649106/3-1.ProjectSprint.pdf)

**Comment by motoi** [comment]
3.0.0で対応する

**Comment by KokoroKagawa** [comment]
対応しました。
