### ISSUE TITLE
アジェンダの項目の調整

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#312]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section3-1.md

アジェンダアイテム名は「何を」とか書いたほうが良いかも。ホゲホゲについて、とかタイトルとしては醜悪の極みであることが伝えたい。
時間は議論の完了までに必要な時間みたいな補足があっても良いか。

> アジェンダアイテムの提出
> 毎回のミーティングが始まる前には、あらかじめ各チームメンバーがアジェンダアイテムを提出します。アジェンダアイテムには、少なくとも次のような内容が含まれている必要があります。
> 
> - アジェンダアイテム名
> - 進行方法（具体的な議論の進行イメージ）
> - 目的や背景（そのアジェンダアイテムを議論したい理由）
> - 誰から誰への議論か（誰がそのアジェンダアイテムのオーナーであり、誰と議論したいのか）
> - 時間

**Comment by motoi** [comment]
3.0.0で対応する

**Comment by KokoroKagawa** [comment]
対応しました。
