### ISSUE TITLE
なんか文字化けしてる？

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#313]
![image](https://user-images.githubusercontent.com/680855/144598180-8ae1a9df-68c6-4286-b449-d91699af9919.png)

https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section3-2.md

**Comment by motoi** [comment]
3.0.0で対応する

**Comment by KokoroKagawa** [comment]
対応しました。
fa89107
