### ISSUE TITLE
コミュニティとは何を指すのか？を明確にする

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#314]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section5-1.md

現状はSGMsのサイトなどではslackの方をユーザーコミュニティと呼んでいる
http://slack.projectsprint.org/

このページではSlackコミュニティと呼んでいる。
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/contributing.md

なので、このコントリビューターの集いはコミュニティとは呼ばず、別の名前の方が良いんじゃないか。
そしてリンク先は以下の方が良いのではないか
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/contributing.md

もはやこのページの「さらに学びたい人へ」がいらないのかもしれない。。。
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/index.md

**Comment by KokoroKagawa** [comment]
- Section5-1はページごと削除し、一部contributingに移植
- Tutorialの「さらに学びたい人へ」を「さらに興味のある方へ」としてcontributingへのリンクに差し替え
- 「Slackコミュニティ」を「ユーザーコミュニティ」に表記変更
