### ISSUE TITLE
タスクの効果についての記述が不足している気がする。

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#315]
前のエッセンシャルズで書いてもらってた以下のような、タスクはいろんな意味や効果があるよ、という記述がどこにもない気がする。
重要だと思うのでチップスではないどこかに記述したい。

－
タスクの意義

プロジェクトにおいて、タスクを実行し完了させることは非常に重要な意味を持ちます。プログレス・アクティビティやチーミング・アクティビティの結果から、プロセス・アクティビティへのインプットとしてのアジェンダが生まれ、プロセス・アクティビティのアウトプットとしてタスクが生まれます。そのタスクが、更なるプログレス・アクティビティやチーミング・アクティビティのソースとなっていくのです。プロジェクトの進捗は、メンバーが納得したタスクが円滑に消化されているかどうかで測ることができます。

プログレスにおいては、ゴール達成に向けた作業を小さなタスクに分解して共有し、メンバー間で漸進的に進めることで、プロジェクトを効率的に推進する効果が得られます。タスクの状況が共有されることには、メンバー間の情報共有を推進し、相互理解が深まり信頼関係の構築が進むという、チーミングにおける効果もあります。プロセスにおいては、タスクが絶えず実行され続けることで問題点や違和感を発見しやすくなり、適切なアジェンダアイテムとして提案されるようになります。効果的な議論や効率のよい意思決定が可能になり、ミーティングでの課題解決の質が上がるのです。

**Comment by KokoroKagawa** [comment]
重複記載ではという声があったので、101の推進プロセスに関する記載に統合したのですが薄かったですかね。もうちょい濃くしてみます。

> 3. **推進プロセス**：個人の活動、チームとしての活動双方の実行と最適化を促進するための仕組みです。全メンバーが同期する定期的・反復的な**ミーティング**で、タスクの実行結果や問題点、テンションを**アジェンダ**として持ち寄り、情報共有や問題発見・解決、意思決定などを行えるようにします。ミーティングのアウトプットとして次のタスクが生まれ、次のミーティングでのアジェンダの材料となっていきます。チームはこうして継続的な改善を行いながら、プロジェクトゴールの達成に近づいていきます。

**Comment by KokoroKagawa** [comment]
@motoi いかがでしょうか

**Comment by motoi** [comment]
@KokoroKagawa 
良いとおもいました！

**Comment by KokoroKagawa** [comment]
確認ありがとうございました！閉じます。
