### ISSUE TITLE
プロジェクトゴールとマイルストーンの見直しは定期的に行う、みんなが見えるところで更新する、の二点を追加で推奨したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#319]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section4-2.md

見直しの手順の部分に以下の要素を追加したい
- とにかく定期的に見直して違和感がないかを確認すること
- みんなの前（特に会議で全員が集まっているところ）で調整し続けてみんなものにしていくこと

**Comment by KokoroKagawa** [comment]
対応しました。
