### ISSUE TITLE
実践の初歩についてまとめが必要？

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#32]
エッセンシャル、ついでアドバンスをプロダクトチームに説明した時に、エッセンシャルズの概念的な内容、アドバンスの実践的な内容、それぞれわかるが、いきなりアドバンスの内容までやらなくていいと思うと、じゃあその手前で最低限やらなくてはいけない「実践」はなんだろう？
という話になりました。
アドバンスに対してベーシックのようなものがあるのかも。と。

例えば、SGMsのUIではアジェンダの項目としてWHATとWHENを必須のように扱っている(小さなスペースで省略される場合など)
https://github.com/copilot-jp/project-sprint/blob/master/ja/advance/index.md#%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AF%E3%82%B9%E3%83%88%E3%81%AE%E7%90%86%E8%A7%A3
WHATとWHENだけ書く、ということがありえるのだけど、それはPJSの最低限必要な実践を満たしているのか？と思ってエッセンシャルズを見ても答えがない。アドバンスにはマックスの状態(WHY WHO WHOM HOW...)が書いてある。

**Comment by kikuchiharuma** [comment]
個人的には、アドバンスを解体して、共通事項(抽象的な話の続きが書かれているので)をエッセンシャルズ ディテイルズに引越し。エッセンシャルズ+ディテイルズで概念の説明が全部読めるようにする。
ドメインごとの章は、それぞれアドバンス プログレス、アドバンス プロセス、アドバンス チーミングの3つの文書に独立させ、お勧めする最大範囲の実践の記述としてアドバンスシリーズにまとめる。
その上、ベーシックを新たに作って、アドバンスの内容のうち、これだけは絶対やって、という項目だけを説明する。

これができると
理論編: エッセンシャルズ/エッセンシャルズ・ディテイルズ
実践編: ベーシック/アドバンス プログレス/アドバンス プロセス/アドバンス チーミング
の6つの文書構成になり、参照しやすくなるんじゃないかと思いました。

**Comment by Satoshi-Matsumoto** [comment]
気持ちはすごくわかるのですが・・・そもそも、エッセンシャルズ / アドバンスほか、CODEは定義書 = 理論の説明であって、実践については基本的にマニュアルに委ねています。

理論面の話だけでいうと、エッセンシャルズでの記述としては
> 個々人のアクティビティの結果（アウトプットとテンション）が、チームメンバーと共有されるために明文化されたもの
ということで、これでThat's allなんですよね。そのために、解像度を上げられるのであれば、アドバンスに書いている内容に沿って書いてください、というだけの話で。なので、原理主義的に言うと、WHATとWHENについては、必須じゃなくてもいいです。

というか、ある意味、SGMsの仕様決定自体もある意味実践の一部であって、CODEと矛盾はしないほうがいいものの、位相を合わせる類のものではない気がしてきました。

エッセンシャルズ / アドバンスはあくまで方法論の定義であって、これを受けてツールがどうするべきか、というのは、メソッドとして考えるべきことではあるかもしれませんが、CODE内に仕様上明らかにすることをメインにして修正を加える、というのは強く反対です。

**Comment by Satoshi-Matsumoto** [comment]
**これまで**
エッセンシャルズ -> 外せない事項
アドバンス -> 推奨事項

**実態**
エッセンシャルズ -> 抽象的な概念
アドバンス -> 具体的・実践的な内容

修正の方向性
- ドキュメントの役割を変える
- 新しいドキュメントの種類をつくる (ディレクトリを増やす / 位置を変えるなど）

方向性が決まったあとで、記述内容の修正。

**Comment by kikuchiharuma** [comment]
この話、もしかして

- 実践
- 最適化

この2つの区別がCODE全般の項目に対して意識化されないといけない、という問題なのかも知れないですね。CODE自体は実践にも、最適化にも言及する、ということがずれていなければ。

抽象的な記述、と言っているのは、両方に関わる基本的な道具立ての話なのかも。

**Comment by Satoshi-Matsumoto** [comment]
Essentials : 
〇本質的な内容
〇いかなる時にもProject Sprintを定義づける原理原則
〇ルール、骨組み
〇真理
× 要約、まとめ
× 概論

Advance
〇 より具体的な内容
〇 何をしたらいいかわからないときに推奨されるのフォーマルなやりかた

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
上記の整理もとに読んでみて、感想ください！

**Comment by kikuchiharuma** [comment]
あらためてEssentialsを「原理」、Advanceを「やりかた」と思いながら読んでみました。

そうすると、確かに現状原理とやり方が書かれている、という差があるようにも思いましたが、「それぞれ中途半端だし、元々そういう話ではなかった気がするぞ…？」という気持ちになりました。
頭の整理のために対義語を書き出してみたのですが、

![PJSのメソッドのジャム - 13](https://user-images.githubusercontent.com/607971/82665842-90a11480-9c6f-11ea-86a5-b6de052e5a09.png)

原理とやり方を「理論」と「実践」と言い換えると、

CODEは理論編、Manualは実践編
CODE+Manual=Project Sprintのドキュメント全体

ということで、原理とやり方、という内容は元々CODEとManualの区別を対応させる構想だったように思いました。
一方、エッセンス、アドバンス、という名前になったのも構想の一部で、

Essentialsは基本編、Advanceは応用編
Essentials+Advance=CODEの必須部分(プラグインはオプション)

という整理だったように思います。
Essentialsがどんな時にも有効な、意識されて欲しい内容に絞ってあるのはこういう由来で、アジェンダのタイプなどが外れてAdvanceに書かれています。アジェンダのタイプはAdvanceに書かれていますが理論といって差し支えないと思います。実戦と最適化についての話も理論だと思います。

まとめると、元々の構想に忠実にするなら、

- CODE(EssentialsとAdvanceとPlug-in)とManual(チュートリアル等)を理論的な内容と実践的な内容で書き分ける
- EssentialsとAdvanceを基本的な内容と応用的な内容で書き分ける

ということになるのかなと思いました。

今のAdvanceが実践に寄っているので実践編のように扱っていく、という方向は、あまり現実的でないと思います。書き方が実践寄りになってしまっているものの、ファンクションや振り返りなどがやり方を想像しながら議論した結果そうなってしまっただけで、伝えたい内容は理論的なもので、本来抽象的なレベルで揃えられるように思います。(ファンクションのメタレベルでの作用、チームの状態を明らかにする機会を作るべき、長期的な効果を期待する作用と短期的な効果を期待する作用がある、など)

**Comment by kikuchiharuma** [comment]
@motoi 定金さんどう思いますかー

**Comment by kikuchiharuma** [comment]
あー、このIssueのタイトルが悪かったかも知れません。
理論編の中でも、基本(Essentials)と応用(Advance)の区別をもっと明確にできるのでは？
ということだったのかも。

**Comment by motoi** [comment]
> 理論編の中でも、基本(Essentials)と応用(Advance)の区別をもっと明確にできるのでは？

これだとおもいました。
で、基本と応用の言葉の定義をすればよいのかなとおもいました。

基本：
これは必須もふくみますよね。
必須のニュアンスを入れるかは確定したい（チェックリストつくってるからかもですが）

応用：
初心者⇔熟達者
初歩⇔極意
と菊地さんは書かれていますが、このあたりが議論が必要そうだなとおもいました。

だれが、どんな目的で、参照するドキュメントなのかを想定してもよいんでないかなとおもいました。
私の感覚では、
・基本をまず抑えてもらい、それを超えた人が、ここまでやってもらえるとよりメロドロジーの効果がでる場合がある。
・運用はめんどくさく場合が多いので、そのあたりは運用コストと効果のバランスでケースバイケースなんだけど、おすすめします。
みたいな感じです。

だれが、目的、で書いてみると

 だれが
基本を理解した人（実践しているかは問わない）

どんな目的で
・メソドロジーがより効果を発揮する方法を取得する。ただしチームによりケースバイケースなので実践すると必ず運用コストよりも効果が高いとは言えないが。
・メソドロジーの効果やもたらす状況、理想の形をより理解する
・より基本、エッセンシャルの理解を深める

こんな感じです！

**Comment by motoi** [comment]
@Satoshi-Matsumoto に一回まわしてみる。

**Comment by Satoshi-Matsumoto** [comment]
現在の整理として、下記。

![PJS-ドキュメント体系の整理](https://user-images.githubusercontent.com/61894329/83348551-bf527580-a368-11ea-8829-bdeba0dd9b0f.png)

まずcodeから着手します。
（マニュアルは、そちらを作成のときに改めて話したほうが良いと思うので）

具体的には、マニュアルに記載の内容のうち、特にAdvanceの記載内容を、いま包括している3つの領域（基本 - 実践、応用 - 理論、応用 - 実践）、に分けたらどのようになるか実際にブランチ切って整理してみます。

@motoi @kikuchiharuma

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma @motoi 

ディテクトリを分けてみました。
構造としては

```
- ja
 - theory
  - essentials
  - details
 - practice
  - basic
  - advance
  - plug-in

```
というかたち。
マニュアルについては特に手を付けていません。（=CODEのみ作業）
また、理論 × 拡張に当たる部分はありません。なぜなら、拡張部分 = nice to haveの部分は、実践で必要だからこそnice to haveとして用意するものであって、nice to haveな理論というものが想定できないからです。
結局、最初の最初に @kikuchiharuma さんが言っていたことに落ち着いた気がします。

切ったブランチと修正内容は下記でみれます。
https://github.com/copilot-jp/project-sprint/blob/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89/ja/index.md

ただ個別の内容を確認するのも大変だと思うので、一時的に目次をまとめました
https://github.com/copilot-jp/project-sprint/blob/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89/ja/index.md
こちらを見てもらって、中身のイメージがつかないところは各ファイルを見てください。

分かることとしては、3つのドメインで深ぼれているところに濃淡があったり、
情報が足りないところ、バランスが悪いところがある、ということですね。
これ自体は悪いことというよりは、これからそこを検討していく必要がある、ということだと思います。

いろいろ書きましたが今回レビューしてもらいたい内容としては、
- 各ファイルの記載内容と記載されるべき内容が分かりやすくなっているか？
- 実際に書いている内容をみて、こういうことが書かれるな、とイメージした内容とあっているか？または、読んでみて「ああこういうことが書かれるべきものなのか」と納得できるものであったか？

です。

まずは @kikuchiharuma さん、ご確認ください。

**Comment by kikuchiharuma** [comment]
整理、ネーミングともに良いと思いました！
気になったのはbasicが新しい「必須」内容になるとすると、ちょっと多いな(一部advanceで良さそう)と思ったくらいですが、それは今後の議論ですね。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん

ありがとうございます！

> 気になったのはbasicが新しい「必須」内容になるとすると、ちょっと多いな(一部advanceで良さそう)と思ったくらいですが、それは今後の議論ですね。

そうですね。一度今の形で読みやすいように整形してからどんどん修正加えていくのかなーと思います。

というわけで次は　@motoi さん、どうですか？
チェックしてもらいたいポイントは

https://github.com/copilot-jp/project-sprint/issues/32#issuecomment-640328324
です。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
目次をみておもったことを。
details という名称が essentials の details なのかなーという気分に読めてしまい、人によっては essentials の項目が多いのかなーと感じてしまいました。
英語的に違和感なければこのままでよいですが純日本人の私はそう感じてしまいました。

あと修正内容をみようとおもったけど見方がわからない。。。URL同じ？
ここをみればよいのかしら。
https://github.com/copilot-jp/project-sprint/find/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
> details という名称が essentials の details なのかなーという気分に読めてしまい、人によっては essentials の項目が多いのかなーと感じてしまいました。
ここちょっとよくわからないので、補足お願いできますか？
essentialsのdetailsなのはその通りだと思うのと、目次上はessentialsのほうが少ないと思っているのですが・・・・

修正内容ですが、
https://github.com/copilot-jp/project-sprint/tree/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89/ja

の、theory配下、practice配下の個別のファイルをご確認ください。

https://github.com/copilot-jp/project-sprint/commits/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89
で dfb091a 以降のコミット追ってもらってもいいのですが大きく配置換えしているので実際のファイル見てもらったほうが早いと思います。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
エッセンシャルズのドキュメントをどういう位置づけににするかによりますが、これをやってないとPJSではないというものだとすると、
essentials も （essentials）details もできてないとPJSをできてない、となってしまいそうな感じを受けたという意味ですー。

> 修正内容ですが、
> https://github.com/copilot-jp/project-sprint/tree/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89/ja
> の、theory配下、practice配下の個別のファイルをご確認ください。
これでよければ確認しました！とりあえずいまは違和感ないですー。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
あ、なるほどですね。

"これをやってないとPJSではないというもの"に相当するのは今の整理上 essentialsとbasicになります。

で、detailsは、
Project Sprint の Theoryのdetails であって、 
Project Sprint の Theoryのessentialsのdetailsではないです。

何が言いたいかというと、（これまでessentials detailsっていう表現をしていることがあったので勘違いしちゃうかもしれませんが）いま、detailsにessentialsの意味合いは含まれません。

ということで、改めて名称、どうでしょう？
もし名称だけが問題であれば、代替案もらえると助かります。
特になければ、いったんこの名称でいくという選択肢もあります。

@kikuchiharuma いちおうこちら経緯はご確認ください。

**Comment by kikuchiharuma** [comment]
変更後の図がないなと思ったので描いてみました。

![Paper SuperGoodMeetings 86](https://user-images.githubusercontent.com/607971/84238080-6daea580-ab35-11ea-8631-2f4d9f60a16d.png)

@Satoshi-Matsumoto こんな感じで認識合ってるでしょうか？

**Comment by kikuchiharuma** [comment]
「これをやってないとPJSではない」に対応するのは、CODEの「基本」を見ればわかる、ということなのかと。

**Comment by kikuchiharuma** [comment]
もしこの整理が合っているとすると、CODEのセオリーの応用と拡張をまとめた文書として、Detailsという名称がどれくらいしっくりくるか、で考えられるのかも知れませんね。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
図のupdateありがとうございます。一か所だけ、detailsは理論 ×応用にあたる部分だけであり、理論×拡張の部分はN/Aです。下記はその意図です。

> 理論 × 拡張に当たる部分はありません。なぜなら、拡張部分 = nice to haveの部分は、実践で必要だからこそnice to haveとして用意するものであって、nice to haveな理論というものが想定できないからです。

下記は私もそうおもっております。
>「これをやってないとPJSではない」に対応するのは、CODEの「基本」を見ればわかる、ということなのかと。

**Comment by kikuchiharuma** [comment]
![Paper SuperGoodMeetings 87](https://user-images.githubusercontent.com/607971/84259110-eec86580-ab52-11ea-8d31-94d9d7363f4f.png)

こういうことですね？

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
その通りです！！！

**Comment by kikuchiharuma** [comment]
![Paper SuperGoodMeetings 88](https://user-images.githubusercontent.com/607971/84260635-5384bf80-ab55-11ea-9ca6-ec1b6799571a.png)

こういうのも思い思い浮かびました。
マニュアルと同じく、理論と実践の区別ない感じ。

**Comment by Satoshi-Matsumoto** [comment]
```
- Theory
 - Basic
 - Advance
-Practice
 - Basic
 - Advance

- Plug-in (Theory的な内容もPractice的な内容もどちらも入る）

``` 
Theory と PracticeのBasicを合わせて"Essentials"と呼び、この二つが"必須"の意味合いをもつ。

**Comment by Satoshi-Matsumoto** [comment]
新しい体系に合わせて、ディレクトリ変更しました。

https://github.com/copilot-jp/project-sprint/commits/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89

で沿ってみてもらうのが良いかと思います。
他からのリンクも調整しています。

まず @kikuchiharuma さん、確認ください。その後、 @motoi さん、お願いします。
ポイントは、上記まででの議論がドキュメントの体系(ディレクトリ構造)に反映され、ドキュメントの内容と齟齬がないか。です。

**Comment by kikuchiharuma** [comment]
いいと思いました！
ベーシックを合わせてエッセンシャルズと呼ぶ、という部分含めて。

**Comment by motoi** [comment]
@Satoshi-Matsumoto GH素人におしえてください。。。
リンク先のこの画面から何を沿ってみればよいんじゃろうか。。。。
ディレクトリ変更ということだけどディレクトリだけ見ればよいってこと？
ディレクトリってこの画面からどう見るの。。。。ほんとすません。
![image](https://user-images.githubusercontent.com/680855/84645912-4a706580-af3c-11ea-85ac-c68df39f345d.png)

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
すみませんちょっと私が不親切でした。
commits on Jun 14のところが今回の修正分になるので確認ください。
具体的には、↓を上から順に見てもらえばよいです。
https://github.com/copilot-jp/project-sprint/commit/1e2eea67d0c64e6207a1f46379c46705b2451b99
https://github.com/copilot-jp/project-sprint/commit/e82d3c879445a8721dfae0e44400bc4e836f6318
https://github.com/copilot-jp/project-sprint/commit/c48af3717f2c011f9222b31d0d9b55eab58fd2d5
https://github.com/copilot-jp/project-sprint/commit/d7e066b7625e4f449d6edb5fbc3f8c594ac037ae
https://github.com/copilot-jp/project-sprint/commit/fa1189e4cccac2c386cdb0ee75d22d6f15dfd905
https://github.com/copilot-jp/project-sprint/commit/b4a269e744361022aa5c21aa2034094aead91902
https://github.com/copilot-jp/project-sprint/commit/51cbf6805b239af5e319aa66b79c1d0abb355b71

これらの変更を経て、最終の修正結果だけでよければ
https://github.com/copilot-jp/project-sprint/tree/code-v0.9.0-CODE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E4%BD%93%E7%B3%BB%E5%86%8D%E6%A7%8B%E7%AF%89/ja
のディレクトリ構造と各ファイルを確認してもらえばよいです。

**Comment by motoi** [comment]
確認しました！整理された感！
