### ISSUE TITLE
ロールが人につく感じを払拭したい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#33]
アジャイルの役割を「帽子」、ホラクラシーでいうと「椅子」で表現しているのがよい。
erとかマネージャーとか、人につく感じが良くない。なんかそこ良い表現にできないか。

**Comment by motoi** [comment]
定金案としては陸上競技ってこともあるので、腕章、アームバンドとか？

**Comment by kikuchiharuma** [comment]
@motoi 何が課題なのか、どうなれば解決なのか共有が欲しいです

**Comment by kikuchiharuma** [comment]
ここでファンクションが属人的でないものの呼び名、として提案されていますが
https://github.com/copilot-jp/project-sprint/issues/30#issuecomment-627338085
もしその整理で行くとすると、このIssueはファンクションの呼び方の検討、ということになると思います。

そうではなく、ロールは人と対応してしまうとまずい(=ファンクションのように扱うべきな)のではないか？ということだとすると、ファンクション-ロールの区別自体を再検討、という問題になるのかなと。

他にも可能性があるかも知れませんが、とりあえず曖昧さを回避したいというお話でした。

**Comment by kikuchiharuma** [comment]
ファンクションの名前が、ファシリテーター、コーディネイターなど「〜する人」という表現なのが、ロールなのか帽子なのかわかりづらい、という表現の問題もありそうですね。

中身としてPJSとしてどっちの方針なのか x それを飲み込みやすくするにはどういう表現をするべきなのか
掛け算の問題になっていそうなので因数分解が必要かと。

**Comment by Satoshi-Matsumoto** [comment]
- "ロール" の属人性を排除した名称として、 "ファンクション" にする
- いまのミーティングファンクションの中にあるそれぞれは、Plug-inに移行
- スプリントマスターについては、essentialsには入らないが、Plug-inかadvanceにするか、は要議論

**Comment by motoi** [comment]
ファンクションって言葉を積極的につかってみていると。

ミーティングのファンクション決めたいよね
とか
このトラックのファンクション決めたいよね

とか言ってみた時に
トラックの機能をいっているのか、トラックに参加する人のファンクションのことを言っているのがよくわからなくなる現象が発生しました（笑）
うーん、ちょっと一ひねりいる気がしました。
なにかやっぱり人についてる感がかもしだされないとつらいのかもしれない！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
進め方まで提示もらってもよいですか？
- だれかの意見求む
- いったんサトマツが書いてしまう
など

**Comment by motoi** [comment]
では、@Satoshi-Matsumoto さん、まず私のコメントを読んで「ファンクション」でいけそうか？で意見ください。そのあと @kikuchiharuma さんに意見求めます！

**Comment by Satoshi-Matsumoto** [comment]
経緯と、これを受けての見解を述べます。

もともとは、スプリントマスターやプログレスマネジメントなどある程度属人性が排除できないものを"ロール"、ミーティングの中のファシリテーターなど属人性が完全に排除できる（しやすい）ものを"ファンクション"で区別していました。

その後、基本的には常に属人性は排除すべきだよねという結論と思いますので、この時点でロールとファンクションの区別はなく、どちらかに統一 or まったく別の一語で統一するべきだと思います。（いまのcodeのバージョン = v0.8.4だと統一されていませんが修正対象）

で、名前ですが、人に対して使用する、PJS上の固有名詞としての"ファンクション"と、それ以外の意味を持つ一般名称としての"ファンクション"が紛らわしいのであれば、これは使うのはやめましょう。（「実践」の単語がややこしいのと同じ問題かと思います）

そのうえでですが、私個人の意見としては、"ロール"でよいのではないかと思います。
理由は下記。

- 属人性を排除したいのはわかりますが結局人に対して使う
- 帽子とか椅子は言っていることはわかりますがたぶん浸透しない
- むしろほかの表現のほうが、一対一関係が想起しづらい（= 同じ役割の帽子が何個もあって、みんながその帽子をかぶっていて…とか考えづらいのでは？）
- イメージがしにくいのであれば使いやすい用語にしてその意味を丁寧に説明したほうがいい

ネーミング系の問題なので、これだ！という代替案が出てくる or これにしてくれ！という誰かの強い意志がない限りは、ロールで推し進めてしまいます。

と、いうわけで、次は @kikuchiharuma さんにコメントもとめたく。

**Comment by kikuchiharuma** [comment]
経緯をさかのぼってみたのですが、「人につく感じ」をブレークダウンしないと課題を見落とすのではないか、という気がしました。

ロールとファンクションの用語の使われ方の違いは、PJS内の経緯を含めて、以下のように感じます。

ロール: 私はそのロールを担っているから○○をやる (やる理由/責任の所在の明確化)
ファンクション: 私が誰であれ/チームの誰かがそのファンクションをやる (やる対象の明確化)

誰がやってもいいものをファンクションと呼ぶ、という区別が出てきたときに、この差が暗黙に意識されていたのではないかと思います。
そう考えると、「人につく感じ」というのは、「ロール」を名付けてもその責任があると言っているだけで、その中身がようわからんくなってしまわね？それはメソッドという問題意識なのではないかという気がしました。

あれ、ここまで書いて
https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-629920712
これってお返事もらえてないかも？この課題の明確化からやり直してるかも？という気になってきました。
@motoi どうなんでしたっけ

**Comment by kikuchiharuma** [comment]
それは置いといて、もし上のような課題だとしてもうすし書きますと、

チーミングに関して「属人性は排除すべき」という方針が何を意味するかというと、PJSが何を明確化しようとしているかに合致するように、チームメンバーが担う仕事を整理するべし、ということかと思います。

そしてそれは、「チームがどういう責任分担をするべきか」を明確化したいのではなく、「プロセスやプログレスやチーミングがどういう活動/貢献によって支えられるか」を明確にしたいのではないか、と思いました。つまり何をすればプロセスが進むか、を言いたいのであって、こういう責任者を立ててくださいと言いたいわけではない。

つまり、ロールと書いてしまうと「PJSのドメインを分割してその中を暗黙的に統治する人」ということになってしまい、それはメソッドが表現したい、透明性があり、相互協力的で自律的な人の関わり合いと逆の事態を示唆してしまうのではないか。
そうではなく、書くべきは、誰が担っても良いがチームの中で誰かが引き受けて実行すべき仕事について、あくまでも「やる対象」として明確化すること。

「帽子」はそういう文脈を持った用語ということでヒントとしてこの議論に持ち込まれた、ということなのかなと思いました。

**Comment by kikuchiharuma** [comment]
どうしよ。とりあえず @motoi さんがどういう課題と理解しているのか知りたいです。どこかに書いてたら教えてください。

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/84559703-f9177900-ad77-11ea-8520-c9670442cb6d.jpeg)

**Comment by motoi** [comment]
役割の中に機能を置く構造として考える方向だったけど、結局、情報を整理するようになってみると、役割の中に役割が存在することになる構造と変わらないかなと。
上の絵は機能はなにをさすのかと書いてみても結局ロールの入れ子構造にしかならなかった。

機能とか行動とかの言葉を作ってみても結局は役割と定義が変わらないなと。

ということで、プロジェクトスプリントにおける必要な役割の呼称は「ロール」でよいのではないかという結論にいたった。（もういっそロール以外にしたかったけど良い言葉が探しても見当たらないので）

ロールという言葉がどうなんだ論があるが、ロールとファンクションという構造は作らなくてもよいんじゃないかと。ファンクションよりはロールがよいなと。

で、人にロールがつくイメージがある、という発端なので、ロールと人との関係をちゃんと表現すればそのイメージが払拭できるんじゃないかと。

ここは人にロールがつくのではなく、ロールに人がつくのはホラクラシーの考え方を踏襲したい。
そして、ロールを担当する期間がわかることが重要じゃないかとおもいました。

・このミーティングにおける〇〇のロールをスポットで担当
・このスプリントにおける〇〇のロールをパートで担当
・このプロジェクトにおける〇〇のロールのメンバーとして就任
（特に期間が指定はされず異議を唱える、異議が唱えられるまで）

みたいな呼称がうまくできればよいんじゃないかなとおもいはじめてます。
全然決まりてがでなかったけど一回放流。。。

**Comment by motoi** [comment]
一応調べた羅列の文字列を。

役割の目印
アームバンド
バッチ
マーク
ワッペン
当番
日直
係
班長
先生
仕事
担当
アサイン

役割・機能を意味するもの
ロール（引き受ける感じ）を担当する
パート（一時的）を担当する
レスポンシビリティ
チャージ
デューティ（ロールより責任が強い）
ジョブ
オブリゲーション
ファンクション
フィーチャー

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-641422220
↑のところの通りで、私はロールで別に問題ないと思っているので、特に異論ないです。
言ってくれているように、細かいニュアンスはそれを記述してあげるほうが大事だと思います。

なので、対応として、
- 名称類はロール。いまエッセンシャルズに入っているものもプラグイン内に含むものもロール。別にその二つの"ロール"に区別はない。
で、いければと思いますがどうでしょう。

@kikuchiharuma さん、ご確認ください。
で、特に何かコメントがある場合、正直私はそこまでこだわりがない（しいて言うなら名称、どう呼ぶか、の話にこだわらないほうがいいというこだわりがある）ので、 @motoi さんと @kikuchiharuma さんでしばらく直接ラリーしてもらって、結論を私宛に教えてほしいです。

あと内容面とは別件の話として、
@motoi さん、次のアクションする人にAsssigneeを変更するよう意識ください。

**Comment by kikuchiharuma** [comment]
でかいロール、小さいロール、ロールのまとまり、などがあるということだと思いますが、結論、それらをひっくるめて「ロール」と呼ぶのはよいと思いました。

ここまでのやりとりを見てようやく思い出しましたが、一般的な名称よりも、個別のロールの名前こそ属人的な印象を作ってしまいやすいので、そちらをがんばったほうが良いな、という気がします。

「スプリントマスター」なんかが典型ですが、一時的に担うものとしては「人につく感じ」が過剰だなと感じます。

「レコーダー」「モデレーター」なんかは、一時的に担うものとしていい呼び方だと感じます。

ロールのまとまりとして大きすぎると、ロール間の関係が暗黙的になって、「人」の中で処理される感じがしてしまうのかもしれませんね。人によって違う部分が大きいと、次は自分がやるかもしれない、と思いづらくなりますし、そもそも定義が難しくなる。
あまり大きいロールは誤解を避けるために作らない、という方法もあるかもしれません。

**Comment by kikuchiharuma** [comment]
@motoi それから、このIssueのスレッド自体の話ですが、元々のヒアリング内容を知らないサトマツさんに対して、課題の明確化がされないまま(何がどうなれば解決なのか示されないまま)手数が増えてしまったのはよくないなと感じました。

サトマツさんにIssue完了の基準が示されてない以上、決めてください、になってしまうのは必然かなと思いました。

Issueのタイトルは最初は素朴なものでもいいと思いますが、払拭したい、だけではなぜそうしたいのか不十分なのは明らかなので、途中でアップデートがあるべきだったと思います。

何度か課題として書き下してみてほしい、とメンションしましたが、もう少しクリティカルな話として共有すべきだったと反省してます。

アサインのつけかえを全員で積極的にやらないといけない理由はこのあたりかなと思います。
課題を明確化しませんか、となったら、それを行うひとを決めて、その人なりの案が出る(または別の進め方の案が出る)まで待つようにしつつ、自分がそれをやらないと進まない、と自覚できるようにするには、アサインのつけかえは有効だと思います。

**Comment by motoi** [comment]
> 課題の明確化がされないまま(何がどうなれば解決なのか示されないまま)手数が増えてしまったのはよくないなと感じました。

これはすみません。確かにそうですね。
なんかボヤっとしたものを投げるとこうなっちゃうんだろうなあと思いました。途中でアップデートするときの型みたいなものがあったらよいかもとおもいました。

アサインの付け替えを徹底します。

**Comment by motoi** [comment]
@kikuchiharuma 
一旦サトマツさんからは菊地さんと決めてください、とボールを渡されているので定金と菊地さんで結論持っていきます。

ということでいまさら課題の明確化を行います。こういう書き方でよい？という事例にもなるかなともおもい。

issueを立てた背景：
プロダクトチームや菊地さんから、以下のような意見をもらった。
ロールという言葉だと役割が人につく感じがよくない、明示的に役割分担という作業が絶対必要というニュアンスが感じられ暗黙的な役割分担が産まれづらくケースバイケースで役割を担うような自律性が損なわれそう。ソフトウェア開発とかだと帽子とか椅子とかそういう表現もあるよね。
これらの意見をもらい、確かにそうだなとおもい、例としてもらった、帽子とか椅子とかであれば、人につかない役割名称にできるんじゃないかなーと感じてこのissueを立てた。

完了の定義：
プロジェクトスプリントにおける役割の呼称（とその活用例やルール）が決まっている

前回のMTGまでの経緯：
ロールという名前が人っぽいからファンクションにする、人につく役割はロールで人につかない役割はファンクションにする、という整理があった。その整理で名称を定金が金曜日中に考えてくれ、が前回のMTGの結論だった。

いままでの流れを見て私なりの結論：
名称は「ロール」でいくで3人とも納得している。

> 名称類はロール。いまエッセンシャルズに入っているものもプラグイン内に含むものもロール。別にその二つの"ロール"に区別はない。

ということでよいかなとおもいます。

あらたなIssue ：
> ここまでのやりとりを見てようやく思い出しましたが、一般的な名称よりも、個別のロールの名前こそ属人的な印象を作ってしまいやすいので、そちらをがんばったほうが良いな、という気がします。

とても同意しました。このあたりはこのイシューではなく、ロールの運用方法や名称規則の検討の別のイシューにするということでどうでしょうか。もうちょっと運用しながら考えるという時間も必要な気もしており。

ということで確認は以下の2点です。
1点目は、名称としてロールでよいか。
2点目は、ロールの詳細な名称の付け方や運用の仕方は別イシューでよいか。
確認くださいー。

**Comment by kikuchiharuma** [comment]
いいと思います！

**Comment by motoi** [comment]
@Satoshi-Matsumoto さんお待たせしました。
結論、以下でお願いします！
> 名称類はロール。いまエッセンシャルズに入っているものもプラグイン内に含むものもロール。別にその二つの"ロール"に区別はない。

**Comment by motoi** [comment]
サトマツさんが修正してくれたら確認してクローズってことでお願いします。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
諸々進めてもらいありがとうございます。
それでは私のほうで修正してからお二人にボール渡します。

ただこの段階で、コメントが2点。

- #51 で別issue立てるのは私も賛成です。
- 定金さんの書いてくれた前回までの経緯ですが、

> ロールという名前が人っぽいからファンクションにする、人につく役割はロールで人につかない役割はファンクションにする、という整理があった。その整理で名称を定金が金曜日中に考えてくれ、が前回のMTGの結論だった。

正確には、

> もともとの課題をつまびらかにすると：
> ロールだけだと、人につくものしか表現できない。
> それに加えて、人につかないものも表現したい。
からの、
> 人につかないもの1種類で統一。
> CODEの理想としては、人につくものはあくまでない世界。
です。なので、いま結論として、"人につくもの"ではなく、"人につかないもの"(もしくは"属人性のないもの”のほうが正確でしょうか）の一種類のみがあり、この名称がロールで合意した、という理解です。

この辺は正確に残しておかないとあとからすぐ混乱が生まれそうだったので、念のため丁寧めに書いておきます。

では修正に入ります！

**Comment by kikuchiharuma** [comment]
🙏

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
修正しました。
https://github.com/copilot-jp/project-sprint/commit/c68a4bfbe730f5c7fd33b181e5a07a5132ab3bc3

修正元は、ディレクトリ修正後のものです。（ほかのレビューと混線しないように）
名称をロールに統一するというところであれば、実は修正箇所としてはそこまでないです。

ということで、 @motoi さんが確認して問題なければそのままクローズでよいかと思います。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
> いま結論として、"人につくもの"ではなく、"人につかないもの"(もしくは"属人性のないもの”のほうが正確でしょうか）の一種類のみがあり、この名称がロールで合意した、という理解です。

これが「人につく」目線でしか会話されていないのですが、私の手書きの絵の一番下にかいているように、「役割に人がつく」という目線に変えれば属人性のあるものもないものも一つの表現にできるなと思った次第です。
昔 @kikuchiharuma さんが書いてくれた絵が引用したいけどどこにあったか思い出せない（笑）

そのあたりも次のイシューで議論したいなとおもっています。

**Comment by motoi** [comment]
かくにんしましたー。こちらはクローズで。
