### ISSUE TITLE
プロジェクトスプリントの原理、の記述はこのままでよいか

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#330]
https://github.com/copilot-jp/project-sprint/blob/v.3.0.0/ja/code/tutorial/section4-1.md

> では、「過去」「現在」「未来」について、具体的に何を見るとよいでしょうか。 「プロジェクトスプリントの原理」でも記載しているようにプロジェクトスプリントでは、単にプロジェクトの進捗だけでなく、個人の活動やチームとしての活動が理想の状態にあるかどうか、また推進プロセスが円滑に機能しているかどうかがプロジェクトを進めていく上で重要な要素と考えており、継続的改善アプローチでも、これらを検証することを推奨しています。

これこのままでよいんだっけとおもった。

**Comment by KokoroKagawa** [comment]
よくなかったです。直しました。
https://github.com/copilot-jp/project-sprint/commit/c087cf0fdf0b134f086333dca63b3132d501575b
