### ISSUE TITLE
readmeにリリース手順の明文化

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#34]
目的：暗黙的なロール、フローの明文化
サンプルを探す→具体的に書く

**Comment by motoi** [comment]
まずは菊地さんサンプル探しお願いします！

**Comment by kikuchiharuma** [comment]
Kubernetesの日本語Readme
https://github.com/kubernetes/website/blob/master/README-ja.md

どうすれば貢献できるのか簡潔にまとまっており、非常に素敵です

**Comment by kikuchiharuma** [comment]
リリースということに関してはこのページ&章が参考になりそう
https://kubernetes.io/docs/contribute/new-content/overview/

**Comment by kikuchiharuma** [comment]
ロールに関してはこの辺りが参考になりそう

ジャンルごとのレビュア
https://github.com/kubernetes/website/wiki/Tech-reviewers

お話相手担当者のシフト
https://github.com/kubernetes/website/wiki/PR-Wranglers

**Comment by kikuchiharuma** [comment]
これもReadmeの必読に入ってますが、スタイルガイド
https://kubernetes.io/docs/contribute/style/style-guide/

複数人で書くことが前提になると、必要になってきそうですね。

**Comment by kikuchiharuma** [comment]
@motoi この辺りを参考に、Readmeにリポジトリの位置付け、コントビューター歓迎、リリースの手順、ロールや相談相手の一覧、Slackや毎週のディスカッションなどへの参加案内、などが(まずは簡単なレベルから始める意味で)1ページにまとめて書かれると良いかと思いました。

**Comment by motoi** [comment]
https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/jp.md
行動規範もいるのかな

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
この流れを受けて
https://github.com/copilot-jp/project-sprint/issues/46
のissueたったということでいいですか？

であれば、二重管理になるのでこちらは閉じてしまってください。

**Comment by motoi** [comment]
あ、こっちがルートだった。あっちけします。

**Comment by motoi** [comment]
ブランチ切ってあげてみました。

https://github.com/copilot-jp/project-sprint/commit/25780e959e4b008565ff8c0d5fa4b72d74e76e2b?diff=split

こんな構成や内容でよいのかを確認ください。
また日本語と英語をわけるのか、わけるとしたら英語と日本語では貢献してもらうことが違うのかなども考えなきゃダメなのだろうか、など。

@kikuchiharuma さん、まずご意見ください！

**Comment by kikuchiharuma** [comment]
@motoi 追加部分の内容はいいんじゃないでしょうか！PJSとは、のセクションが消えてしまってるので、それは残したほうがいいかなと思いました。

**Comment by motoi** [comment]
@Satoshi-Matsumoto さんご意見ください！
フォークの話とかこれでよいんだっけ。。。クバネテスのものそのままマネしてるんだけど（笑）

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
みました！いまあるものに対する修正案みたいなものはブランチ切って更新してます。

他issueとの調整
https://github.com/copilot-jp/project-sprint/commit/ddd4866f240798d32e968108f57bfa706e2dcdfa

文言の修正
https://github.com/copilot-jp/project-sprint/commit/7de4c2d748614679206acd4e522069e9625a50ed

https://github.com/copilot-jp/project-sprint/commit/b679f36547189944f59e43b5bfa97c948dddab3d

https://github.com/copilot-jp/project-sprint/commit/0b1732b0fda94f0f112ff14b7fa29cc68cfe21fc

最後のものは、文言調整のほかに"毎週のミーティング"といきなりするとちょっとハードル上がるのじゃないかと思ったので、"ミートアップ"としています。

このブランチは @motoi さんの切ったreadme-for-v1.0を基にしているので、内容的に問題なさそうだったらマージしてしまってください。一部だけ取り入れたい場合は、いったんマージのうえで修正するコミットをするとかがよいですかね？(この辺のやりかた、気になる点あったらコメントもらえると助かります @kikuchiharuma )

**Comment by Satoshi-Matsumoto** [comment]
で、私が直接修正の手を入れていないところだと、下記あたりです。

1.  日本語 / 英語問題ですが、いったんは日本語版だけでだして、あとから英語でおいついていくというのはどうですかね？というのもCODE本文でも思うのですが、ある程度日本語の内容が固まらないとダブルメンテがすごく大変になるのです。だから、今の段階では、「英語の対応はいま検討中であとからお知らせ予定です」という主旨の内容だけ英語で書いておいて、しばらく日本語で回してみるとかじゃないかと。

2. あと基本的にCODEほかこのドキュメントの記載内容はマークダウンですよ、というのは言っておいたほうがいいような気がしました。まあ、ファイルがmd拡張子なので別にいい気もしますが…

3. いまの記載内容だとforkしてプルリクする、など、ある程度Github習熟している人を前提になっているんですが、フランクにこのリポジトリでissueたてて会話する、みたいなことも考えられるのじゃないかなーと思います。こういうのコントリビュートの方法も書いたほうが良いのじゃないかと（こうなるとGihubのアカウント管理の問題もあるのでいけるんだっけ？というのが気になってますが・・・）

なんとなく、Githubお作法的なものもある気がするので、まずこのあたりの、修正案が見えていない内容について @kikuchiharuma さんに意見をもらいたいです（こうした修正をしたほうがいい / しなくてもよい / しないほうがよい、など）。

そのうえで、 @motoi さんのほうで、修正ごりごりすすめてもらえればと。

**Comment by kikuchiharuma** [comment]
日本語英語について、Readmeの話としては、ディスカッションする言語はこれです、という指定になるような気がしました。今このプロジェクトは日本語で進めているので日本語で参加してね、いずれ英語で参加できるようになるよ！とかそういう方針を話せば、Readmeを読む人との期待がズレない気がします。どうすれば入れるのかな、入ったらどうなるのかな、関心事だと思うので。

**Comment by kikuchiharuma** [comment]
マークダウンですよ、とだけ書くのも変かな…という気はしました。マークダウンのテキストがソースになって、GitHub Pagesでホストするサイトをジェネレートしてるよ。だからPJSのコントリビュータになるというのは、マークダウンの文書の変更について議論したり、実際に書いたりすることを意味するよ。ということを書けば丁寧ではある気がします。

**Comment by kikuchiharuma** [comment]
確かに、いきなりプルリクしてこいよ、だけではなくIssueも気軽にどうぞ！くらいはあっても良いと思います。

**Comment by kikuchiharuma** [comment]
サトマツさんの指摘は全体にもっともですが、自分はv1.0.0に向けて、まずコントリビューターになりたい人、Issueで意見、Slack参加、いずれも歓迎だよ！おいでよ！というメッセージさえちゃんと書かれており、定金さんが仲間集め発信者としてその文書を書いてくれていたら満足なので、いずれも将来で良いレベルの話かなと思いました。

**Comment by motoi** [comment]
> このブランチは @motoi さんの切ったreadme-for-v1.0を基にしているので、内容的に問題なさそうだったらマージしてしまってください。一部だけ取り入れたい場合は、いったんマージのうえで修正するコミットをするとかがよいですかね？(この辺のやりかた、気になる点あったらコメントもらえると助かります @kikuchiharuma )
菊地さんこれについてコメントもらえますかー？！気にならないってことかな。

**Comment by Satoshi-Matsumoto** [comment]
"コントリビューターを歓迎します"の部分： @Satoshi-Matsumoto が文責。
=> "歓迎します" のところ (気持ち面)は @motoi さんにお願いするかも。その分も含めて構成はいったん @Satoshi-Matsumoto 。

それ以外の部分の修正 + Githubの取り回しは、 @motoi さん。

cc @kikuchiharuma

**Comment by Satoshi-Matsumoto** [comment]
まず @Satoshi-Matsumoto のほうで

> "コントリビューターを歓迎します"の部分： @Satoshi-Matsumoto が文責。
> => "歓迎します" のところ (気持ち面)は @motoi さんにお願いするかも。その分も含めて構成はいったん @Satoshi-Matsumoto 。

を対応して、そののち @motoi さんに pass。

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648736045

↑のポイントは、@Satoshi-Matsumoto がプルリクをして、@motoi さんがReview → 違和感がある箇所は修正リクエストをこのプルリク上で行う。そのうえで、切っているブランチ上で @Satoshi-Matsumoto が修正、再度プルリク、の流れで最終的に @motoi さんのブランチにマージ。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
さし当たりコントリビューターのところを、
 - コントリビューターを歓迎します
 - コントリビューターとしての参加の方法
というかたちで分けて、さらにこれまでの私の修正案をプルリクしました。まずこれをレビュー ~ マージまでの流れを進めましょう。

そのあとの流れとしては、 @motoi さんのほうで 
 - コントリビューターを歓迎します
のところを更新してください。

内容的には、
このCODEがオープンソースとなることを意識してつくっており、広くあまねくコントリビューターを歓迎している、という思想・気持ち面（？）のようなものを書いてもらえればと思います。

そのうえで、@kikuchiharuma さんがレスくれている下記の点については、
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648623379
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625072
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625459
お作法の話として、コントリビューターとしての参加の方法 にはいる部分で、これは上記の @motoi さんの更新が終わったあとに、私の文責で引き取ります。（そして、これはREADME更新の第二弾として、別issueにしましょう）

てことで、プルリクのレビューお願いします！

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/pull/76
こちらのプルリクあげました。マージされたら
> （そして、これはREADME更新の第二弾として、別issueにしましょう）
これを立てる。

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん プルリクマージされました。
ので、
> （そして、これはREADME更新の第二弾として、別issueにしましょう）
と書かれているので別イシューたてをお願いします。立てたらこのイシューはクローズで（よいですかね？）

**Comment by Satoshi-Matsumoto** [comment]
#91 でイシューたてました。こちらは、クローズしてしまいます！ @motoi
