### ISSUE TITLE
Project Sprintをパッと一言で伝えたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#356]
とある資料で書けと言われて書いたけどわかりやすそう。

定例ミーティングを定期的・反復的な実践の起点とすることにより、
プロジェクトの進化する目的・目標を、みんなで漸進的に達成するための推進メソッド。

誰にどんなシチュエーションなのかによって変わりそうだが、汎用的にひとことで言い表せるものを作っておきたい。

**Comment by KokoroKagawa** [comment]
> 定例ミーティングを定期的・反復的な実践の起点とすることにより、進化するプロジェクトゴールをプロジェクトチームで漸進的に達成するための推進メソッド。

一旦↑で行く。目的・目標については更なる深掘りを待つ。
将来的に理論編と実践編で異なる一行要約を置くこともありうるかもしれないメモ。
