### ISSUE TITLE
「Project Sprintにおけるプロジェクトの概念」絵をバージョンアップさせたい

### ISSUE THREAD

**Issue by KokoroKagawa** [copilot-jp/project-sprint#359]
### 「Project Sprintにおけるプロジェクトの概念」の絵
元絵：下記URL内p.24
https://docs.google.com/presentation/d/1eQt4854mcezXFkmoPnKO6U9HThFpkX4kAKvi2PySEXA/edit?usp=sharing
実装される場所：下記URL内1枚目
https://www.projectsprint.org/ja/v3/ja-v3.1/tutorial/section1-1

### 表現したいこと（優先順位順。特に上2つはデザインの力を借りたい！）
・プロジェクトは、「全体」の中の「部分」である（プロジェクト＝現状のプロジェクトチームで推進・達成に現実味が持てる「部分」を切り出したもの）。プロジェクトだけではなく、その外側の「全体」も表現したい。
・プロジェクトゴールが達成される＝全体に対する部分的デリバリー（漸進性）
・プロジェクトを実際に進めてみることで、「全体」も進化する（一部の進化の影響が全体の活動にも波及する）
・プロジェクトの主体はプロジェクトチーム
・プロジェクトゴールはプロジェクトチームの意思を反映して設定されたもの
・プロジェクトそのものもプロジェクトゴールも、環境の変化に応じ、プロジェクトチームの意思を反映していつでも再定義・最適化可能（今の絵で緑の点線になっているのは、この不確定性を表現したいという努力の痕跡）

**Comment by kameokamayu** [comment]
@KokoroKagawa 

ありがとうございます！

表現したいことは理解できました！
より理解高めるために、「現状の絵の課題点」もご教授できないでしょうか？

**Comment by KokoroKagawa** [comment]
@kameokamayu 

今の絵だとプロジェクトなるものが最初から独立して存在しているように見えてしまう点が一番気になってます。
プロジェクトチームが始点・主体である感は一定程度出せていると思うのですが、「プロジェクトチームの意思によって全体から一部を切り出したもの」感が足りないなあと。

また、プロジェクトは複数並行して（始点と終点はそれぞればらばらに、しかしそれぞれが全体ゴールの部分的な達成として）存在しうることも表現できるとよりよいなと！そのほうが部分と全体の関係がより伝わるのではないかと思っています。

**Comment by kameokamayu** [comment]
@KokoroKagawa @motoi 

ポンチ絵で恐縮ですが、ラフ描いてみました。
プロジェクトゴールは時系列に依存せず、全体にひも付きながら徐々に理想に近づいていく様を表現するにはどうしたらよいか苦心しまして、
雲のようなものが集まって、徐々に大きくなる、ような比喩で表現できないか、と考えたものです
![image](https://user-images.githubusercontent.com/80878730/177065192-874e7188-b9a1-481d-81ce-ad5e88928d5b.png)
![image](https://user-images.githubusercontent.com/80878730/177065221-54cf008a-2670-44ac-9288-84a124ce3cbb.png)

ただ、これだと

「プロジェクトゴールの集合体がただの集まりに見える」

ため、現状の状態から理想の状態に移行する過程、みたいなものが削ぎ落ちてしまっているのが気になっています。

一旦ご意見お聞かせいただけると嬉しいです。

**Comment by KokoroKagawa** [comment]
@kameokamayu ありがとうございます！ヵヮィィ。
雲の集まりのイメージ、しっくりきます。

「Project Sprintにおけるプロジェクトの概念」絵として、部分の達成が全体の達成につながるというところはうまく表現してくださっていると思います。部分としてのプロジェクトが複数ありうることは表現したいのですが、「（あるひとつの）プロジェクトの概念」絵としては1枚目の構図が分かりやすく感じます。

あとは、プロジェクトの始まりの部分で、「あの大きい雲のこの一部なら僕たちが作れそう・作る！」みたいなチームの意思がなんらか表現できるとbetterかなと思いました。雲の素材が散らばっていて、チームで「大きい雲の一部分を達成するためにこの素材を使う」という境界線を引く、とか？

> 現状の状態から理想の状態に移行する過程、みたいなものが削ぎ落ちてしまっている

たとえば2枚目の絵で集合体の絵も時系列で表現し、ひとつのプロジェクトゴールが達成されるたびに集合体の雲が少しずつ大きくなっていくとかくっきりしていくとかというような表現でもよいのかも…とおもいました。

@motoi なにかコメントあればぜひ！

**Comment by KokoroKagawa** [comment]
@kameokamayu 
メソッドチームで話をしました。一度反映試みていただけますと幸いです！

★プロジェクトの始まり（全体からの切り出し）と終わり（全体への統合）
GitHubにおけるブランチの作成とマージの解説でよく見かける、↓のような絵に近いイメージを持っています。全体から切り取って持ってきて、プロジェクトチームのものとして進めて、また全体に戻す（そのことにより全体も前に進む）イメージ。ご参考になるでしょうか。
![image](https://user-images.githubusercontent.com/84454164/178713038-38e657f4-d3d7-4228-84ea-e38f0d2c52e8.png)
https://www-creators.com/archives/4996#i

★プロジェクトチームのあり方
プロジェクトという箱に人間が合わせていく世界観を想起させず、プロジェクトチームありきで、すべての定義と外部への説明責任をプロジェクトチームが担う感を出せるとよいなあと。
（このISSUEにもつながる：https://github.com/copilot-jp/project-sprint/issues/367）
外部とのインタラクション（説明責任、環境の変化への適応）や他のプロジェクトチームとの連携（同じ全体ゴールを目指す中での説明責任、他のチームが前進したことによる環境の変化への適応）も意識しつつ。

★時系列の表現
プロジェクトのスタートからゴールまで、時間が進んでいることは表現したいものの、定例ミーティングという要素はここで表現されていなくても構いません。（PJSにおける重要要素ではありますが、「プロジェクトの概念」絵としては、「定例ミーティングで漸進的に進んでいく」ことよりも、プロジェクトとプロジェクト外の世界の表現を優先したい。）

なお、メソッドチームでは今のCODEの記述に加えて、PJS利用の手引きとしてのチュートリアルを作ろうと構想しています。
描いていただいた絵のトーンがポップで親しみやすいので、理論編・実践編に組み込むより、チュートリアル向けのほうがしっくりくるかなという気がしています～～～
