### ISSUE TITLE
「アジェンダ」 の言葉の定義

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#36]
一度コパ社内で議論なったりプロダクトチームでも会話がでているのですが、「アジェンダ」 と 「議題」って違うんじゃないかと。

1つ1つの議論すべき話題 → 議題
議題があつまったもの → アジェンダ
じゃね？と。
いまPJSでもSGMsでも議題も、議題があつまったものもアジェンダと呼んでいるなと。
これは定金の完全に言葉の認識の違いから来ているものなんだけどこの整理を一緒にやりたいなと。
英語ではここでいう議題とアジェンダをつかいわけているのかとかも含めてリサーチいれてまとめたいとおもっています。
@Satoshi-Matsumoto さんが全部このあたり含めてやるのか、定金が言葉の定義を決めたほうが良いのか、一回会話するのかとか、まずこの辺の作業切り分けもしてもらってよい？

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/issues/21#issuecomment-626064653_

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/21#issuecomment-626756320

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
議題 / アジェンダは広く意味もとらえられるファジーな言葉なので、いったん特に対応しない。
