### ISSUE TITLE
最新版のコードにたどり着くまでのクリック数が多い

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#361]
![image](https://user-images.githubusercontent.com/680855/170895755-e7bf5f7d-da3d-441c-88e4-6f3e0ec8070c.png)
ここに全部のバージョンを並べるとか？
orgのトップに各言語最新のコードへのリンクの導線があればよいのか？

**Comment by KokoroKagawa** [comment]
@motoi 
本日のリリースでディレクトリ構造を再構成したため、多少はアクセスしやすくなったかと思います。いかがでしょうか。

**Comment by motoi** [comment]
ルートが日英併記になりつつ、そこに日英の最新版へのパスが置かれているとよいとおもいました！

**Comment by KokoroKagawa** [comment]
@nanamikagwa orgのトップページから英語版への導線を作るため、下記の一文だけ取り急ぎ日英併記にしたいのですが、英訳お願いできますでしょうか…！
https://www.projectsprint.org/

> 定例ミーティングを定期的・反復的な実践の起点とすることにより、進化するゴールをチームで漸進的に達成するためのプロジェクト推進メソッド。

**Comment by nanamikagwa** [comment]
@KokoroKagawa なかなか作業できておらずすみません。。
ご連絡いただいた一文だけ英訳をしました。以下文面お願いします！

> 定例ミーティングを定期的・反復的な実践の起点とすることにより、進化するゴールをチームで漸進的に達成するためのプロジェクト推進メソッド。


> A project promotion method to progressively achieve evolving objectives with teams using regular meetings as a basis 
> for regular and iterative practice.

**Comment by KokoroKagawa** [comment]
@nanamikagwa ありがとうございます！

A project promotion method to progressively achieve evolving objectives with teams using regular meetings as a basis for regular and iterative practice.

- project promotion method
promotionという単語がProject Sprintにあまりフィットしなくなってきたなーという気がしています（主体性の薄さ…？）。
最近、Project Sprintにおける用語を、航海・宇宙っぽいトーンにしたいね（https://github.com/copilot-jp/project-sprint/issues/355）という話をしているのもあり、promotionではなくpilotという語はいかがでしょうか。”pilot project”という表現もあるので誤解を生むだろうか…と思いつつ、ご意見いただければと！

- progressively
incrementallyってあんまり言わないですかね。（イテレーティブ&インクリメンタル）

- evolving objectives
objectivesという語からは、がっちり定まった目的が存在している（&見えている）ような印象を受けるような気がします（evolvingがついてはいるのですが）。
もうすこしふわっと&走りながら軌道修正していく感を出したく、purpose等の語だと違和感ありますか？

- with teams
Project Sprint、v3からは「チームが主体！」感を強く出しています。この一文は「チームが主体」よりは「定例ミーティングが重要」感を出したいものではあるのですが、もう少しチームに焦点が当たるような構文・表現があれば。

- regular meetings
regularのほうが「一般的な定例会議」の訳としてはナチュラルな表現だとは思うものの、現時点のProject Sprintにおいては、recurring meetingsのほうがよいかな、と思っています。認識合わせと意思決定のためのハコとしてのミーティングをとにかく設置するんだよ！という意思。recurringの循環感も、スプリントのサイクルを回すという意味ではフィット感あるかなと。

- as a basis for
基礎や基準として定例ミーティングが置かれるというよりは、「個人の活動を定例ミーティングで持ち寄って認識合わせと意思決定を行うことでまた個人が次の行動に自律的に向かうことができる」という文脈で、定例ミーティングが各スプリントの起点になる、というようなイメージです。なんかいい表現ないですかね←

**Comment by nanamikagwa** [comment]
@KokoroKagawa ご連絡が遅くなり大変失礼しました。長くなってしまうのですが、以下にて返信します！

★project promotion method
> promotionという単語がProject Sprintにあまりフィットしなくなってきたなーという気がしています（主体性の薄　　さ…？）。
> 最近、Project Sprintにおける用語を、航海・宇宙っぽいトーンにしたいねという話（https://github.com/copilot-jp/project-sprint/issues/355）をしているのもあり、promotionではなくpilotという語はいかがでしょうか。”pilot project”という表現もあるので誤解を生むだろうか…と思いつつ、ご意見いただければと！

→COPILOT project methodとかどうです？笑　推進という意味合いはなくなりますが、コパイロツトの名称自体がトンマナと近く、コパのプロジェクトメソッドではあるのでどうかなと思ったのですが、、どうでしょう？


★progressively
> incrementallyってあんまり言わないですかね。（イテレーティブ&インクリメンタル）

→Incrementallyで大丈夫です！PJS英文で他の箇所でも使っていたのであえて変えてみようかと思っただけでした。

★evolving objectives
> objectivesという語からは、がっちり定まった目的が存在している（&見えている）ような印象を受けるような気がします（evolvingがついてはいるのですが）。
> もうすこしふわっと&走りながら軌道修正していく感を出したく、purpose等の語だと違和感ありますか？

→objectivesという言葉の方が短期的な目的・ゴールの意味であり、変化も同様に伴いつつ軌道修正していくイメージに合っているかなと思いました。参考としてWrikeというプロジェクト管理ツールの会社が出している「objectives」と「goals」 の違いの説明が私自身しっくりきたかなと思いました。
・goals→長期的なプロジェクトゴール
・objectives→短期的なゴールという意味合い
もしゴールを使うなら「switching goals」とかですかね？軽すぎるかもですが。。
例）https://www.wrike.com/project-management-guide/faq/what-is-the-difference-between-goals-and-objectives-in-project-management/
例）https://www.brighthubpm.com/change-management/73697-dealing-with-changing-goals-in-the-middle-of-a-project/ 


★with teams
> Project Sprint、v3からは「チームが主体！」感を強く出しています。この一文は「チームが主体」よりは「定例ミーティングが重要」感を出したいものではあるのですが、もう少しチームに焦点が当たるような構文・表現があれば。

→team membersという表現に変えてみました。

★regular meetings
> regularのほうが「一般的な定例会議」の訳としてはナチュラルな表現だとは思うものの、現時点のProject Sprintにおいては、recurring meetingsのほうがよいかな、と思っています。認識合わせと意思決定のためのハコとしてのミーティングをとにかく設置するんだよ！という意思。recurringの循環感も、スプリントのサイクルを回すという意味ではフィット感あるかなと。

→了解です！recurring meetingsで変更しておきます！

★as a basis for
> 基礎や基準として定例ミーティングが置かれるというよりは、「個人の活動を定例ミーティングで持ち寄って認識合わせと意思決定を行うことでまた個人が次の行動に自律的に向かうことができる」という文脈で、定例ミーティングが各スプリントの起点になる、というようなイメージです。なんかいい表現ないですかね←

→こちらはもう一文ではカバーできないので、文面を長めにして説明するしかないかなと思います。

★**新しい文章）**
定例ミーティングを定期的・反復的な実践の起点とすることにより、進化するゴールをチームで漸進的に達成するためのプロジェクト推進メソッド。

COPILOT project method to incrementally achieve evolving objectives with team members using recurring meetings as a basis for regular and iterative practice. The individual team members bring their activities to the recurring meetings to ensure everyone is on the same page and in decision-making. Then again, the individuals can move autonomously to the following action.

こちら上記全てを満たせていないかもですが、どうでしょう？
ご指摘いただけますと幸いです！

**Comment by KokoroKagawa** [comment]
@nanamikagwa ありがとうございます！

★project promotion method

> promotionという単語がProject Sprintにあまりフィットしなくなってきたなーという気がしています（主体性の薄　　さ…？）。
最近、Project Sprintにおける用語を、航海・宇宙っぽいトーンにしたいねという話（https://github.com/copilot-jp/project-sprint/issues/355%EF%BC%89%E3%82%92%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%82%82%E3%81%82%E3%82%8A%E3%80%81promotion%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%8Fpilot%E3%81%A8%E3%81%84%E3%81%86%E8%AA%9E%E3%81%AF%E3%81%84%E3%81%8B%E3%81%8C%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B%E3%80%82%E2%80%9Dpilot project”という表現もあるので誤解を生むだろうか…と思いつつ、ご意見いただければと！

→COPILOT project methodとかどうです？笑　推進という意味合いはなくなりますが、コパイロツトの名称自体がトンマナと近く、コパのプロジェクトメソッドではあるのでどうかなと思ったのですが、、どうでしょう？

⇒よい！です！今後コパイロツト
色を薄める必要が出てきたらまたご相談させてください。

★progressively

> incrementallyってあんまり言わないですかね。（イテレーティブ&インクリメンタル）

→Incrementallyで大丈夫です！PJS英文で他の箇所でも使っていたのであえて変えてみようかと思っただけでした。

⇒承知しました！

★evolving objectives

> objectivesという語からは、がっちり定まった目的が存在している（&見えている）ような印象を受けるような気がします（evolvingがついてはいるのですが）。
もうすこしふわっと&走りながら軌道修正していく感を出したく、purpose等の語だと違和感ありますか？

→objectivesという言葉の方が短期的な目的・ゴールの意味であり、変化も同様に伴いつつ軌道修正していくイメージに合っているかなと思いました。参考としてWrikeというプロジェクト管理ツールの会社が出している「objectives」と「goals」 の違いの説明が私自身しっくりきたかなと思いました。
・goals→長期的なプロジェクトゴール
・objectives→短期的なゴールという意味合い
もしゴールを使うなら「switching goals」とかですかね？軽すぎるかもですが。。
例）https://www.wrike.com/project-management-guide/faq/what-is-the-difference-between-goals-and-objectives-in-project-management/
例）https://www.brighthubpm.com/change-management/73697-dealing-with-changing-goals-in-the-middle-of-a-project/

⇒ニュアンス理解しました～、ありがとうございます。日本語の方の「ゴール」は最終的なプロジェクトゴールのイメージで書いていたのですが、確かにマイルストーン的な中間成果としての短期的なゴールobjectivesを漸進的に達成しつづけていくイメージの方がしっくりくるなあと思いました！

★with teams

> Project Sprint、v3からは「チームが主体！」感を強く出しています。この一文は「チームが主体」よりは「定例ミーティングが重要」感を出したいものではあるのですが、もう少しチームに焦点が当たるような構文・表現があれば。

→team membersという表現に変えてみました。

⇒下記だと違和感ありますか？
COPILOT project method for teams to incrementally achieve evolving objectives using recurring meetings as a basis for regular and iterative practice. 
日本語のほうをより丁寧に書くなら、「チームが進化するゴールを漸進的に達成し続けられるようにするためのメソッド」かもしれません。

★regular meetings

> regularのほうが「一般的な定例会議」の訳としてはナチュラルな表現だとは思うものの、現時点のProject Sprintにおいては、recurring meetingsのほうがよいかな、と思っています。認識合わせと意思決定のためのハコとしてのミーティングをとにかく設置するんだよ！という意思。recurringの循環感も、スプリントのサイクルを回すという意味ではフィット感あるかなと。

→了解です！recurring meetingsで変更しておきます！

⇒ありがとうございます！

★as a basis for

> 基礎や基準として定例ミーティングが置かれるというよりは、「個人の活動を定例ミーティングで持ち寄って認識合わせと意思決定を行うことでまた個人が次の行動に自律的に向かうことができる」という文脈で、定例ミーティングが各スプリントの起点になる、というようなイメージです。なんかいい表現ないですかね←

→こちらはもう一文ではカバーできないので、文面を長めにして説明するしかないかなと思います。

⇒丁寧にありがとうございます。ストレートに説明するのもありだなあと思いつつ、定例ミーティングはプロジェクト開始時に一連のものとしてセットされるにとどまらず、プロジェクト終了まで個々の定例ミーティングが個々の実践サイクルの起点となり続けるイメージを表現するのに、下記だと違和感ありますか？（くどい…？）
using recurring meetings as a series of originations of regular and iterative practice

原文でもこの点は伝えきれていないよなあと思い（別途テンションももらっており）、原文の方も見直しています～～～

★新しい文章）
原文旧）定例ミーティングを定期的・反復的な実践の起点とすることにより、進化するゴールをチームで漸進的に達成するためのプロジェクト推進メソッド。
原文新）定例ミーティングを起点とする実践を定期的・反復的に重ねることにより、進化するゴールをチームで漸進的に達成するためのプロジェクト推進メソッド。


COPILOT project method for teams to incrementally achieve evolving objectives using recurring meetings as a series of originations of regular and iterative practice.

**Comment by nanamikagwa** [comment]
@KokoroKagawa 新しい原文の文章&英文も作成いただきありがとうございました！
ほんの少しだけ直してみたのですが、ほぼ共有いただいたもので良いかと私は思いました。ご確認をお願いします。

**The COPILOT project method allows teams to incrementally achieve evolving objectives by using recurring meetings as a series of originations of regular and iterative practice.**

**Comment by KokoroKagawa** [comment]
ありがとうございました！こちらをベースに反映させていただきます。
（そもそもPJSは「メソッド」なのか？という話が出てきており、このあと少々語句の変更が生じるかもしれません。）
