### ISSUE TITLE
リンクの指定がおかしい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#363]
https://www.projectsprint.org/ja/v3.2/theories
![image](https://user-images.githubusercontent.com/680855/171154913-98f2e2d3-c30f-4f30-8a41-d4705abc2ac7.png)

> [期待値とロール]rolls.md)

こういうのペロッと私がなおせるように今度やり方おしえてください。
ってGitHub上でペロッとパッチのブランチ切ればよいんだっけ？

**Comment by KokoroKagawa** [comment]
ありがとうございます、対応しておきました。

▼Githubから
いきなりmaster修正で大丈夫です（不安であれば適宜新規ブランチ切ってください←既存のマイナーアップデート用ブランチは触らない！）。

▼Gitbookから
いきなり本番環境修正で大丈夫です（不安であれば作業用コレクションのどこかでお試しください）。

いずれの場合も、バージョン番号をつけてリリースノート記載・Github上のRelease登録をお願いします。
