### ISSUE TITLE
PJSにおけるプロジェクトと今までのプロジェクトの捉え方の違いをまず理解してもらうことからはじめたほうが良さそう

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#367]
いろんな人に説明するときに、まず理解してもらうことが大事だなとおもうのは、プロジェクトの捉え方。

まず箱が有りきでそこに人間が合わせる世界から、プロジェクトメンバーが自分たちで規定して行く世界をPJSでは表現していることをつたえる。
PJSの世界はプロジェクト外部への説明責任が必ず果たされる必要があるので、今までの世界より求められることも責任も大きい。いままでの世界のほうがある種楽であるとも言える。

どちらが求める姿なのかで決めるしかないが、どちらにせよこのVUCAな状況においては、外部への説明責任や、状況をみえるようにするしかない。

みたいなことを整理したい。

**Comment by KokoroKagawa** [comment]
チーム自体に説明責任があるぶん大変でもある
外部から規定されるプロジェクト、チーム自身で規定するプロジェクト、それぞれプロコンある

Tutorialができたら導入に書きたい内容

**Comment by KokoroKagawa** [comment]
![image](https://user-images.githubusercontent.com/84454164/195465423-3181b16d-f30e-4dbe-8cd8-b233ccc41a6e.png)

**Comment by KokoroKagawa** [comment]
v4.0以降のIntroduction、Definitionsにて記述済み
