### ISSUE TITLE
バージョンアップはPJS Slackのリリースノートに投稿する

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#37]
と思っていましたが違いましたっけ。
リリース時のアクションとかどこかにまとめてもよいかも。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma @motoi 
下記のissueの結果を受けて対応内容を決めます。もしその中でこちらのissueの内容も解決されたらこちらは閉じましょう。
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-628280119

**Comment by kikuchiharuma** [comment]
必須にするなら、リリース手順の中に、どのタイミングで、誰が、何を、という書式で明文化しておくのが良いと思いました

**Comment by motoi** [comment]
@kikuchiharuma 必須にしたいんですけど違和感あります？あ、マージしたらスラックに勝手にポストされるでよいのかもしれませんね。って今その設定されてましたっけ。

**Comment by kikuchiharuma** [comment]
@motoi Readmeにひとこと書きたい、ということですかね。https://github.com/copilot-jp/project-sprint/blob/readme_for_v1.0/README.md#slack%E3%82%84%E6%AF%8E%E9%80%B1%E3%81%AE%E3%83%87%E3%82%A3%E3%82%B9%E3%82%AB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AA%E3%81%A9%E3%81%B8%E3%81%AE%E5%8F%82%E5%8A%A0%E6%A1%88%E5%86%85 このセクションに、リリースノートはこのチャンネルでやってるよ！とか書くのであれば良いんじゃないかと思いましたー

**Comment by motoi** [comment]
@kikuchiharuma 
うまく伝わってなくてすみません。
そうではなくて、projectsprint.orgがアップデートされたら projectsprint.slack.com の #release_note のチャンネルに以下のようなものを投稿することで、Slackに参加しているひとにも通知したいとおもっています。

具体的にはリリースノートに書かれているものとおなじものをサトマツさんがポストする？自動的にポストされる？ようにしたいということです。

投稿イメージ

---
v0.8.3 (May 23rd, 2020)
JA
アジェンダの定義を変更(Essentials / Advance)
アドバンス内から予約ロールの概念を撤廃
---

目的としては、Slackの活性化、SGMsに興味をもっているひとへPJSへの認知、の2点にになります。

**Comment by kikuchiharuma** [comment]
@motoi ピンポイントでやりたいこととしてはわかるのですが、「アクションをまとめたい」という範囲とか形式が曖昧ですかね。

例えば、

Issueのチェックリストを使ってリリースのタスクを明確にする、そのチェックリストをリリースごとに使い回す
https://help.github.com/en/github/managing-your-work-on-github/about-task-lists

とか、

ここでいうPost Release Activitiesのようにリリースの手順を文書化する
https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md#releases-management

とか、

このRelease手順をまとめた上で、ステップごとにIssue化してアサインしていくとか。

あたりでしょうか。
いずれにしてもSlackにポストする、という部分だけ書いても運用に乗らないと思うので、今暗黙にあるリリースの流れの中のまとまった部分を書き出す必要があると思います。
そこまでできない場合は、Readmeにしれっと書いて、人間が善意の範囲で運用、くらいになってしまうかなと思います。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
このissueですが次アクションがぼやっとしている気がするのでjump inしますね。

ちょうど別issueでこういうのをたてたのですが、
https://github.com/copilot-jp/project-sprint/issues/70

リリースの流れ、といういわば内部運用ルールみたいなものを
1. まず、どういうものにするか？(@kikuchiharuma さんが言うように、暗黙的に決まっているものを書き出す必要がありますね）
2. そのうえで、決まったものをどこに記載するか？（対外的に見せるものにするか？projectsprint.orgに乗せるか？README?リリースノート？）

という話で、この二つそれぞれについて対処すればよいのだと思いました。

あとは単純に作業者誰かっていう話な気がしますが、これは @motoi さんアサインお願いできますか？

そもそもなんか違う、ということであればコメントくださいまし。

**Comment by motoi** [comment]
@Satoshi-Matsumoto さんジャンプインすみません助かります。
担当ですが、コントリビューターが読むべき内容だとおもったのでreadmeに書かれるものかなとおもうので、readmeと同様にこれもサトマツさんに書いてもらったほうが良いと思いました。

1の観点だと、コントリビューターに向けて書き出すということでよいと思いました。
2の観点であれば私はコントリビューターが理解すべきものだとおもったので、readmeでよいかと思いましたが、それは全体の文章構造を把握しているサトマツさんに決めてもらってよいですかね。

そのあと菊地さんにオープンソースおじさんとしての違和感を挙げてもらうという流れかなと。
ということでサトマツさんお願いします！

**Comment by Satoshi-Matsumoto** [comment]
https://github.com/copilot-jp/project-sprint/pull/76
がmergeされたらブランチ切って修正していきます。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma @motoi 
これなんですが、

まず、
https://github.com/copilot-jp/project-sprint/commit/ec9810eb67a5c283d7c8a4668fb1123f82a348f0
https://github.com/copilot-jp/project-sprint/commit/e06eb4fd6967d13771d9f02166ebe6866d8cbfc4
で、

- READMEの中で、コントリビューターの参加方法を / contributeでディレクトリを新しく切ったうえで、
- コントリビューターと議論して反映された変更内容はリリースノートと Slackコミュニティに投稿される
旨を追記しました。

まずディレクトリを分けた意図としては、
最終的にREADME を入り口として、下記のような形にもっていきたいと思っているからです。
/contribute -> コントリビューターにとってどのような貢献の方法があるかの全体像の説明
/releasemanagement -> リリースまでの作業手順の明示化
/releasenote -> リリース内容の履歴明示、どんなリリースがあったかをわかるようにする

/contribute には大枠でこうしていますよ、というどちらかといえば初見の人向けの内容。
/realesemangement のほうは内部でいま暗黙的に行っているリリースまでの作業手順や、バージョン管理の考え方を書いていくイメージです。（これはまだディレクトリ切っていません。）

このissueでの議論に応えていくと、

まず @motoi さんのこちらは、
> そうではなくて、projectsprint.orgがアップデートされたら projectsprint.slack.com の #release_note のチャンネルに以下のようなものを投稿することで、Slackに参加しているひとにも通知したいとおもっています。
> 目的としては、Slackの活性化、SGMsに興味をもっているひとへPJSへの認知、の2点にになります。
> このSlackへの投稿を必須にすることに対して違和感ありますか？という質問です。

これは必須にするという判断のうえ、それをいったん /contribute内の変更として反映しています。

一方、
https://github.com/copilot-jp/project-sprint/issues/37#issue-619370969
や
https://github.com/copilot-jp/project-sprint/issues/37#issuecomment-645280916
ではなされているように、リリース後のアクションをしっかりまとめるという話もあります。

これは、v1.0.0のスコープに入っていない
#70 
#68 
#69 
などもあるので、これらと一緒に、v1.0.0以降のアップデートの対応とする、でいかがでしょうか？

ちなみに、これらの「リリース後のアクションをしっかりまとめる」修正は、 /releasemanagement に記載していくようなイメージを持っています。

**Comment by Satoshi-Matsumoto** [comment]
というわけでまとめると、
- このissueは もともとのissueタイトルである 「バージョンアップをPJS Slackのリリースノートに投稿します」ということを明示する対応で、close
- ほか、派生している、リリースまでのアクションをまとめる作業は、別issue & 1.0.0以降の対応としていきたい

ということになります。

対応の方向性とか最終アウトプットイメージについて、まずセマンティックおじさん @kikuchiharuma さんに賛否伺いたいのですが、どうでしょう？

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto いいと思います！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
ありがとうございます！

@motoi 
https://github.com/copilot-jp/project-sprint/issues/37#issuecomment-663498392
https://github.com/copilot-jp/project-sprint/issues/37#issuecomment-663499065
こんな感じでこのissueの進め方考えていますがどうでしょうか？

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
よいとおもいます！

**Comment by Satoshi-Matsumoto** [comment]
@motoi ありがとうございます！別issueたてました。こちらはcloseします。
