### ISSUE TITLE
Project Recurring Meetings / プロジェクト定例会議 的な概念をつくってもよいかも

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#370]
普通の定例会議と明らかにProject Sprintで表現しようとしている定例会議は異なる。
プロジェクトを推進するための、プロジェクトのための定例会議、という言葉をつくったほうがわかりやすいかもなーと思い始めてきました。
ということで色々と候補になる言葉を調べてみる。

Project Recurring Meetings
プロジェクト定例会議
プロジェクト循環会議

スパイラルアップ
spiral-up

改善が奏効しあって継続的な改良・向上に結びつくこと。「善循環」「好循環」とも言う。

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/185261953-110ccad1-0e79-4351-ba8b-bce2b33d60bb.png)
この分類もよく活用するので説明に使えるかも

**Comment by KokoroKagawa** [comment]
創造的なミーティングと意思決定のミーティングは異なる。
創造的なミーティングは作成物を伴うので実験（プロジェクトの成果にインパクトを出すための作成物を作る行為はすべて実験と言える）。
プロセスに属するプロジェクト定例会議は意思決定のミーティングであり、実験ではない。

**Comment by KokoroKagawa** [comment]
一般的な定例会議について記述するときは「一般的な」をつける。
Project Sprintにおける現行の「プロジェクト定例会議」は、「定例会議」と記述する。

**Comment by KokoroKagawa** [comment]
v4.1より以下の定義を置く。

定例会議:　プロジェクトチームが、短期的・定期的なサイクルで反復的に実施する対話の場。各メンバーが自身の次の行動を自己決定できる状態を目指して他のメンバーと同期し対話を行い、共通了解の形成、問題の共同解決、アイデアの共同創造、意思決定などを行う。
