### ISSUE TITLE
フレームワークを書いてみる

### ISSUE THREAD

**Issue by KokoroKagawa** [copilot-jp/project-sprint#374]
https://miro.com/app/board/uXjVOiKhgcU=/?share_link_id=368014950998

**Comment by KokoroKagawa** [comment]
https://github.com/copilot-jp/project-sprint/discussions/382
プロジェクトゴールに関する記述において、与えられたプロジェクトゴールに納得するプロセスも含まれる記述にする（「意思の反映」の説明が不十分）。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/blob/c236a7333198eaa6d7b317eecdb8408017b2ecbe/JA/v3.4/framework.md
記述中mdへのリンク

**Comment by KokoroKagawa** [comment]
https://github.com/copilot-jp/project-sprint/blob/c972b893df1a190693f318e586b899b707393cc0/JA/v3.4/framework.md
[更新]記述中mdへのリンク

**Comment by KokoroKagawa** [comment]
Issueとしては完。Discussion等でフィードバックが入ってきたら都度対応する。
次はチュートリアル！
