### ISSUE TITLE
スプリントマスターの位置づけ - Advanceか、Plug-inか

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#40]
_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-631430550_

https://github.com/copilot-jp/project-sprint/issues/32

とも関連。

essentialsとadvanceの位置づけが決まった後で、スプリントマスターの書き方を検討

**Comment by motoi** [comment]
@Satoshi-Matsumoto これもうプラグインに入っているのでクローズでよいよね？一応最終確認くださいー。

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん
元のやり取り紐解くとプラグインに入れるかアドバンスに入れるかの議論をしましょう、という話で、
当時からその議論は進んでいないのでクローズにはできません。

`スプリントマスターについては、essentialsには入らないが、Plug-inかadvanceにするか、は要議論`

**Comment by Satoshi-Matsumoto** [comment]
#64に合流。こちらはクローズします。
