### ISSUE TITLE
プロジェクトソースという言葉は普段使わないので少し違和感があった

### ISSUE THREAD

**Issue by MasaruSaito** [copilot-jp/project-sprint#400]
https://www.projectsprint.org/ja/v3.3/theories/project_lifecycle
上記に書かれているプロジェクトイシューという用語が普段使っていないので、違和感がありました。
（発案者）と補足があるので、意味は理解できますが、どちらかというと発案者もしくはプロジェクトの発案者
と記載いただいたほうが違和感なく読み進めることができると思いました。

**Comment by KokoroKagawa** [comment]
対応したので閉じます。
