### ISSUE TITLE
マイルストーンに関する記述をアップデートする

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#402]
https://www.projectsprint.org/ja/v3.3/practices/milestones

![image](https://user-images.githubusercontent.com/680855/191167167-d4fd1e2b-58bb-4ca8-8c1f-1651c46020e8.png)

**Comment by KokoroKagawa** [comment]
一旦ステージで統一。
4.0へのバージョン上げに伴い、マイルストーン周りの記載を調整する必要あり。

**Comment by KokoroKagawa** [comment]
実践知チームよりフィードバック

>チームAPIとの関連性が高いと思うので、トラックの設定と紐づけてチームAPIの説明が今後書かれているとよいかと思いました
（ミーティングの設計ですかね）

チームAPIを示す会議体のテンプレ機能？
概念と必要な要素があると実践しやすい。

**Comment by KokoroKagawa** [comment]
プラクティカルガイドで記述される内容になりそう一旦クローズ
