### ISSUE TITLE
"実践"の言葉の定義

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#41]
https://github.com/copilot-jp/project-sprint/commit/678046633447428c192a9255187ced579498e7c2#r39302058
より。

"最適化" "実践" および"実作業"についての定義の整理と修正作業の必要があるかどうかを検討 / 必要であれば修正。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
もともとのコメントに対するアンサーですが、

"実践"という言葉と、"最適化"という言葉の定義はadvanceの中に記載があります。
https://projectsprint.org/ja/advance/index.html
共通事項 配下、実践と最適化 のところ

> 実践と最適化は、プログレス・アクティビティやチーミング・アクティビティといった、プロジェクトのゴールが達成されている状態や自律的で理想的なチームが形成されている状態に直接寄与する実作業とは異なり、これらの活動をより効率的・効果的なかたちで促進するための取り組みである。

単純に"実践"という言葉を使わず他名称にして修正かけますので、そののち、なお違和感がある / または、そもそも言葉だけの問題ではない、ということであれば教えてください。

**Comment by motoi** [comment]
実践と最適化のサンプルください！

私の中ではこの2つを合わせ最適化（定金ワード）とよんでいたので、分ける必然性を検討したいです。

私の昔の資料では以下でした。
実作業→実践（定金ワード）
実践と最適化→最適化（定金ワード）

**Comment by Satoshi-Matsumoto** [comment]
- 実行 (Execution) : 成果物に対した直接的推進
- 最適化 (Optimization) : プロセスの改善による間接的推進

で分ける。

プロセスの改善による間接的推進を ad hocか継続的かで二つにわけることはしない。

**Comment by Satoshi-Matsumoto** [comment]
マイルストーンをcode-v1.0.0に指定します。
重要な概念であり、v1.0.0を出すにあたり誤解の内容に整えておきたいため。

**Comment by Satoshi-Matsumoto** [comment]
ここでいうところの実践や最適化の話（調整後の実行や最適化の話）はいま理論編のアドバンスに入っているが、むしろ、実践編いれたほうがよいのではないか？ （@kikuchiharuma さんより）

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さんのこのコメント**以外**のところを先に修正しました。
> コメント：ここでいうところの実践や最適化の話（調整後の実行や最適化の話）はいま理論編のアドバンスに入っているが、むしろ、実践編いれたほうがよいのではないか？ （@kikuchiharuma さんより）


理論編アドバンス
https://github.com/copilot-jp/project-sprint/commit/ae92ec2fb210d46dfb027e7f407f0d756b84adaa
https://github.com/copilot-jp/project-sprint/commit/aa4a3aa7780e8065665b88318e648ed1a58938f0

理論編ベーシック
https://github.com/copilot-jp/project-sprint/commit/f0c160020ce1304e365acaffadba335da8a407e0

実践編ベーシック
https://github.com/copilot-jp/project-sprint/commit/f0b2e4af5845044e137c3aef8770a78b38e111ae

よく考えたら実践編 / 理論編 っていう言葉で整理しているのに "実践"っていう言葉に固有の意味を持たせるのめちゃくちゃややこしかったですね。。。。なので、実践という言葉は使わないようにしています。

@motoi さんこの記述で違和感ないですか？
実際にごりごり成果物をつくっていく"実行"と、効率を上げるための"最適化"があり、"最適化"には、短期と長期のものがあるよね、という整理です。

まずこの修正が問題なさそうであれば、続いて下記のポイントの修正にすすみます。
> コメント：ここでいうところの実践や最適化の話（調整後の実行や最適化の話）はいま理論編のアドバンスに入っているが、むしろ、実践編いれたほうがよいのではないか？ （@kikuchiharuma さんより）

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
> 実際にごりごり成果物をつくっていく"実行"と、効率を上げるための"最適化"があり、
こちらは違和感ありません！
私も色んな資料で、実践・実装・実行とかゆれて書いているので実行に統一しようとおもいます。

> "最適化"には、短期と長期のものがあるよね、という整理です。
この部分については、私が整理しきれていないのと、あんまりこの目線を意識できていないので、自分の実践がともなっていないものだなーとおもってしまいました。ですが、記述があるのは違和感ないです。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ありがとうございます！回答になってます。

続いて
https://github.com/copilot-jp/project-sprint/issues/41#issuecomment-657554914
のポイントの修正に入ります。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/issues/41#issuecomment-657554914
このコメントに対する修正として

https://github.com/copilot-jp/project-sprint/commit/8cdbaa945b0beafdfa3bd153a70f8bafdc568383
https://github.com/copilot-jp/project-sprint/commit/fbc0f5fc827ef28e1fcd2eb167bc64f62f173200

こんな感じで修正いれてみました。
確かにご指摘の通りで、実践編ベーシックで、
https://github.com/copilot-jp/project-sprint/issues/89
で集中的に議論している内容である「振り返り」「継続的改善アプローチ」といったところで"最適化"という言葉が出てきているのに、最適化自体の説明が理論編アドバンスにあるのはバランス悪かったですね。

ということで、最適化の基本的な説明については実践編ベーシックに持ってきました。こうすることで、続く内容とのつながりもスムーズかなと。

また長期的 / 短期的 といった内容は @motoi さんも言っているように実際に実務での意識がそこまで浸透していないという意味でも、実践編アドバンスにするのが適当かなと。

位置づけについて、どうでしょう？またこのタイミングでこれまで @motoi さんとしていた議論の中に違和感があれば追加でコメント付け加えてもらって構いません。

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto 位置づけの整理、ExecutionとOptimizationのネーミングともに違和感ないです！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma ありがとうございます！こちら、クローズします。
