### ISSUE TITLE
タグマネージャーを設置したい

### ISSUE THREAD

**Issue by hatakeyama-y** [copilot-jp/project-sprint#42]
なぜなら。
アナリティクスなどのタグを管理したいためです。

**Comment by hatakeyama-y** [comment]
Google タグ マネージャーをインストール
下のコードをコピーして、ウェブサイトのすべてのページに貼り付けてください。
このコードは、次のようにページの <head> 内のなるべく上のほうに貼り付けてください。
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WMXXLXJ');</script>
<!-- End Google Tag Manager -->
```
また、開始タグ <body> の直後にこのコードを次のように貼り付けてください。
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WMXXLXJ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```
Google タグ マネージャー スニペットの導入について詳しくは、クイック スタートガイドをご覧ください。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 基本設置でよいと思いますがいかがでしょうか？
問題なければ、実際の仕込みは
@kikuchiharuma さんにお願いすると思うので、アサイン変更ください。

**Comment by motoi** [comment]
問題ないとおもいます！菊地さんお願いしますー！

**Comment by kikuchiharuma** [comment]
@hatakeyama-y 埋め込み方について相談させてください。今このJekyllテンプレート https://github.com/jekyll/minima を使って、そのタグ埋め込みの機能を使ってるんです。https://github.com/copilot-jp/project-sprint/blob/master/_config.yml にGAのIDを書いてパラメータとして渡すと、今のサイトのソースコードが出力される、という具合です。minimaがタグマネージャーに対応できるのか調べる -> できない場合テンプレートを改造する、という手順になるのかなと思いました。これをhatakeさんが可能であればPRまでしていただければ、自分の方でレビューしてマージします。難しい場合は僕の方でやってみます。

**Comment by kikuchiharuma** [comment]
ちょっと調べましたが、default.html を編集するしかないみたいですね。
https://github.com/mmistakes/minimal-mistakes/issues/1005

今minimaテンプレートの改造はせずそのまま使ってる状態なので、_layouts/default.html を新しく作って、そこに書く形になりそうですね。

@hatakeyama-y いかがでしょうか。Pull Requestまで行けるかどうか判断お願いします。

**Comment by hatakeyama-y** [comment]
@kikuchiharuma 初見では何もわからなかったのですが、
ヒントいただけたのでやってみます！ありがとうございます。

**Comment by hatake0-0** [comment]
どこから_layouts/ をよんでいるのかわからず。。
もうちょっとみてみます。

**Comment by kikuchiharuma** [comment]
@hatake0-0 ビルドに失敗する原因は、GitHub Pagesの使っているminimaのバージョンと違うテンプレートで上書きしようとしたことだったようです。

https://pages.github.com/versions/
ここにminima 2.5.1とあります。

https://github.com/jekyll/minima/releases/tag/v2.5.1
ここからテンプレートやインクルードファイルを持ってくればOK

**Comment by kikuchiharuma** [comment]
こんな風に変更すれば大丈夫なはずなので、やっておきました。
https://github.com/copilot-jp/project-sprint/commit/bfa6f9cc9ab95cece6d9dbbf54bb584d03380319

**Comment by kikuchiharuma** [comment]
@hatake0-0 別の問題として、minimaの機能を使ったGAタグUA-160350510-1を仕込むオプションが有効になっているのですが、こちらをオフにするべきか判断お願いします。https://github.com/copilot-jp/project-sprint/blob/master/_config.yml#L8

https://github.com/jekyll/minima/blob/2.5-stable/_includes/google-analytics.html
このインクルードでコードが生成されて、今はそれが入ってます。

必要ならオプションをコメントアウトして、プルリクください

**Comment by hatakeyama-y** [comment]
@kikuchiharuma ありがとうございます。
オプションをコメントアウトしてPRさせていただきました。
