### ISSUE TITLE
価値と成果と出力

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#421]
![プロジェクト推進改善メンバー定例MTG - Frame 1](https://user-images.githubusercontent.com/680855/198495001-4d03dbfe-ebcf-4098-8500-d01de891e3e6.jpg)

こういうことなのか感。こころさんフィードバックプリーズ。

**Comment by KokoroKagawa** [comment]
v4.1にて一旦書ききりクローズ。
