### ISSUE TITLE
会議体という概念をPJSに導入するか検討

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#43]
プロダクトチームと会話していてトラックが説明しづらいね、という話になりました。その時に、会議体という概念を使うと分かりやすいのでは？という議論になりました。メソッドチームの意見を聞きたくおもっております。よければCODEに採用してもらうとかもありかなとおもっています（プロダクト定金）

**Comment by motoi** [comment]
まずは @Satoshi-Matsumoto さんご意見ください！

**Comment by Satoshi-Matsumoto** [comment]
そもそもトラックというのがわかりにくい概念という実感がある。

トラックは会議体という言葉で説明できるのではないか？

トラックは、マイルストーンによって定義されるもの。

会議体 => 印象としてはオーソライズするための形式的なものという語感をもってしまうのでは？

会議にかかわる人たちのことを呼ぶ名称はあるか？ => 会議体 ではなくて、チーム、グループ、マイルストーンごとのチーム、マイルストーン体、など

プロジェクトでよくあるのは、ワーキンググループ(WG) という言葉。
ただWGベースでトラックをつくるのではなく、トラックはマイルスストーンベースで作り、それに合わせて人をつけるべき。

結論）
・トラックの定義をアップデート。(Plug-inにて）
・会議体という言葉は使わない。

**Comment by motoi** [comment]
@Satoshi-Matsumoto これ同じイシューで処理するの？こっちクローズして別イシュー？

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
あ、そうですね。
会議体の概念は使わないで結論でているのでこのissueとしてはクローズで。
トラックの概念のアップデートは別issueたてましょう。
私のほうで、たてておきます。
