### ISSUE TITLE
全員で議論に参加する → どういう条件・態度で望めばよいのか、が深ぼりたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#44]
> 全員で議論に参加する → どういう条件・態度で望めばよいのか、が深ぼりたい
> これが実現していれば「プロセスに参加するだけで」「認識を合わせることができる」がもっとしっくりくる気がする！
> これちょっと議論したらでるかなーとおもったけどどうだろう。
>いっかいセンスメイキング理論についてまとめるのでそれを持ってアップデートを検討しましょう！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
これ、私にアサインされてますが、よくみたらまずはセンスメイキング理論まとめるという @motoi さんの作業ですね。というわけでまずはアサインを変えます。

で、これいつくらいまでに完了しそうです？こっちで〆切きったほうがいいですかね？

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん
もうこれミーティングで共有したとおもうけども。そこでじゃ一回サトマツさんよろしくね、でアサイン付け替えたんじゃなかったっけ。菊地さんがオールドタイプのリーダー論みたいでつらいみたいな会話したのとかとか。
ということでまとめ資料はもうありんす。
もう一回どこかで共有しよか？

**Comment by Satoshi-Matsumoto** [comment]
@motoi さん、あぁああー、そうか、あれそもそもこのissue発端なんですね。。すみません、ぜんぜん繋がっていなかったです。もう一回共有お願いできると、助かります。。

**Comment by motoi** [comment]
ミーティングで共有すると菊地さんの時間もったいないので、別のタイミングでやりましょー。今日そのスケジュール確認させてください。

**Comment by Satoshi-Matsumoto** [comment]
元issueと関連付けます
https://github.com/copilot-jp/project-sprint/issues/12

**Comment by Satoshi-Matsumoto** [comment]
センスメイキング理論をもとに

問：
1) PJSのミーティングがセンスメイキング理論を実現するのはどういうポイントか？
2) センスメイキング理論をサポートするためにはどのようなミーティングであればよいのか？

センスメイキング理論を参照して、1)の観点から書き下す方向性。

**Comment by motoi** [comment]
コメントもらいました
↓
ミーティングに参加する時の心構え的なものとかはメソッドに入って来たらより良いかも？と思いました。
uniba koide

**Comment by Satoshi-Matsumoto** [comment]
上記のコメントはマニュアルをよんでのものだが、CODEから修正が必要かも検討。

**Comment by yoneyama-tomohiro** [comment]
米山メモ

「センスメイキング理論」はあくまでも道具なので、それを目的にした整理にはしたくない。

■ミーティングに参加する時の心構えについての雑記
- センスメイキング理論もだが、社会構成主義（社会も客観的な存在ではなく、個々人の言葉を通じて作り上げられたものであるちう考え方）が参考になる
- つまり、PJも多様化・複雑化する中で、客観的な正解などありえないので、個々人が感じることを共有・対話しながら進めるしかないものであるということ
- だから、正しいかどうかというマインドではなく、「私はこう思う」「私はこうしたい」をまずはテーブルに出し合うことが大事

的な話。

**Comment by yoneyama-tomohiro** [comment]
9/28（月）のAM中目処で言語化します。

**Comment by motoi** [comment]
9/28（月）の米山さんの状況により0.9.0に乗せるかを検討

**Comment by yoneyama-tomohiro** [comment]
遅くなってしまいましたが、一旦。
センスメーキングは十分に読み込めていないですが、ホラクラシー的考え方も含めて。
---
【＜私＞の発信】
・各自が感じていることを率直に会議の場に投げ込むこと
・ネガティブな違和感であっても、それを発信して、チームで共有することが重要
【＜他＞の許容】
・違う見方・考えは会議・プロジェクトにとって不可欠であり、積極的に許容すること
・他者の考えに対して、すぐに是非を判断せずに、良い意味で判断を保留すること
【行動・アウトプットを通じた関与】
・行動やアウトプットを通じて、会議・プロジェクトに関与していく
・過度に考えようとしすぎず、行動・アウトプットを通じて状況に働きかけて、そこから情報を得るようにすること
・行動・アウトプットによってしか分からないことも少なくない。次にとるべき行動・アウトプットは仮説であることを認め、間違う可能性を怖れない。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/tree/dev-manual-v0.9.0
からブランチを切って更新する

**Comment by motoi** [comment]
@Satoshi-Matsumoto このブランチがなくなっていたのでマスターにマージされたってことだとおもうので、マスターからブランチきりました。問題ないよね？一応確認。

**Comment by yoneyama-tomohiro** [comment]
一旦テキストベースですが、文案です。
明朝もう一度だけブラッシュアップして、gitに載せたいと思います。
---
会議の目的は、適切な意思決定を行うことです。

そのためには、意思決定する対象の状況をまず適切に捉える必要がありますが、状況が意味するものは往々にして多義的で、複数の解釈が存在しうるものです。状況判断を誤ると適切に意思決定を行うことはできないため、まずは多様な解釈を共有して、状況の多様性・複雑性をそのまま把握することが適切な意思決定を行う土台となります。

会議では、まず、お互いの考えの一致点・相違点を認識しながら、状況に対するチームとしての解釈の共通認識を作りましょう。

そこで大事なのは、「意思決定」の前に、「そもそも問うべきもの・検討すべきものは何なのか？」ということについての共通認識を作ることです。問うべきもの・検討すべきものがそもそもズレていたとするならば、いくら検討しても正しい意思決定にはなりません。

状況をありのままに理解した上で、「問うべきもの」「検討すべきもの」についての共通認識をチームとして作っていきましょう。

そのような会議を実現するために、参加者には以下のような態度が求められます。

【参加者に求められる態度】
・絶対的な正解が存在するとは限らないことを受け入れること
・誰かが正解を教えてくれるはずという他者への依存的態度ではなく、チームとしての解釈を一つずつ積み上げていこうというマインドで参加すること
・そのため、まずは各自が考えていること・感じていることを率直に提示すること
・また、他者の考えに対する価値判断を保留し、「そのような考え方もあるのだな」と受け入れること

**Comment by yoneyama-tomohiro** [comment]
@motoi @Satoshi-Matsumoto 
本件は、下記で記載しているのですが、この後のアクションとして何をすれば良いでしょうか？
https://github.com/copilot-jp/project-sprint/commit/4ffdca970fa892dacd7492f4b5a41edea9eab857

**Comment by yoneyama-tomohiro** [comment]
@motoi 
まず、定金さんレビュー
→よければ、高津さんレビュー
で良いですかね？
一旦、定金さんにアサインを変えています。

**Comment by Satoshi-Matsumoto** [comment]
新しいブランチ切ったのでここをベースに確認しましょう。
4ffdca970fa892dacd7492f4b5a41edea9eab857

**Comment by Satoshi-Matsumoto** [comment]
みました。よいとおもいます。ただちょっと修正しました。

e8cf2aae5a9c1d4fb764e58e2d28c98d72b3a92b
=> 見た目の調整をちょっとしました。

e218e2ad84a83728c33676e9fe17b33d9b3fb044
=> 下記のコメントを受けて修正して見ました。プロセスにおいて共通認識をつくるために必要なのはプログレスにおけるゴールやマイルストーンだけではなく、チーミングにおけるロールもあると思います。
> 「そもそも問うべきもの・検討すべきものは何なのか？」
> これとマイルストーンやプロジェクトのゴールの関係が示されているとPJSぽいかなとおもいましたが、なんかその関係性って書けそうですか？
> 

@motoi さん、まず問題ないかご確認いただき、そのあと @yoneyama-tomohiro さん、問題なければクローズしてしまってください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto さん、よいとおもいました。
@yoneyama-tomohiro さん、最終確認くださいー。

**Comment by yoneyama-tomohiro** [comment]
@motoi @tk2hiroaki 
高津さんの追記、異論ありません。
クローズします。
