### ISSUE TITLE
タスクとアクション（try/todo）について記述する

### ISSUE THREAD

**Issue by KokoroKagawa** [copilot-jp/project-sprint#445]
https://docs.google.com/document/d/15zPKvkJA3ESSaXjLahcCQaJtPJhKQMi7UDbrtWvT0C0/edit

記述に落とす際の要点（タスク、アクション、try、todoの定義をしたうえで以下の記述を想定）

- タスクについてチームの対話の場で共通了解を作ることで、
  - タスク同士が互いに疎であるか/それぞれeffectiveであるかが確認できる。
  - 自発型のタスクでも、アクティビティ仮説を一度チームでの対話の場に持ち込むことにより助言プロセスを踏める。
- tryとtodoの定義がチーム内で共有されていることで、チームから見たタスクタイプと実行者から見たタスクタイプのミスマッチを検知できる。
- 個々のタスクのタスクタイプを明確にすることで、実行者がチームからの期待を正しく理解できる。
  - 実行者はチームからの期待を理解した上で、タスクに対するスタンスを決定できる。（実行時の動き方の話でもあるが、そもそも自分が引き受けるべきタスクかどうかの判断もできるため、タスクと実行者のミスマッチが起きにくくなる。）
  - 実行者は納得感を持って適切な役割を引き受け、自律的にタスクを遂行することができる。
- このプロセス（ドメイン的な意味での）がうまく回ることで、
  - 【チーミング】期待値の共有と役割の引き受けがスムーズになり、メンバー同士がより信頼しあえるようになる。
  - 【プログレス】タスク同士が疎結合な状態を維持しながら、成果物を効率的に生み出せる。

@motoi 過不足、認識ずれなどあればご意見ください！

**Comment by motoi** [comment]
3つ目のポチにあるアクティビティとはアクションのこと？

**Comment by motoi** [comment]
3つ目のポチにあるアクティビティとはアクションのこと？タスクタイプではなくアクションタイプのほうがわかりやすい？

**Comment by motoi** [comment]
一番最後の今回の区分けの効果を読んで思ったのだが、タスクとアクションそれぞれを分けて考えた方がわかりやすいかも。

タスク（と実行されるアクション）の効果はこれである

それとは別にアクションを2つに分ける効果はこれである

みたいな。
以上っす。

@KokoroKagawa 確認くださいー。

**Comment by KokoroKagawa** [comment]
> 3つ目のポチにあるアクティビティとはアクションのこと？文脈からするとタスク？
> タスクタイプがtry,todoってこと？だとするとアクションタイプでは？

→ご指摘ありがとうございます。いずれもアクションですね、整理しました。
https://docs.google.com/document/d/15zPKvkJA3ESSaXjLahcCQaJtPJhKQMi7UDbrtWvT0C0/edit
2023/08/17

最後のコメントはこのあとお話しさせてください！

@motoi

**Comment by KokoroKagawa** [comment]
https://github.com/copilot-jp/project-sprint/commit/7bc34e0232ed1ab5fcbc9f14b4d6e0e9fc559369
対応済みclose
