### ISSUE TITLE
マニュアル・チュートリアルのディレクトリ構造を整理

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#45]

**Comment by kikuchiharuma** [comment]
CODEの新しい構造
https://github.com/copilot-jp/project-sprint/issues/32#issuecomment-641942660

**Comment by kikuchiharuma** [comment]
`CODE
 - Theory
  - Basic
  - Advance
 - Practice
  - Basic
  - Advance
 - Plug-in (Theory的な内容もPractice的な内容もどちらも入る）`

**Comment by kikuchiharuma** [comment]
こんな姿になるのかな、というのを書き出してみる

```
/code/index
/code/theory/index
/code/theory/basic/
/code/theory/advance
/code/practice/index
/code/practice/basic
/code/practice/advance
/code/plug-in/index
/manual/index
/manual/tutorial/index
/manual/tutorial/introduction/index
/manual/tutorial/introduction/section1-1
/manual/tutorial/introduction/section1-2...
/manual/tutorial/setup/index
/manual/tutorial/setup/section1-1
/manual/tutorial/setup/section1-2...

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto こんなディレクトリになったとしたら、書くイメージ持てそうですか。すでにある目次に、セクション番号をつけるような感じになると思います

**Comment by Satoshi-Matsumoto** [comment]
提案いただいたものでディレクトリ構造整理してみます。完了したらご連絡するので、それを @kikuchiharuma さんがそうそうあってる、と確認してもらった時点でこのissueは一度closeしましょうか。
その後、特に何か問題があったらreopenか別issueたてるということで。

**Comment by kikuchiharuma** [comment]
オネシャス！

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto Manual v0.8.0のサイト構成を見て思ったのですが、こんな感じに改めた方が良いように感じました。

/code/index.md
/code/theory/index.md
/code/theory/basic.md
/code/theory/advance.md
/code/practice/index.md
/code/practice/basic.md
/code/practice/advance.md
/code/plug-in/index.md
/manual/index.md
/manual/tutorial/index.md
/manual/tutorial/section1-1.md
/manual/tutorial/section1-2.md
/manual/tutorial/section2-1.md
/manual/tutorial/section2-2.md ...
/manual/tips/index.md
/manual/tips/tips1.md
/manual/tips/tips2.md ...

チュートリアルのセクションごとのディレクトリの分割が冗長&一貫性を欠くのではないか、という視点です。
ディレクトリごとにindexがあることが望ましく、その意味でセクションごとは必要ないかなと。

セマンティクス的には、ディレクトリ直下をリクエストしたときに返すものがあるとかっこいい、という面もあります。
/manual/tutorial/ = /manual/tutorial/index.md

そういう視点では、CODEの方も分割しすぎかもしれませんね…理論編の文書がどんどん増えていって目次ができる、という必要性は今後もなさそうですし。

**Comment by Satoshi-Matsumoto** [comment]
上記の @kikuchiharuma さんのコメントを反映し、

48dcecf6428b0981da99231d431d905be0aa9b3b
からの
4f0c63973737e143b0256e90e210fb5d4a4bcbac
によりmanual v0.8.0リリース。

このリリース時点でのディレクトリ構造は
563a988f8458e0596ef7778d5f38b6741b8f6308
で確認できます。

このissueはmanual v0.8.0のリリースに向けたものなので、解決済みとし、クローズします。
