### ISSUE TITLE
プラクティカルガイド関連の調整

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#452]
- プラクティカルガイドへのリンクはいきなりMiroではなく以下の扉ページへのリンクにする
 https://www.projectsprint.org/practical-guide

- Miroへのリンクであるところはクリックする前にMiroだとわかるようにする

- ビジュアルプラクティカルガイドみたいになんかスライドで図解で説明してるよとか書いても良いかも。
図解プラクティカルガイドとか、プラクティカルガイド（イラスト版）プラクティカルガイド（ビジュアル版）みたいにしても良いか

- この図から白熱教室周りの文言は削除する。準備中もなくて良いのでは。
![image](https://github.com/copilot-jp/project-sprint/assets/680855/bf334012-a5cf-49c3-8316-401c9a465541)

**Comment by KokoroKagawa** [comment]
@motoi 

- プラクティカルガイドへのリンクはいきなりMiroではなく以下の扉ページへのリンクにする
https://www.projectsprint.org/practical-guide
→org反映済み
- Miroへのリンクであるところはクリックする前にMiroだとわかるようにする
→次のリリースに乗せます。対応済み。
- ビジュアルプラクティカルガイドみたいになんかスライドで図解で説明してるよとか書いても良いかも。
図解プラクティカルガイドとか、プラクティカルガイド（イラスト版）プラクティカルガイド（ビジュアル版）みたいにしても良いか
→次のリリースに乗せます。対応済み。
- この図から白熱教室周りの文言は削除する。準備中もなくて良いのでは。
→ ねのきさんに依頼するのでちょいとお待ちを。

**Comment by KokoroKagawa** [comment]
![ドキュメント体系](https://github.com/copilot-jp/project-sprint/assets/84454164/31d12645-caa3-4076-a9cd-d3f24f7f8d79)

こんなかんじにしようかなー

**Comment by KokoroKagawa** [comment]
対応済みclose
