### ISSUE TITLE
OGP関連を設定しておきたい

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#47]
![image](https://user-images.githubusercontent.com/680855/83367543-06377e00-a3f0-11ea-9cad-74c7c58bf64d.png)
テキストとOGP画像をv1.0までに設定したいですー。

**Comment by kikuchiharuma** [comment]
追加した
https://github.com/copilot-jp/project-sprint/commit/253d0582a37fdd8b36611d28f5403952220e334f
