### ISSUE TITLE
Project Sprintはいったい何なのか？という点の修正

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#48]
例えば https://projectsprint.org/ にある

> 多様性のあるメンバーによる部門/組織横断のチームが、不確実性の高い環境・状況で、複雑なアウトプットを行うプロジェクトを推進するためのフレームワークとメソッド。

など。

 "プロジェクト推進メソッド" で統一。そのための修正。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma @motoi 
https://github.com/copilot-jp/project-sprint/commit/d1f591ce718f5cfbcc00fd1facd68821477d20a4
なおしました。

@motoi さんが見てオッケーであればcloseにしてしまってよいかなとおもいます。

**Comment by motoi** [comment]
オケーす！
