### ISSUE TITLE
ロールの定義の仕方、運用方法、記入方法の決定

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#51]
でかいロール、小さいロール、ロールのまとまり、などがあるということだと思いますが、結論、それらをひっくるめて「ロール」と呼ぶのはよいと思いました。

ここまでのやりとりを見てようやく思い出しましたが、一般的な名称よりも、個別のロールの名前こそ属人的な印象を作ってしまいやすいので、そちらをがんばったほうが良いな、という気がします。

「スプリントマスター」なんかが典型ですが、一時的に担うものとしては「人につく感じ」が過剰だなと感じます。

「レコーダー」「モデレーター」なんかは、一時的に担うものとしていい呼び方だと感じます。

ロールのまとまりとして大きすぎると、ロール間の関係が暗黙的になって、「人」の中で処理される感じがしてしまうのかもしれませんね。人によって違う部分が大きいと、次は自分がやるかもしれない、と思いづらくなりますし、そもそも定義が難しくなる。
あまり大きいロールは誤解を避けるために作らない、という方法もあるかもしれません。

_Originally posted by @kikuchiharuma in https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-643727306_

**Comment by motoi** [comment]
一旦定金の方で、以下のような目線で実践しながら検討してその結果を共有する。

- 必要なロールリスト：こんなロールがあったらよい
- ロールの大きさ・小ささの検討：テンションが運用できやすいものを検討する
- ロール名の付け方の検討：人につくロール名っぽいものは別の名前にする
- ロールの詳細：ホラクラシーの目的、領域、責務、でよいか
- 運用方法の検討：ロールはどのように必要な場合に明文化したらよいか

**Comment by motoi** [comment]
期限としては1.0までにできる気があんまりしてないので、割と時間がかかると思っていますが、CODE的にはいったんここら辺までに整理してほしいとか期限的な希望はありますか？1.0までにとかあれば今思ってることをガガッとまとめます。
@Satoshi-Matsumoto さん

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
1.0の定義は

> CODE外で実際の運用にあたって必要なドキュメント ＝ マニュアル類（仮称）のα版、書きさし、の内容を受けた反映修正がCODE上にされている

となっていて、いまつくっているチュートリアルを作りながら出てきたものと、これまでにすでに出てきたものを反映していけばそれでよいと思っています。

なので、このissueに関して言うとv1.0.0以降で大丈夫です。むしろv1.0.0以降のほうがいい気がします。

というのも、v0.9.0 / v1.0.0を経て、CODEのディレクトリ構造や内容がそれなりに変わってきています。
やはり記述の手厚い箇所、薄い箇所どちらもあり、このissueの内容は薄い箇所を補完するものになると思います。そのため、いちどv1.0.0を眺めながら、どこの何の要素が足りないのか、を意識しながら考えたほうがいい気がしています。

具体的には、これらをCODE上のどこに記述するかをより細かくイメージできるようになるだろうな、ということですね。
> - 必要なロールリスト：こんなロールがあったらよい
> - ロールの大きさ・小ささの検討：テンションが運用できやすいものを検討する
> - ロール名の付け方の検討：人につくロール名っぽいものは別の名前にする
> - ロールの詳細：ホラクラシーの目的、領域、責務、でよいか
> - 運用方法の検討：ロールはどのように必要な場合に明文化したらよいか

というわけでいったん検討を @motoi さんにお渡しして、マイルストーンは別途私が引きます。

**Comment by kikuchiharuma** [comment]
@motoi 横からになりますが、進め方について、方針をまとめるのは大変そうなので1.0以降、というのはいいと思うのですが、すでにロールの名前がCODE内にたくさん存在します。

方針を決めるIssue、というのはあまり気が乗らないこともあり、(書きながら考えるに反する感じがする) すでに存在するロール名の違和感を感じたらIssueにする、というやり方にできないでしょうか。

ファシリテーター、モデレーター、アクセラレーター、コーディネーター、レコーダー、この辺りは「今日モデレーター誰がやる？」と言えそうで、個人的には大きな違和感はないです。これはみなさんどうなんでしょうか。

一方、プラグインにある、

https://github.com/copilot-jp/project-sprint/blob/dev-code-v0.9.0-%E3%83%95%E3%82%A1%E3%83%B3%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3-/-%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AE%E4%BD%8D%E7%BD%AE%E3%81%A5%E3%81%91%E3%81%A8%E5%90%8D%E7%A7%B0/ja/plug-in/index.md

スプリントマスター、プロセスアドミン、あたりは、違和感があります。
そもそも役割として大きく、属人的な印象という以上に実態がそうなのではないかという気もしますが、CODEの記述としてファシリテーターほど分解がされておらず、「複数人で担うことも可能」という説得力に乏しい気がします。

**Comment by motoi** [comment]
私があとから参照することが漏れそうなコメントをリンクしておく。
https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-644078396
https://github.com/copilot-jp/project-sprint/issues/33#issuecomment-644493358

**Comment by motoi** [comment]
@kikuchiharuma このイシューは残しつつ、違和感があるロールについて、別イシューを立てるのはどうでしょうか？
https://github.com/copilot-jp/project-sprint/issues/51#issuecomment-644086513

**Comment by motoi** [comment]
@kikuchiharuma あと昔書いてくれた役割と人との関係の絵をここに貼ってくれませんかね？いつものiPad手書きで書いてくれてたやつだったとおもいます。CODEに追加で必要な絵かもねって提示してくれてた気がしています。

**Comment by kikuchiharuma** [comment]
> ロール名称１つ１つについてそれぞれイシューを立てる

いいと思います！

**Comment by kikuchiharuma** [comment]
![Paper SuperGoodMeetings 79](https://user-images.githubusercontent.com/607971/84730449-2a3eb600-afd1-11ea-9765-aafea8e58d49.png)
![Paper SuperGoodMeetings 76](https://user-images.githubusercontent.com/607971/84730457-2f036a00-afd1-11ea-893d-b96fe11ab367.png)
![Paper SuperGoodMeetings 74](https://user-images.githubusercontent.com/607971/84730458-2f9c0080-afd1-11ea-9a3c-2b0ba4d6bd69.png)
![Paper SuperGoodMeetings 73](https://user-images.githubusercontent.com/607971/84730462-30349700-afd1-11ea-8896-9404a093b908.png)

@motoi いろいろ貼っておきます

**Comment by motoi** [comment]
![COPILOT Roles - 情報発信](https://user-images.githubusercontent.com/680855/108196291-4bf1cd80-715c-11eb-8673-a365e1a61775.jpg)
現状最新版のロールの考え方。
エフェクチュエーション的にロールが作られ始め、コーゼーション的に規定されると交換可能な役割になっていくイメージ。

**Comment by motoi** [comment]
ホラクラシーは先に役割を決めるが柔軟に変わって良いことを前提としているので、そのルールによりエフェクチュエーション的なアプローチを可能にしているのではないかとおもった。

**Comment by motoi** [comment]
チームにおけるロールの必要性が一旦薄れている
ロールセッションの記述はできている
ということでまた気になったらイシューをあげる
