### ISSUE TITLE
リファレンスページ

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#59]
https://github.com/copilot-jp/project-sprint/blob/code-appendix/ja/appendix.md

重要キーワードをせめてv 1.0.0には公開するぞ！

**Comment by motoi** [comment]
最初の方の資料に書いた参照したものテキストをコピペしておく。

アジャイルソフトウェア開発手法「スクラム」・デザイン思考・ホラクラシー・デザインスプリント・広義のKJ法・リーンスタートアップ・SECIモデル・学習する組織・OKR

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/commit/0f31de914df33a70c6898f33b333e21d0ca6476b#diff-b198f6479bb6340e48144fc8f095ebd4
こんな感じでまとめてみました！

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/blob/code-appendix/ja/appendix.md
微調整しました。なんかコミットのリンクの貼り方が分からないのと最終版を見てもらったほうが速い気がするのでこちらで！

**Comment by kikuchiharuma** [comment]
@motoi ぼくの雛形があまり良くなかったかも知れないですが、ちょっとざっくりし過ぎてるかなあと思いました。「アジャイルソフトウェア開発宣言と12の原則」のうち、どの原則がPJSのどれに対応する、どれは違う、などは、メソッドのチーム内でも意見が別れるような気がします。個人的なリストになってしまうと、いいのか悪いのか判断がつかず、今後チームとしてのメンテが不能になってしまうと思いました。

項目はこのままでも、「PJSのこの部分の背景にこれがあります」という関係をそれぞれ明確にしてはどうでしょうか。もちろん全体的な在り方や構造を真似している、どこがとは言いづらい、というのはあってもいいと思うのですが、全てそうなってしまうのはまずいなあと。

**Comment by motoi** [comment]
@kikuchiharuma ちょっとこのページに何を書いたらよいのかわからなくなったので、このページの目的を整理してみます。

コントリビューター向け目的
・PJSをアップデートするにあたり、何が根本にあるかを深堀したいときに参照するため
PJSユーザー向け目的
・PJSを理解するにあたり、どの理論のどのあたりを参照しておけば理解が深まるのかを知るため

ぐらいかなと思っていました。
これは菊地さんと認識合わせたいです。

> 「アジャイルソフトウェア開発宣言と12の原則」のうち、どの原則がPJSのどれに対応する、どれは違う、などは、メソッドのチーム内でも意見が別れるような気がします。

このどれになにが対応するかの作業自体を私がやったことないですが、それをいまから引用しているものから紐解いていった方が良いってことですかね。そしてメソッドがアップデートされるたびにその原典との比較などが行われるってことですよね。あんまり作業のイメージが沸いてないので教えてください。

> 個人的なリストになってしまうと、いいのか悪いのか判断がつかず、今後チームとしてのメンテが不能になってしまうと思いました。

これは何の良い悪いの判断を原典由来で行いたいということでしょうか。
大元にあるものを参照しながら経験則でこんな感じでやるとうまくいくねってものをまとめているものなので、そこまで原典にもとづいたメンテを私は想定してなかったです。というかあんまりできる気がしてないです。

例えばで記述してみますね。

アジェンダ の 完了の定義  の項目は スクラムの Difinition of Done と TOC の ODSC におけるサクセスクライテリアをみて、アジェンダには完了の定義があったほうがよいとおもって設定して実践してみたらうまくいったのでその項目をアジェンダの要素としておいてます。

みたいなことを書くことをイメージされてます？
そして完了の定義ってやっぱりいらないよねとかそういう話は実際にやってみてやっぱりいるよねいらないよね身たいな経験から来るんじゃないかなとおもいました。

運用のイメージが違うのかな。今日会話させてください。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
あとから振り替えられるよう、交通整理の結論だけ記録しておきますね。

このissueは、
https://github.com/copilot-jp/project-sprint/issues/59#issuecomment-650540587
までの内容で、”リファレンスページをまず立ち上げる”ことが完了したとして、クローズ。
で、この立ち上がったリファレンスページは、まずcode v1.0.0のリリース対象とします。
@motoi さんが作ってくれた https://github.com/copilot-jp/project-sprint/pull/73 がその内容なので、これが終了したらこっちも閉じましょう。

そのうえで、その内容をそこからどかこまで洗練されたものにするか、という議論は、 @motoi さんの立ててくれた #74 のほうで、引きつづき議論しましょう。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/pull/73
こちらにプルリクしました。これがマージされたらこのイシュー閉じます。

**Comment by motoi** [comment]
とおもったらレビュー終わってたのでクローズしますー。
