### ISSUE TITLE
トラックの概念の更新

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#62]
#43 の議論より。
トラックは"会議体"という言葉とはことなる、マイルストーンベースで定義されるものである。この"マイルストーンベース"という点がplug-inでしっかり表現されていないので、この点を修正。

=======================
そもそもトラックというのがわかりにくい概念という実感がある。

トラックは会議体という言葉で説明できるのではないか？

トラックは、マイルストーンによって定義されるもの。

会議体 => 印象としてはオーソライズするための形式的なものという語感をもってしまうのでは？

会議にかかわる人たちのことを呼ぶ名称はあるか？ => 会議体 ではなくて、チーム、グループ、マイルストーンごとのチーム、マイルストーン体、など

プロジェクトでよくあるのは、ワーキンググループ(WG) という言葉。
ただWGベースでトラックをつくるのではなく、トラックはマイルスストーンベースで作り、それに合わせて人をつけるべき。

結論）
・トラックの定義をアップデート。(Plug-inにて）
・会議体という言葉は使わない。

_Originally posted by @Satoshi-Matsumoto in https://github.com/copilot-jp/project-sprint/issues/43#issuecomment-638146908_

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
まず私が修正してご連絡します。

**Comment by Satoshi-Matsumoto** [comment]
最終的に別issueにするのが良いのかもしれませんが、関連して。
例えば複数のトラックが走っていた際に、トラック感をまたいで (関連して）ミーティング開催をする必要がある、となったときに、どのようにすればいいのか。
トラックの定義= マイルストーンベースのものになるので、本質的には関係ない気がするのですが、なんかケアが必要な気がします。

（課題意識をとりあえずメモしているので後からきれいにすると思います）

**Comment by Satoshi-Matsumoto** [comment]
このコメント
https://github.com/copilot-jp/project-sprint/issues/62#issuecomment-650954535
は #75 にて。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
修正しました。このissueでの議論と、Manualでも深まったトラックの概念を踏まえてより正確な表現にしています。

f384ea6d6f362880e40262e5b7eeb2656ad0bf78

トラックはマイルストーンベースで決定されるものであってチームに依存するものではない。またゴールを細かく細分化すればそれは別プロジェクトなのでここも修正。

確認  & 問題なければクローズお願いします。

cc @yoneyama-tomohiro

**Comment by motoi** [comment]
問題なっす！
