### ISSUE TITLE
スマホで見ると太文字の後に全角スペースが入っている

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#63]
![image](https://user-images.githubusercontent.com/680855/85271368-afd0d300-b4b5-11ea-95d2-c41021cf8312.png)
![image](https://user-images.githubusercontent.com/680855/85271391-b65f4a80-b4b5-11ea-9544-d47fa3727e77.png)
![image](https://user-images.githubusercontent.com/680855/85271400-b95a3b00-b4b5-11ea-8bcf-dc637ca1f97c.png)
![image](https://user-images.githubusercontent.com/680855/85271412-be1eef00-b4b5-11ea-9c25-c29cc915bd5d.png)
![image](https://user-images.githubusercontent.com/680855/85271429-c37c3980-b4b5-11ea-962f-283d866c1084.png)

**Comment by motoi** [comment]
mdの書き方なのかなーと思いつつアサイン

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なおしましたのでクローズしてしまいます。
8bd06c641839110311c0da4b74a6d667840ec4d5
cc1f50d44cf5e0d6aa93716bed07ed5e61f2ce4e
89a57bafabe46754f7215ea1c141113bda496367
9292b10a5372510923572ac32d2ed4641acd7911
b91ddb7a201d1b27dcce6824854a818ea2fb2abc
b090624af77bdf380363d9a1c7aa9ee2d84e65d8
4c80fc2f03e76572aaafe71de746627a79887ee1
