### ISSUE TITLE
Tips5の各種ロールの名称 / 位置づけ・役割更新

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#64]
スプリントマスター、プロセスアドミン、プログレスマネジメント、チームマネジメントについてもっといい呼び名がないか。

**Comment by kikuchiharuma** [comment]
ファシリテーター、モデレーター、アクセラレーター、コーディネーター、レコーダー、などミーティングロールは「-er」で統一されている。これはフラットで良い印象。

**Comment by kikuchiharuma** [comment]
ミーティングロールの各ロールの説明もアクションレベルで記述されていて、わかりやすい。みんなで持ち回りでやれそうな感じ。

**Comment by kikuchiharuma** [comment]
スプリントマスター、プロセスアドミン、プログレスマネジメント、チームマネジメントの説明は、リードする、サポートする、といった表現になっていて、具体的なアクションではない。ある達成に対して全面的な責任(と権限)を持っていそうな印象を、名称、説明からともに受けました。

ロールの定義が、複数人で担うことが可能で、チームメンバーが率先して引き受けることが推奨されるものであるなら、

- 達成に対する責任はロールではなくドメインとしてチームの共有する責任範囲としてあるべき(チームから委託される場合はあっても良いと思うが推奨はされるべきではない)
- 複数人で担うことが可能ということは、担う人による差異ができる限り小さくなるようなロールの範囲と内容をもつものであるべき(おそらくアクションのような具体的なものでなければ、差異が大きくなってしまうし、属人的な役割の存在を許してしまうと、ロールを区別して呼ぶ必要性自体を弱めてしまう)
- 率先してロールを引き受けるためには、チームメンバーのあいだでそのロールが機能するやり方やそのあと期待される効果について、認識がズレてはいけない。認識や期待において担う人を想起させたり、人によって自由度が大きすぎるロールの範囲や内容は避けるべき

というようなことが必要なのに、そう受け取りづらい、それと矛盾してそうな説明になっている、という問題なのかと思いました。

**Comment by kikuchiharuma** [comment]
その上で、既存のプラグインロールは

スプリントマスター: PJSをチームが理解し、実践し始める、実践し続けるために必要な知見を持ち込んだり、方法を提案する

プロセスアドミン: PJSのプロセス計画？を提案し、そこで定義されたプロセスが実行されるように支援したり、計画に変更があればそれを最新の状態に維持する

プログレスマネジメント: PJSのプログレス計画？を提案し、そこで定義されたASISTOBEをチームが理解できるように支援したり、成果物との対応を維持し、ASISTOBEを最新の状態に保つ

チームマネジメント: チーム内に発生するテンションが表現されチームで共有される機会がプロセス計画の中に組み込まれるよう提案し、チーミングドメインの状態を明確にしてチームに提示する

というようなものなのかな、と理解しました。

**Comment by kikuchiharuma** [comment]
そもそも各ロールが、ミーティングロールのようにもっと細分化される必要がある気がしますが、とりあえずネーミングとしては、

スプリントマスター -> PJSインストーラー / PJSマネージャー

プロセスアドミン -> プロセスハンドラ / プロセスマネージャー

プログレスマネジメント -> プログレスマネージャー

チームマネジメント -> チームマネージャー

のほうが交換可能で、マネージャーは何するの？と問いやすくなるように思いました。ベストではない気がしますけど。

PJSが始まったり進化するようにチームに説明する、チームが議論を始めるための仮のマイルストーンを置く、などがPJSインストーラー
PJSチェックリストのようなもので、PJS視点でチームを見てる、みたいな感じでしょうか。

各ドメインのマネージャーは、それぞれのドメインの状態を可視化したり、そこに違和感があれば上げてもらえるようにチームに促す
マイルストーン管理はプログレスマネージャー
振り返りの実施はチームマネージャー
ミーティングロールを決めるように促すのはプロセスマネージャー
など。

というようなイメージです。

**Comment by kikuchiharuma** [comment]
「プロジェクトマネージャー」が、ドメインごとのマネージャーに分解され、さらにもっと細かいロールに細分化されていく、みたいな感じなのかもしれないなあ、と思いました。今はミーティングロールしかないですけど。たくさんありそう。

**Comment by motoi** [comment]
いまのところぜんぜん自分がひらめかないので、ロールまとめシートをシンプルにして更新しやすくしたりアップデートしながら考えています。（進捗報告）

**Comment by motoi** [comment]
リードという言葉がよいかなとおもってだいぶつかって違和感なくなってきました。
PJSはコリーディングアプローチだし！

![image](https://user-images.githubusercontent.com/680855/97285991-4a875700-1886-11eb-9bdf-f1fe7d538090.png)
![image](https://user-images.githubusercontent.com/680855/97286031-570baf80-1886-11eb-861e-8f394f5e8f0e.png)
![image](https://user-images.githubusercontent.com/680855/97286091-6d197000-1886-11eb-9e81-8bba4834b2e5.png)

@kikuchiharuma イシューたててくれた菊地さんどうでしょう？

**Comment by kikuchiharuma** [comment]
@motoi 管理を想起させるマネージャーとかアドミンや、支配者と聞こえるマスターという名前に違和感があったので、リード、という言葉の方がずっとしっくりきますね。いいと思います。

**Comment by motoi** [comment]
じゃ、これでいこうとおもいます！
@Satoshi-Matsumoto さん
諸々への反映お願いします。

@yoneyama-tomohiro  さん
違和感があったら指摘くださいー。

**Comment by yoneyama-tomohiro** [comment]
@motoi 
違和感ありません。
ちなみに、「ミーティングロール」は「プロセスロール」の一部という位置付けですかね。

**Comment by Satoshi-Matsumoto** [comment]
CODEv2.0.0からプラグインの区分がなくなり、ここで議論されているロールは下記に集約されたのでこちらを更新します。
https://projectsprint.org/ja/code/tips/tips5.html

合わせてIssueタイトルを変更しました。

**Comment by KokoroKagawa** [comment]
@motoi 対応しましたのでご確認お願いします。
https://github.com/copilot-jp/project-sprint/compare/%2364

また、https://github.com/copilot-jp/project-sprint/issues/77#issuecomment-880548879 に従って
- Tips5: 実務で使いやすいロールの設定に、Project Sprint に必要なロールの図表を挿入
- Tips6: ロールシートの利用に、ロール記入シートの図表を挿入

をやりたいので、お手すきの際に画像挿入の手順を教えてください。

**Comment by motoi** [comment]
@KokoroKagawa
> https://github.com/copilot-jp/project-sprint/compare/%2364
よいとおもいました！

> Tips6: ロールシートの利用に、ロール記入シートの図表を挿入
これはアップデートしているところなのでいったんこの作図はなしでおねがいします。

画像挿入の手順は画像が入っているmdファイルを見てもらったほうがよいかもです。
一回GitHubデスクトップ見ながら会話しましょうか。サトマツさんに聞くことになるかもですが。
次の定例で！

**Comment by KokoroKagawa** [comment]
@motoi 
Tips5に図表を挿入しました。　c21bfdf
これで問題なければ、一旦v2.1.0にマージします。

Tips6への図表の挿入は、 #65 で対応します。
（ロール記入シートの中で、ファシリテーターの役割として「ミーティングの日程調整」を記載するイメージです。）

**Comment by motoi** [comment]
@KokoroKagawa コメントしました！

**Comment by KokoroKagawa** [comment]
@motoi 修正しました！図表のタイトルは全体通してマークダウン記述にします。
https://github.com/copilot-jp/project-sprint/commit/a41d0127b37eed513012d604880b0dc5e1e430a1

**Comment by motoi** [comment]
@KokoroKagawa 
よいとおもいました！

**Comment by KokoroKagawa** [comment]
v.2.1.0 にマージしたので閉じます。
