### ISSUE TITLE
ミーティングの日程調整はどのロールが担うか明確化

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#65]
ミーティングロールの中に、ミーティングの日程調整についての説明がない。

**Comment by kikuchiharuma** [comment]
ミーチティング外で仕事が発生しやすく、結構難しくて重要性の高い仕事。

**Comment by kikuchiharuma** [comment]
既存のミーティングロールの中では、コーディネーターが近そう。

**Comment by motoi** [comment]
私もコーディネーターのイメージです！が、ファシがやることが多いですね。なぜそういう印象かというと、テレカンになって、ファシとコーディネーターが同じ人がやることがめちゃ増えているからだとおもいます。

あと毎回会議の役割をローテーションしているとコーディネーターが変わる場合があるので隙間タスクはプロセスアドミンが引き取るケースが多い気もします。

**Comment by motoi** [comment]
コーディネーターのロールの再設定してこのチームで実験する。

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/97288183-dac69b80-1888-11eb-9e3a-3b863a8c34e6.png)
いったんこの方向で！

@Satoshi-Matsumoto @yoneyama-tomohiro 違和感ください！
まずは @yoneyama-tomohiro さんから！

**Comment by yoneyama-tomohiro** [comment]
@motoi 
簡単そうで、悩ましい。。

- MTGの「参加者」や「日程」を決定するのは、実質的には内容を理解している「プログレスリード」になるような気がしていて、コーディネーターがその役割を担ったとしても、結局プログレスリードに判断を仰ぐ形になりそうです。
- また、「プロセスリード」との関係はどうなるのだろう、、とも思いました。「ミーティング・アジェンダ管理」がありますが、「参加者」や「日程調整」は、「ミーティング管理」には含まれないということですよね。

一旦、 @Satoshi-Matsumoto にパス！

**Comment by KokoroKagawa** [comment]
ロール記入シートのアップデート待ち。アップデート後、Tips6へ挿入。
ロール記入シートの中で、ファシリテーターの役割として「ミーティングの日程調整」が記載されるイメージ。

**Comment by KokoroKagawa** [comment]
ミーティングにおいてはコーディネーターが日程調整を担うとして記述する。

**Comment by KokoroKagawa** [comment]
Frameworkの内容ではない。一旦Close。

▽参考資料
https://docs.google.com/presentation/d/1C0V7YJFiU70itwqEOp5rnd0LiVsFwtSU7SW0fw6FJbU/edit#slide=id.g1eda5d048e7_2_574
