### ISSUE TITLE
code英語版のバージョン管理方法策定

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#68]

**Comment by motoi** [comment]
菊地さんに差分管理の方法を相談する

**Comment by motoi** [comment]
こころさんに管理方法をコメントしてクローズしてもらう。wikiにも記載する。

**Comment by motoi** [comment]
@KokoroKagawa 英語版の管理方法がwikiにも記述されたらこのイシュークローズください。

**Comment by KokoroKagawa** [comment]
@motoi 記述済みなので閉じます。 
https://github.com/copilot-jp/project-sprint/wiki/Method-operation-rules/_edit
