### ISSUE TITLE
code v1.0.0以降のissueトリアージ / 優先順位付け方法の策定

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#69]
v1.0.0以降のバージョンについて、バージョン番号の定義はできているものの、issueの対応優先度の感が方などは定まっていないので、今後「これどうすんだっけ？」が増える気がしたため、どうしていくか議論してみたい

6/24時点の結論
1.0.0 -> 2.0.0みたいになるときは、なんらかのパラダイムシフトがあるはず。

1.X.0のXの部分は？優先順位づけをして修正対応していく必要がある。
- ドメインごと で分けて、状況ごとに"薄い"ところから修正していく
- basic > advance > plug-inで優先順位がある程度決まるはず

この2軸で優先順位決められるのでは？

issueを能動的に生み出すスキームも考えられるのでは？

**Comment by Satoshi-Matsumoto** [comment]
2020/8/4 暫定対応内容。このあたりもwikiにいれるか、など議論。

→ 1.0.1のブランチを切る（サトマツ）
→ 対応するマイルストーンなどをつくる（菊地）

プルリクのレビュアーをとにかく全員にしない
→ マージ先のメンテナーを最低限レビュアーに入れる

**Comment by motoi** [comment]
@Satoshi-Matsumoto これ最新ステータスにアップデートくださいー。私がよくわからなくなりました…。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
これがメソッドチームの11月 / 12月のマイルストーンになっている
> ②メソッドアップデートのフローがまわりはじめる
に相当するissueです。
projectsprint.orgとの対応でどのようなアップデートになるかは未定なのでまだマイルストーン定義なくて問題ないです。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 了解しました。アサイン戻します。

**Comment by Satoshi-Matsumoto** [comment]
issueでトラックする必要なし、ということでクローズします。
