### ISSUE TITLE
バージョン定義やissueのトリアージ方法の記載場所の検討

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#70]
vX.X.Xで記載されるバージョンの定義（下記）、

![CODEバージョン管理の考え方](https://user-images.githubusercontent.com/61894329/86010520-7caeb680-ba56-11ea-8216-87832c7852bd.PNG)

#69 #66 で話しているようなバージョニングのルールはどこかに記載すべき？
README?それとも、バージョニングの定義はREADMEで書かれても困るので、GithubのWikiとか？
そもそも書かない？

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん、
このissueについてご意見もらえないでしょうか？バージョン管理の考え方とかってこのリポジトリ / projectsprint.org上は見えないのですが、このどこかに残しておかないと今後わからなくなりそうだなというのが課題意識です。

で、issueは開いたり閉じたりある種フロー的な情報なので、ストックしたいなと思ったとに、直感的にはREADMEかWikiなのですが…あんまり外に出す必要がないということからするとWikiですかね？

**Comment by kikuchiharuma** [comment]
方針を知りたくなったときに参照できるところに置いておきたい、Readmeに入りきらない、ということですね。

このプロジェクトの方向性からすると、CODE、Manualのほかに、Contributionについてのドキュメントの一群があるのが良いんじゃないかと思いました。バージョニングについての考え方もその中に入るのではないかと。
Readmeはその入り口の案内になり、詳しくはContributionについての各ドキュメント見てね、という感じです。

みんな大好きKubernetes Documentationにもその章があります。
https://kubernetes.io/docs/contribute/

**Comment by motoi** [comment]
@Satoshi-Matsumoto これもマニュアル1.0のタイミングで対応してもよいんじゃない？と思ったので一応マイルストーンつけておきます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
マニュアルのマイルストーンとは別ですね。
いまマイルストーンには
- site
- CODE
- Manual
がありますがこれらのどれにも当てはまらないやつがまだあります。
本当はこれらの定義もしっかりする必要がありますが手が回ってなくmilestoneがundefinedだったりします。

これも11月12月のマイルストーンの

> ②メソッドアップデートのフローがまわりはじめる
> ③pjs.orgのサイトとしての完成度を上げる

このあたりにかけて進めるイメージを持っています。（というか、このあたりが整備できていない実感があってこれらをマイルストーンに入れる提案をしていたという背景です）

**Comment by Satoshi-Matsumoto** [comment]
というわけで管理方法含めこのissueはしばらくundefineのままとさせてください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 了解。引き続きお願いします。

**Comment by KokoroKagawa** [comment]
wikiを整理したので一旦closeとします。追加修正事項は随時対応。
外部向けには/releasemanagementを書きすすめていきます（#102）。
