### ISSUE TITLE
CODE v1.0.0のbranch/pull requestがmasterに対してbehind

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#72]
pr61/dev-code-v1.0.0がmasterに対してbehindになってしまっている(Site v1.0.0のぶん)

https://github.com/copilot-jp/project-sprint/pull/61
https://github.com/copilot-jp/project-sprint/tree/dev-code-v1.0.0

ので、解決お願いします！
新しくmasterからブランチを切っていただくのがいいかなと思います。

(v0.9.1のprができたら、既存のブランチのマージ先としてprにしたりできそうで、早くそれをやりたいなという気持ち)

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/pull/78
対応しました！確認いただいて、問題なさそうであればこのissueもクローズしちゃってくださいまし。

**Comment by kikuchiharuma** [comment]
あざす！
