### ISSUE TITLE
リファレンスページの調整

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#74]
@motoi ぼくの雛形があまり良くなかったかも知れないですが、ちょっとざっくりし過ぎてるかなあと思いました。「アジャイルソフトウェア開発宣言と12の原則」のうち、どの原則がPJSのどれに対応する、どれは違う、などは、メソッドのチーム内でも意見が別れるような気がします。個人的なリストになってしまうと、いいのか悪いのか判断がつかず、今後チームとしてのメンテが不能になってしまうと思いました。

項目はこのままでも、「PJSのこの部分の背景にこれがあります」という関係をそれぞれ明確にしてはどうでしょうか。もちろん全体的な在り方や構造を真似している、どこがとは言いづらい、というのはあってもいいと思うのですが、全てそうなってしまうのはまずいなあと。

_Originally posted by @kikuchiharuma in https://github.com/copilot-jp/project-sprint/issues/59#issuecomment-650682859_

**Comment by motoi** [comment]
@kikuchiharuma 
https://github.com/copilot-jp/project-sprint/issues/59#issuecomment-651691400
このイシューに私からも返信しておりますが、これに返信する形でもよいので、詳細教えてもらえればとおもいます。

その内容をもってどのマイルストーンで更新するかを @Satoshi-Matsumoto さんと決めていきたい。

**Comment by kikuchiharuma** [comment]
@motoi  Issue切り出しあざす！

現在のバージョンにどんな違和感を感じるか、ということですが…。
https://github.com/copilot-jp/project-sprint/pull/78/files#diff-b198f6479bb6340e48144fc8f095ebd4

リファレンスを、誰がどう読むかということだと思うんですが、例えばCODEを読み進める中で、「インクリメンタルにデリバリーする」「心理的安全性が必要」「テンションを出す」というだけで説明を終えているところがありますが、これがよくわからない、というときなどに参照してもらい、その表現の元になっている考え方や用語はこれですよ、と元ネタを伝えること、というのが主なものになるのではないかと思います。

元々その元ネタを知っている人であれば、あーあれのことね、という補助の情報になりますし、もし知らない人であれば、まだそれについて知らないけどテンションについてはホラクラシーを読めばわかりそう、という有用な情報になります。

そういう価値のあるリファレンスにしていくためには、直接的な関係(この用語・表現の元ネタはここにある)を表現する必要があります。この人が言っていたよ、とか、この本に載っているよ、とか。

その視点で見ると、今のリファレンスの書き方は、参考にしている、共感している、という表現になっていて、まず「あんた誰？」ということになってしまいそう。
もし書かれたプロセスとして理解可能だったとしても、上に書いたような有用な情報になるためには、全体として類似している、関係している、では曖昧すぎると思います。
この用語はこの用語と同じ、ほとんど同じだけどPJSでは少しだけ変えて使っている、くらいの精度が全体的に必要だと思いました。

**Comment by motoi** [comment]
@kikuchiharuma 了解しました。具体的な例で行きたいのですが、心理的安全性とか参照元とかもしっかり書いているつもりですがこれだと何が足りない感じでしょうか？

> 心理的安全性
> エイミー・エドモンドソンにより提唱された概念。チームのなかでどのような発言でも大丈夫だと信じられている環境をつくる重要性に共感している。
> Googleが行った生産性の高いチームの調査プロジェクトにより注目が集まった。
> https://www.jstor.org/stable/2666999
> Google re:Work https://rework.withgoogle.com/jp/guides/understanding-team-effectiveness/

**Comment by kikuchiharuma** [comment]
@motoi 参照先は明確ですが、重要性、共感している、という表現が曖昧なのでやめた方がいいと思いました。

重要性: 心理的安全性の価値について、まずは「チームの中でどのような発言でも大丈夫だと信じられている環境」がどうしてPJSにとって重要なのか、まで書けると思います。

共感している: この用語そのものの説明や位置づけについて、PJSの「心理的安全性」はGoogle re:Workの定義と同じである、言葉だけ借りていてPJSではこういうことを表現しようとしている、、など、用語の意味の理解を助ける説明が書けると思います。

リファレンス=PJSがreferしている、といったときに、論文を引用するときのマナーが(形式は簡単なものでもよいので)最低限意識されている必要があるのではないか、と思うのです。

**Comment by motoi** [comment]
@kikuchiharuma 
> リファレンス=PJSがreferしている、といったときに、論文を引用するときのマナーが(形式は簡単なものでもよいので)最低限意識されている必要があるのではないか、と思うのです。

これは全面的に同意です。このPJSのドキュメントにおける論文引用の記述方法を決めようということですよね？

**Comment by motoi** [comment]
> 重要性: 心理的安全性の価値について、まずは「チームの中でどのような発言でも大丈夫だと信じられている環境」がどうしてPJSにとって重要なのか、まで書けると思います。
> 共感している: この用語そのものの説明や位置づけについて、PJSの「心理的安全性」はGoogle re:Workの定義と同じである、言葉だけ借りていてPJSではこういうことを表現しようとしている、、など、用語の意味の理解を助ける説明が書けると思います。

ここまで書くとCODEの中身に大きくかかわり、と原典とのすごく厳密な対比が必要になるので、CODEの記述者ではない私だけでは書けないですね（この観点は以前にミーティングで「用語集」にするのか？という会話した記憶もありますが）

と、いま書きながら思ったのですが、菊地さんがいってるのは 注釈・アノテーションを書いてほしいということなのかとおもいました。
CODEのなかでわかりづらい単語に注釈を入れたいということであれば理解できます。
そしてそれは私が素材を用意しますが、記述はCODEのなかなので @Satoshi-Matsumoto さんに書いてもらったほうが良いとおもいました。

〇注釈・アノテーション 例
https://projectsprint.org/ja/practice/basic.html

> 場
> ここでいうところの場(ba)とはミーティングが行われるの物理的・心理的空間のことを指す。
> 
> 物理的には、プロジェクトスプリントの迅速な認識合わせを実現するために、前述の参加者が漏れなく参加でき、かつ、情報をリアルタイムに共有できる環境が整備されている必要がある。
> 
> またプロジェクトスプリントにおける意思決定は、メンバーの納得を伴うものである。このためには各メンバーが自律的に意見を発していることが不可欠となるが、これを保障するのが 心理的安全性 であり、これを保障できるような空間づくりが求められる。

この部分に「心理的安全性」という用語がそのまま使われているので、ここに注釈で用語の説明を挿入するイメージじゃないでしょうか。そこに参照元へのリンクがあってもよいかとおもいます。（意匠的にどのようにいれるのかは検討ですが）

でCODEと離れた、書籍であれば巻末の参考文献一覧的なものであるリファレンスページに書く内容としては、以下ぐらいでよいとおもいました。

〇参照元・参考文献一覧・リファレンス 例
心理的安全性
エイミー・エドモンドソンにより提唱された概念。Googleが行った生産性の高いチームの調査プロジェクトにより注目が集まった。
https://www.jstor.org/stable/2666999
Google re:Work https://rework.withgoogle.com/jp/guides/understanding-team-effectiveness/

**Comment by kikuchiharuma** [comment]
@motoi ありがとうございます、

> このPJSのドキュメントにおける論文引用の記述方法を決めようということですよね？

この通りです。
なのでリファレンスページがどんなページになると、

- PJSが外部のリソースから引用している事実や、その範囲を正確に表現できるか (内容の正しさ)
- 引用している原典とPJSの関係を正しく伝えられるか (参照元への誠実さ)
- CODEやManualを読む人が、外部のリソースを使ってPJSをより深く理解できるか (リファレンスページの有用性)

をよりよく達成できるか考えませんか、というIssueとして再定義できると良いなと思いました。

**Comment by kikuchiharuma** [comment]
@motoi 質問に質問で返すみたいになってしまいますが、今のリファレンスページを https://github.com/copilot-jp/project-sprint/issues/74#issuecomment-664371746 の視点でもっとよくできないか、という意味で、できそうなことはありますか？もしあまりないようなら、僕が変更案を書いて提案するのが良いかな、という気がしました。

提案いただいた内容については、方法の話なので、課題に共感していただけるか次第かなという気がしました。

**Comment by motoi** [comment]
@kikuchiharuma 
これちょっとテキストでの返信に限界を感じている（私の言語化能力だと解釈して整理するのに無限に時間がかかりそうという意味です）ので今日お話しさせてくださいー。

**Comment by motoi** [comment]
素材を出すフェーズから形を作るフェーズに変わる
・素材として定金はリファレンスページに提供しているものでいったんよい（素材をだす）
・サトマツ、菊地でアウトプットイメージをつくる（形をつくる）→菊地さん

背景の考え方を共有できないとCODEが理解されないのではないか
・CODEの厳密さも起因して、ネット上に置かれたときに厳密性が問われるのでそのレベルで書く

**Comment by motoi** [comment]
内容の理解ができたのでこのイシューはクローズ。
用語集めのイシューを定金が立てる。
