### ISSUE TITLE
トラック間の連絡MTGのようなものはどう扱えばいいか

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#75]
PJSでいうメソッドとプロダクトの意見交換会は、どのトラックにあるのか？という疑問から出発して、
よく考えていくと、トラックがひとつの場合も、外側の組織のミーティングに参加したり、共同の場をもったりするなあと気付きました。

独立したマイルストーンを持つ「自分の」タイムラインに、外部から影響を受ける、外部と連絡する、という場面があって、それがCODE上整理がないように思いました。
(自分の目標、自分たち、には整理があるけど、その外側についてあまり言及がない、ということなのかも)

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
うおぉ、まったく同じことを、ひっそりこっちに書いてました。
https://github.com/copilot-jp/project-sprint/issues/62#issuecomment-650954535

#62 は、あくまで、トラック = マイルストーンに紐づいた概念だよね、という話なので、↑の私のコメントは、こちらのissueで議論しましょう。

**Comment by kikuchiharuma** [comment]
ほんとだ！全く同じ論点ですね

**Comment by kikuchiharuma** [comment]
Generalおじさんをやっていると、個別のトラック内の役割とは別に、「つなぎ」みたいに呼ばれることが多くなり、それって何なんだろう？という気持ちになることが多いです。
ホラクラシーのリードリンク、レプリンク的なもの。

**Comment by motoi** [comment]
@kikuchiharuma 
このissueとコメントをよみましたが、論点が3つあると感じました。
> トラックがひとつの場合も、外側の組織のミーティングに参加したり、共同の場をもったりするなあ
の観点から
1. PJSで管理しているプロジェクトと外部のプロジェクトや組織とのかかわりをCODEで表現するか？

https://github.com/copilot-jp/project-sprint/issues/62#issuecomment-650954535 のサトマツコメントも含めた
> PJSでいうメソッドとプロダクトの意見交換会は、どのトラックにあるのか？という疑問
の観点から
2. 1つのプロジェクトのなかのトラック同士のMTGの存在はCODEでどこに位置付けるべきか？

> 個別のトラック内の役割とは別に、「つなぎ」みたいに呼ばれることが多くなり、それって何なんだろう？
の観点から
3. 各トラックを外部（同じプロジェクト内の別トラック or 外部のプロジェクト）とつなぐロールの定義がCODEに必要なのではないか？

この整理であっているのか、またどこから議論していったらこのイシューが解決しそうかを @kikuchiharuma  さんご意見くださいー。

**Comment by kikuchiharuma** [comment]
@motoi 整理あざす、

そうですね、議論の進め方としては、PJSの在り方に関わるところから考えていくのが良いかなと思っていて、1つめの論点とどう向き合うのか、が今後の議論を方向づけると思います。2はその派生(トラックひとつひとつは基本的にPJSプロジェクトの性質を引き継ぐため)、3は末端の問題(1、2が方向づけられていれば、人の動きにブレークダウンして名前をつけるだけ)かなと。

**Comment by kikuchiharuma** [comment]
ミーティングだったかプロジェクトだったか、「外」との関わりについて書かれた過去のPJS資料がひとつあって、どこにあるか探せば見つかると思うんですが、外部環境も動き続けているけど、それを仮に固定することで「内」の議論を高める、みたいなことが書かれていてなるほどなと思ったんです。外の環境は一度動かないものとして考えないと、パラメータが多すぎてミーティングやワークショップが捗らないと。

プロジェクトにも同じことが言える気がしていて、環境要因を仮に固定したときに、自分たちは何をするべきか、と考えると思うんです。

その場合に、

- 外からの情報を持ち帰る
- 自分たちの仮説や現在の状態を外の情報と付き合わせて評価する

などの仕事がプロジェクトが必要とするものとしてある気がしています。
「仮定」しなければいけないので、能動的な動きです。

ドメインを整理するために描いた
https://github.com/copilot-jp/project-sprint/blob/master/ja/images/essentials.png
この図も、内側だけ描いていますが、外部との関わりなく進むプロジェクトなんて本当にあるだろうか？という疑問が出てきます。
これは、「環境要因を固定」したときにいっとき可能になる視界でしかないのではないか。
プロジェクトが数ヶ月、1年と続いていく中では、環境要因を取り込んだりする仕組みを持っていないと、外部に対して没交渉になってしまうのではないか。
マイルストーンは内的動機だけでは成立せず、環境要因と付き合わせることによる外部との調整機会にもなっているべきなのではないか。
など。

というように考えていくと、PJSプロジェクト、または3つのドメインが外部とどのように関わるかについてCODEに記述が必要なのではないかと思いました。

**Comment by motoi** [comment]
@kikuchiharuma これですよねたぶん。
> ミーティングだったかプロジェクトだったか、「外」との関わりについて書かれた過去のPJS資料がひとつあって
![センスメイキング理論と外部内部の環境とカゴ球理論図解](https://user-images.githubusercontent.com/680855/87404061-9cb6ac00-c5f8-11ea-8f49-20385ec2d026.PNG)

**Comment by motoi** [comment]
> 1つめの論点とどう向き合うのか、が今後の議論を方向づけると思います。
ここから進めていくで了解です。

> 1. PJSで管理しているプロジェクトと外部のプロジェクトや組織とのかかわりをCODEで表現するか？
ここから行きます。表現するかしないかは追っての議論で外部とのかかわりについて。

> 外からの情報を持ち帰る
> 自分たちの仮説や現在の状態を外の情報と付き合わせて評価する

この話を今回参照している他のメソッドの事例で置き換えてみます。
アジャイルソフトウェア開発では、成果物を定期的に市場にリリースする、ということが外部とのコネクトになり、そこからフィードバックをもらっている、ということだとおもいます。

ということで、PJSではプロジェクトのマイルストーン（成果物）が外部とのコネクトの材料になると思っています。その成果物の定義を、できるだけ外部とのコネクトを意識するということがいったんCODEに書くべきことじゃないかなと今回整理していておもいました。じゃないと菊地さんの言われるように内向きだけで進めてしまうということになることもありうるとおもいます。
システム開発でもとにかくユーザーに使ってもらいましょうよ、みたいな会話をするように、PJSでも成果物をどんどん周りに共有してフィードバックもらいましょうよ、みたいなことが推奨される姿勢なんだなと思いました。

実際のプロジェクトでもとにかくアウトプットして顧客にぶつけてみるみたいなことを意識するように、何かしらCODEでそのあたりが書ければよいなーとおもいました。

菊地さんもマイルストーンと書かれていますが、3つのドメインでいうとプログレスが一番外部との関りに関与するんだろうなとおもいました。

@kikuchiharuma さんご意見ください！

**Comment by kikuchiharuma** [comment]
@motoi 確かに、そうですね。成果物を通して外部と通じる、というのはすごくアジャイル的な世界観かも。セオリーかプラクティスかはわからないですが、Essentialsにそういう記述があると良いなと思いました。

一方、マイルストーンや成果物も、実態としてはミーティングで扱われる必要があると思います。
成果物を評価する場がチームの外部の人立ち合いのもとで行われるミーティングとして現れるか、チームのメンバーが外部のミーティングで報告を行うか、どちらかが現実的に起こらないと「アウトプットを顧客にぶつける」の具体的な場面設定ができないように思います。
そのミーティングの位置づけか、外部に出席するメンバーのロール、いずれにしても「トラック」の外部と連携する具体的な方法についても記述が必要な気がしましたけど、どうでしょう。こちらは必ずしもEssentialsに含まれないと思いますが。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
トラック間のミーティングを調整するひとはプロセスでよい。
ミーティングが必要と気づくのは各トラックのマイルストーンを理解してテンションを挙げることができるプログレスの人になる。

ということで記述お願いします！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
05b642b3ba80aef4e254dfc15c0c78f8effbffe3
記述を加えました。追加箇所は流れ的にtips1でいいと思います。

ご確認のうえ問題なければクローズください。

cc @yoneyama-tomohiro

**Comment by motoi** [comment]
確認しました！
