### ISSUE TITLE
CODEにおけるFigureの置き所整理（文章中のどういう場所に図があるとうれしいかの整理）

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#77]
画像で表現すべき概念や整理その他を、ドキュメント体系がしっかりしたので、どこにどんな図があると嬉しいのか整理して描き進めたい。

**Comment by kikuchiharuma** [comment]
特に、v1.0.0の時点で足すものがあるか。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
すみません、課題感はなんとなくわかるものの、具体的なアクションとしてアサイン先をどうするか @motoi さんが難しくなってしまうと思うので、もう少し課題を具体化してもらって、次にどういうアクションに落ちるか、までひも解いてもらうことはできますか？

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto 絵を描けるところが(現状唯一図が入っている)理論編ベーシック以外にもたくさんありそうだと思いつつ、ドキュメント体系全体のなかで、どこにどんな図があるべきかの整理(誰か) -> それを書いてみる(菊地)という手順で進められるとありがたいです。どこにどんな図があると良さそうかの全体像を叩きを作ってみる、が次のステップかなと思いました。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
なるほどですね。であれば、
>どこにどんな図があるべきかの整理(誰か)
ここ、わたしでひきとりますよ！

**Comment by kikuchiharuma** [comment]
アザーっす！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
すみません、v1.0.0 のほかissueで文章構造や内容自体を進めていたらこちらのお願いをするのがどうしても後回しになってしまいました。v1.0.0に入れず、それ以降の対応にさせてもらえればと思います。

**Comment by motoi** [comment]
コメントありました
↓
ターゲットによると思うのですが、全体的にもじもじしいので、ちょっとでもイラストが入ってたりするといいのかもなあと思ったりしました。
内容よりも先に文字と文字がすごいつまってるなと思ってしまったというか……。
デリバリー平林

**Comment by Satoshi-Matsumoto** [comment]
#164 でCODEの図についても言及があったのでこちらに転載します

@yoneyama-tomohiro さんより

> https://projectsprint.org/ja/code/theory/basic.html
> ・追加ではありませんが、一番下の概念図は一番上の方に置いた方が良いかと思いました（図の存在に気づかないため）
> ・3つのドメインの関係図
> 
> https://projectsprint.org/ja/code/practice/basic.html
> ・「具体的に必要なロール」は図表にしたい（すでにスライドで作っているもので良い）
> ・アジェンダの構成要素は、表にしたほうがもう少し読みやすくなる
> ・「継続的改善アプローチ」における「ふりかえり」と「テンション」の関係図（関係が理解できないと、どちらをどう実施したら良いか分かりにくいため）

@motoi さんより

> https://projectsprint.org/ja/code/practice/basic.html
> ミーティング環境は図示したほうが分かりやすいのではないかなと思いました。
> 
> 継続的改善アプローチを定期的に行う必要がある理由でよく話すものを図で入れてもよいかとおもいました。
> そのためにはプロジェクトの性質を理解する必要があって。理解のためには比較表が重要。
> image
> プロジェクトにおけるプロセスがいつ始まっていつ終わるかがわからないので定期的に行う必要がある。
> image
> この辺があると定期的に振り返りする必要が分かりやすいかなと。
> 
> https://projectsprint.org/ja/code/practice/advance.html
> 発散収束共有の部分は絵の方が分かりやすいと思いました。
> image

imageは[元コメント](https://github.com/copilot-jp/project-sprint/issues/164#issuecomment-699288660)を参照。

**Comment by motoi** [comment]
@Satoshi-Matsumoto さんがどこにどんな図があればよいのか？について、引き続きまとめる、ということでよい？

**Comment by Satoshi-Matsumoto** [comment]
@motoi あっていますが次回のManual / CODEのアップデートに関係ない箇所は優先順位下げさせてください。

**Comment by KokoroKagawa** [comment]
まずは@yoneyama-tomohiro さんからのコメントへの対応方針、整理させてください。

>https://projectsprint.org/ja/code/theory/basic.html
>・追加ではありませんが、一番下の概念図は一番上の方に置いた方が良いかと思いました（図の存在に気づかないため）

→こちら対応済みとの認識です。
https://projectsprint.org/ja/code/essentials.html
>・3つのドメインの関係図

→こちらに関しても、↑のURL内の概念図で問題ないように思うのですが、さらに詳細な関係図があったほうが良いとお考えでしょうか？
>https://projectsprint.org/ja/code/practice/basic.html
・「具体的に必要なロール」は図表にしたい（すでにスライドで作っているもので良い）

→以下で違和感ないでしょうか？
- [Tips5: 実務で使いやすいロールの設定](https://projectsprint.org/ja/code/tips/tips5.html)に、[Project Sprint に必要なロール
](https://docs.google.com/presentation/d/1bmweV5LUZQG2gcn1HJSGYxHmMeGipZA1ZsXMf2RmOTo/edit#slide=id.gd0c86d8f0b_0_0)の図表を挿入
- [Tips6: ロールシートの利用](https://projectsprint.org/ja/code/tips/tips6.html)に、[ロール記入シート](https://docs.google.com/presentation/d/1bmweV5LUZQG2gcn1HJSGYxHmMeGipZA1ZsXMf2RmOTo/edit#slide=id.g9b3dad2dbd_1_2)の図表を挿入

> ・アジェンダの構成要素は、表にしたほうがもう少し読みやすくなる

→ アジェンダの構成要素が固まり切っていないので、対応を #83 にマージしました。
> ・「継続的改善アプローチ」における「ふりかえり」と「テンション」の関係図（関係が理解できないと、どちらをどう実施したら良いか分かりにくいため）

→ #239 と合わせて対応しますが、以下のスライドをベースに(?)、米山さんに関係図を作っていただくかたちでよいでしょうか？もしくは菊地さんに依頼しますか？
https://docs.google.com/presentation/d/1N06GI7DGXi5iJUyVCae4YDZHxBmNmlH3XJW6Qita-N8/edit#slide=id.gd9bae1c266_0_0

**Comment by motoi** [comment]
@KokoroKagawa さん判断で決定し定金が確認して更新。

> ・「継続的改善アプローチ」における「ふりかえり」と「テンション」の関係図（関係が理解できないと、どちらをどう実施したら良いか分かりにくいため）

については米山さんに戻す別イシューを立てる

**Comment by KokoroKagawa** [comment]
対応が必要なもの
・「具体的に必要なロール」は図表にしたい（すでにスライドで作っているもので良い）
こちらは #64 で対応します。
・「継続的改善アプローチ」における「ふりかえり」と「テンション」の関係図
こちらは #283 として新しくIssueを立て、 @yoneyama-tomohiro さんにアサインさせていただきました。

続いて、 @motoi さんからのコメントに対応していきます。
imageは[元コメント](https://github.com/copilot-jp/project-sprint/issues/164#issuecomment-699288660)を参照。

>https://projectsprint.org/ja/code/practice/basic.html
>ミーティング環境は図示したほうが分かりやすいのではないかなと思いました。
>
>継続的改善アプローチを定期的に行う必要がある理由でよく話すものを図で入れてもよいかとおもいました。
>そのためにはプロジェクトの性質を理解する必要があって。理解のためには比較表が重要。
>image
>プロジェクトにおけるプロセスがいつ始まっていつ終わるかがわからないので定期的に行う必要がある。
>image
>この辺があると定期的に振り返りする必要が分かりやすいかなと。

→対応しました。 b189022 

>https://projectsprint.org/ja/code/practice/advance.html
>発散収束共有の部分は絵の方が分かりやすいと思いました。
>image

→対応しました。 289db8d

@motoi さん、ご確認お願いします！

**Comment by motoi** [comment]
@KokoroKagawa さんそれぞれのブランチにコメントしてみましたー。

**Comment by KokoroKagawa** [comment]
@motoi さん
対応しました。　https://github.com/copilot-jp/project-sprint/commit/1578c9e131cbd217ed7cbb75b3bcc9ac4452375b

※「それぞれのブランチ」とありましたが、 289db8d にはコメントが見当たらず、問題なしですかね、念のため。

**Comment by motoi** [comment]
@KokoroKagawa コメント残ってないけど今見直したら大丈夫だとおもいました。
ということで良いと思いますー。イシューのクローズについてはおまかせします！

**Comment by KokoroKagawa** [comment]
v.2.1.0にマージしたので閉じます。
