### ISSUE TITLE
projectsprint.orgのサイト上で、CODEが誰がどういうために読むものなのか、がわかるようにする

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#79]
projectsprint.org 上でドキュメントの位置づけ / 対象読者 / 目的がわかるようにする。

https://projectsprint.org/
に記載する、または
https://projectsprint.org/ja
など。

**Comment by Satoshi-Matsumoto** [comment]
修正進めています。

まずこのissue解決するために、
https://projectsprint.org/
と
https://projectsprint.org/ja
の記載内容の整理が必要だと思ったので、

https://github.com/copilot-jp/project-sprint/commit/4028e0404cbbf412c99f84614a14e272920e3c3b

で修正しました。/indexはPJSとは何かの端的な説明、ドキュメント群へのリンク、リリースノートへのリンク、SGMへのリンク。

/ja/indexは、
CODEの簡単な説明と、それぞれのドキュメントへのリンク、になります。
https://github.com/copilot-jp/project-sprint/issues/45
で話しているディレクトリ構造でいくとすると、このページに、マニュアルの簡単な説明と、それぞれのドキュメントへのリンクが作られることになると思います。

まずこの修正について、セマンティックおじさん @kikuchiharuma さん、どうでしょう？

それがOKであれば、
https://github.com/copilot-jp/project-sprint/commit/78bc3f2f2d67b0a0b729d8ae50833dbe92102689
で書いているような実際の対象読者の議論をしたいです。

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto とてもセマンティックだと思います！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
ありがとうございます！

続いて

> それがOKであれば、
> 78bc3f2
> で書いているような実際の対象読者の議論をしたいです。

の議論に移ります。

@motoi 
CODEの対象読者ですが、いまいま下記のように書いてみています。
> 対象読者：プロジェクトスプリントの厳密な定義について、詳細に理解したい人

まとめちゃうとすごいシンプルになるなあ…という印象なんですが、ほかにこういう人に読んでもらうものだと思っていた、みたいなイメージとか、この表現への違和感とか、ありますか？

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
今よく話題に出るのは、
PJS.orgにアクセスしたときに、どういうステータスのひとがどういうときに読むものなのかがわからない
です。

単体だと説明してもわかりづらいので、比較としていま考えている3つのドキュメント体系をかけばよいとおもいました。それでCODEはこの位置づけなんだよ、が表現できればよいんじゃないかとおもいました。

サトマツさんが整理してくれた文章群の使われ方を並べてかけばわかりやすいんじゎないかしら。こんな感じ？


1. CODE
対象者 
プロジェクトスプリントを深く理解しているひと

どういうときに読むか
定義を改めて確認したいとき


2. チュートリアル
対象者
プロジェクトスプリントの概要は理解できているひと

どういうときに読むか
プロジェクトスプリントを深く理解したいとき


3. 導入トレーニング
対象者
これからスプリントマスターを担当する人

どういうときに読むか
これからチームにプロジェクトスプリントを導入するとき

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
コメントありがとうございます。

以前整理したのはこの辺なのですが
![image](https://user-images.githubusercontent.com/61894329/88471163-addcb280-cf40-11ea-90a1-fd9a75667244.png)
![image](https://user-images.githubusercontent.com/61894329/88471168-c64ccd00-cf40-11ea-9370-015bf5995b9d.png)

トレーニング資料は公開の前提がないのでprojectsprint.orgに載せないほうがいいと思います。
また、チュートリアルはこれ単体で完結し、それだけで読み始めても理解できるものを目指すので、対象者のイメージはちょっとずれているかなと思いました。
> 対象者
> プロジェクトスプリントの概要は理解できているひと

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
で、下記の修正を加えてみました。
217fa6de17144b4225c0de8325ebd0f039d09a7c
d6837205364d43cf2ca872ff6c3b13c59d9259f5
dbc0b8d924ca622a7a3fd2b383c1a1f9ccc8e576
d294bf53e5a8430884b2f972cf94e61b17e1be9d

チュートリアルについてはv1.0.0段階では出来上がっていないので、「作成中」と書くしかありませんが、それでよいかどうかですね。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
> トレーニング資料は公開の前提がないのでprojectsprint.orgに載せないほうがいいと思います。
あ、失礼しました。記憶違ってた。

> チュートリアルについてはv1.0.0段階では出来上がっていないので、「作成中」と書くしかありませんが、それでよいかどうかですね。
私はこれがあったほうがCODEの対象者が明確になってよいとおもいますので、作成中でよいと思いました！
あとドキュメントは2種類あるんだって雰囲気が伝わるような修正イメージをブランチに切ってやってみます。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/pull/98
こんな感じでやってみました！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
コメント & 修正案ありがとうございます。
表は情報の整理という意味ではよいと思うのですが、ページに来た人からするといきなり表がでてくるとちょっと驚くんじゃないかなとおもいました。

なので、元文章はそのままで、下に表をいれる。
で、表に入れる情報を絞ればよいと思います。

もらったプルリクはマージのうえこちらで修正します。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
06b53a91a21b603616e1752f9822d08b11926dd3
こんな感じでしょうか。

**Comment by motoi** [comment]
いいとおもいました！
