### ISSUE TITLE
会議が定例であることについての記述の充実

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#80]
@motoi さんより。

定例会議についてはv0.9.0時点で、実践編ベーシックの
https://projectsprint.org/ja/practice/basic.html
時間 の項目以下に書いているが、実際にProject Sprintをやろうとするとき / 説明するときの温度感と記述内容の厚さにギャップがあるので、これを埋めたい。

**Comment by motoi** [comment]
定期性、定例ミーティングが重要となる点を箇条書きしてみます。（いま書いてもらっているものも含め書いてみます）
いかがでしょう？！

- 社会や組織がうねっているなかで、定期的にあつまり、みんなで差分を吸収することで、変化をキャッチアップでき、プロジェクトの目的やマイルストーンをみんなで合意して変化させることができる。
→ センスメイキング理論でいうとみんなの多義性を定期的にミーティングで絞り込む感じ。

- 業務のリズムをつくりやすいのでタスクが消化しやすくなる。
→ 毎週月曜日はこのミーティングがあるのでこういう作業時間を確保しておこう、など。

- 同じ曜日時間に開催されることで、他のチームの人が共有のために覗きに来やすくなるし、スポットで必要になったスペシャリストなどの予定も調整しやすくなる。
→スクラムのデイリースタンドアップも似たような考え方だったはず

- 社内外の多様なメンバーが参加するため、ミーティングのスケジュール調整コストが高くなるため、あらかじめ抑えておく方が効率がよい。
→ また都度ミーティングを調整しているとミーティング開催が遅くなり、集まって外部環境をいったん固定して一気に認識合わせをして大きな意思決定をするというタイミングが遅れる。

- 定期的なプロジェクトの記録になる。
→ 振り返りのときには参照しやすいログになる。またベロシティ的なものを計測したい場合は、タスクが消化される定期的な期間として、活動の勢いの計測がしやすくなる。
→ 他のメンバーが参加した時に過去の情報を一気に見るよりは、定期的に出力されたものをフローに合わせてみるとで把握しやすくなる
→ その他のプロジェクトがこのようにすすんだのだという行動のひな型にしやすくなる

- 定期的に期間を切るほうがタスクの粒度を作りやすい。
→ 1週間でできること、という考え方が定着することで、これぐらいだったらできるかな、という予測がしやすくなる。
→ アウトプットを確実につくることで確度の高いアジェンダが出やすくなる。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
まずManualのTipsのかたちで整理しました。(Tutorialからは外だし）
e96228d450bfc50f8f0ac0f2efd77e1ab52aaecf

一点だけ、ベロシティの記述は入れていません。タスクの消化率でスピードをはかる的なアプローチはこれまで議論していませんが、PJSで必要かというと若干腑に落ちなかったため。

まずはManualの方をアップデートして、そのあとCODEに必要な部分を反映します。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/2a30dbce651ff4d9c46b6edc406347450e192b79
順番だけいれかえました。問題なければクローズで！

**Comment by Satoshi-Matsumoto** [comment]
@motoi たしかに、この順番のほうが自然ですね。ありがとうございます。
このissueは閉じつつ、この内容をCODEに反映するためのissueを新しく立てましたので、そちらも進めます。
https://github.com/copilot-jp/project-sprint/issues/190
