### ISSUE TITLE
実践編ベーシックに書くべきアジェンダの記載内容の見直し

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#84]
@kikuchiharuma さんより。

実践編ベーシックのプロセスに書かれているコンテクストの理解 / 完了時の理解の話は、アドバンスではないか？

むしろ、アジェンダには
- プログレスのためのアジェンダ 
- チーミングのためのアジェンダ
- プロセスのためのアジェンダ
といった種類のものがあるはずで、これをベーシックでは書くべきではないか。

**Comment by motoi** [comment]
これいったん @Satoshi-Matsumoto さんの方で書けそうなら進めてくださいー。
もうちょっとイシューを深堀してよ…ということであれば菊地さんに、ネタくれよ…であれば定金にアサインつけてください！

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん、CODE v2.0.0を踏まえて、ドキュメント構造が変わっているので、アドバンスに書くかどうか、などは改めて検討したいのですが、まず、

> - プログレスのためのアジェンダ
> - チーミングのためのアジェンダ
> - プロセスのためのアジェンダ

この分類の必要性について議論したいです。 @motoi さんと、あるいみ当たり前にこの分類はあるので、明文化しなくてもいいのでは？という話になってますが、いかがでしょう？

**Comment by KokoroKagawa** [comment]
ドキュメント体系の変更によりclose
