### ISSUE TITLE
成功指標についての記載

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#85]
@kikuchiharuma さんより。実践編アドバンスにある成功指標の記述のうち、「プロジェクトのスプリントの成功指標」（＝「プログレスの成功指標」の手前まで）は、共通部分。「プログレスの成功指標」と、「チーミングの成功指標」は、それぞれ、プログレス編 / チーミング編に入る内容ではないか。

> プロジェクトスプリントの成功指標
> プロジェクトスプリントは、
> 
> プロジェクトのゴールが達成されている状態
> 理想的なチームが形成されている状態
> を目指すメソドロジーである。
> 
> したがって、プロジェクトスプリントが成功しているかどうかは、これらがそれぞれ実現しているか(プログレスの成功 と チーミングの成功)、という観点で評価することができる。
> 
> ここで、いずれの成功についても、絶対的に到達すべき状態がないものであることに注意しなければならない。 プロジェクトのゴールは変化しうるものであり、また何をもって理想的なチームとするかはプロジェクトの規模や時間軸などに依存する。
> 
> 一方、プロジェクトスプリントが正しく導入・運営されていれば、それはプログレスの成功とチーミングの成功がもたらされることを意味する。 そのため、プロジェクトスプリント自体の活発さ自体を成功指標とみなすことができる。
> 
> プログレスの成功指標
> プログレスの成功指標は次の2つである。
> 
> プログレスに関わるToDoがリストアップされ、消化されているか、
> ミーティングにおいてプログレスに関わるアジェンダが多くリストアップされ、消化されているか
> チーミングの成功指標
> チーミングの成功指標は次の2つである。
> 
> チーミングに関わるタスクがリストアップされ、消化されているか、
> ミーティングにおいてチーミングに関わるアジェンダが多くリストアップされ、消化されているか

**Comment by Satoshi-Matsumoto** [comment]
併せて、共通部分として残りそうな部分が、実践編アドバンスでいいのか？も検討。共通部分が実践編ベーシックで、より発展的な内容として、プログレスの成功指標 / チーミングの成功指標は実践編アドバンスなのでは？

**Comment by Satoshi-Matsumoto** [comment]
#240 の議論の後にあらためて検討。成功指標自体の再検討をして、そのあと、入れるべき場所を検討。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/249
こちらで議論するのでクローズ
