### ISSUE TITLE
プロセスにおける記述の充実（ミーティングとアジェンダ以外の内容がないのか）

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#86]
@kikuchiharuma さんより。
code v0.9.0の理論編アドバンスには、次のような記述しかない。例えば理論編ベーシックに書いているようなほかの活動との接続や、ミーティングのあとに生まれた作業の実行をどう進行するか、など、書けることがあるのではないか？

> ミーティング
> ミーティングの意義
> プロジェクトスプリントにおけるミーティングとは、チームメンバー全員が空間や時間を共有する機会のことである。 チームメンバーは、ミーティングの場で全員でアジェンダを議論する。これによって、個々人中にとどまっている情報を一斉に共有することができ、各メンバーはこのプロセスに参加するだけでプロジェクトの状況や個々人の思っていることについて自然と認識を合わせることができる。すなわち、チームメンバーの 素早く効率的な認識合わせと、納得を伴う意思決定 を実現できるのである。
> 
> アジェンダ
> アジェンダの意義
> アジェンダ　とは、個々人のアクティビティの結果（アウトプットとテンション）が、チームメンバーと共有されるために明文化されたものである。ある成果やテンションは、アジェンダとなってはじめて、チームメンバー全員から明示的に認識されることが可能になる。

**Comment by motoi** [comment]
@Satoshi-Matsumoto これは一回書き始めてもらって足りないなーとか質問があったら定金に連絡してもらう、かなーとおもいましたがどうでしょう？！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @yoneyama-tomohiro

このissueですが、

これまでCODEではプロセスについて
- ミーティング
- アジェンダ
の2要素でしか語っていませんでした。

一方Manualを書いていて思ったのは、ここで書こうとしているのはまさしくプロセスなので、
ミーティングとは何か、アジェンダとは何か、というところだけではなく、「進行の方法」を書かなければいけないということです。いまCODEはこの目線がないので、「ほかのミーティングとの接続」とかが若干座りの悪い形で記載されているのかなと。

進行方法の書き方はManualで書いた下記の考え方がしっくりきているので、
- ミーティングの設計
- ミーティングの実行
 - ミーティングの準備
 - ミーティングの開催
　　- 序盤 / 中盤 / 終盤
- ミーティングを超えた継続的改善アプローチ

これに合わせて構成を変更しました。

27334e17b7652fafe6178bbfe1a81fe5ac167dd3
5551c70b8f1d398dae1038d3220093b0209a2e07
3b117bff952ce2e74901fa87680c8130e2f1f67c

**Comment by Satoshi-Matsumoto** [comment]
@motoi まずこの構成変更についてご確認ください。
かえってわかりにくい、とかがない限り、この構成で書いていってしまい、必要な修正を加えていきます。

CODE1.1.0に含めようと思っている↓のissueたちも、構成変更後に更新してしまったほうがいいので、まずは構成変更について確認したいです。
https://github.com/copilot-jp/project-sprint/issues/182
https://github.com/copilot-jp/project-sprint/issues/190
https://github.com/copilot-jp/project-sprint/issues/180
https://github.com/copilot-jp/project-sprint/issues/181
https://github.com/copilot-jp/project-sprint/issues/183
https://github.com/copilot-jp/project-sprint/issues/184

**Comment by yoneyama-tomohiro** [comment]
「ミーティング終了後」があっても良いかも。
たとえば、こんな話。
https://docs.google.com/presentation/d/1dQgbxB6_0kosazzgfk0Gmoa8c7dInfOy_NvZejfpneo/edit#slide=id.g83fa5a3645_0_79

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
構造は理解したので継続してください！

**Comment by Satoshi-Matsumoto** [comment]
@motoi @yoneyama-tomohiro 
構造は決定したのでいったんこのissueの修正はここまでとします。

https://github.com/copilot-jp/project-sprint/issues/86#issuecomment-722222451
のミーティング終了後の話は別issueをたて、次回マイルストーンでの対応にさせてください。

@yoneyama-tomohiro さん、別issueをたててください。修正先のドキュメント、修正内容のイメージがあればそれも記載しておいてください。

@motoi ↑のissueが立ったのち、進め方確認してもらったら、このissueは閉じていいので閉じてしまってください。

**Comment by yoneyama-tomohiro** [comment]
↑のとおり、取り急ぎ、別イシューを起こしました。
https://github.com/copilot-jp/project-sprint/issues/208

**Comment by motoi** [comment]
@yoneyama-tomohiro さん イシュー確認しました。わかりやすいとおもいました。
@Satoshi-Matsumoto さん イシュー問題なかったのでクローズしますー。
