### ISSUE TITLE
"タスク"という言葉の意味の定義 (または、定義する必要がないかの決定）

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#87]
@motoi さんより。
タスクという言葉に何らかの意味や定義があるか。どのような意味で使っているか。

例えば「ミーティングが終わったあとにタスクを設定する必要がある」というようなことをCODEのどこかで記述したいが、この時の記述はタスクでいいのか。

**Comment by Satoshi-Matsumoto** [comment]
@Satoshi-Matsumoto 補足
似た言葉として、TODO や 実践、実行、実作業など。

**Comment by Satoshi-Matsumoto** [comment]
まず #41 のほうで、「実践」であるとか「最適化」であるとかの言葉の意味を整理します。
そのあとこちらに帰ってきます。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
このissueにまつわる修正を行いました。

まず前提ですが、これまでに出てきたややこしい言葉として
- ToDo
- タスク
- 作業
- 実行
- 実践
- 実作業
などがありました。これらを整理してCODE上の不整合をなくすのが今回のIssueの目的です。

このうち、「実行」「実践」「実作業」については、 #41 で整理した通りで、
実行 -> プロジェクトの推進に直接寄与する作業
実践 -> 固有名詞としての意味は持たない。また、「実践編」「理論編」というCODEの体系で使われている名称とややこしいのでできるだけ使わない
実作業 -> 新しく定義された「実行」で言葉を統一。ややこしいので、今後使わない
となりました。

残りの「ToDo」「タスク」「作業」といった内容ですが、

まず「作業」についてはいまいま特に固有の用語としての意味を持たせておらず、単に"やること"くらいな意味で使っています。これはとくに固有名詞と勘違いする人もいないと思いますし、このままでいいと思います。

次に「ToDo」と「タスク」ですが、これはどちらかに統一して、"個人が割り当てられた、何かしらの作業"という意味で使うのが良いと思いました。これまで混在して書いてしまっていたので、今回「ToDo」に統一した修正を加えてみましたが、あまり違和感ありませんでした。（下記のコミット）

https://github.com/copilot-jp/project-sprint/commit/fd906049469d2104a6adea9512f7afde322b3db0

用例）
- 実行のためのToDo
- 最適化のためのToDo
- ミーティングの後にToDoを設定する
など。

どうでしょう？違和感なく使えそうか確認ください。

ちなみに下記のポイントは、
> 例えば「ミーティングが終わったあとにタスクを設定する必要がある」というようなことをCODEのどこかで記述したいが、この時の記述はタスクでいいのか。

実践編ベーシックに次のような記述がすでにあって、今回の修正上ToDoのままでいいのじゃないか、とおもいます。
```
#### 各ミーティングにおける仕組み
  - **ToDo確認**:ミーティングを受けて生まれたToDoとその担当者を確認すること。
```

**Comment by motoi** [comment]
> 実行 -> プロジェクトの推進に直接寄与する作業
> 実践 -> 固有名詞としての意味は持たない。また、「実践編」「理論編」というCODEの体系で使われている名称とややこしいのでできるだけ使わない
> 実作業 -> 新しく定義された「実行」で言葉を統一。ややこしいので、今後使わない

了解した！

**Comment by motoi** [comment]
いままとめてくれているのをみていると私も決めなはなしだと思い始めてきました。
そもそもタスクとTo Do, to-doって何が違うのかと思ってまずタスク管理アプリのメジャーどころでどのように使われているかをいくつか見てみました。

Asana, Google Tasks, Todoist をみても「To Do」という言葉を使わず「タスク」という言葉を使うようになっている。使っていたとしても「To Doリスト」という言葉で使っている。
To Doは英語の辞書で検索してみてもあんまりワンワードでは登録されていない（to-do list ならでてくる）
to-doは別の意味があるようで、騒ぐみたいな意味があり、同義語にfussとかの言葉が出てくるようなニュアンスなんだろうなという感じ。

ということで「タスク」の方が単語として日本語として使われている感じがするのでタスクで統一でよいかなとおもいました。
調べてもわからなかったけど、私の仮説では to-do list を日本人は ToDo と略して使っているだけなんじゃないか説が浮上しています。英語の辞書に出てこないので。。そして、英語のビジネス的な慣用句で things to do的なニュアンスとか to do list を to do と言ってる感じがします。

また業務の粒としては以下の関係かなとおもいました。
タスク ＞ to do list 

英語担当のサトマツさん的に英語の to do のニュアンスはどうでしょう。違和感ありますかね。

ということで結論
"個人が割り当てられた、何かしらの作業"という意味であれば「タスク」の統一でよいんじゃないかなと思いました。

もっと細かい、例えばMTGが終わったあとに出される割とアクショナブルな細かめ洗い出されたやるべきことは「To Do リスト」と呼ぶのはありかもしれません。

https://github.com/copilot-jp/project-sprint/commit/fd906049469d2104a6adea9512f7afde322b3db0
この今回の修正範囲は「タスク」でよいとおもいました。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

単純にToDoリストとかToDo確認とは言うけどタスクリストとかタスク確認とは言わないなー、というのが今回ToDoにそろえてる理由で、ほかのこだわりはあんまりないです。
> Asana, Google Tasks, Todoist をみても「To Do」という言葉を使わず「タスク」という言葉を使うようになっている。使っていたとしても「To Doリスト」という言葉で使っている。
むしろこれが説得力があるというか、ほかのメインストリームにそろえることが大事だと思いました。

というわけで、タスクで統一しました。
9a58e24e5d63774bb397115c59bfa0fb8a408563

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
ここまでの議論ご参照いただき、

> ToDo
> タスク
> 作業
> 実行
> 実践
> 実作業
> などがありました。これらを整理してCODE上の不整合をなくすのが今回のIssueの目的です。
> 

この観点で違和感ないか、レビューもらえますでしょうか？
@motoi さんには確認してもらっているので @kikuchiharuma さんがOKであればクローズです。

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto 個人的にはToDoのほうが即物的な響きで、ToBeと綺麗に対照的で、良いなと感じました。でもまずはいろいろ言葉があったところ「実行」「タスク」に統一されたので良かった、ということでこのIssueは終わって良いんじゃないでしょうか。

**Comment by motoi** [comment]
ToDo（という細かいアクションになるような即物的なもの）が必要になったら別イシューをたてるが、いったんはタスク統一でこのイシューは終了。
