### ISSUE TITLE
振り返りの種類や定義の深堀

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#89]
CODE v0.9.0 実践編ベーシックでは、振り返りのことを下記のように定義している。

> 複数回以上のミーティングを横断する仕組み:振り返り
> 振り返り とは、それまでのプロジェクトの進め方についてレビューし、改善のための実践や最適化を行うことができないか話し合うための仕組みである。 振り返りは各ミーティングごとに実施しても良いし、マイルストーン終了のタイミングなど、複数回以上のミーティングを経て実施してもよい。ただし、特定のタイミングで振り返りは必ず実施する必要がある。
> この仕組みを実施する責任はプロセスアドミンにある。
> 

目的に応じて振り返りにもいろいろな種類があるのではないか？
定期の間隔でやる振り返り や、特定のフェーズ終了時（マイルストーン終了時）にやる振り返りなど、複数の振り返りの種類がありえるのではないか？

**Comment by Satoshi-Matsumoto** [comment]
これまでの議論

====
- 月ごとの振り返り と、 フェーズ（意味上の変化）ごと振り返りがあるのではないか

- ロールを確認する振り返りは労力はかかるがチームのステータスを確認する、という振り返りの趣旨を達成するものではある

- このようなロールにフォーカスするものは月よりももうちょっと広い方向でやる必要がある

- ロールにフォーカスしない、月一回で全体的な情報を取り入れるものをやる、というのは実務でもよく運用している

**Comment by Satoshi-Matsumoto** [comment]
これまで「振り返り」と呼ばれていたもの（＋近しいものとしてテンショントリアージ）をまとめてみました。
目的 / 頻度 / CODEにおけるドメインの考え方との対応 を書いています。

![image](https://user-images.githubusercontent.com/61894329/87327801-844e7f00-c56f-11ea-809c-367f011bd045.png)

いまCODEでは
②の振り返りが理論編ベーシックで
> チーミング・ステータスは、チームメンバー全員で行う定期的な　振り返り によって把握される。
のように記述されていて、

③の振り返りが実践編ベーシックで
> 振り返り とは、それまでのプロジェクトの進め方についてレビューし、改善のための実践や最適化を行うことができないか話し合うための仕組みである。 振り返りは各ミーティングごとに実施しても良いし、マイルストーン終了のタイミングなど、複数回以上のミーティングを経て実施してもよい。ただし、特定のタイミングで振り返りは必ず実施する必要がある。

のように記述されていて、意味が複数できてしまっていました。（すみません）

まず確認したいのは、言葉として「振り返り」 というものを
②のみにするか / ③のみにするか / ②③両方を含むものにするか
です。

**Comment by Satoshi-Matsumoto** [comment]
@motoi @kikuchiharuma 
このissueにまつわる更新をアップデートしました。

まず、このissueの背景やCloseできる基準を改めて記載します。

これまで振り返りというものについて、いろいろな議論があり、それがissue化されていない状況があったので、私のほうでissue化しました。議論内容をサマリーしているのが [これ](https://github.com/copilot-jp/project-sprint/issues/89#issue-655959889) であったり [これ](https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-657652529) です。

そのあとわたしのほうでの考察などをした結果を[ここ](https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-657657316)に記録していました。

さらにそのあと、https://github.com/copilot-jp/project-sprint/issues/88 とともにこのissueもcode v1.0.0に記載する方向で進めています。

というわけでこのissueでは、まず、これまでの議論を受けた振り返りの定義や種類の整理を行うところまで行えればと思います。これを超えた詳細事項は、https://github.com/copilot-jp/project-sprint/issues/88 のほうで追記していきます。

**Comment by Satoshi-Matsumoto** [comment]
というわけで、今回行った振り返りの定義や種類の整理を行うためのアップデートですが、

https://github.com/copilot-jp/project-sprint/commit/78ef08b3338e332e8d644919ff6bc8c0ad085f2f
https://github.com/copilot-jp/project-sprint/commit/71079bd247bf91c4e5f979e19f0e6832b4897812
https://github.com/copilot-jp/project-sprint/commit/37683bfd1f21bc9c1b2a32e5866700f5448bf153
https://github.com/copilot-jp/project-sprint/commit/b20d39f84af7a2d3da36a14f6a2bf62be903f72e

です。今までCODEで「振り返り」といったときには、[このコメント](https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-657657316)で書いているところの②③が混在していました。このうち③を明確に「振り返り」として定義し、②については「ロール確認」という別のものとして整理したものになります。

（なお、①については #88 で引き取る議論とできればと思います）

この整理の仕方 / 言葉の分け方で違和感ないか、まずは @motoi さん、コメントもらえますでしょうか？

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
実務で最近型になりつつあるパターンを書いてみます。

〇振り返り
時間：30-60分
タイミング：月に1回の定期 もしくは フェーズやプロジェクトの終了などのの分かりやすいタイミング
やり方：KPT+A, プラスデルタ（KPTのKPだけ）, YWT
テーマの目線：チーム, プロセス ＞プログレス（ここではロールの話もでる）

〇テンショントリアージ
時間：5-30分
タイミング：ミーティング毎（1~2週間ごと）
やり方：ホラクラシールール
テーマの目線：アジェンダの順番としてテンショントリアージの前に何をおこなっているかででてくるものはかわるものの、割とばらつきはない印象
※振り返りの手法としてテンショントリアージを使うこともある

〇ロールセッション
時間：30-60分
タイミング：プロジェクト開始時、月に1回の定期の振り返りのタイミングと一緒にみなおし
やり方：コパ独自フォーマットをみんなで議論しながら埋める
テーマの目線：ロールを決める、見直す

**Comment by motoi** [comment]
![image](https://user-images.githubusercontent.com/680855/88271744-93bd8d00-cd12-11ea-8eed-1deb28a39bf8.png)
図にするとこんな感じだなと思ってまして。

**Comment by motoi** [comment]
自分でブランチ切って治そうかとおもったけどまず整理を書いて、サトマツさんとすり合わせて修正したいなと。

サトマツさんと認識が違うかなとおもったのは、テンションはチーミングの問題解決だけに使われるものではないです。
テンションを出す、という行為が、言いたいことが言えるようになったり、関係の質があがるということにつながるので、よりよいチームになるから、テンショントリアージや振り返りを行うことはチーミングに寄与することではあります。

あとロール確認というものも定期的に振り返る対象というか振り返りのタイミングで一緒に見る、ある意味振り返りをするための素材になってるという感じです。

なので、テンションでは、マイルストーン間に合って無くね？とかプログレス的なことも出るし、プロセス的なものも許容されます。基本的にはなんでもあり。チームメイトに感謝を伝えるとかでもよいという議論も最近あります（なので「テンション（ひずみ）」というワードではなく小さな声・つぶやきみたいなほうがよいんじゃないかという議論はいまコパ内で行われている）

上のコメントの絵で書いたときにおもいましたがいままで使っていた「振り返り」という言葉を意味的に解釈しなおして「継続的改善アプローチ」と書いてみると整理しやすくなるかなとおもいました。

継続的改善アプローチ
A. ふりかえり：過去を省みて考えていることを書いてもらう
　　手法：KPT, YWT, +Δ など
B. いまの気持ち（今付けた仮称）：今の素直な気持ちを書いてもらう
　　手法：テンショントリアージ

それぞれで書かれるものはプログレスか、プロセスか、チーミングかというと、タイミング、チームのステータス、その時のテーマによってコントロールされるかなとおもいます。

A. 「ふりかえり」について
毎月の定期的に実施
対象：今のフェーズを改善したい
アクションになるドメイン：プログレス・プロセス・チーミング

フェーズの終わりに実施
対象：次のフェーズを改善したい
アクションになるドメイン：プロセス・チーミング

スポット
対象：今のフェーズを改善したい
アクションになるドメイン：スポットで開催する理由による


B. 「いまの気持ち」について
これはAよりももっとタイミングとチームのステータスに非常に左右されます。
アジェンダのタイミングで例示すると、毎週のTODOがたくさんあるチームだと、TODOを確認したあとのアジェンダにテンショントリアージを行うと、プログレスっぽいものが出やすい。
ステータスで例示すると、案件が炎上している時だと、プログレスの話しかでない、案件が平和なときだとチーミングとかプロセスのテンションがでやすい。
「ふりかえり」はテーマを決めたりしますが、「いまの気持ち」の方は割とコントロールできないししなくてもよいのかなとおもいます。

こんな構造が現状考えられるものかなーとおもっています。

ちなみに、継続的改善アプローチのためには、プロジェクトやフェーズのキックオフでの設定が重要で、そこではこういうことをやるべしってのもある程度見えてきているけど（ノーミングセッション的なやつ）あんまり固まっていないのと、このイシューではふりかえりだったとおもうので、今回の整理ぐらいをCODEに反映するのはどうでしょうか？！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
確認ありがとうございました。ふむふむと思いつつ修正しちゃいました。
いままでの内容との差分が大きいのでいちおう新しくブランチを切っています。
https://github.com/copilot-jp/project-sprint/commit/28d2633d1110962881ebd791e1d61cf743680f7a
https://github.com/copilot-jp/project-sprint/commit/abad5291e0a98902f242c5bc51c91089f9ba1e65
https://github.com/copilot-jp/project-sprint/commit/6ff120ea176363c5312534e43d87b9816a142153
https://github.com/copilot-jp/project-sprint/commit/a08fb0340651f1ac298d2d9587ebbe93a20f0e21

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
補足していくと、
> テンションを出す、という行為が、言いたいことが言えるようになったり、関係の質があがるということにつながるので、よりよいチームになるから、テンショントリアージや振り返りを行うことはチーミングに寄与することではあります。
ここはなるほどですね。テンション自体はメンタルアクティビティであると 理論編ベーシックで定義されているので（概念図でもそうなっている）勘違いしましたが、だからといって寄与する先がチーミングだけとは限らないですね。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

継続的改善アプローチとその整理、はCODE的にはそのまま取り入れられそうかなと思ったので修正反映しています。ただ、
> フェーズの終わりに実施
> 対象：次のフェーズを改善したい
> アクションになるドメイン：プロセス・チーミング

これは、フェーズ終わりのタイミングで行う振り返りであっても、次回のマイルストーンに向けた最適化の話し合い = プログレスの話し合いはされるはずなので、アクションになるドメインはいずれにせよ対象を区切りません。

それと、「フェーズ」はcode v0.9.0時点でplug-inの用語なので、basic / advance上は使わない形で書きました。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
https://github.com/copilot-jp/project-sprint/commit/b20d39f84af7a2d3da36a14f6a2bf62be903f72e
で修正したロール確認、はチーミングの部分に残しています。

> あとロール確認というものも定期的に振り返る対象というか振り返りのタイミングで一緒に見る、ある意味振り返りをするための素材になってるという感じです。

たしかにこれはこれでそうなのですが、
https://github.com/copilot-jp/project-sprint/issues/22
で議論のように「チーミングのステータスを把握するもの」としてロール確認が位置付けられているのです。これまでそれを"振り返り"と呼んで混在してしまっていましたが、

- 最適化のための継続的改善アプローチ（含む振り返り）
- チーミングのステータス確認のためのロール確認

は全く別の概念として、いずれも残す必要があると考えています。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
> ちなみに、継続的改善アプローチのためには、プロジェクトやフェーズのキックオフでの設定が重要で、そこではこういうことをやるべしってのもある程度見えてきているけど（ノーミングセッション的なやつ）あんまり固まっていないのと、このイシューではふりかえりだったとおもうので、今回の整理ぐらいをCODEに反映するのはどうでしょうか？！

これは別イシューにしましょう。もしなんらかCODEの修正内容にしたほうがよさそうな場合、まずはラフな感じでいいのでこういう内容を盛り込みたい！みたいな感じでイシュー立ててもらえると助かります。

**Comment by Satoshi-Matsumoto** [comment]
てことでまずは修正内容どうですかね？ @motoi 
そして結構なボリュームの内容になってきたので @kikuchiharuma さんをいったんメンションしておきます。( @motoi さんのレビューがDONEになった時点で @kikuchiharuma さんにも確認依頼すると思います）

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
テンションという言葉は今後検討だなと思いつつ（別イシューにします）書いてもらったものでよいと思いました！

とかきつつ、1点全体を読んで付け加えるとするならば、継続的改善アプローチのために重要な要素は、振り返り、なり、今を見つめる、という作業を定期的なイベントとすることが望ましいです。今の書き方だと指定するどこかのタイミングでやってほしい、みたいに読めてしまっていて、理想としては、毎月決まってKPTやるとか、毎週ちょっとだけテンション出してもらう、という定期性が継続的改善につながるとおもっているので、その記述をいれたいなと感じました。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 

> 1点全体を読んで付け加えるとするならば、継続的改善アプローチのために重要な要素は、振り返り、なり、今を見つめる、という作業を定期的なイベントとすることが望ましいです。今の書き方だと指定するどこかのタイミングでやってほしい、みたいに読めてしまっていて、理想としては、毎月決まってKPTやるとか、毎週ちょっとだけテンション出してもらう、という定期性が継続的改善につながるとおもっているので、その記述をいれたいなと感じました。

こんな感じでどうでしょ？
https://github.com/copilot-jp/project-sprint/commit/9ee220eb5044dc9b87482e07da79778860d90dd2
https://github.com/copilot-jp/project-sprint/commit/e32a655058be78d2e18305512cfda2800f68815b
https://github.com/copilot-jp/project-sprint/commit/a04610fcf9ce8d9dfd9bd6eb63747b72b4836b0a
https://github.com/copilot-jp/project-sprint/commit/5f5ba505dc4bd35e9e6e51b425c3bc8cedb76676

**Comment by motoi** [comment]
@Satoshi-Matsumoto 良いと思いました！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
ありがとうございます！

@kikuchiharuma 
割とたくさんの修正内容があるので一度流してみてもらいたいと思っています。
修正内容は

https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-663130338
https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-663383894

です。

細かい経緯はやりとりを確認していただくとよいと思うのですが、
ポイントしては、これまでぼやっとしていた「振り返り」という単語を整理していくというなかで、より高次の概念の「継続的改善アプローチ」という考え方が生まれ、その中で、過去起こったことに軸足を置く「振り返り」/ いまの気持ちの共有としての「テンショントリアージ」という整理になった。これらが取り扱う内容や、議論される内容は、プロセス / プログレス / チーミング問わない。

またこれまで振り返りはロールのすり合わせ = チーミングにおけるステータス確認、という意味も持っていたが、これは「ロール確認」という別の概念として切り出した。

というところです。整理の仕方に違和感があったり、修正内容中で分からないところ、質問事項がありましたら、くださいまし！

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto 過去の流れを読んでみました。

良い整理になってきているな(確かに振り返りってどのドメインの話も出てくる柔軟なものでないといけないのに、今までの整理は偏りがあったな)、と思いつつひとつ思ったのは、プロセスで扱うべき形式的なものと、プログレスやチーミングの内容について踏み込んだものが、混ざってしまっているのではないかという点です。

今のミーティングについての説明をざっと並べてみると、やることが色々並んでいて論理的な構造が希薄になってきている感じがします。

- ミーティング
  - 参加者
  - 場
  - 時間
  - アジェンダ
  - 他の活動との接続
    - 各ミーティングにおける仕組み
    - 継続的改善アプローチ
      - 振り返り:過去を省みる
      - テンショントリアージ:いまの気持ちを共有する

思うに、やること自体は色々ある、というか、ミーティングはPJSの根幹を成すものなので色々と含んでいて当然だと思うのですが、だからこそ、明確な構造を与えていくべきかなとも思います。

振り返りの議論に戻ると、「最適化の機会」をプロセスとして(できれば安定的に、必要十分なスパンで)用意していくことと、その機会の中で過去や将来や今を「最適化の対象＝話し合いの内容」として取り上げることは別なのではないか、と思いました。

- チームの話し合いの機会＝ミーティングは、予測可能で、スパンに偏りのない形で開催されるようにするべき(定期的であることの重要性/プロセスの独立性)
- 節目ごと(フェーズ？ある程度長い定期的なスパン？)に特別な機会があるべき
- 特別な問題が生じたら都度のミーティングもやろう
- その中で実践と最適化を両立させよう

これが形式について言えることなのではないかと。
そして、最適化について、

- 健全なチームを保つには、チームの「今」を共有すべき(短いスパンで少しずつ最適化のための材料出しをやるべし:アジェンダとして入れる)
- 同様に、過去や将来についても中長期で認識を合わせる機会を持つべき(頻繁でなくても良いが節目でしっかり最適化の実践をやるべし:振り返りをやる)
- プログレスを継続的に最適化するためには…
- プロセスを継続的に最適化するためには…

などが、機会が用意できた上で、その機会を使って行われるべき最適化の中身としてあるのかなと思いました。
なので、ここまでの議論での発見(いくつかの種類の機会があって、その中でどのドメインの話もすることで、継続的な改善が達成される)を構造に落とすと、

- ミーティング
  - ミーティングの種類(場のあり方、時間、参加者)
    - 定例
    - フェーズごと？長期スパンの定例？
    - 臨時
  - ミーティングが扱う内容
    - プログレス
      - 実践
      - 最適化
    - チーミング
      - 実践
      - 最適化
    - プロセス
      - 実践
      - 最適化
    - その他
      - 他の活動との接続？
      - (別トラックや外部との連絡もここに入る？)
  - ミーティングの方法
    - アジェンダ
    - 振り返り
    - テンショントリアージ
    - (アジェンダトリアージもここに入る？ミーティング単体の最適化を行うプロセス活動？)

こんな感じに例えばなるのではないかと思いました。
このIssueでの発見は、形式と内容の分離であり、だとすると章立ての整理に反映できると、すっきり理解でき、将来性もあるものとして定着できるのではないかと思いました

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 

コメントありがとうございます。
一応確認ですが、いまいま構造的には下記のようになっています。

- ミーティング
　- 参加者
　- 場
　- 時間
- アジェンダ
　- アジェンダの構成要素
- 他の活動との接続
　- 各ミーティングにおける仕組み
　- 継続的改善アプローチ(ミーティング横断の仕組み）
　　- 振り返り:過去を省みる
　　- テンショントリアージ:いまの気持ちを共有する

（#41 との兼ね合いで若干変更がありますがこのissueで切っているブランチ上ではこの状態です。）

つくりの意図としては、
- プロセスにはミーティングとアジェンダという要素があり、こういう方法でやることができます、ほかの活動との接続はこういう仕組みで接続されます
というものになっていて、たしかに「ミーティングで取り扱う内容」というものが何か、ということは実は強く意識していません。
なので今回の議論の中で形式と内容について分けたほうがいいというのは確かに発見でありそこは取り入れたいと思いつつ、どちらかというと振り返りというよりかはプロセスの定義の話な気がしました = 別issueにしてつぶしていくのはどうでしょうか？

たぶん #41 のほうでの内容も完結してから修正していったほうがいいポイントな気がしています。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma 
また、上記の点にくわえて、このissueの本丸である、振り返りという言葉の意味上の整理、つまり

- プロセス
　- 継続的改善アプローチ
　　- 振り返り:過去を省みる
　　- テンショントリアージ:いまの気持ちを共有する
- チーミング
　- ロール確認

この整理自体については、いかがでしょう？

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto プロセスドメインの中で継続的改善アプローチが行われる、継続的改善はミーティング単体では難しく複数ミーティングを俯瞰したプロセスの視点で行われる(だからプロセス直下に記述される)、かつ特定ドメインだけが対象ではなく全てのドメインで継続的改善が可能、という議論は賛成です。なので振り返りの整理は良いと思います。

形式と内容は確かに欲張ってしまったので別Issueで立てますね。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma ではこちらは別issueを立てていただいたので、closeします！
