### ISSUE TITLE
マイルストーンの記述の見直し

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#90]
@Satoshi-Matsumoto より。
マイルストーンは理論編 ・実践編 / ベーシック・アドバンスを通して各所に出てくる概念だが、実際にどのようにマイルストーンをつくればいいのか、ということがわからないものになっている気がする。
特に、実践編ベーシックにおける記述をもう少し充実できないか。

合わせて、 @motoi さん指摘のように、マイルストーンの構成要素 （例："みんなの納得”など）が妥当か？も再考したい。

**Comment by motoi** [comment]
これ定金が一回マイルストーンってどうやって作るものなのかとか説明したほうが良いかしら？
ちなみに某社さんむけ資料で（ロードマップという言葉がよいってことだったので合わせたけど）こんな資料を作ってみたけど、これが参考になるかしら。昔定例で共有した話をもうちょっと資料化した感じなのでご存知の内容かもだけど。
[なぜシンプルなロードマップでよいのか.pdf](https://github.com/copilot-jp/project-sprint/files/4917788/default.pdf)
進め方のイメージをください！

**Comment by Satoshi-Matsumoto** [comment]
@motoi さんのコメントは別途返しますね。

@kikuchiharuma さんとのディスカッションを受けて @Satoshi-Matsumoto から追記します。
CODEではプログレス / プロセス / チーミングのドメインを定義しているが、この3つのプログレス / プロセス / チーミングの分け方はある程度普遍的な概念なのではないか？

たとえば、成果物として、
1) あるシステムと、
2) それを使うための運用ドキュメントと、
3) それをうまく回すためのチームの在り方
があるときに、1はプログレス、2はプロセス、3はチーミング、と考えられる。（CODE上のPJSの概念とは違うが）

なので、この概念はマイルストーンのブレイクダウンに使えるのではないか。

また、それに紐づくロール、というものを考えることもできるのではないか。とも思います。

まずはマイルストーンのブレイクダウンという切り口で深ぼっていきたいと思います。

**Comment by Satoshi-Matsumoto** [comment]
![image](https://user-images.githubusercontent.com/61894329/87421245-9680f980-c611-11ea-8352-2349f5e05e77.png)

参考

**Comment by Satoshi-Matsumoto** [comment]
CODE上のマイルストーンの記述はv1.1.0に向けて下記のissueでも対応予定です。

https://github.com/copilot-jp/project-sprint/issues/179
https://github.com/copilot-jp/project-sprint/issues/185
https://github.com/copilot-jp/project-sprint/issues/186

これらのissueがクローズ後このissueに立ち戻り、追加の更新が必要か判断します。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
マイルストーン関係の修正を諸々加えましたが結局このイシューで問題になるのは
> マイルストーンは理論編 ・実践編 / ベーシック・アドバンスを通して各所に出てくる概念だが、実際にどのようにマイルストーンをつくればいいのか、ということがわからないものになっている気がする。
> 特に、実践編ベーシックにおける記述をもう少し充実できないか。

このポイントのように思いました。このあたりはManualで議論を尽くしたので、それをCODEに反映しました。
e2b43b159221b7bf1166e5f321b450c28df7534f

確認 & 問題なければクローズください。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
概ね問題ないのですが、以下の文章だけがきになりました。

> マイルストーンは、明文化されたかたちでチームメンバー全員に共有され、全員が納得された状態になるまで議論を重ねてつくらなければいけない。

なんかすごいこの文章がウォーターフォール的に事前に決めて固めなければというニュアンスを受けました。
常に全員が納得している状態を維持し続けて、進化させつづける、みたいなニュアンスをここにいれたいなとおもいました。
ティール組織の、進化する目的、みたいな感じにしたいなと。

ちょっとここ私の文章力だと作文が難しそうなので引用すると。
https://nol-blog.com/what_is_teal_organization/
"また、生き続ける中で、目的も進化していくため、進化する目的と表現されています。そのため、定期的に、「この組織はどこに行きたがっているのだろうか？」と互いに感じながら、話し合う場等が設けられている組織もあります。"
の引用している部分をマイルストーンで繰り返す感じです。

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
なるほど。こういうことかなと。
3e1e36cc7c234a4d83020c982839e87d0ec29a46

**Comment by motoi** [comment]
よいとおもいました！
