### ISSUE TITLE
README 更新

### ISSUE THREAD

**Issue by Satoshi-Matsumoto** [copilot-jp/project-sprint#91]
#34 であがっていた下記のポイントへの対応。
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648623379
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625072
https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625459

**Comment by Satoshi-Matsumoto** [comment]
対応しました。

まず前提として、文章の構造を整理しています。
https://github.com/copilot-jp/project-sprint/commit/21a8b3c9ba54ce174b6ac6cca1f9eaafe6f73218
https://github.com/copilot-jp/project-sprint/commit/c50177b09034144b53452ca43d701473203bf4d3
https://github.com/copilot-jp/project-sprint/commit/5fdd6425dac9bc63f86db6210c96f63770e5e68e
ここで最終的につくったながれとしては、
Githubの経験値は問わない。自分に合った方法で参加してください。
=> Githubを通じての参加方法（Issue / プルリク)と、それ以外（Slackコミュニティ）での参加方法があるよ
というものです。そのうえで、

Githubを通じての参加方法（Issue / プルリク) について、
https://github.com/copilot-jp/project-sprint/commit/c6f47482651fdb8e904ae550f2332c7fdb902e42
https://github.com/copilot-jp/project-sprint/commit/da720ea653ad4477ccb68ae010b5f9d96b7e333f (これが、https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625459 への対応に相当します。）
のように書きました。

https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648623379
は、
https://github.com/copilot-jp/project-sprint/commit/7e549a3c91327cbb956e20e3cec345db6527b516
https://github.com/copilot-jp/project-sprint/commit/11da1ba5f9e81b2b80aeab2c39139135236917cf
で対応しました。冒頭に記載する形。以降の内容との区別したおおもとの大前提みたいなことだと思うので区別するべく表示もスクリプトの引用のために使われるものにしています。

https://github.com/copilot-jp/project-sprint/issues/34#issuecomment-648625072
は、もともと私が出している課題意識だったのですが、対応しないほうがよいかなという考えにいたったので、何もしていません。理由は、Github経験値を問いません！と言っているのにマークダウンの話とか、リテラシーを要求することをREADMEに書かないほうがいいかな…となったためです。

いちおう元コメントが @kikuchiharuma さんのものになるので、まず元コメントへの対応としてどうか、レビューもらってもよいでしょうか？

そのあとで @motoi さんにもレビューしてもらう流れにしようと思っています（趣旨は残しているつもりですが、元の文章も結構変えているので、伝えたいポイントがそがれていないか聞きたい）

**Comment by kikuchiharuma** [comment]
@Satoshi-Matsumoto ありがとうございます、全体に良いと思いました。
日本語話者以外に向けてメッセージを置くのであれば、簡単で良いのでPJSって何なのか、の紹介はあると良いなと思いました。
GitHubのReadmeはまずもって何？に答える必要があるので。

https://github.com/copilot-jp/project-sprint/commit/25780e959e4b008565ff8c0d5fa4b72d74e76e2b#diff-04c6e90faac2675aa89e2176d2eec7d8

ここで消されてしまっているので、元の紹介文を復活してはどうでしょう。

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん確認ありがとうございます！なおしました。
https://github.com/copilot-jp/project-sprint/commit/bb366c426a12aa8ea0a993fed79b64c7d6d32ae9

このまま @motoi さんに確認もらえればと思います。修正ご確認下さい。

全体みてもらいたいですが特に @motoi さんに確認もらいたいのはここの部分ですね。

> 21a8b3c
> c50177b
> 5fdd642
> ここで最終的につくったながれとしては、
> Githubの経験値は問わない。自分に合った方法で参加してください。
> => Githubを通じての参加方法（Issue / プルリク)と、それ以外（Slackコミュニティ）での参加方法があるよ
> というものです。そのうえで、

元の文章で伝えたかった意図が落ちてしまっていないか（落ちてしまっていた場合、問題があるかないか）が特にききたいところです。

**Comment by motoi** [comment]
@Satoshi-Matsumoto 
https://github.com/copilot-jp/project-sprint/commit/5fdd6425dac9bc63f86db6210c96f63770e5e68e
ここだけ調整しました。簡単な修正なので問題ないだろうとおもって同じブランチで定金のほうで治してみました。
あとは全体的に文意を汲んでもらっていて調整ありがとうございます！よりよくなったかと！

**Comment by Satoshi-Matsumoto** [comment]
@motoi 
確認ありがとうございました！修正も進めてもらってありがとうございます。ばっちりです。

@motoi @Satoshi-Matsumoto 
英文説明の冒頭文だけ、不自然だった部分を私のほうでちょっと修正しました。
a0d12ca

特に問題ないと思うので、こちらはクローズしてしまいます。
