### ISSUE TITLE
継続的改善アプローチのためには、プロジェクトやフェーズのキックオフについて記述する

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#96]
継続的改善アプローチ
A. ふりかえり：過去を省みて考えていることを書いてもらう
　　手法：KPT, YWT, +Δ など
B. いまの気持ち（今付けた仮称）：今の素直な気持ちを書いてもらう
　　手法：テンショントリアージ

それぞれで書かれるものはプログレスか、プロセスか、チーミングかというと、タイミング、チームのステータス、その時のテーマによってコントロールされるかなとおもいます。

A. 「ふりかえり」について
毎月の定期的に実施
対象：今のフェーズを改善したい
アクションになるドメイン：プログレス・プロセス・チーミング

フェーズの終わりに実施
対象：次のフェーズを改善したい
アクションになるドメイン：プロセス・チーミング

スポット
対象：今のフェーズを改善したい
アクションになるドメイン：スポットで開催する理由による

B. 「いまの気持ち」について
これはAよりももっとタイミングとチームのステータスに非常に左右されます。
アジェンダのタイミングで例示すると、毎週のTODOがたくさんあるチームだと、TODOを確認したあとのアジェンダにテンショントリアージを行うと、プログレスっぽいものが出やすい。
ステータスで例示すると、案件が炎上している時だと、プログレスの話しかでない、案件が平和なときだとチーミングとかプロセスのテンションがでやすい。
「ふりかえり」はテーマを決めたりしますが、「いまの気持ち」の方は割とコントロールできないししなくてもよいのかなとおもいます。

こんな構造が現状考えられるものかなーとおもっています。

ちなみに、継続的改善アプローチのためには、プロジェクトやフェーズのキックオフでの設定が重要で、そこではこういうことをやるべしってのもある程度見えてきているけど（ノーミングセッション的なやつ）あんまり固まっていないのと、このイシューではふりかえりだったとおもうので、今回の整理ぐらいをCODEに反映するのはどうでしょうか？！

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-662941555_

**Comment by motoi** [comment]
実践の結果をこちらに持ち込む！実践中！

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/239
こちらにまとめているので統合で良いかも？
@Satoshi-Matsumoto さんどうでしょう？

**Comment by Satoshi-Matsumoto** [comment]
@motoi いいとおもいます。こちらもクローズで。
