### ISSUE TITLE
テンション、テンショントリアージの用語の再定義と「振り返り」と並ぶ用語の発明

### ISSUE THREAD

**Issue by motoi** [copilot-jp/project-sprint#97]
テンションの問題点：
ひずみという言葉がネガティブな印象になってしまい、感謝みたいなものがでづらいのがちょっと言葉としてよくないかなーとおもっている。

テンショントリアージの問題点：
トリアージという言葉が医療用語としてものすごく厳しい取捨選択（命の優先順位をつける）ような印象をもっているので、なんかもうちょっとだけほのぼのしたものに変えたい。

この二つはホラクラシーからそのまま来ているので便利なのでそのまま使っているが…。

あとは「ふりかえり」に対してこのテンショントリアージするという行為をなんか名付けたい。「今の気持ち」「いまをみつめる」「立ちどまり」とか？

---
「継続的改善アプローチ」と書いてみると整理しやすくなるかなとおもいました。

継続的改善アプローチ
A. ふりかえり：過去を省みて考えていることを書いてもらう
　　手法：KPT, YWT, +Δ など
B. いまの気持ち（今付けた仮称）：今の素直な気持ちを書いてもらう
　　手法：テンショントリアージ

それぞれで書かれるものはプログレスか、プロセスか、チーミングかというと、タイミング、チームのステータス、その時のテーマによってコントロールされるかなとおもいます。

A. 「ふりかえり」について
毎月の定期的に実施
対象：今のフェーズを改善したい
アクションになるドメイン：プログレス・プロセス・チーミング

フェーズの終わりに実施
対象：次のフェーズを改善したい
アクションになるドメイン：プロセス・チーミング

スポット
対象：今のフェーズを改善したい
アクションになるドメイン：スポットで開催する理由による

B. 「いまの気持ち」について
これはAよりももっとタイミングとチームのステータスに非常に左右されます。
アジェンダのタイミングで例示すると、毎週のTODOがたくさんあるチームだと、TODOを確認したあとのアジェンダにテンショントリアージを行うと、プログレスっぽいものが出やすい。
ステータスで例示すると、案件が炎上している時だと、プログレスの話しかでない、案件が平和なときだとチーミングとかプロセスのテンションがでやすい。
「ふりかえり」はテーマを決めたりしますが、「いまの気持ち」の方は割とコントロールできないししなくてもよいのかなとおもいます。

_Originally posted by @motoi in https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-662941555_

**Comment by motoi** [comment]
> テンションの問題点：
> ひずみという言葉がネガティブな印象になってしまい、感謝みたいなものがでづらいのがちょっと言葉としてよくないかなーとおもっている。
しばらく実践してみて、例えば感謝についてはテンション以外のところで出てくればよいと思い直している。
なので、テンションという言葉はこのままでよいという印象になった。

**Comment by motoi** [comment]
> あとは「ふりかえり」に対してこのテンショントリアージするという行為をなんか名付けたい。「今の気持ち」「いまをみつめる」「立ちどまり」とか？

これは今後も検討したい。

**Comment by motoi** [comment]
https://github.com/copilot-jp/project-sprint/issues/239
これはこちらのイシューに統合で良い気がします

@Satoshi-Matsumoto さんどうでしょう？

**Comment by Satoshi-Matsumoto** [comment]
@motoi いいとおもいます。いったんクローズで。
