### ISSUE TITLE
プロセスドメインのメタ的な位置づけを明確にできないか

### ISSUE THREAD

**Issue by kikuchiharuma** [copilot-jp/project-sprint#99]
振り返りと、継続的改善アプローチについての議論より
https://github.com/copilot-jp/project-sprint/issues/89#issuecomment-663816894_

**Comment by kikuchiharuma** [comment]
プロセスが用意する機会と、その機会を使って行われる中身に分けて記述が可能なのではないか。

継続的改善アプローチの例でいうと、適切なスパンで振り返りの機会を提供するのがプロセス、振り返りの中ではプロセス、プログレス、チーミング全ての内容が話される、などと書き分ける。

分離することで、ミーティングは行われているがチーミングのアジェンダが出ておらず話し合いが不足した、テンショントリアージはされていないが暗黙的なロールが十分あるのでチーミングの問題はない、などの記述が可能になるのではないか。
そうなると、CODEでもっと記述できる部分が明らかになるのではないか。(ポテンシャル)

**Comment by Satoshi-Matsumoto** [comment]
@kikuchiharuma さん、
いま過去のIssue含めて対応優先順位づけをしています。その中でこのIssueもレビューしているのですがすみません、内容の理解があっているかを確認したく。

- CODEで記述している「プロセス」には、ミーティングの開催、継続的改善アプローチ、など形式的な手順（まさにプロセス）は書かれている。
- これに加え、「プロセスのなかで議論される内容」 = プロセスそのものについて / チーミングについて / プログレスについて　

という2層構造でかき分けてみる

みたいな案、ということで、あってますか？

**Comment by motoi** [comment]
現行CODEは解消した記述になっているためクローズ
